# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_marque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureModele',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_modele', models.CharField(max_length=25)),
                ('nom_variante', models.CharField(blank=True, max_length=25, null=True)),
                ('nombre_portes', models.IntegerField(choices=[(3, '3 portes'), (5, '5 portes')])),
                ('nbre_places', models.PositiveSmallIntegerField()),
                ('taille_reservoir', models.DecimalField(decimal_places=2, help_text='En litres', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voiture_marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles', to='voiture_marque.voituremarque')),
            ],
        ),
    ]
