# Generated by Django 6.0 on 2026-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodele',
            name='nombre_portes',
            field=models.IntegerField(choices=[(2, '2 portes'), (3, '3 portes'), (5, '5 portes')]),
        ),
    ]
