# Generated by Django 5.2.10 on 2026-02-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0002_voituremodele_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='voituremodele',
            name='capacite_batterie',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Capacite batterie', null=True),
        ),
    ]
