# Generated by Django 6.0 on 2026-01-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0002_alter_voituremodele_nombre_portes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodele',
            name='nom_variante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
