# Generated by Django 6.0 on 2026-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0003_alter_voituremodele_nom_variante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodele',
            name='nom_modele',
            field=models.CharField(max_length=100),
        ),
    ]
