# Generated by Django 5.2.10 on 2026-02-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_marque', '0002_voituremarque_societe'),
        ('voiture_modele', '0004_alter_voituremodele_capacite_batterie'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voituremodele',
            constraint=models.UniqueConstraint(fields=('voiture_marque', 'nom_modele', 'nom_variante'), name='unique_modele_variante_par_marque'),
        ),
    ]
