# Generated by Django 5.2.10 on 2026-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0005_voituremodele_unique_modele_variante_par_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodele',
            name='capacite_batterie',
            field=models.PositiveIntegerField(blank=True, help_text='Capacité batterie en kWh', null=True),
        ),
    ]
