# Generated by Django 5.2.10 on 2026-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0007_alter_voituremodele_nombre_portes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodele',
            name='nombre_portes',
            field=models.IntegerField(choices=[(0, '0 portes'), (2, '2 portes'), (3, '3 portes'), (4, '4 portes'), (5, '5 portes')]),
        ),
    ]
