# Generated by Django 5.2.10 on 2026-03-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0008_alter_voituremodele_nombre_portes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voituremodele',
            name='annee_debut',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='voituremodele',
            name='annee_fin',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='voituremodele',
            name='mois_debut',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='voituremodele',
            name='mois_fin',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
