# Generated by Django 5.2.10 on 2026-03-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0009_voituremodele_annee_debut_voituremodele_annee_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodele',
            name='annee_debut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voituremodele',
            name='annee_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voituremodele',
            name='mois_debut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voituremodele',
            name='mois_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
