# Generated by Django 5.2.10 on 2026-03-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_marque', '0002_voituremarque_societe'),
        ('voiture_modele', '0010_alter_voituremodele_annee_debut_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voituremodele',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mois_debut__gte', 1), ('mois_debut__lte', 12)), ('mois_debut__isnull', True), _connector='OR'), name='mois_debut_entre_1_12'),
        ),
        migrations.AddConstraint(
            model_name='voituremodele',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mois_fin__gte', 1), ('mois_fin__lte', 12)), ('mois_fin__isnull', True), _connector='OR'), name='mois_fin_entre_1_12'),
        ),
        migrations.AddConstraint(
            model_name='voituremodele',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annee_debut__gte', 1850), ('annee_debut__lte', 2026)), ('annee_debut__isnull', True), _connector='OR'), name='annee_debut_valide'),
        ),
        migrations.AddConstraint(
            model_name='voituremodele',
            constraint=models.CheckConstraint(condition=models.Q(('annee_fin__gte', models.F('annee_debut')), ('annee_fin__isnull', True), ('annee_debut__isnull', True), _connector='OR'), name='annee_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='voituremodele',
            constraint=models.CheckConstraint(condition=models.Q(('annee_fin__gt', models.F('annee_debut')), ('annee_fin__isnull', True), ('annee_debut__isnull', True), ('mois_fin__gte', models.F('mois_debut')), _connector='OR'), name='mois_fin_apres_debut_si_meme_annee'),
        ),
    ]
