# Generated by Django 5.2.10 on 2026-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_marque', '0002_voituremarque_societe'),
        ('voiture_modele', '0011_voituremodele_mois_debut_entre_1_12_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voituremodele',
            name='annee_debut_valide',
        ),
        migrations.AddField(
            model_name='voituremodele',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='voituremodele',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='voituremodele',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AddConstraint(
            model_name='voituremodele',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annee_debut__gte', 1940), ('annee_debut__lte', 2026)), ('annee_debut__isnull', True), _connector='OR'), name='annee_debut_valide'),
        ),
    ]
