# Generated by Django 5.2.10 on 2026-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_modele', '0012_remove_voituremodele_annee_debut_valide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremodele',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='voituremodele',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
