# Generated by Django 5.2.10 on 2026-02-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmortisseurControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=25, verbose_name='Emplacement')),
                ('fuite', models.BooleanField(default=False, verbose_name='Fuite')),
            ],
            options={
                'verbose_name': 'Amortisseur',
                'verbose_name_plural': 'Amortisseurs',
            },
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControleBruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=10, verbose_name='Emplacement')),
                ('type_bruit', models.CharField(choices=[('ROULEMENT_ROUE', 'Roulement de roue'), ('ROULEMENT_SUSPENSION', 'Roulement de suspension'), ('MOTEUR', 'Moteur'), ('BOITE_VITESSE', 'Boîte de vitesse'), ('PONT', 'Pont')], max_length=30, verbose_name='Type de bruit')),
                ('niveau_bruit', models.CharField(choices=[('NORMAL', 'Normal'), ('ANORMAL', 'Anormal')], default='NORMAL', max_length=10, verbose_name='Niveau de bruit')),
                ('commentaire', models.TextField(blank=True, verbose_name='Observation')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='Tag')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControleFreins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie', models.CharField(choices=[('AVANT', 'Avant'), ('ARRIERE', 'Arrière'), ('AV_AR', 'Avant et arrière')], max_length=10, verbose_name='Partie contrôlée')),
                ('usure_plaquettes', models.FloatField(verbose_name='Usure des plaquettes (%)')),
                ('epaisseur_disques', models.FloatField(verbose_name='Épaisseur des disques (mm)')),
                ('fentes_disques', models.BooleanField(default=False, verbose_name='Présence de fentes sur les disques')),
                ('fuites', models.BooleanField(default=False, verbose_name='Présence de fuite du système de freinage')),
                ('disques_remplacer_av', models.BooleanField(default=False, verbose_name='Disques avant à remplacer')),
                ('disques_remplacer_ar', models.BooleanField(default=False, verbose_name='Disques arrière à remplacer')),
                ('Plaquettes_remplacer_av', models.BooleanField(default=False, verbose_name='Plaquettes avant à remplacer')),
                ('plaquettes_remplacer_ar', models.BooleanField(default=False, verbose_name='Plaquettes arrière à remplacer')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControleGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=10, null=True, verbose_name='Emplacement / partie du véhicule')),
                ('essuie_glace_av', models.BooleanField(default=True, verbose_name='Essuie-glace AV fonctionnel')),
                ('essuie_glace_ar', models.BooleanField(default=True, verbose_name='Essuie-glace AR fonctionnel')),
                ('pare_brise', models.BooleanField(default=True, verbose_name='Pare-brise sans coups')),
                ('moteur_fuite', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Fuite moteur')),
                ('boite_fuite', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Fuite boîte de vitesse')),
                ('liquide_frein_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='État liquide de frein')),
                ('remplacement_liquide_frein', models.BooleanField(default=False, verbose_name='Remplacement liquide de frein')),
                ('specif_liquide_frein', models.CharField(blank=True, max_length=100, verbose_name='Spécification liquide de frein')),
                ('quantite_liquide_frein', models.FloatField(default=0.0, verbose_name='Quantité liquide de frein (L)')),
                ('direction_fuite', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Fuite direction assistée / crémaillère')),
                ('niveau_direction', models.FloatField(default=0.0, verbose_name='Niveau liquide direction')),
                ('bruit_roulement', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='État roulement de roue')),
                ('location_roulement', models.CharField(blank=True, choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=10, null=True, verbose_name='Emplacement du roulement')),
                ('batterie_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='État batterie')),
                ('reglage_phares', models.BooleanField(default=True, verbose_name='Phares réglés correctement')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrôle général',
                'verbose_name_plural': 'Contrôles généraux',
            },
        ),
        migrations.CreateModel(
            name='JeuPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('ROTULE_DIRECTION', 'Rotule de direction'), ('ROTULE_SUSPENSION', 'Rotule de suspension'), ('BIELLETTE_BARRE_STAB', 'Biellette de barre stabilisatrice'), ('BARRE_STABILISATRICE', 'Barre stabilisatrice'), ('AMORTISSEUR', 'Amortisseur'), ('ROULEMENT_ROUE', 'Roulement de roue'), ('TRIANGLE', 'Triangle'), ('MULTI_BRAS', 'Multi-bras')], max_length=50, verbose_name='Pièce contrôlée')),
                ('emplacement', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=10, verbose_name='Emplacement')),
                ('etat', models.CharField(blank=True, choices=[('BON', 'Bon'), ('USE', 'Usé'), ('HS', 'Hors service')], max_length=10, null=True, verbose_name='État')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='VERT', max_length=10, verbose_name='État visuel / Tag')),
                ('commentaire', models.TextField(blank=True, verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NettoyageExterieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traces_gomme', models.BooleanField(default=False, verbose_name='Traces de gomme')),
                ('carrosserie', models.BooleanField(default=False, verbose_name='Carrosserie')),
                ('jantes', models.BooleanField(default=False, verbose_name='Jantes')),
                ('validation', models.BooleanField(default=False, verbose_name='Validation finale')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Nettoyage extérieur',
                'verbose_name_plural': 'Nettoyages extérieurs',
            },
        ),
        migrations.CreateModel(
            name='NettoyageInterieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitres', models.BooleanField(default=False, verbose_name='Vitres')),
                ('pare_brise', models.BooleanField(default=False, verbose_name='Pare-brise')),
                ('aspirateur', models.BooleanField(default=False, verbose_name='Aspirateur')),
                ('interieur_portes', models.BooleanField(default=False, verbose_name='Intérieurs de porte')),
                ('tableau_de_bord', models.BooleanField(default=False, verbose_name='Tableau de bord')),
                ('plastiques', models.BooleanField(default=False, verbose_name='Plastiques')),
                ('validation', models.BooleanField(default=False, verbose_name='Validation finale')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Nettoyage intérieur',
                'verbose_name_plural': 'Nettoyages intérieurs',
            },
        ),
        migrations.CreateModel(
            name='NoteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('APPRENTI', 'Apprenti'), ('MECANICIEN', 'Mécanicien'), ('CHEF', 'Chef mécanicien')], max_length=20)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RessortControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=25, verbose_name='Emplacement')),
                ('etat', models.CharField(choices=[('OK', 'OK'), ('CASSE', 'Cassé')], default='OK', max_length=25, verbose_name='État')),
            ],
            options={
                'verbose_name': 'Ressort',
                'verbose_name_plural': 'Ressorts',
            },
        ),
    ]
