# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('check_up', '0001_initial'),
        ('client_particulier', '0001_initial'),
        ('voiture_exemplaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='client_particulier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_particulier.clientparticulier'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='exemplaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='voiture_exemplaire.voitureexemplaire'),
        ),
    ]
