# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('check_up', '0002_initial'),
        ('maintenance', '0001_initial'),
        ('voiture_exemplaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='maintenance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkup', to='maintenance.maintenance'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='mecanicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlebruit',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bruits_checkup', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_freins_checkup', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_general_checkup', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='amortisseurcontrole',
            name='controle_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortisseurs_checkup', to='check_up.controlegeneral', verbose_name='Contrôle général'),
        ),
        migrations.AddField(
            model_name='jeupiece',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeux_pieces_checkup', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='jeupiece',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jeux_pieces_checkup', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='nettoyageexterieur',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_exterieur_nettoyage_exterieur', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='nettoyageexterieur',
            name='mecanicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nettoyages_exterieur_nettoyage_exterieur_mecanicien', to=settings.AUTH_USER_MODEL, verbose_name='Mécanicien'),
        ),
        migrations.AddField(
            model_name='nettoyageexterieur',
            name='voiture_exemplaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_exterieur_nettoyage_exterieur', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_interieur_checkup', to='maintenance.maintenance', verbose_name='Nettoyage intérieur'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='mecanicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nettoyages_interieur_checkup_mecanicien', to=settings.AUTH_USER_MODEL, verbose_name='Mécanicien'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='voiture_exemplaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_interieur_checkup', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='notemaintenance',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_checkup_auteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemaintenance',
            name='maintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_checkup', to='maintenance.maintenance'),
        ),
        migrations.AddField(
            model_name='ressortcontrole',
            name='controle_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressorts', to='check_up.controlegeneral', verbose_name='Contrôle général'),
        ),
    ]
