# Generated by Django 5.2.10 on 2026-03-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0003_initial'),
        ('maintenance', '0003_maintenance_societe'),
        ('nettoyage_exterieur', '0001_initial'),
        ('nettoyage_interieur', '0001_initial'),
        ('voiture_exemplaire', '0005_voitureexemplaire_est_avant_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='mecanicien',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='voiture_exemplaire',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='mecanicien',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='Plaquettes_remplacer_av',
            new_name='plaquettes_remplacer_av',
        ),
        migrations.RenameField(
            model_name='jeupiece',
            old_name='vehicle',
            new_name='vehicule',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='client_particulier',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='exemplaire',
        ),
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_exterieur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nettoyage_exterieur.nettoyageexterieur'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_interieur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nettoyage_interieur.nettoyageinterieur'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voiture_exemplaire.voitureexemplaire'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='maintenance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenance'),
        ),
        migrations.DeleteModel(
            name='NettoyageExterieur',
        ),
        migrations.DeleteModel(
            name='NettoyageInterieur',
        ),
    ]
