# Generated by Django 5.2.10 on 2026-03-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0004_remove_nettoyageinterieur_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebruit',
            name='controle_general',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bruits_checkup', to='check_up.controlegeneral'),
        ),
    ]
