# Generated by Django 5.2.10 on 2026-03-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0006_remove_controlegeneral_location_nettoyageexterieur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeupiece',
            name='controle_general',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jeux_pieces_checkup', to='check_up.controlegeneral'),
        ),
    ]
