# Generated by Django 5.2.10 on 2026-03-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0007_jeupiece_controle_general'),
        ('maintenance', '0003_maintenance_societe'),
        ('voiture_exemplaire', '0005_voitureexemplaire_est_avant_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JeuPiece',
            new_name='JeuxPiecesControle',
        ),
    ]
