# Generated by Django 5.2.10 on 2026-03-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0008_rename_jeupiece_jeuxpiecescontrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkup',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='nettoyage_exterieur',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='nettoyage_interieur',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='voiture_exemplaire',
        ),
        migrations.RemoveField(
            model_name='controlebruit',
            name='controle_general',
        ),
        migrations.RemoveField(
            model_name='controlebruit',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='controlefreins',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='jeuxpiecescontrole',
            name='controle_general',
        ),
        migrations.RemoveField(
            model_name='jeuxpiecescontrole',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='jeuxpiecescontrole',
            name='vehicule',
        ),
        migrations.RemoveField(
            model_name='nettoyageexterieur',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='voiture_exemplaire',
        ),
        migrations.RemoveField(
            model_name='notemaintenance',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='notemaintenance',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='ressortcontrole',
            name='controle_general',
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_ar',
            field=models.BooleanField(default=False, verbose_name='Disques arrière à remplacer'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_av',
            field=models.BooleanField(default=False, verbose_name='Disques avant à remplacer'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_epaisseur_disques',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques (mm)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_fentes_disques',
            field=models.BooleanField(default=False, verbose_name='Présence de fentes sur les disques'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_fuites',
            field=models.BooleanField(default=False, verbose_name='Présence de fuite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_partie',
            field=models.CharField(blank=True, choices=[('AVANT', 'Avant'), ('ARRIERE', 'Arrière'), ('AV_AR', 'Avant et arrière')], max_length=10, null=True, verbose_name='Partie contrôlée'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_plaquettes_remplacer_ar',
            field=models.BooleanField(default=False, verbose_name='Plaquettes arrière à remplacer'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_plaquettes_remplacer_av',
            field=models.BooleanField(default=False, verbose_name='Plaquettes avant à remplacer'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes',
            field=models.FloatField(default=0.0, verbose_name='Usure des plaquettes (%)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_carrosserie',
            field=models.BooleanField(default=False, verbose_name='Carrosserie'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_jantes',
            field=models.BooleanField(default=False, verbose_name='Jantes'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_traces_gomme',
            field=models.BooleanField(default=False, verbose_name='Traces de gomme'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_validation',
            field=models.BooleanField(default=False, verbose_name='Validation finale'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_aspirateur',
            field=models.BooleanField(default=False, verbose_name='Aspirateur'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_pare_brise',
            field=models.BooleanField(default=False, verbose_name='Pare-brise'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_plastiques',
            field=models.BooleanField(default=False, verbose_name='Plastiques'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_portes',
            field=models.BooleanField(default=False, verbose_name='Intérieurs de porte'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_tableau_de_bord',
            field=models.BooleanField(default=False, verbose_name='Tableau de bord'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_validation',
            field=models.BooleanField(default=False, verbose_name='Validation finale'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_vitres',
            field=models.BooleanField(default=False, verbose_name='Vitres'),
        ),
        migrations.DeleteModel(
            name='AmortisseurControle',
        ),
        migrations.DeleteModel(
            name='Checkup',
        ),
        migrations.DeleteModel(
            name='ControleBruit',
        ),
        migrations.DeleteModel(
            name='ControleFreins',
        ),
        migrations.DeleteModel(
            name='JeuxPiecesControle',
        ),
        migrations.DeleteModel(
            name='NettoyageExterieur',
        ),
        migrations.DeleteModel(
            name='NettoyageInterieur',
        ),
        migrations.DeleteModel(
            name='NoteMaintenance',
        ),
        migrations.DeleteModel(
            name='RessortControle',
        ),
    ]
