# Generated by Django 5.2.10 on 2026-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0009_remove_checkup_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux barre stabilisatrice arrière'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux barre stabilisatrice avant'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_direction_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de direction arrière droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_direction_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de direction arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de direction avant droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_direction_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de direction avant gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_arD',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_arD',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant droite'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant gauche'),
        ),
    ]
