# Generated by Django 5.2.10 on 2026-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0010_controlegeneral_biellette_barre_stabilisatrice_ard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlegeneral',
            name='freins_epaisseur_disques',
        ),
        migrations.RemoveField(
            model_name='controlegeneral',
            name='freins_fentes_disques',
        ),
        migrations.RemoveField(
            model_name='controlegeneral',
            name='freins_partie',
        ),
        migrations.RemoveField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes',
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur arrière droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur avant gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_epaisseur_disques_ar',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques arrières (mm)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_epaisseur_disques_av',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques avants (mm)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_fentes_disques_ar',
            field=models.BooleanField(default=False, verbose_name='Présence de fentes sur les disques arrières'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_fentes_disques_av',
            field=models.BooleanField(default=False, verbose_name='Présence de fentes sur les disques avants'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes_ar',
            field=models.FloatField(default=0.0, verbose_name='Usure des plaquettes arrières (%)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes_av',
            field=models.FloatField(default=0.0, verbose_name='Usure des plaquettes avants (%)'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_ar',
            field=models.BooleanField(default=False, verbose_name='Disques arrières à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_av',
            field=models.BooleanField(default=False, verbose_name='Disques avants à remplacer'),
        ),
    ]
