# Generated by Django 5.2.10 on 2026-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0011_remove_controlegeneral_freins_epaisseur_disques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='Biellette_barre_stabilisatrice_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur arrière droit'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur avant droit'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux barre amortisseur avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux barre stabilisatrice arrière'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux barre stabilisatrice avant'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='boite_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite boîte de vitesse'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='bruit_roulement',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État roulement de roue'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='direction_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite direction assistée / crémaillère'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='liquide_frein_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='moteur_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite moteur'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_direction_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de direction arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_direction_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de direction arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de direction avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_direction_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de direction avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_arD',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_inferieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_arD',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='rotule_suspension_superieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant gauche'),
        ),
    ]
