# Generated by Django 5.2.10 on 2026-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0012_alter_controlegeneral_biellette_barre_stabilisatrice_ard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlegeneral',
            name='bruit_roulement',
        ),
        migrations.RemoveField(
            model_name='controlegeneral',
            name='location_roulement',
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='bruit_roulement_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État roulement de roue arrière droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='bruit_roulement_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État roulement de roue arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='bruit_roulement_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État roulement de roue avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='bruit_roulement_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État roulement de roue avant gauche'),
        ),
    ]
