# Generated by Django 5.2.10 on 2026-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0015_controlegeneral_balais_essuie_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='pare_brise_remplacer',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise à remplacer'),
        ),
    ]
