# Generated by Django 5.2.10 on 2026-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0016_controlegeneral_pare_brise_remplacer'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='boite_bruit',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bruits boîte de vitesse'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='boite_embrayage',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Problème d'embrayage"),
        ),
    ]
