# Generated by Django 5.2.10 on 2026-03-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0017_controlegeneral_boite_bruit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='liquide_frein_etat',
            new_name='frein_liquide_frein_etat',
        ),
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='quantite_liquide_frein',
            new_name='freins_quantite_liquide_frein',
        ),
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='remplacement_liquide_frein',
            new_name='freins_remplacement_liquide_frein',
        ),
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='specif_liquide_frein',
            new_name='friens_specif_liquide_frein',
        ),
    ]
