# Generated by Django 5.2.10 on 2026-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0019_rename_biellette_barre_stabilisatrice_ard_controlegeneral_jeu_biellette_barre_stabilisatrice_ard_and'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='friens_specif_liquide_frein',
            new_name='freins_specif_liquide_frein',
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_rotule_direction_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_rotule_direction_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_rotule_direction_avg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant gauche'),
        ),
    ]
