# Generated by Django 5.2.10 on 2026-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0020_rename_friens_specif_liquide_frein_controlegeneral_freins_specif_liquide_frein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_Biellette_barre_stabilisatrice_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_Biellette_barre_stabilisatrice_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_Biellette_barre_stabilisatrice_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_Biellette_barre_stabilisatrice_avg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_amortisseur_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière droit'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_amortisseur_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_amortisseur_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant droit'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_amortisseur_avg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice arrière'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice avant'),
        ),
    ]
