# Generated by Django 5.2.10 on 2026-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0021_alter_controlegeneral_jeu_biellette_barre_stabilisatrice_ard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_validation',
        ),
        migrations.RemoveField(
            model_name='controlegeneral',
            name='nettoyage_interieur_validation',
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_carpettes',
            field=models.BooleanField(default=False, verbose_name='Carpettes'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_interieur_sieges',
            field=models.BooleanField(default=False, verbose_name='Sièges'),
        ),
    ]
