# Generated by Django 5.2.10 on 2026-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0022_remove_controlegeneral_nettoyage_exterieur_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_sechage',
            field=models.BooleanField(default=False, verbose_name='Séchage'),
        ),
    ]
