# Generated by Django 5.2.10 on 2026-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0023_controlegeneral_nettoyage_exterieur_sechage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='essuie_glace_ar',
            field=models.BooleanField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='NOT_OK', max_length=25, verbose_name='Essuie-glace AR fonctionnel'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='essuie_glace_av',
            field=models.BooleanField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='NOT_OK', max_length=25, verbose_name='Essuie-glace AV fonctionnel'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='pare_brise',
            field=models.BooleanField(verbose_name='Pare-brise sans coups'),
        ),
    ]
