# Generated by Django 5.2.10 on 2026-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0024_alter_controlegeneral_essuie_glace_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='pare_brise',
            field=models.BooleanField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='NOT_OK', max_length=25, verbose_name='Pare-brise sans coups'),
        ),
    ]
