# Generated by Django 5.2.10 on 2026-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0026_alter_controlegeneral_essuie_glace_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques arrières à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques avants à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_fentes_disques_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques arrières'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_fentes_disques_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques avants'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_fuites',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fuite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_plaquettes_remplacer_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_plaquettes_remplacer_av',
            field=models.CharField(default=False, verbose_name='Plaquettes avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_remplacement_liquide_frein',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Remplacement liquide de frein'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes_ar',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes arrières (%)'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes_av',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes avants (%)'),
        ),
    ]
