# Generated by Django 5.2.10 on 2026-03-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0027_alter_controlegeneral_freins_disques_remplacer_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlegeneral',
            name='pare_brise',
        ),
    ]
