# Generated by Django 5.2.10 on 2026-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0028_remove_controlegeneral_pare_brise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_plaquettes_remplacer_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes avant à remplacer'),
        ),
    ]
