# Generated by Django 5.2.10 on 2026-03-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0029_alter_controlegeneral_freins_plaquettes_remplacer_av'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='pare_brise_coups',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise avec coups'),
        ),
    ]
