# Generated by Django 5.2.10 on 2026-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0030_controlegeneral_pare_brise_coups'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_roulement_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_roulement_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_roulement_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_roulement_avg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_triangle_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_triangle_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_triangle_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_triangle_avg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant gauche'),
        ),
    ]
