# Generated by Django 5.2.10 on 2026-03-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0031_controlegeneral_jeu_multi_bras_avd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlegeneral',
            name='reglage_phares',
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='phares_anti_brouillard_arrière',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phares anti-brouillard arrière'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='phares_anti_brouillard_avant',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phares anti-brouillard avant'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='phares_avant',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de routes'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='phares_clignotants',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clignotants'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='phares_gros_phares',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Grand phares'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='phares_recul',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de recul'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='phares_reglages',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Réglage phares'),
        ),
    ]
