# Generated by Django 5.2.10 on 2026-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0032_remove_controlegeneral_reglage_phares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_multi_bras_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_multi_bras_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_multi_bras_avg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant droit'),
        ),
    ]
