# Generated by Django 5.2.10 on 2026-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0035_alter_controlegeneral_bruit_roulement_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='direction_fuite',
            field=models.CharField(blank=True, choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Fuite direction assistée / crémaillère'),
        ),
    ]
