# Generated by Django 5.2.10 on 2026-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0036_alter_controlegeneral_direction_fuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='pont_bruit',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bruits pont arrière'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pont_fuite',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite pont arrière'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pont_jeu',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu pont arrière'),
        ),
    ]
