# Generated by Django 5.2.10 on 2026-03-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0038_controlegeneral_kilometres_maintenance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='kilometres_maintenance',
            new_name='kilometres_checkup',
        ),
    ]
