# Generated by Django 5.2.10 on 2026-03-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0039_rename_kilometres_maintenance_controlegeneral_kilometres_checkup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='jeu_rotule_suspension_inferieure_arD',
            new_name='jeu_rotule_suspension_inferieure_ard',
        ),
        migrations.RenameField(
            model_name='controlegeneral',
            old_name='jeu_rotule_suspension_superieure_arD',
            new_name='jeu_rotule_suspension_superieure_ard',
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_Biellette_barre_stabilisatrice_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='jeu_Biellette_barre_stabilisatrice_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière gauche'),
        ),
    ]
