# Generated by Django 5.2.10 on 2026-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up',
         '0040_rename_jeu_rotule_suspension_inferieure_ard_controlegeneral_jeu_rotule_suspension_inferieure_ard_and'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlegeneral',
            name='kilometres_checkup',
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='kilometrage_checkup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du Checkup'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
