# Generated by Django 5.2.10 on 2026-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0042_remove_controlegeneral_kilometres_checkup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='moteur_niveau_huile_qualite',
            field=models.CharField(choices=[('0W30', '0W30'), ('0W40', '0W40'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W60', '10W60')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='moteur_niveau_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='kilometrage_checkup',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du Checkup'),
        ),
    ]
