# Generated by Django 5.2.10 on 2026-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0043_controlegeneral_moteur_niveau_huile_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='boite_niveau_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='75W', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='boite_niveau_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pont_niveau_huile_qualite',
            field=models.CharField(choices=[('75W140', '75W140')], default='75W140', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pont_niveau_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='moteur_niveau_huile_qualite',
            field=models.CharField(choices=[('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
    ]
