# Generated by Django 5.2.10 on 2026-03-19 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0044_controlegeneral_boite_niveau_huile_etat_and_more'),
        ('societe', '0002_alter_societe_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_epaisseur_ard',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneus arrière droit (mm)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_epaisseur_arg',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneus arrière gauche (mm)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_epaisseur_avd',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneus avant droit (mm)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_epaisseur_avg',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneus avant gauche (mm)'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_pression_bar_ard',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_pression_bar_arg',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_pression_bar_avd',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_pression_bar_avg',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu avant gauche en bar'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_sidewall_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='flanc du pneu arrière droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_sidewall_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='flanc du pneu arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_sidewall_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='flanc du pneu avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_sidewall_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='flanc du pneu avant gauche'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_train_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='NON', max_length=25, verbose_name='Train arrière à remplacer'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='pneu_train_av',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='NON', max_length=25, verbose_name='Train avant à remplacer'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='refroidissement_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité de liquide de refroidissement'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='refroidissement_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='refroidissement_radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Radiateur'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='societe.societe'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
    ]
