# Generated by Django 5.2.10 on 2026-03-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0046_rename_nom_technicien_controlegeneral_tech_nom_technicien_and_more'),
        ('societe', '0002_alter_societe_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='utilisateurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_generals', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_tech_societe', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='tech_technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_techs', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
    ]
