# Generated by Django 5.2.10 on 2026-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0047_controlegeneral_utilisateurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_carrosserie',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Carrosserie'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_jantes',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Jantes'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_sechage',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Séchage'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_exterieur_traces_gomme',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Traces de gomme'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_aspirateur',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Aspirateur'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_carpettes',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Carpettes'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_pare_brise',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Pare-brise'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_plastiques',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Plastiques'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_portes',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Intérieurs de porte'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_sieges',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Sièges'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_tableau_de_bord',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Tableau de bord'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='nettoyage_interieur_vitres',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Vitres'),
        ),
    ]
