# Generated by Django 5.2.10 on 2026-03-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0048_alter_controlegeneral_nettoyage_exterieur_carrosserie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
    ]
