# Generated by Django 5.2.10 on 2026-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0049_controlegeneral_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='pneu_epaisseur_ard',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneu arrière droit (mm)'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='pneu_epaisseur_arg',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneu arrière gauche (mm)'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='pneu_epaisseur_avd',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneu avant droit (mm)'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='pneu_epaisseur_avg',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur du pneu avant gauche (mm)'),
        ),
    ]
