# Generated by Django 5.2.10 on 2026-03-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0050_alter_controlegeneral_pneu_epaisseur_ard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlegeneral',
            name='utilisateurs',
        ),
    ]
