# Generated by Django 5.2.10 on 2026-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0051_remove_controlegeneral_utilisateurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
