# Generated by Django 5.2.10 on 2026-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0052_alter_controlegeneral_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
