# Generated by Django 5.2.10 on 2026-04-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0053_controlegeneral_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_epaisseur_disques_ar',
            field=models.FloatField(default=0, verbose_name='Épaisseur des disques arrière (mm)'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_epaisseur_disques_av',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques avant (mm)'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes_av',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes avant (%)'),
        ),
    ]
