# Generated by Django 5.2.10 on 2026-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0054_alter_controlegeneral_freins_disques_remplacer_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_disques_remplacer_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_fentes_disques_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques arrière'),
        ),
    ]
