# Generated by Django 5.2.10 on 2026-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0055_alter_controlegeneral_freins_disques_remplacer_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='phares_avant',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Feux de route'),
        ),
    ]
