# Generated by Django 5.2.10 on 2026-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0056_alter_controlegeneral_phares_avant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_fentes_disques_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques avant'),
        ),
        migrations.AlterField(
            model_name='controlegeneral',
            name='freins_usure_plaquettes_ar',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes arrière (%)'),
        ),
    ]
