# Generated by Django 5.2.10 on 2026-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0057_alter_controlegeneral_freins_fentes_disques_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegeneral',
            name='balais_essuie_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Balais avant a remplacer'),
        ),
    ]
