# Generated by Django 5.2.10 on 2026-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0059_controlegeneral_jeu_biellette_direction_avd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_arbre',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Jeu dans l'arbre de transmission"),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_cardan_ard',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_cardan_arg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_cardan_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AddField(
            model_name='controlegeneral',
            name='jeu_cardan_avg',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
    ]
