# Generated by Django 5.2.10 on 2026-05-12 12:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0061_controlegeneral_main_oeuvre'),
        ('maindoeuvre', '0007_remove_maindoeuvre_created_at_and_more'),
        ('maintenance', '0009_alter_maintenance_type_maintenance'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0018_voitureexemplaire_nombre_remplacements_moteurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControleGeneral',
            new_name='Checkup',
        ),
    ]
