# Generated by Django 5.2.10 on 2026-05-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0062_rename_controlegeneral_checkup'),
        ('maintenance', '0009_alter_maintenance_type_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkup', to='maintenance.maintenance', verbose_name='Checkup'),
        ),
    ]
