# Generated by Django 5.2.10 on 2026-05-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0064_checkup_tech_last_maintained_by'),
        ('voiture_exemplaire', '0021_alter_voitureexemplaire_voiture_moteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkup',
            name='phares_anti_brouillard_arrière',
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_anti_brouillard_arriere',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Phares anti-brouillard arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_anti_brouillard_avant',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Phares anti-brouillard avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_clignotants',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Clignotants'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_gros_phares',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Grand phares'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_recul',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Feux de recul'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_reglages',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Réglage phares'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_general_checkup_exemplaire_km', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_checkup'),
        ),
    ]
