# Generated by Django 5.2.10 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0065_remove_checkup_phares_anti_brouillard_arrière_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
