# Generated by Django 5.2.10 on 2026-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0067_alter_checkup_kilometrage_checkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='serrage_roues',
            field=models.CharField(choices=[('AFAIRE', 'À faire'), ('Fait', 'Fait')], default='AFAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
