# Generated by Django 5.2.10 on 2026-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0068_checkup_serrage_roues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF_DSG', 'ATF DSG'), ('ATF_DCT', 'ATF DCT'), ('ATF_CVT', 'ATF CVT'), ('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('ATF_MERCON', 'ATF Mercon'), ('ATF_MERCON_V', 'ATF Mercon V'), ('ATF_MERCON_LV', 'ATF Mercon LV'), ('ATF_MULTI', 'ATF Multi Vehicle'), ('ATF_WS', 'ATF Toyota WS'), ('ATF_ZF_LIFEGUARD', 'ZF Lifeguard'), ('ATF_MOPAR', 'Mopar ATF+4'), ('ATF_AISIN', 'Aisin ATF'), ('ATF_MBV236', 'Mercedes MB 236.x'), ('ATF_VOLVO', 'Volvo ATF'), ('ATF_HONDA', 'Honda ATF DW-1'), ('ATF_NISSAN', 'Nissan Matic')], default='75W', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_specif_liquide_frein',
            field=models.CharField(blank=True, choices=[('DOT3', 'DOT 3'), ('DOT4', 'DOT 4'), ('DOT5', 'DOT 5'), ('DOT51', 'DOT 5.1')], default='DOT4', max_length=100, verbose_name='Spécification liquide de frein'),
        ),
    ]
