# Generated by Django 5.2.10 on 2026-07-03 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0070_alter_checkup_pneu_epaisseur_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
    ]
