# Generated by Django 5.2.10 on 2026-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0071_alter_checkup_boite_niveau_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='feux_stops',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Feux stop'),
        ),
    ]
