# Generated by Django 5.2.10 on 2026-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0073_alter_checkup_boite_niveau_huile_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='feux_position_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Feux de position arrière'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='feux_position_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Feux de position avant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='troisieme_feux_stop',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Troisième feux stop'),
        ),
    ]
