# Generated by Django 5.2.10 on 2026-07-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0074_checkup_feux_position_ar_checkup_feux_position_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='feux_position_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de position arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='feux_position_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de position avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='feux_stops',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux stop'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_anti_brouillard_arriere',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phares anti-brouillard arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_anti_brouillard_avant',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phares anti-brouillard avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_avant',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de route'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_clignotants',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clignotants'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_gros_phares',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Grand phares'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_recul',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de recul'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='phares_reglages',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Réglage phares'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_qualite',
            field=models.CharField(choices=[('75W140', '75W140'), ('75W90', 'Porsche 75W90')], default='75W140', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='troisieme_feux_stop',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Troisième feux stop'),
        ),
    ]
