# Generated by Django 5.2.10 on 2026-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0076_alter_checkup_serrage_roues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='balais_essuie_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Balai arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='balais_essuie_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Balais avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='batterie_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État batterie'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_bruit',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bruits boîte de vitesse'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_embrayage',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Problème d'embrayage"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite boîte de vitesse'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_ard',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_arg',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_avd',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_avg',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='direction_fuite',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Fuite direction assistée / crémaillère'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='essuie_glace_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Essuie-glace AR fonctionnel'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='essuie_glace_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Essuie-glace AV fonctionnel'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='frein_liquide_frein_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_remplacer_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_remplacer_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_fentes_disques_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_fentes_disques_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_fuites',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fuite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_remplacer_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_remplacer_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_remplacement_liquide_frein',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Remplacement liquide de frein'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_arbre',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Jeu dans l'arbre de transmission"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_biellette_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de direction droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_biellette_direction_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de direction gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_bruit',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bruit moteur'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_casse',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Moteur à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite moteur'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_perte',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Perte de puissance'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pare_brise_coups',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise sans coups'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pare_brise_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat du Pare-brise'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_sidewall_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flanc du pneu arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_sidewall_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flanc du pneu arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_sidewall_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flanc du pneu avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_sidewall_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flanc du pneu avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_train_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Train arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_train_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Train avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_bruit',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bruits pont arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite pont arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_jeu',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu pont arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Radiateur'),
        ),
    ]
