# Generated by Django 5.2.10 on 2026-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0078_checkup_taux_horaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_epaisseur_disques_ar',
            new_name='freins_disques_ar_epaisseur',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_fentes_disques_ar',
            new_name='freins_disques_ar_fentes',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_disques_remplacer_ar',
            new_name='freins_disques_ar_remplacer',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_epaisseur_disques_av',
            new_name='freins_disques_av_epaisseur',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_fentes_disques_av',
            new_name='freins_disques_av_fentes',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_disques_remplacer_av',
            new_name='freins_disques_av_remplacer',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_plaquettes_remplacer_ar',
            new_name='freins_plaquettes_ar_remplacer',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_usure_plaquettes_ar',
            new_name='freins_plaquettes_ar_usure',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_plaquettes_remplacer_av',
            new_name='freins_plaquettes_av_remplacer',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_usure_plaquettes_av',
            new_name='freins_plaquettes_av_usure',
        ),
        migrations.AddField(
            model_name='checkup',
            name='boite_niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='MOBIL', max_length=25, verbose_name="Fabricant de l'huile de boite de vitesse"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='boite_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de l'huile de boite de vitesse"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_disques_ar_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des disques arrière'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_disques_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat des disques arrière HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_disques_ar_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_disques_av_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des disques avant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_disques_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat des disques avant HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_disques_av_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_plaquettes_ar_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des plaquettes arrière'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_plaquettes_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat des plaquettes arrière HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_plaquettes_ar_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_plaquettes_av_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des plaquettes avant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_plaquettes_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat des plaquettes avant HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='freins_plaquettes_av_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='moteur_niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='MOBIL', max_length=25, verbose_name="Fabricant de l'huile moteur"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='moteur_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de l'huile moteur"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pont_niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='MOBIL', max_length=25, verbose_name="Fabricant de l'huile de pont"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pont_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de l'huile de pont"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='refroidissement_fabricant',
            field=models.CharField(choices=[('ABRO', 'ABRO'), ('AISIN', 'AISIN'), ('ARECA', 'Areca'), ('BARDAHL', 'Bardahl'), ('BASF_GLYSANTIN', 'BASF Glysantin'), ('BEL_RAY', 'Bel-Ray'), ('BIZOL', 'BIZOL'), ('BMW', 'BMW'), ('BOLK', 'BOLK'), ('BOSCH', 'Bosch'), ('CASTROL', 'Castrol'), ('CHAMPION', 'Champion'), ('COMMA', 'Comma'), ('ELF', 'ELF'), ('EUROL', 'Eurol'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('FUCHS', 'Fuchs'), ('GATES', 'Gates'), ('GENERAL_MOTORS', 'General Motors'), ('HEPU', 'HEPU'), ('HOLTS', 'Holts'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('IGOL', 'Igol'), ('IPONE', 'IPONE'), ('K2', 'K2'), ('KIA', 'Kia'), ('LIQUI_MOLY', 'Liqui Moly'), ('MANNOL', 'Mannol'), ('MAZDA', 'Mazda'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('MEYLE', 'Meyle'), ('MILLERS_OILS', 'Millers Oils'), ('MITSUBISHI', 'Mitsubishi'), ('MOBIL', 'Mobil'), ('MOPAR', 'Mopar'), ('MOTIP', 'Motip'), ('MOTOREX', 'Motorex'), ('MOTUL', 'Motul'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('ORLEN', 'Orlen'), ('PEMCO', 'Pemco'), ('PEUGEOT_CITROEN', 'Peugeot Citroën'), ('PETRONAS', 'Petronas'), ('PORSCHE', 'Porsche'), ('PRESTONE', 'Prestone'), ('PUTOLINE', 'Putoline'), ('RAVENOL', 'Ravenol'), ('REPSOL', 'Repsol'), ('RENAULT', 'Renault'), ('ROWE', 'ROWE'), ('SHELL', 'Shell'), ('SONAX', 'Sonax'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('SWAG', 'SWAG'), ('TEXACO', 'Texaco'), ('TOTALENERGIES', 'TotalEnergies'), ('TOYOTA', 'Toyota'), ('TRIPLE_QX', 'Triple QX'), ('VALEO', 'Valeo'), ('VALVOLINE', 'Valvoline'), ('VAG', 'Volkswagen Audi Group'), ('VOLVO', 'Volvo'), ('WOLF', 'Wolf'), ('XENUM', 'Xenum'), ('YACCO', 'Yacco'), ('YAMAHA', 'Yamaha'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant du liquide de refroidissement'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='refroidissement_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva du liquide de refroidissement"),
        ),
    ]
