# Generated by Django 5.2.10 on 2026-07-23 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0079_rename_freins_epaisseur_disques_ar_checkup_freins_disques_ar_epaisseur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_specif_liquide_frein',
            new_name='freins_liquide_specif',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='freins_quantite_liquide_frein',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='freins_remplacement_liquide_frein',
        ),
        migrations.AddField(
            model_name='checkup',
            name='frein_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='CASTROL', max_length=25, verbose_name='Fabricant du liquide de frein'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='frein_liquide_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat du liquide HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='frein_liquide_quantite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité liquide de frein (L)'),
        ),
    ]
