# Generated by Django 5.2.10 on 2026-07-23 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0080_rename_freins_specif_liquide_frein_checkup_freins_liquide_specif_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='niveau_direction',
            new_name='direction_niveau',
        ),
        migrations.AddField(
            model_name='checkup',
            name='direction_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='direction_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='CASTROL', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='direction_liquide_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='direction_liquide_qualite',
            field=models.CharField(choices=[('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('LDS', 'LDS'), ('LHM', 'LHM'), ('PSF', 'PSF'), ('PSF_3', 'PSF-3'), ('PSF_4', 'PSF-4'), ('MB_236_3', 'Mercedes-Benz 236.3'), ('MB_345_0', 'Mercedes-Benz 345.0'), ('VW_G002000', 'Volkswagen G 002 000'), ('VW_G004000', 'Volkswagen G 004 000'), ('BMW_ATF', 'BMW ATF'), ('BMW_CHF', 'BMW CHF'), ('HONDA_PSF', 'Honda PSF'), ('TOYOTA_PSF', 'Toyota PSF'), ('MINERALE', 'Huile minérale'), ('SEMI_SYNTHETIQUE', 'Huile semi-synthétique'), ('SYNTHETIQUE', 'Huile synthétique'), ('CONSTRUCTEUR', 'Spécification constructeur'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Qualité de liquide de direction'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='direction_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de direction ajoutée en litres'),
        ),
    ]
