# Generated by Django 5.2.10 on 2026-07-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0081_rename_niveau_direction_checkup_direction_niveau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='direction_fuite',
            new_name='direction_liquide_fuite',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='direction_niveau',
            new_name='direction_liquide_niveau',
        ),
    ]
