# Generated by Django 5.2.10 on 2026-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0082_rename_direction_fuite_checkup_direction_liquide_fuite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='jeu_rotule_direction_avd_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='jeu_rotule_direction_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='jeu_rotule_direction_avd_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantite'),
        ),
    ]
