# Generated by Django 5.2.10 on 2026-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0086_rename_feux_position_ar_checkup_phares_feux_position_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='pneu_train_ar_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir un fabricant'), ('ACHILLES', 'Achilles'), ('APOLLO', 'Apollo'), ('ARMSTRONG', 'Armstrong'), ('ATTURO', 'Atturo'), ('AUSTONE', 'Austone'), ('AVON', 'Avon'), ('BARUM', 'Barum'), ('BFGOODRICH', 'BFGoodrich'), ('BRIDGESTONE', 'Bridgestone'), ('CEAT', 'CEAT'), ('CHAOYANG', 'Chaoyang'), ('CONTINENTAL', 'Continental'), ('COOPER', 'Cooper'), ('CORDIANT', 'Cordiant'), ('CST', 'CST'), ('DAVANTI', 'Davanti'), ('DAYTON', 'Dayton'), ('DEBICA', 'Dębica'), ('DOUBLE_COIN', 'Double Coin'), ('DUNLOP', 'Dunlop'), ('DURATURN', 'Duraturn'), ('EP_TYRES', 'EP Tyres'), ('EVENT', 'Event'), ('FALKEN', 'Falken'), ('FEDERAL', 'Federal'), ('FIREMAX', 'Firemax'), ('FIRESTONE', 'Firestone'), ('FORTUNA', 'Fortuna'), ('FULDA', 'Fulda'), ('GENERAL_TIRE', 'General Tire'), ('GITI', 'Giti'), ('GISLAVED', 'Gislaved'), ('GOFORM', 'Goform'), ('GOODYEAR', 'Goodyear'), ('GRENLANDER', 'Grenlander'), ('GT_RADIAL', 'GT Radial'), ('HANKOOK', 'Hankook'), ('HAIDA', 'Haida'), ('HIFLY', 'Hifly'), ('INFINITY', 'Infinity'), ('KELLY', 'Kelly'), ('KENDA', 'Kenda'), ('KETER', 'Keter'), ('KLEBER', 'Kleber'), ('KORMORAN', 'Kormoran'), ('KUMHO', 'Kumho'), ('LANDSAIL', 'Landsail'), ('LAUFENN', 'Laufenn'), ('LEXANI', 'Lexani'), ('LINGLONG', 'Linglong'), ('MARSHAL', 'Marshal'), ('MATADOR', 'Matador'), ('MAXXIS', 'Maxxis'), ('MICHELIN', 'Michelin'), ('MILESTONE', 'Milestone'), ('MINERVA', 'Minerva'), ('MITAS', 'Mitas'), ('MOMO', 'MOMO'), ('NANKANG', 'Nankang'), ('NEXEN', 'Nexen'), ('NOKIAN', 'Nokian Tyres'), ('NORDEXX', 'Nordexx'), ('OVATION', 'Ovation'), ('PETLAS', 'Petlas'), ('PIRELLI', 'Pirelli'), ('POWERTRAC', 'Powertrac'), ('PREMIORRI', 'Premiorri'), ('RADAR', 'Radar'), ('RAPID', 'Rapid'), ('RIKEN', 'Riken'), ('ROADSTONE', 'Roadstone'), ('ROCKBLADE', 'Rockblade'), ('ROTALLA', 'Rotalla'), ('SAILUN', 'Sailun'), ('SEMPERIT', 'Semperit'), ('SAVA', 'Sava'), ('STAR_PERFORMER', 'Star Performer'), ('SUMITOMO', 'Sumitomo'), ('SUNNY', 'Sunny'), ('TOYO', 'Toyo'), ('TRIANGLE', 'Triangle'), ('TRISTAR', 'Tristar'), ('TUNGA', 'Tunga'), ('UNIROYAL', 'Uniroyal'), ('VIKING', 'Viking'), ('VREDESTEIN', 'Vredestein'), ('WANLI', 'Wanli'), ('WESTLAKE', 'Westlake'), ('WINDFORCE', 'Windforce'), ('YOKOHAMA', 'Yokohama'), ('ZEETEX', 'Zeetex'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Manufacturier'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_train_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_train_ar_quantite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_train_av_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir un fabricant'), ('ACHILLES', 'Achilles'), ('APOLLO', 'Apollo'), ('ARMSTRONG', 'Armstrong'), ('ATTURO', 'Atturo'), ('AUSTONE', 'Austone'), ('AVON', 'Avon'), ('BARUM', 'Barum'), ('BFGOODRICH', 'BFGoodrich'), ('BRIDGESTONE', 'Bridgestone'), ('CEAT', 'CEAT'), ('CHAOYANG', 'Chaoyang'), ('CONTINENTAL', 'Continental'), ('COOPER', 'Cooper'), ('CORDIANT', 'Cordiant'), ('CST', 'CST'), ('DAVANTI', 'Davanti'), ('DAYTON', 'Dayton'), ('DEBICA', 'Dębica'), ('DOUBLE_COIN', 'Double Coin'), ('DUNLOP', 'Dunlop'), ('DURATURN', 'Duraturn'), ('EP_TYRES', 'EP Tyres'), ('EVENT', 'Event'), ('FALKEN', 'Falken'), ('FEDERAL', 'Federal'), ('FIREMAX', 'Firemax'), ('FIRESTONE', 'Firestone'), ('FORTUNA', 'Fortuna'), ('FULDA', 'Fulda'), ('GENERAL_TIRE', 'General Tire'), ('GITI', 'Giti'), ('GISLAVED', 'Gislaved'), ('GOFORM', 'Goform'), ('GOODYEAR', 'Goodyear'), ('GRENLANDER', 'Grenlander'), ('GT_RADIAL', 'GT Radial'), ('HANKOOK', 'Hankook'), ('HAIDA', 'Haida'), ('HIFLY', 'Hifly'), ('INFINITY', 'Infinity'), ('KELLY', 'Kelly'), ('KENDA', 'Kenda'), ('KETER', 'Keter'), ('KLEBER', 'Kleber'), ('KORMORAN', 'Kormoran'), ('KUMHO', 'Kumho'), ('LANDSAIL', 'Landsail'), ('LAUFENN', 'Laufenn'), ('LEXANI', 'Lexani'), ('LINGLONG', 'Linglong'), ('MARSHAL', 'Marshal'), ('MATADOR', 'Matador'), ('MAXXIS', 'Maxxis'), ('MICHELIN', 'Michelin'), ('MILESTONE', 'Milestone'), ('MINERVA', 'Minerva'), ('MITAS', 'Mitas'), ('MOMO', 'MOMO'), ('NANKANG', 'Nankang'), ('NEXEN', 'Nexen'), ('NOKIAN', 'Nokian Tyres'), ('NORDEXX', 'Nordexx'), ('OVATION', 'Ovation'), ('PETLAS', 'Petlas'), ('PIRELLI', 'Pirelli'), ('POWERTRAC', 'Powertrac'), ('PREMIORRI', 'Premiorri'), ('RADAR', 'Radar'), ('RAPID', 'Rapid'), ('RIKEN', 'Riken'), ('ROADSTONE', 'Roadstone'), ('ROCKBLADE', 'Rockblade'), ('ROTALLA', 'Rotalla'), ('SAILUN', 'Sailun'), ('SEMPERIT', 'Semperit'), ('SAVA', 'Sava'), ('STAR_PERFORMER', 'Star Performer'), ('SUMITOMO', 'Sumitomo'), ('SUNNY', 'Sunny'), ('TOYO', 'Toyo'), ('TRIANGLE', 'Triangle'), ('TRISTAR', 'Tristar'), ('TUNGA', 'Tunga'), ('UNIROYAL', 'Uniroyal'), ('VIKING', 'Viking'), ('VREDESTEIN', 'Vredestein'), ('WANLI', 'Wanli'), ('WESTLAKE', 'Westlake'), ('WINDFORCE', 'Windforce'), ('YOKOHAMA', 'Yokohama'), ('ZEETEX', 'Zeetex'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Manufacturier'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_train_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_train_av_quantite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_train_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneus arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pneu_train_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneus avant à remplacer'),
        ),
    ]
