# Generated by Django 5.2.10 on 2026-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0087_checkup_pneu_train_ar_fabricant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_exterieur_produits_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_exterieur_produits_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_interieur_produits_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='nettoyage_interieur_produits_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
