# Generated by Django 5.2.10 on 2026-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0090_alter_checkup_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='pneu_bande_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneu arrière droit'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_bande_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneu arrière gauche'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_bande_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneu avant droit'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pneu_bande_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneu avant gauche'),
        ),
    ]
