# Generated by Django 5.2.10 on 2026-08-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0091_checkup_pneu_bande_ard_checkup_pneu_bande_arg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='frein_liquide_fabricant',
            new_name='freins_liquide_fabricant',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='frein_liquide_frein_etat',
            new_name='freins_liquide_frein_etat',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_fuites',
            new_name='freins_liquide_fuites',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='frein_liquide_prix',
            new_name='freins_liquide_prix',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='frein_liquide_quantite',
            new_name='freins_liquide_quantite',
        ),
    ]
