# Generated by Django 5.2.10 on 2026-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0092_rename_frein_liquide_fabricant_checkup_freins_liquide_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
    ]
