# Generated by Django 5.2.10 on 2026-08-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0093_alter_checkup_nettoyage_exterieur_produits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='pare_brise_coups',
            new_name='pare_brise_av_coups',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='balais_essuie_ar',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='balais_essuie_av',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='essuie_glace_ar',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='essuie_glace_av',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='pare_brise_remplacer',
        ),
        migrations.AddField(
            model_name='checkup',
            name='balais_essuie',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat des balais arrières'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='balais_essuie_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='balais_essuie_quantite',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='essuie_glace',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat des balais avant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='essuie_glace_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='essuie_glace_quantite',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pare_brise_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pare_brise_av_quantite',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='pare_brise_av_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise à remplacer'),
        ),
    ]
