# Generated by Django 5.2.10 on 2026-08-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0094_rename_pare_brise_coups_checkup_pare_brise_av_coups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='freins_liquide_frein_etat',
            new_name='freins_liquide_etat',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='direction_liquide_niveau',
        ),
    ]
