# Generated by Django 5.2.10 on 2026-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0096_checkup_batterie_ampere_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='phares_reglages',
            field=models.CharField(choices=[('OK', 'OK'), ('FAIT', 'Fait'), ('A_FAIRE', 'A faire')], default='OK', max_length=25, verbose_name='Réglage des phares'),
        ),
    ]
