# Generated by Django 5.2.10 on 2026-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0099_alter_checkup_boite_niveau_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='balais_essuie_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='essuie_glace_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pare_brise_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
    ]
