# Generated by Django 5.2.10 on 2026-08-18 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0100_alter_checkup_balais_essuie_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='MOBIL', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='direction_liquide_qualite',
            field=models.CharField(choices=[('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('LDS', 'LDS'), ('LHM', 'LHM'), ('PSF', 'PSF'), ('PSF_3', 'PSF-3'), ('PSF_4', 'PSF-4'), ('MB_236_3', 'Mercedes-Benz 236.3'), ('MB_345_0', 'Mercedes-Benz 345.0'), ('VW_G002000', 'Volkswagen G 002 000'), ('VW_G004000', 'Volkswagen G 004 000'), ('BMW_ATF', 'BMW ATF'), ('BMW_CHF', 'BMW CHF'), ('HONDA_PSF', 'Honda PSF'), ('TOYOTA_PSF', 'Toyota PSF'), ('MINERALE', 'Huile minérale'), ('SEMI_SYNTHETIQUE', 'Huile semi-synthétique'), ('SYNTHETIQUE', 'Huile synthétique'), ('CONSTRUCTEUR', 'Spécification constructeur'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='direction_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_ar_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_av_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CASTROL', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_liquide_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_liquide_quantite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_ar_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_av_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='MOBIL', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='MOBIL', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_fabricant',
            field=models.CharField(choices=[('ABRO', 'ABRO'), ('AISIN', 'AISIN'), ('ARECA', 'Areca'), ('BARDAHL', 'Bardahl'), ('BASF_GLYSANTIN', 'BASF Glysantin'), ('BEL_RAY', 'Bel-Ray'), ('BIZOL', 'BIZOL'), ('BMW', 'BMW'), ('BOLK', 'BOLK'), ('BOSCH', 'Bosch'), ('CASTROL', 'Castrol'), ('CHAMPION', 'Champion'), ('COMMA', 'Comma'), ('ELF', 'ELF'), ('EUROL', 'Eurol'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('FUCHS', 'Fuchs'), ('GATES', 'Gates'), ('GENERAL_MOTORS', 'General Motors'), ('HEPU', 'HEPU'), ('HOLTS', 'Holts'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('IGOL', 'Igol'), ('IPONE', 'IPONE'), ('K2', 'K2'), ('KIA', 'Kia'), ('LIQUI_MOLY', 'Liqui Moly'), ('MANNOL', 'Mannol'), ('MAZDA', 'Mazda'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('MEYLE', 'Meyle'), ('MILLERS_OILS', 'Millers Oils'), ('MITSUBISHI', 'Mitsubishi'), ('MOBIL', 'Mobil'), ('MOPAR', 'Mopar'), ('MOTIP', 'Motip'), ('MOTOREX', 'Motorex'), ('MOTUL', 'Motul'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('ORLEN', 'Orlen'), ('PEMCO', 'Pemco'), ('PEUGEOT_CITROEN', 'Peugeot Citroën'), ('PETRONAS', 'Petronas'), ('PORSCHE', 'Porsche'), ('PRESTONE', 'Prestone'), ('PUTOLINE', 'Putoline'), ('RAVENOL', 'Ravenol'), ('REPSOL', 'Repsol'), ('RENAULT', 'Renault'), ('ROWE', 'ROWE'), ('SHELL', 'Shell'), ('SONAX', 'Sonax'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('SWAG', 'SWAG'), ('TEXACO', 'Texaco'), ('TOTALENERGIES', 'TotalEnergies'), ('TOYOTA', 'Toyota'), ('TRIPLE_QX', 'Triple QX'), ('VALEO', 'Valeo'), ('VALVOLINE', 'Valvoline'), ('VAG', 'Volkswagen Audi Group'), ('VOLVO', 'Volvo'), ('WOLF', 'Wolf'), ('XENUM', 'Xenum'), ('YACCO', 'Yacco'), ('YAMAHA', 'Yamaha'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricantt'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité de liquide'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
    ]
