# Generated by Django 5.2.10 on 2026-08-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0102_checkup_balais_essuie_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_qualite',
            field=models.CharField(choices=[('75W80', '75W80'), ('75W85', '75W85'), ('75W90', '75W90'), ('75W110', '75W110'), ('75W140', '75W140'), ('80W90', '80W90'), ('80W140', '80W140'), ('85W90', '85W90'), ('85W140', '85W140'), ('SAE90', 'SAE 90'), ('SAE140', 'SAE 140'), ('PORSCHE_75W90', 'Porsche 75W90'), ('PORSCHE_75W140', 'Porsche 75W140'), ('AUTRE', 'Autre'), ('INCONNUE', 'Huile inconnue')], default='75W80', max_length=25, verbose_name="Qualité d'huile"),
        ),
    ]
