# Generated by Django 5.2.10 on 2026-08-19 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0105_alter_checkup_refroidissement_fabricant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='direction_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_liquide_quantite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
    ]
