# Generated by Django 5.2.10 on 2026-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0107_alter_checkup_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='phares_anti_brouillard_arriere_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_anti_brouillard_avant_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_avant_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Feux de route'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_clignotants_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_feux_position_ar_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_feux_position_av_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_feux_stops_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_gros_phares_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_recul_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='phares_troisieme_feux_stop_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
