# Generated by Django 5.2.10 on 2026-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0109_alter_checkup_phares_avant_fabricant'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
