# Generated by Django 5.2.10 on 2026-08-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0111_rename_refroidissement_fabricant_checkup_refroidissement_liquide_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Radiateur'),
        ),
    ]
