# Generated by Django 5.2.10 on 2026-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0113_alter_checkup_direction_liquide_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_ard',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('BRUIT', 'Petit bruit'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_arg',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('BRUIT', 'Petit bruit'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_avd',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('BRUIT', 'Petit bruit'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='bruit_roulement_avg',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('BRUIT', 'Petit bruit'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='État roulement de roue avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_Biellette_barre_stabilisatrice_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_arbre',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Jeu dans l'arbre de transmission"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_biellette_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de direction droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_biellette_direction_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de direction gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_cardan_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu du cardan avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_multi_bras_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_direction_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_inferieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure avant droite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_rotule_suspension_superieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_roulement_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant droit'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='jeu_triangle_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant gauche'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouter les produits')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouter les produits')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_jeu',
            field=models.CharField(choices=[('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu pont arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_liquide_fabricant',
            field=models.CharField(choices=[('ABRO', 'ABRO'), ('AISIN', 'AISIN'), ('ARECA', 'Areca'), ('BARDAHL', 'Bardahl'), ('BASF_GLYSANTIN', 'BASF Glysantin'), ('BEL_RAY', 'Bel-Ray'), ('BIZOL', 'BIZOL'), ('BMW', 'BMW'), ('BOLK', 'BOLK'), ('BOSCH', 'Bosch'), ('CASTROL', 'Castrol'), ('CHAMPION', 'Champion'), ('COMMA', 'Comma'), ('ELF', 'ELF'), ('EUROL', 'Eurol'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('FUCHS', 'Fuchs'), ('GATES', 'Gates'), ('GENERAL_MOTORS', 'General Motors'), ('HEPU', 'HEPU'), ('HOLTS', 'Holts'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('IGOL', 'Igol'), ('IPONE', 'IPONE'), ('K2', 'K2'), ('KIA', 'Kia'), ('LIQUI_MOLY', 'Liqui Moly'), ('MANNOL', 'Mannol'), ('MAZDA', 'Mazda'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('MEYLE', 'Meyle'), ('MILLERS_OILS', 'Millers Oils'), ('MITSUBISHI', 'Mitsubishi'), ('MOBIL', 'Mobil'), ('MOPAR', 'Mopar'), ('MOTIP', 'Motip'), ('MOTOREX', 'Motorex'), ('MOTUL', 'Motul'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('ORLEN', 'Orlen'), ('PEMCO', 'Pemco'), ('PEUGEOT_CITROEN', 'Peugeot Citroën'), ('PETRONAS', 'Petronas'), ('PORSCHE', 'Porsche'), ('PRESTONE', 'Prestone'), ('PUTOLINE', 'Putoline'), ('RAVENOL', 'Ravenol'), ('REPSOL', 'Repsol'), ('RENAULT', 'Renault'), ('ROWE', 'ROWE'), ('SHELL', 'Shell'), ('SONAX', 'Sonax'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('SWAG', 'SWAG'), ('TEXACO', 'Texaco'), ('TOTALENERGIES', 'TotalEnergies'), ('TOYOTA', 'Toyota'), ('TRIPLE_QX', 'Triple QX'), ('VALEO', 'Valeo'), ('VALVOLINE', 'Valvoline'), ('VAG', 'VAG'), ('VOLVO', 'Volvo'), ('WOLF', 'Wolf'), ('XENUM', 'Xenum'), ('YACCO', 'Yacco'), ('YAMAHA', 'Yamaha'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
