# Generated by Django 5.2.10 on 2026-09-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0114_alter_checkup_bruit_roulement_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_ar_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('DIXCEL', 'Dixcel'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_av_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('DIXCEL', 'Dixcel'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_ar_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('DIXCEL', 'Dixcel'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_av_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('DIXCEL', 'Dixcel'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
