# Generated by Django 5.2.10 on 2026-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0117_alter_checkup_jeu_biellette_barre_stabilisatrice_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='balais_essuie',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Etat des balais arrières'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_bruit',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Bruits boîte de vitesse'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_embrayage',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Problème d'embrayage"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='boite_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Fuite boîte de vitesse'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='direction_liquide_fuite',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, null=True, verbose_name='Fuite direction assistée / crémaillère'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='essuie_glace',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Etat des balais avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_ar_fentes',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_ar_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Disques arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_av_fentes',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_disques_av_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Disques avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_liquide_fuites',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Présence de fuite'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_ar_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Plaquettes arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='freins_plaquettes_av_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Plaquettes avant'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_bruit',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Bruit moteur'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_casse',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Moteur à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Fuite moteur'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_perte',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Perte de puissance'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pare_brise_av_coups',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pare-brise sans coups'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pare_brise_av_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pare-brise à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_bruit',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Bruits pont arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_fuite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Fuite pont arrière'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Radiateur'),
        ),
    ]
