# Generated by Django 5.2.10 on 2026-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0118_alter_checkup_balais_essuie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
