# Generated by Django 5.2.10 on 2026-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0119_checkup_kilometres_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='kilometres_boite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkup',
            name='kilometres_boite_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback boite'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='kilometres_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkup',
            name='kilometres_rollback_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback boite'),
        ),
    ]
