# Generated by Django 5.2.10 on 2026-09-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0120_checkup_kilometres_boite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='kilometres_rollback_moteur',
            new_name='kilometres_moteur_rollback',
        ),
    ]
