# Generated by Django 5.2.10 on 2026-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0121_rename_kilometres_rollback_moteur_checkup_kilometres_moteur_rollback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='kilometres_moteur_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback moteur'),
        ),
    ]
