# Generated by Django 5.2.10 on 2026-09-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0123_rename_kilometres_moteur_rollback_checkup_kilometres_m_rollback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='kilometres_m_rollback',
            new_name='kilometres_moteur_rollback',
        ),
    ]
