# Generated by Django 5.2.10 on 2026-09-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0127_alter_checkup_refroidissement_liquide_qualite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='moteur_bruit',
            new_name='moteur_diag_bruit',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='moteur_casse',
            new_name='moteur_diag_casse',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='moteur_fuite',
            new_name='moteur_diag_fuite',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='moteur_perte',
            new_name='moteur_diag_perte',
        ),
    ]
