# Generated by Django 5.2.10 on 2026-09-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0128_rename_moteur_bruit_checkup_moteur_diag_bruit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='boite_bruit',
            new_name='boite_diag_bruit',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='boite_embrayage',
            new_name='boite_diag_embrayage',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='boite_fuite',
            new_name='boite_diag_fuite',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='pont_bruit',
            new_name='pont_diag_bruit',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='pont_fuite',
            new_name='pont_diag_fuite',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='pont_jeu',
            new_name='pont_diag_jeu',
        ),
    ]
