# Generated by Django 5.2.10 on 2026-10-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0130_alter_checkup_boite_niveau_huile_qualite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='balais_essuie_prix',
            new_name='essuie_galce_ar_prix',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='balais_essuie',
            new_name='essuie_glace_ar',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='balais_essuie_fabricant',
            new_name='essuie_glace_ar_fabricant',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='balais_essuie_quantite',
            new_name='essuie_glace_ar_quantite',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='essuie_glace',
            new_name='essuie_glace_av',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='essuie_glace_fabricant',
            new_name='essuie_glace_av_fabricant',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='essuie_glace_prix',
            new_name='essuie_glace_av_prix',
        ),
        migrations.RenameField(
            model_name='checkup',
            old_name='essuie_glace_quantite',
            new_name='essuie_glace_av_quantite',
        ),
    ]
