# Generated by Django 5.2.10 on 2026-10-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0131_rename_balais_essuie_prix_checkup_essuie_galce_ar_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkup',
            old_name='essuie_galce_ar_prix',
            new_name='essuie_glace_ar_prix',
        ),
    ]
