# Generated by Django 5.2.10 on 2026-10-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0133_checkup_lave_glace_liquide_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='direction_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
    ]
