# Generated by Django 5.2.10 on 2026-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_up', '0137_checkup_phares_eclaire_plaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='refroidissement_liquide',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('AJOUTER', 'Ajouté'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Liquide de refroidissement '),
        ),
    ]
