# Generated by Django 5.2.10 on 2026-02-04 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureFreins',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marque_disques_av', models.CharField(blank=True, max_length=100, null=True)),
                ('marque_plaquettes_av', models.CharField(blank=True, max_length=100, null=True)),
                ('taille_disque_av', models.FloatField(blank=True, null=True, verbose_name='Taille disque AV (mm)')),
                ('epaisseur_disque_av', models.FloatField(blank=True, null=True, verbose_name='Épaisseur disque AV (mm)')),
                ('epaisseur_min_disque_av', models.FloatField(blank=True, null=True, verbose_name='Épaisseur minimum disque AV (mm)')),
                ('plaquettes_av', models.FloatField(blank=True, null=True, verbose_name='Plaquettes AV (mm)')),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='freins', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'verbose_name': 'Voiture – Freins',
                'verbose_name_plural': 'Voitures – Freins',
            },
        ),
    ]
