# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureFreins',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taille_disque_av', models.FloatField(verbose_name='Taille disque AV (mm)')),
                ('taille_disque_ar', models.FloatField(verbose_name='Taille disque AR (mm)')),
                ('epaisseur_disque_av', models.FloatField(verbose_name='Épaisseur disque AV (mm)')),
                ('epaisseur_disque_ar', models.FloatField(verbose_name='Épaisseur disque AR (mm)')),
                ('epaisseur_min_disque_av', models.FloatField(verbose_name='Épaisseur minimum disque AV (mm)')),
                ('epaisseur_min_disque_ar', models.FloatField(verbose_name='Épaisseur minimum disque AR (mm)')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freins', to='voiture_exemplaire.voitureexemplaire', verbose_name='Voiture exemplaire')),
                ('voiture_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freins', to='voiture_modele.voituremodele', verbose_name='Voiture modèle')),
            ],
            options={
                'verbose_name': 'Voiture – freins',
                'verbose_name_plural': 'Voitures – freins',
            },
        ),
    ]
