# Generated by Django 5.2.10 on 2026-03-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_freins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturefreins',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friens', to='societe.societe'),
        ),
    ]
