# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtre',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_filtre', models.CharField(choices=[('AIR', 'Filtre à air'), ('HUILE', 'Filtre à huile'), ('CARBURANT', 'Filtre à carburant'), ('POLLEN', 'Filtre à pollen')], max_length=20, verbose_name='Type de filtre')),
                ('nom_filtre', models.CharField(blank=True, max_length=100, verbose_name='Nom du filtre')),
            ],
            options={
                'verbose_name': 'Filtre',
                'verbose_name_plural': 'Filtres',
            },
            bases=('piece.piece',),
        ),
    ]
