# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Differentiel',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_differentiel', models.CharField(choices=[('huile_differentiel', 'Huile de différentiel'), ('arbre_transmission', 'Arbre de transmission'), ('joint', 'Joint'), ('vidange', 'Vidange'), ('couronne_pignon', 'Couronne et pignon'), ('roulements_differentiel', 'Roulements de différentiel'), ('carter_differentiel', 'Carter de différentiel'), ('visserie', 'Visserie'), ('soufflet', 'Soufflet'), ('synchroniseur', 'Synchroniseur'), ('axe_satellite', 'Axe satellite'), ('satellites_planetaires', 'Satellites planétaires')], max_length=50, verbose_name='Type de pièce de différentiel')),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='differentiels', to='voiture_moteur.moteurvoiture', verbose_name='Moteurs compatibles')),
            ],
            options={
                'verbose_name': 'Pièce de différentiel',
                'verbose_name_plural': 'Pièces de différentiel',
            },
            bases=('piece.piece',),
        ),
    ]
