# Generated by Django 5.2.10 on 2026-04-28 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindoeuvre',
            options={},
        ),
        migrations.AlterField(
            model_name='maindoeuvre',
            name='temps',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='maindoeuvre',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_oeuvres', to=settings.AUTH_USER_MODEL),
        ),
    ]
