# Generated by Django 5.2.10 on 2026-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0002_alter_maindoeuvre_options_alter_maindoeuvre_temps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindoeuvre',
            name='temps',
        ),
        migrations.AddField(
            model_name='maindoeuvre',
            name='temps_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
