# Generated by Django 5.2.10 on 2026-04-29 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0004_maindoeuvre_date_maindoeuvre_updated_at_and_more'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoeuvre',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_oeuvre', to='societe.societe'),
        ),
    ]
