# Generated by Django 5.2.10 on 2026-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0005_maindoeuvre_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoeuvre',
            name='descriptif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maindoeuvre',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
    ]
