# Generated by Django 5.2.10 on 2026-05-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0006_maindoeuvre_descriptif_maindoeuvre_remarques'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindoeuvre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maindoeuvre',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='maindoeuvre',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taux horaire client'),
        ),
        migrations.AlterField(
            model_name='maindoeuvre',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maindoeuvre',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_oeuvres', to='societe.societe'),
        ),
    ]
