# Generated by Django 5.2 on 2026-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0007_remove_maindoeuvre_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindoeuvre',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taux horaire travailleur'),
        ),
    ]
