# Generated by Django 5.2.10 on 2026-07-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0008_alter_maindoeuvre_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoeuvre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='maindoeuvre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
