# Generated by Django 5.2.10 on 2026-07-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0009_maindoeuvre_created_at_maindoeuvre_updated_at'),
        ('voiture_exemplaire', '0024_voitureexemplaire_kilometres_rodage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoeuvre',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_oeuvres', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule'),
        ),
    ]
