# Generated by Django 5.2.10 on 2026-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0010_maindoeuvre_voiture_exemplaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindoeuvre',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
