# Generated by Django 5.2.10 on 2026-07-16 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0011_maindoeuvre_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindoeuvre',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Taux horaire'),
        ),
    ]
