# Generated by Django 5.2.10 on 2026-08-13 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0012_alter_maindoeuvre_taux_horaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindoeuvre',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_oeuvres', to=settings.AUTH_USER_MODEL),
        ),
    ]
