# Generated by Django 5.2.10 on 2026-04-08 10:11

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0012_alter_voitureexemplaire_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometrage_admission', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du controle')),
                ('filtre_air', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Filtre à air')),
                ('filtre_air_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix')),
                ('filtre_air_quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('boitier_filtre_air', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Boîtier filtre à air')),
                ('boitier_filtre_air_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boitier_filtre_air_quantite', models.IntegerField(default=0)),
                ('debitmetre', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name="Débitmètre d'air")),
                ('debitmetre_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debitmetre_quantite', models.IntegerField(default=0)),
                ('capteur_map', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Capteur MAP')),
                ('capteur_map_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capteur_map_quantite', models.IntegerField(default=0)),
                ('capteur_temperature_air', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Capteur température air')),
                ('capteur_temperature_air_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capteur_temperature_air_quantite', models.IntegerField(default=0)),
                ('corps_papillon', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Corps de papillon')),
                ('corps_papillon_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('corps_papillon_quantite', models.IntegerField(default=0)),
                ('collecteur_admission', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name="Collecteur d'admission")),
                ('collecteur_admission_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collecteur_admission_quantite', models.IntegerField(default=0)),
                ('turbo', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Turbo')),
                ('turbo_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turbo_quantite', models.IntegerField(default=0)),
                ('intercooler', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Intercooler')),
                ('intercooler_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('intercooler_quantite', models.IntegerField(default=0)),
                ('vanne_egr', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Vanne EGR')),
                ('vanne_egr_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vanne_egr_quantite', models.IntegerField(default=0)),
                ('durites_admission', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name="Durites d'admission")),
                ('durites_admission_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('durites_admission_quantite', models.IntegerField(default=0)),
                ('joints_admission', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=25, verbose_name='Joints admission')),
                ('joints_admission_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joints_admission_quantite', models.IntegerField(default=0)),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_checkup')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
