# Generated by Django 5.2.10 on 2026-04-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='filtre_air',
            new_name='filtre_air_p',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='filtre_air_prix',
            new_name='filtre_air_p_prix',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='filtre_air_quantite',
            new_name='filtre_air_p_quantite',
        ),
    ]
