# Generated by Django 5.2.10 on 2026-04-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_rename_filtre_air_admission_filtre_air_p_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='filtre_air_p',
            new_name='filtre_air_pc',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='filtre_air_p_prix',
            new_name='filtre_air_pc_prix',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='filtre_air_p_quantite',
            new_name='filtre_air_pc_quantite',
        ),
    ]
