# Generated by Django 5.2.10 on 2026-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_rename_filtre_air_p_admission_filtre_air_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='boitier_filtre_air',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Boîtier filtre à air'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='capteur_map',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Capteur MAP'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='capteur_temperature_air',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Capteur température air'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='collecteur_admission',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Collecteur d'admission"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='corps_papillon',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Corps de papillon'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='debitmetre',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Débitmètre d'air"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='durites_admission',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Durites d'admission"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='filtre_air_pc',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Filtre à air'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='intercooler',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Intercooler'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='joints_admission',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Joints admission'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='turbo',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Turbo'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='vanne_egr',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Vanne EGR'),
        ),
    ]
