# Generated by Django 5.2.10 on 2026-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_admission_boitier_filtre_air_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
