# Generated by Django 5.2.10 on 2026-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_alter_admission_voiture_exemplaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Immatriculation'),
        ),
    ]
