# Generated by Django 5.2.10 on 2026-05-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_admission_immatriculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='immatriculation',
        ),
    ]
