# Generated by Django 5.2.10 on 2026-05-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_admission_immatriculation'),
        ('voiture_exemplaire', '0018_voitureexemplaire_nombre_remplacements_moteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_admission'),
        ),
    ]
