# Generated by Django 5.2.10 on 2026-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_alter_admission_boitier_filtre_air_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='kilometrage_admission',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du controle'),
            preserve_default=False,
        ),
    ]
