# Generated by Django 5.2.10 on 2026-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_alter_admission_kilometrage_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='taux_horaire',
            field=models.DecimalField(choices=[('50.00', '50 €/h'), ('60.00', '60 €/h'), ('70.00', '70 €/h'), ('80.00', '80 €/h'), ('90.00', '90 €/h'), ('100.00', '100 €/h'), ('110.00', '110 €/h')], decimal_places=2, default='50.00', max_digits=10, verbose_name='Taux horaire'),
        ),
    ]
