# Generated by Django 5.2.10 on 2026-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_alter_admission_boitier_filtre_air_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='boitier_filtre_air_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='boitier_filtre_air_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='capteur_map_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='capteur_map_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='capteur_temperature_air_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='capteur_temperature_air_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='collecteur_admission_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='collecteur_admission_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='corps_papillon_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='corps_papillon_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='debitmetre_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='debitmetre_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='durites_admission_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='durites_admission_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='filtre_air_pc_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='intercooler_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='intercooler_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='joints_admission_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='joints_admission_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='turbo_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='turbo_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='vanne_egr_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='admission',
            name='vanne_egr_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
