# Generated by Django 5.2.10 on 2026-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_alter_admission_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
