# Generated by Django 5.2.10 on 2026-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_admission_kilometrage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
