# Generated by Django 5.2.10 on 2026-09-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_alter_admission_boitier_filtre_air_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
