# Generated by Django 6.0 on 2026-01-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magasinier',
            name='role',
        ),
    ]
