# Generated by Django 5.2.10 on 2026-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0001_initial'),
        ('utilisateurs', '0005_alter_utilisateur_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Magasinier',
        ),
        migrations.CreateModel(
            name='Magasinier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('utilisateurs.utilisateur',),
        ),
    ]
