# Generated by Django 5.2.10 on 2026-04-29 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adresse', '0005_alter_adresse_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to='adresse.adresse')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to='societe.societe')),
            ],
        ),
        migrations.CreateModel(
            name='ProprietaireVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_proprietaire_pourcent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='proprietaire.proprietaire')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires_voiture', to='voiture_exemplaire.voitureexemplaire')),
            ],
        ),
    ]
