# Generated by Django 5.2.10 on 2026-04-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0002_proprietairevoiture_societe'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietairevoiture',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires_voiture', to='societe.societe'),
        ),
    ]
