# Generated by Django 5.2.10 on 2026-04-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0003_alter_proprietairevoiture_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietairevoiture',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire_voitures', to='proprietaire.proprietaire'),
        ),
    ]
