# Generated by Django 5.2.10 on 2026-04-30 06:30

import client_particulier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0004_alter_proprietairevoiture_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='numero_carte_bancaire',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de carte bancaire'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='numero_carte_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro de carte d'identité"),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[client_particulier.models.validate_iban], verbose_name='Numéro de compte bancaire'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de permis de conduire'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
        migrations.AddField(
            model_name='proprietairevoiture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='proprietairevoiture',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='proprietairevoiture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
