# Generated by Django 5.2.10 on 2026-05-01 13:33

import carrosserie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaire', '0005_proprietaire_created_at_proprietaire_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[carrosserie.models.validate_iban], verbose_name='Numéro de compte bancaire'),
        ),
    ]
