# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_marque', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBarre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code-barre')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('annee', models.PositiveSmallIntegerField(default=2026, verbose_name='Année')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Site')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('emplacement_etagere', models.CharField(blank=True, help_text='A-Z / 1-50', max_length=4, verbose_name='Emplacement étagère')),
                ('qualite', models.CharField(blank=True, max_length=50, verbose_name='Qualité')),
                ('oem', models.CharField(blank=True, max_length=50, verbose_name='Code OEM')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat")),
                ('majoration_pourcent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Majoration (%)')),
                ('tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='TVA (%)')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente')),
                ('quantite_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('quantite_utilisee', models.PositiveIntegerField(default=0, verbose_name='Quantité utilisée')),
                ('quantite_min', models.PositiveIntegerField(default=0, verbose_name='Quantité minimale')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('organe', models.CharField(blank=True, max_length=100, verbose_name='Organe')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('codes_barres', models.ManyToManyField(blank=True, related_name='pieces', to='piece.codebarre', verbose_name='Codes-barres')),
                ('fabricants', models.ManyToManyField(related_name='pieces', to='piece.fabricant', verbose_name='Fabricants')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='voiture_modele.voituremodele', verbose_name='Modèle')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
                ('voiture_marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='voiture_marque.voituremarque', verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.IntegerField(help_text='+ entrée / - sortie', verbose_name='Variation')),
                ('stock_apres', models.PositiveIntegerField(default=0, verbose_name='Stock après')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='piece.piece', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
            },
        ),
    ]
