# Generated by Django 5.2.10 on 2026-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0002_piece_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='emplacement_etagere',
            field=models.CharField(blank=True, help_text='A-Z / 1-4 / 1-50', max_length=4, verbose_name='Emplacement étagère'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site'),
        ),
    ]
