# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adresse', '0001_initial'),
        ('societe_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peppol_id', models.CharField(help_text='Ex : 0208:BE0123456789', max_length=50, verbose_name='Identifiant Peppol')),
                ('code_pays', models.CharField(default='BE', max_length=2, verbose_name='Code pays')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='adresse.adresse', verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Société émettrice',
                'verbose_name_plural': 'Sociétés émettrices',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant facture')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('issue_date', models.DateField(verbose_name='Date d’émission')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='facture.company', verbose_name='Société émettrice')),
                ('societe_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='societe_cliente.societecliente', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='FactureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='Taux de TVA : 6, 12, 21', max_digits=4, verbose_name='Taux de TVA')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='facture.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
