# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facture', '0001_initial'),
        ('societe_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='societe_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='societe_cliente.societecliente', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='factureline',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='facture.facture', verbose_name='Facture'),
        ),
    ]
