# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climatisation',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_clim', models.CharField(choices=[('qualite_gaz', 'Qualité de gaz'), ('quantite_gaz', 'Quantité de gaz'), ('compresseur', 'Compresseur'), ('evaporateur', 'Évaporateur'), ('condenseur', 'Condenseur'), ('filtre', 'Filtre'), ('dehydrateur', 'Déshydrateur'), ('valves', 'Valves'), ('durites', 'Durites'), ('huile_clim', 'Huile de climatisation')], max_length=50, verbose_name='Type de pièce de climatisation')),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='climatisations', to='voiture_moteur.moteurvoiture', verbose_name='Moteurs compatibles')),
            ],
            options={
                'verbose_name': 'Pièce de climatisation',
                'verbose_name_plural': 'Pièces de climatisation',
            },
            bases=('piece.piece',),
        ),
    ]
