# Generated by Django 5.2.10 on 2026-07-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0003_alter_piece_emplacement_etagere_alter_piece_pays_and_more'),
        ('piece_climatisation', '0001_initial'),
        ('voiture_moteur', '0005_remove_moteurvoiture_kilometres_moteur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Climatisation',
            new_name='ClimatisationPieces',
        ),
    ]
