# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adresse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocieteCliente',
            fields=[
                ('id_societe_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_societe_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom Societe')),
                ('directeur_nom_prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom Prémon Directeur')),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('numero_tva', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de TVA')),
                ('site_internet', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('peppol_id', models.CharField(blank=True, help_text='Identifiant Peppol du client, ex: 0208:BE0987654321', max_length=50, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('code_pays', models.CharField(default='BE', max_length=2)),
                ('numero_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('historique', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societe_cliente', to='adresse.adresse', verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Société cliente',
                'verbose_name_plural': 'Sociétés clientes',
                'ordering': ['nom_societe_cliente'],
            },
        ),
    ]
