# Generated by Django 5.2.10 on 2026-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societecliente',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de compte bancaire'),
        ),
    ]
