# Generated by Django 5.2.10 on 2026-02-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe_cliente', '0002_societecliente_numero_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societecliente',
            name='code_pays',
            field=models.CharField(default='BE', max_length=2, verbose_name='Code pays'),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='directeur_nom_prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du Directeur'),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='nom_societe_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la societe'),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='numero_entreprise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Numero d'entreprise"),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='numero_tva',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numero de TVA'),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='peppol_id',
            field=models.CharField(blank=True, help_text='Identifiant Peppol du client, ex: 0208:BE0987654321', max_length=50, null=True, verbose_name='Peppol id'),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='site_internet',
            field=models.URLField(blank=True, null=True, verbose_name='Site internet'),
        ),
        migrations.AlterField(
            model_name='societecliente',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de tva'),
        ),
    ]
