# Generated by Django 5.2.10 on 2026-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe_cliente', '0003_alter_societecliente_code_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societecliente',
            name='numero_carte_bancaire',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de carte bancaire'),
        ),
    ]
