# Generated by Django 5.2.10 on 2026-02-20 08:01

import societe_cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe_cliente', '0005_remove_societecliente_code_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societecliente',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[societe_cliente.models.validate_iban], verbose_name='Numéro de compte bancaire'),
        ),
    ]
