# Generated by Django 5.2.10 on 2026-03-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('societe_cliente', '0006_alter_societecliente_numero_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='societecliente',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societe_clientes', to='societe.societe'),
        ),
    ]
