# Generated by Django 5.2.10 on 2026-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe_cliente', '0007_societecliente_societe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societecliente',
            options={},
        ),
        migrations.AddField(
            model_name='societecliente',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='societecliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
