# Generated by Django 5.2.10 on 2026-04-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societe_cliente', '0008_alter_societecliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societecliente',
            options={'ordering': ['nom_societe_cliente'], 'verbose_name': 'Société cliente', 'verbose_name_plural': 'Sociétés clientes'},
        ),
        migrations.RemoveField(
            model_name='societecliente',
            name='location',
        ),
    ]
