# Generated by Django 5.2.10 on 2026-09-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0007_adresse_societe'),
        ('societe_cliente', '0009_alter_societecliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societecliente',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='societe_cliente', to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
