# Generated by Django 5.2.10 on 2026-04-09 08:46

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0012_alter_voitureexemplaire_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Alternateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometrage_admission', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du controle')),
                ('pays', models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=25, verbose_name='Pays TVA')),
                ('alternateur', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Alternateur')),
                ('alternateur_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix HTVA')),
                ('alternateur_tva_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TVA à récupérer')),
                ('alternateur_marge', models.IntegerField(blank=True, null=True, verbose_name='Marge à appliquer')),
                ('alternateur_prix_vente_htva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente HTVA')),
                ('alternateur_tva_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA')),
                ('alternateur_prix_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alternateur_quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternateur', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternateur', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternateur', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternateur', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_checkup')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
