# Generated by Django 5.2.10 on 2026-04-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternateur',
            old_name='kilometrage_admission',
            new_name='kilometrage_alte',
        ),
    ]
