# Generated by Django 5.2.10 on 2026-04-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0002_rename_kilometrage_admission_alternateur_kilometrage_alte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur_quantite',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='remarques',
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires_prix_vente_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente HTVA'),
        ),
    ]
