# Generated by Django 5.2.10 on 2026-04-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0003_remove_alternateur_alternateur_prix_ttc_and_more'),
        ('maintenance', '0003_maintenance_societe'),
        ('voiture_exemplaire', '0012_alter_voitureexemplaire_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateur',
            name='kilometres_chassis',
        ),
        migrations.AddField(
            model_name='alternateur',
            name='alternateur_prix_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='alternateur_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires_marge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires_prix_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires_tva_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='courroie_accessoires_tva_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_marge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_prix_vente_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_tva_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_tva_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_prix_vente_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='kilometrage_alte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternateur', to='maintenance.maintenance'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='pays',
            field=models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=5),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternateur', to='voiture_exemplaire.voitureexemplaire'),
        ),
    ]
