# Generated by Django 5.2.10 on 2026-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0004_remove_alternateur_kilometres_chassis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
