# Generated by Django 5.2.10 on 2026-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0005_alternateur_kilometres_chassis'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
    ]
