# Generated by Django 5.2.10 on 2026-04-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0006_alternateur_remarques'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RechargeCarburant',
        ),
    ]
