# Generated by Django 5.2.10 on 2026-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0007_delete_rechargecarburant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_marge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marge'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_prix_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TVAC'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_prix_vente_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente htva'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_tva_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à récupérer'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_tva_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer'),
        ),
    ]
