# Generated by Django 5.2.10 on 2026-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0008_alter_alternateur_alternateur_marge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_prix_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix tvac'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_tva_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='_(TVA à payer'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='kilometrage_alte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometrage du controle alternateur'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilometres chassis'),
        ),
    ]
