# Generated by Django 5.2.10 on 2026-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0009_alter_alternateur_alternateur_prix_ttc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_tva_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer'),
        ),
    ]
