# Generated by Django 5.2.10 on 2026-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0010_alter_alternateur_alternateur_tva_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
    ]
