# Generated by Django 5.2.10 on 2026-04-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0011_alter_alternateur_alternateur_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Courroie d'accessoires"),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_marge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marge'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_prix_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TVAC'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_prix_vente_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente htva'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_tva_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à récupérer'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_tva_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='kilometrage_alte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage du controle alternateur'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
