# Generated by Django 5.2.10 on 2026-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0012_alter_alternateur_courroie_accessoires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
