# Generated by Django 5.2.10 on 2026-04-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0013_alter_alternateur_alternateur_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='diagnostic_charge_ampere',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Diagnostic charge ampere'),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='diagnostic_charge_volt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Diagnostic charge volt'),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='diagnostic_rapport',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25),
        ),
    ]
