# Generated by Django 5.2.10 on 2026-04-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0014_alternateur_diagnostic_charge_ampere_and_more'),
        ('maindoeuvre', '0003_remove_maindoeuvre_temps_maindoeuvre_temps_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternateur', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
