# Generated by Django 5.2.10 on 2026-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0015_alternateur_main_oeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='mode_intervention',
            field=models.CharField(choices=[('INTERNE', 'Interne'), ('EXTERNE', 'Externe')], default='EXTERNE', max_length=10, verbose_name='Type intervention'),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='temps_main_oeuvre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Temps main d'œuvre (heures)"),
        ),
    ]
