# Generated by Django 5.2.10 on 2026-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0016_alternateur_mode_intervention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='taux_horaire_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taux horaire appliqué'),
        ),
    ]
