# Generated by Django 5.2.10 on 2026-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0017_alternateur_taux_horaire_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='temps_heures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alternateur',
            name='temps_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
