# Generated by Django 5.2.10 on 2026-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0018_alternateur_temps_heures_alternateur_temps_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='mode_intervention',
            field=models.CharField(choices=[('INTERNE', 'Interne'), ('EXTERNE', 'Externe')], default='EXTERNE', max_length=10),
        ),
    ]
