# Generated by Django 5.2.10 on 2026-05-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0020_remove_alternateur_temps_heures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateur',
            name='taux_horaire_snapshot',
        ),
    ]
