# Generated by Django 5.2.10 on 2026-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0021_remove_alternateur_taux_horaire_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='taux_horaire_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taux horaire appliqué'),
        ),
    ]
