# Generated by Django 5.2.10 on 2026-05-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0022_alternateur_taux_horaire_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateur',
            name='mode_intervention',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='taux_horaire_snapshot',
        ),
    ]
