# Generated by Django 5.2.10 on 2026-05-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0023_remove_alternateur_mode_intervention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur_marge',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur_tva_achat',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur_tva_vente',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='courroie_accessoires_marge',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='courroie_accessoires_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='courroie_accessoires_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='courroie_accessoires_tva_achat',
        ),
        migrations.RemoveField(
            model_name='alternateur',
            name='courroie_accessoires_tva_vente',
        ),
    ]
