# Generated by Django 5.2.10 on 2026-05-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0024_remove_alternateur_alternateur_marge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternateur',
            old_name='alternateur_prix_achat',
            new_name='alternateur_prix',
        ),
        migrations.RenameField(
            model_name='alternateur',
            old_name='courroie_accessoires_prix_achat',
            new_name='courroie_accessoires_prix',
        ),
    ]
