# Generated by Django 5.2.10 on 2026-05-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0025_rename_alternateur_prix_achat_alternateur_alternateur_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternateur',
            old_name='alternateur_prix',
            new_name='alternateur_prix_achat',
        ),
    ]
