# Generated by Django 5.2.10 on 2026-05-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0026_rename_alternateur_prix_alternateur_alternateur_prix_achat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternateur',
            old_name='courroie_accessoires_prix',
            new_name='courroie_accessoires_prix_achat',
        ),
    ]
