# Generated by Django 5.2.10 on 2026-05-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0027_rename_courroie_accessoires_prix_alternateur_courroie_accessoires_prix_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateur',
            name='alternateur',
        ),
    ]
