# Generated by Django 5.2.10 on 2026-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0029_rename_diagnostic_rapport_alternateur_alternateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='kilometrage_alte',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage du controle alternateur'),
            preserve_default=False,
        ),
    ]
