# Generated by Django 5.2.10 on 2026-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0030_alter_alternateur_kilometrage_alte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Courroie d'accessoires"),
        ),
    ]
