# Generated by Django 5.2.10 on 2026-09-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0039_alternateur_serrage_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternateur',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
