# Generated by Django 5.2.10 on 2026-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateur', '0042_alternateur_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateur',
            name='alternateur_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('VALEO', 'Valeo'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HITACHI', 'Hitachi'), ('MITSUBISHI', 'Mitsubishi Electric'), ('HELLA', 'Hella'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('LUCAS', 'Lucas'), ('PRESTOLITE', 'Prestolite'), ('REMY', 'Remy'), ('MANDO', 'Mando'), ('AS_PL', 'AS-PL'), ('HC_CARGO', 'HC-Cargo'), ('MAHLE', 'Mahle'), ('VISTEON', 'Visteon'), ('MOTORCRAFT', 'Motorcraft'), ('ACDELCO', 'ACDelco'), ('MOPAR', 'Mopar'), ('MOBILETRON', 'Mobiletron'), ('ERA', 'ERA'), ('MEAT_DORIA', 'Meat & Doria'), ('FEBI', 'Febi Bilstein'), ('HERTH_BUSS', 'Herth+Buss'), ('JP_GROUP', 'JP Group'), ('MAPCO', 'Mapco'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('WAI', 'WAI Global'), ('POWERMAX', 'PowerMax'), ('BV_PSH', 'BV PSH'), ('ELSTOCK', 'Elstock'), ('CEVAM', 'CEVAM'), ('SNRA', 'SNRA'), ('LAUBER', 'Lauber'), ('CASCO', 'Casco'), ('SANDO', 'Sando'), ('EUROTEC', 'Eurotec'), ('ALANKO', 'Alanko'), ('ROTOVIS', 'Rotovis'), ('EAI', 'EAI'), ('AUTEX', 'Autex'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('TRW', 'TRW'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('ACKOJAP', 'ACKOJA'), ('ERA_BENELUX', 'ERA Benelux'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='alternateur',
            name='courroie_accessoires_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('CONTINENTAL', 'Continental / ContiTech'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BOSCH', 'Bosch'), ('SKF', 'SKF'), ('INA', 'INA'), ('SNR', 'SNR'), ('HUTCHINSON', 'Hutchinson'), ('OPTIBELT', 'Optibelt'), ('MITSUBOSHI', 'Mitsuboshi'), ('BANDO', 'Bando'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('BLUE_PRINT', 'Blue Print'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('MAPCO', 'Mapco'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('TRISCAN', 'Triscan'), ('METELLI', 'Metelli'), ('GRAF', 'Graf'), ('HEPU', 'HEPU'), ('DOLZ', 'Dolz'), ('KAVO_PARTS', 'Kavo Parts'), ('JAPANPARTS', 'Japanparts'), ('ASHIKA', 'Ashika'), ('HERTH_BUSS', 'Herth+Buss'), ('NIPPARTS', 'Nipparts'), ('ACKOJA', 'ACKOJA'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('VALEO', 'Valeo'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
