# Generated by Django 5.2.10 on 2026-02-20 08:01

import client_particulier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientparticulier',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[client_particulier.models.validate_iban], verbose_name='Numéro de compte bancaire'),
        ),
    ]
