# Generated by Django 5.2.10 on 2026-03-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0002_alter_clientparticulier_numero_compte'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientparticulier',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_particulier', to='societe.societe'),
        ),
    ]
