# Generated by Django 5.2.10 on 2026-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0003_clientparticulier_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientparticulier',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='clientparticulier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
