# Generated by Django 5.2.10 on 2026-05-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0005_alter_clientparticulier_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPilotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('EXPERT', 'Expert'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='DEBUTANT', max_length=20, verbose_name='Niveau')),
                ('historique', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AlterModelOptions(
            name='clientparticulier',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientparticulier',
            name='historique',
        ),
        migrations.RemoveField(
            model_name='clientparticulier',
            name='location',
        ),
        migrations.RemoveField(
            model_name='clientparticulier',
            name='niveau',
        ),
    ]
