# Generated by Django 5.2.10 on 2026-05-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0006_clientpilotage_alter_clientparticulier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientparticulier',
            name='societe_nom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la société'),
        ),
    ]
