# Generated by Django 5.2.10 on 2026-05-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0007_clientparticulier_societe_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientparticulier',
            name='societe_nom',
        ),
    ]
