# Generated by Django 5.2.10 on 2026-05-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0008_remove_clientparticulier_societe_nom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPilotage',
        ),
    ]
