# Generated by Django 5.2.10 on 2026-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0009_delete_clientpilotage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientparticulier',
            name='numero_registre_national',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de registre national'),
        ),
    ]
