# Generated by Django 5.2.10 on 2026-09-28 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0010_clientparticulier_numero_registre_national'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientparticulier',
            name='id_client_particulier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
