# Generated by Django 5.2.10 on 2026-09-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0007_adresse_societe'),
        ('client_particulier', '0011_alter_clientparticulier_id_client_particulier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientparticulier',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='client_particulier', to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
