# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feux',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_feu', models.CharField(choices=[('AVG', 'Avant Gauche'), ('AVD', 'Avant Droit'), ('ARG', 'Arrière Gauche'), ('ARD', 'Arrière Droit'), ('STOP', 'Troisième feu stop'), ('AB_AV', 'Antibrouillard AV'), ('AB_AR', 'Antibrouillard AR'), ('CL_AVG', 'Clignotant Avant Gauche'), ('CL_AVD', 'Clignotant Avant Droit'), ('CL_ARG', 'Clignotant Arrière Gauche'), ('CL_ARD', 'Clignotant Arrière Droit')], max_length=20, verbose_name='Type / Position du feu')),
                ('puissance', models.CharField(blank=True, max_length=20, verbose_name='Puissance')),
                ('couleur', models.CharField(blank=True, max_length=20, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Feu',
                'verbose_name_plural': 'Feux',
            },
            bases=('piece.piece',),
        ),
    ]
