# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('piece_feux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ampoule',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_ampoule', models.CharField(choices=[('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H11', 'H11'), ('HB3', 'HB3'), ('HB4', 'HB4'), ('LED', 'LED'), ('XENON', 'Xénon'), ('C5W', 'C5W'), ('W5W', 'W5W'), ('T10', 'T10'), ('T4W', 'T4W')], max_length=10, verbose_name='Type d’ampoule')),
                ('puissance', models.CharField(blank=True, help_text='Puissance en watts', max_length=10, verbose_name='Puissance')),
                ('couleur', models.CharField(blank=True, help_text='Couleur de la lumière', max_length=20, verbose_name='Couleur')),
                ('tension', models.CharField(blank=True, help_text='Tension en volts', max_length=10, verbose_name='Tension')),
                ('code_barre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampoules', to='piece.codebarre', verbose_name='Code-barres')),
                ('feu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampoules', to='piece_feux.feux', verbose_name='Feu')),
            ],
            options={
                'verbose_name': 'Ampoule',
                'verbose_name_plural': 'Ampoules',
            },
            bases=('piece.piece',),
        ),
    ]
