# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('piece', '0001_initial'),
        ('societe_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers_client', to='client.client', verbose_name='Client')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers_societe', to='societe_cliente.societecliente', verbose_name='Société cliente')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_achat_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat HT")),
                ('taux_tva_fournisseur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TVA fournisseur (%)')),
                ('marge', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marge (%)')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT (vente)')),
                ('taux_tva_client', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TVA client (%)')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='panier.panier', verbose_name='Panier')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panier_items', to='piece.piece', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Ligne de panier',
                'verbose_name_plural': 'Lignes de panier',
                'unique_together': {('panier', 'piece')},
            },
        ),
    ]
