# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_particulier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_achat_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat HT")),
                ('taux_tva_fournisseur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TVA fournisseur (%)')),
                ('marge', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marge (%)')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT (vente)')),
                ('taux_tva_client', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TVA client (%)')),
            ],
            options={
                'verbose_name': 'Ligne de panier',
                'verbose_name_plural': 'Lignes de panier',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers_client', to='client_particulier.clientparticulier', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
    ]
