# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panier', '0001_initial'),
        ('piece', '0001_initial'),
        ('societe_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paniers_societe', to='societe_cliente.societecliente', verbose_name='Société cliente'),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='panier.panier', verbose_name='Panier'),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panier_items', to='piece.piece', verbose_name='Pièce'),
        ),
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together={('panier', 'piece')},
        ),
    ]
