# Generated by Django 5.2.10 on 2026-04-06 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrosserieinterne',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
