# Generated by Django 5.2.10 on 2026-04-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0002_carrosserieinterne_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
