# Generated by Django 5.2.10 on 2026-04-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0004_carrosserieinterne_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrosserieinterne',
            options={'verbose_name': 'Contrôle général', 'verbose_name_plural': 'Contrôles généraux'},
        ),
    ]
