# Generated by Django 5.2.10 on 2026-04-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0005_alter_carrosserieinterne_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrosserieinterne',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
    ]
