# Generated by Django 5.2.10 on 2026-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0006_carrosserieinterne_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='pare_brise_prix',
            new_name='pa_brise_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='pare_brise_quantite',
            new_name='pa_brise_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='support_pare_choc_ar_prix',
            new_name='support_pa_choc_ar_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='support_pare_choc_ar_quantite',
            new_name='support_pa_choc_ar_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='support_pare_choc_av_prix',
            new_name='support_pa_choc_av_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='support_pare_choc_av_quantite',
            new_name='support_pa_choc_av_quantite',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='pare_brise',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='pare_brise_oem',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='support_pare_choc_ar',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='support_pare_choc_ar_oem',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='support_pare_choc_av',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='support_pare_choc_av_oem',
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='pa_brise',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='pa_brise_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Support de pare-chocs arrière'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Support de pare-chocs avant'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Aile arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Aile arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Aile avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Aile avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Anti-brouillard arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Anti-brouillard avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Anti-brouillard avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bas de caisse droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bas de caisse gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bouclier arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bouclier avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Calandre'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Capot'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Capteur de recul'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clignotant arrière droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clignotant arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clignotant avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clignotant avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clips'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Coffre / Hayon'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Coquille d'aile arrière droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Coquille d'aile arrière gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Coquille d'aile avant droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Coquille d'aile avant gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_aile_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Élargisseur d'aile arrière droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Élargisseur d'aile arrière gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Élargisseur d'aile avant droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Élargisseur d'aile avant gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_coffre',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Joint de coffre'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_coffre_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Joint de porte arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Joint de porte arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Joint de porte avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Joint de porte avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Lunette / vitre arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-chocs arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-chocs avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Peinture de l'arrière"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Peinture de l'aile arrière gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Peinture de l'aile avant droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Peinture de l'aile avant gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_capot',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Peinture du capot'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Peinture complète'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Peinture de la face avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feu arrière droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feu arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phare avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phare avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Poignée de porte'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Porte arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Porte arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Porte avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Porte avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Rétroviseur droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Rétroviseur gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Support de radiateur'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Troisième feu stop'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Visserie'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Vitre de porte arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Vitre de porte arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Vitre de porte avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Vitre de porte avant gauche'),
        ),
    ]
