# Generated by Django 5.2.10 on 2026-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0007_rename_pare_brise_prix_carrosserieinterne_pa_brise_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_ard',
            new_name='coquille_ai_ard',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_ard_oem',
            new_name='coquille_ai_ard_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_ard_prix',
            new_name='coquille_ai_ard_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_ard_quantite',
            new_name='coquille_ai_ard_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_arg',
            new_name='coquille_ai_arg',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_arg_oem',
            new_name='coquille_ai_arg_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_arg_quantite',
            new_name='coquille_ai_arg_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_avd',
            new_name='coquille_ai_avd',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_avd_oem',
            new_name='coquille_ai_avd_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_arg_prix',
            new_name='coquille_ai_avd_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_avd_quantite',
            new_name='coquille_ai_avd_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_avg',
            new_name='coquille_ai_avg',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_avg_oem',
            new_name='coquille_ai_avg_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_avg_quantite',
            new_name='coquille_ai_avg_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_ard',
            new_name='elargisseur_ail_ard',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_ard_oem',
            new_name='elargisseur_ail_ard_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_ard_quantite',
            new_name='elargisseur_ail_ard_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_arg',
            new_name='elargisseur_ail_arg',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_arg_oem',
            new_name='elargisseur_ail_arg_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_arg_quantite',
            new_name='elargisseur_ail_arg_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_avd',
            new_name='elargisseur_ail_avd',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_avd_oem',
            new_name='elargisseur_ail_avd_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_avd_quantite',
            new_name='elargisseur_ail_avd_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_avg',
            new_name='elargisseur_ail_avg',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_avg_oem',
            new_name='elargisseur_ail_avg_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='coquille_aile_avd_prix',
            new_name='elargisseur_ail_avg_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='elargisseur_aile_avg_quantite',
            new_name='elargisseur_ail_avg_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_ard',
            new_name='porte_ard_p',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_ard_oem',
            new_name='porte_ard_p_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_ard_quantite',
            new_name='porte_ard_p_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_arg',
            new_name='porte_arg_p',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_arg_oem',
            new_name='porte_arg_p_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_arg_quantite',
            new_name='porte_arg_p_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avd',
            new_name='porte_avd_p',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avd_oem',
            new_name='porte_avd_p_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avd_quantite',
            new_name='porte_avd_p_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avg',
            new_name='porte_avg_p',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avg_oem',
            new_name='porte_avg_p_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avg_quantite',
            new_name='porte_avg_p_quantite',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='coquille_aile_avg_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_ard_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_arg_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_avd_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='elargisseur_aile_avg_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='porte_ard_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='porte_arg_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='porte_avd_prix',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='porte_avg_prix',
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='coquille_ai_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='porte_ard_p_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='porte_arg_p_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='porte_avd_p_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='porte_avg_p_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pa_brise_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_capot_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
    ]
