# Generated by Django 5.2.10 on 2026-04-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0008_rename_coquille_aile_ard_carrosserieinterne_coquille_ai_ard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_ard_p',
            new_name='porte_ard_po',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_ard_p_oem',
            new_name='porte_ard_po_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_ard_p_prix',
            new_name='porte_ard_po_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_ard_p_quantite',
            new_name='porte_ard_po_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_arg_p',
            new_name='porte_arg_po',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_arg_p_oem',
            new_name='porte_arg_po_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_arg_p_prix',
            new_name='porte_arg_po_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_arg_p_quantite',
            new_name='porte_arg_po_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avd_p',
            new_name='porte_avd_po',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avd_p_oem',
            new_name='porte_avd_po_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avd_p_prix',
            new_name='porte_avd_po_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avd_p_quantite',
            new_name='porte_avd_po_quantite',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avg_p',
            new_name='porte_avg_po',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avg_p_oem',
            new_name='porte_avg_po_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avg_p_prix',
            new_name='porte_avg_po_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='porte_avg_p_quantite',
            new_name='porte_avg_po_quantite',
        ),
    ]
