# Generated by Django 5.2.10 on 2026-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0009_rename_porte_ard_p_carrosserieinterne_porte_ard_po_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pa_brise_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
    ]
