# Generated by Django 5.2.10 on 2026-04-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0010_alter_carrosserieinterne_aile_arg_quantite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='capot',
            new_name='capot_pi',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='capot_oem',
            new_name='capot_pi_oem',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='capot_prix',
            new_name='capot_pi_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='capot_quantite',
            new_name='capot_pi_quantite',
        ),
    ]
