# Generated by Django 5.2.10 on 2026-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0011_rename_capot_carrosserieinterne_capot_pi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Peinture de l'aile arrière droite"),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
    ]
