# Generated by Django 5.2.10 on 2026-04-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0012_carrosserieinterne_peinture_arriere_droite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='peinture_arriere_prix',
            new_name='peinture_arriere_complete_prix',
        ),
        migrations.RenameField(
            model_name='carrosserieinterne',
            old_name='peinture_arriere_quantite',
            new_name='peinture_arriere_complete_quantite',
        ),
        migrations.RemoveField(
            model_name='carrosserieinterne',
            name='peinture_arriere',
        ),
        migrations.AddField(
            model_name='carrosserieinterne',
            name='peinture_arriere_complete',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Peinture de arrière complete'),
        ),
    ]
