# Generated by Django 5.2.10 on 2026-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0013_rename_peinture_arriere_prix_carrosserieinterne_peinture_arriere_complete_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Aile arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Aile arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Aile avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Aile avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Anti-brouillard arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Anti-brouillard avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Anti-brouillard avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Bas de caisse droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Bas de caisse gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Bouclier arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Bouclier avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Calandre'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_pi',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Capot'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_pi_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_pi_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Capteur de recul'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Clignotant arrière droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Clignotant arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Clignotant avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Clignotant avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Clips'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Coffre / Hayon'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Coquille d'aile arrière droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_ard_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Coquille d'aile arrière gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Coquille d'aile avant droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Coquille d'aile avant gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Élargisseur d'aile arrière droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Élargisseur d'aile arrière gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_arg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Élargisseur d'aile avant droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Élargisseur d'aile avant gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_coffre',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Joint de coffre'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Joint de porte arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Joint de porte arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Joint de porte avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Joint de porte avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Lunette / vitre arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pa_brise',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Pare-brise'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pa_brise_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pa_brise_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Pare-chocs arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Pare-chocs avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du pare-chocs avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_complete',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Peinture arrière complète'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_complete_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_complete_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Peinture de l'aile arrière droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Peinture de l'aile arrière gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Peinture de l'aile avant droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Peinture de l'aile avant gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_capot',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Peinture du capot'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_capot_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Peinture complète'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Peinture de la face avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Feu arrière droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Feu arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Phare avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Phare avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Poignée de porte'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_quantite',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_po',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Porte arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_po_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_po',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Porte arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_po_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Porte avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_po',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Porte avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_po_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Rétroviseur droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Rétroviseur gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Support de pare-chocs arrière'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Support de pare-chocs avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Support de radiateur'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Troisième feu stop'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Visserie'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Vitre de porte arrière droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Vitre de porte arrière gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Vitre de porte avant droite'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Vitre de porte avant gauche'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
