# Generated by Django 5.2.10 on 2026-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0014_alter_carrosserieinterne_aile_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Aile arrière droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Aile avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Coquille d'aile arrière droit"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Coquille d'aile avant droit"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Élargisseur d'aile arrière droit"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name="Élargisseur d'aile avant droit"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Joint de porte arrière droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Joint de porte avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Porte avant droit'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero OEM'),
        ),
    ]
