# Generated by Django 5.2.10 on 2026-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0015_alter_carrosserieinterne_aile_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Porte avant droite'),
        ),
    ]
