# Generated by Django 5.2.10 on 2026-05-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0017_carrosserieinterne_main_oeuvre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrosserieinterne',
            options={'verbose_name': 'Carrosserie Interne', 'verbose_name_plural': 'Carrosseries Internes'},
        ),
    ]
