# Generated by Django 5.2.10 on 2026-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0019_alter_carrosserieinterne_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='kilometrage_intervention',
            field=models.PositiveIntegerField(default=0, verbose_name="Kilométrage au moment de l'intervention"),
            preserve_default=False,
        ),
    ]
