# Generated by Django 5.2.10 on 2026-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0026_carrosserieinterne_serrage_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrosserieinterne',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
