# Generated by Django 5.2.10 on 2026-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie_interne', '0027_carrosserieinterne_kilometrage_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='aile_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='anti_brouillard_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_d_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bas_de_caisse_g_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='bouclier_av_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='calandre_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_pi_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_pi_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capot_pi_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='capteur_recul_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clignotant_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='clips_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coffre_haillon_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='coquille_ai_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='elargisseur_ail_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_coffre_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_coffre_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_coffre_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='joint_porte_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='lunette_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pa_brise_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pa_brise_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='pare_choc_av_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_complete',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name='Peinture arrière complète'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_complete_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name="Peinture de l'aile arrière droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_droite_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name="Peinture de l'aile arrière gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_arriere_gauche_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name="Peinture de l'aile avant droite"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_droite_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name="Peinture de l'aile avant gauche"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_avant_gauche_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_capot',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name='Peinture du capot'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_capot_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name='Peinture complète'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_complete_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant',
            field=models.CharField(choices=[('PEINT', 'Peint'), ('APEINDRE', 'A peindre')], default='PEINT', max_length=25, verbose_name='Peinture de la face avant'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='peinture_face_avant_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='phare_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='poignee_porte_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_po_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_ard_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_po_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_arg_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avd_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_po_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_po_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='porte_avg_po_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_d_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='retroviseur_g_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_pa_choc_av_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='support_radiateur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='troisieme_feu_stop_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='visserie_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avg_oem',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='carrosserieinterne',
            name='vitre_porte_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
