# Generated by Django 5.2.9 on 2025-12-23 15:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mecanicien', '0001_initial'),
        ('voiture_exemplaire', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id_maintenance', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20)),
                ('date_intervention', models.DateField()),
                ('date_derniere_intervention', models.DateField(blank=True, null=True)),
                ('date_heure_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='GREEN', max_length=10)),
                ('mecanicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='mecanicien.mecanicien')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_heure_creation'],
            },
        ),
    ]
