# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprentis', '0001_initial'),
        ('chef_mecanicien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, verbose_name='Immatriculation')),
                ('date_intervention', models.DateField(verbose_name="Date d'intervention")),
                ('date_derniere_intervention', models.DateField(blank=True, null=True, verbose_name='Date de la dernière intervention')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='VERT', max_length=10, verbose_name='Étiquette')),
                ('kilometres_total', models.PositiveIntegerField(default=0, verbose_name='Kilométrage total')),
                ('kilometres_derniere_intervention', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage à la dernière intervention')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage châssis')),
                ('kilometres_moteur', models.PositiveIntegerField(default=0, verbose_name='Kilométrage moteur')),
                ('kilometres_boite', models.PositiveIntegerField(default=0, verbose_name='Kilométrage boîte')),
                ('remplacement_moteur', models.BooleanField(default=False, verbose_name='Remplacement moteur')),
                ('remplacement_boite', models.BooleanField(default=False, verbose_name='Remplacement boîte')),
                ('apprentis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apprentis.apprenti', verbose_name='Apprenti')),
                ('chef_mecanicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef_mecanicien.chefmecanicien', verbose_name='Apprentis')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
        ),
    ]
