# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('mecanicien', '0001_initial'),
        ('voiture_exemplaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='mecanicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_mecanicien', to='mecanicien.mecanicien', verbose_name='Mécanicien'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='voiture_exemplaire.voitureexemplaire', verbose_name='Voiture exemplaire'),
        ),
    ]
