# Generated by Django 5.2.10 on 2026-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='kilometres_derniere_intervention',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='kilometres_derniere_entretien',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage à la dernier entretien'),
        ),
    ]
