# Generated by Django 5.2.10 on 2026-04-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_remove_maintenance_kilometres_derniere_intervention_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='kilometres_derniere_entretien',
            new_name='kilometres_dernier_entretien',
        ),
    ]
