# Generated by Django 5.2.10 on 2026-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenance_tech_nom_technicien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type_maintenance',
            field=models.CharField(blank=True, choices=[('checkup', 'Check-up'), ('entretien', 'Entretien'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('nettoyage_exterieur', 'Nettoyage extérieur'), ('nettoyage_interieur', 'Nettoyage intérieur'), ('niveaux', 'Niveaux'), ('autres', 'Autres interventions'), ('checkup_track', 'Check-up piste'), ('ABS', 'ABS')], max_length=50, null=True, verbose_name='Type de maintenance'),
        ),
    ]
