# Generated by Django 5.2.10 on 2026-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_maintenance_type_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type_maintenance',
            field=models.CharField(blank=True, choices=[('checkup', 'Check-up'), ('entretien', 'Entretien'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('nettoyage_exterieur', 'Nettoyage extérieur'), ('nettoyage_interieur', 'Nettoyage intérieur'), ('niveaux', 'Niveaux'), ('autres', 'Autres interventions'), ('checkup_track', 'Check-up piste'), ('ABS', 'ABS'), ('remplacement_boite', 'Remplacement boîte'), ('jeux_pieces', 'Jeux pieces'), ('silent_bloc', 'Silent bloc'), ('BOITE', 'Boite'), ('BOITE_AUTO', 'Boite automatique')], max_length=50, null=True, verbose_name='Type de maintenance'),
        ),
    ]
