# Generated by Django 5.2.10 on 2026-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_alter_maintenance_type_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='kilometres_boite_rollback',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage boîte rollback'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='kilometres_chassis_rollback',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage châssis rollback'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='kilometres_moteur_rollback',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage moteur rollback'),
        ),
    ]
