# Generated by Django 5.2.10 on 2026-09-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_maintenance_kilometres_boite_rollback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='kilometres_boite_rollback',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='kilometres_chassis_rollback',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='kilometres_moteur_rollback',
        ),
    ]
