# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiecePont',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_pont', models.CharField(choices=[('pont_av', 'Pont avant'), ('pont_ar', 'Pont arrière'), ('pont_central', 'Pont central'), ('differentiel_complet', 'Différentiel complet'), ('couronne', 'Couronne'), ('pignon_attaque', 'Pignon d’attaque'), ('couple_conique', 'Couple conique'), ('satellite', 'Satellite'), ('planetaire', 'Planétaire'), ('axe_satellite', 'Axe de satellite'), ('carter_pont', 'Carter de pont'), ('couvercle_pont', 'Couvercle de pont'), ('bouchon_vidange', 'Bouchon de vidange'), ('bouchon_remplissage', 'Bouchon de remplissage'), ('reniflard', 'Reniflard de pont'), ('roulement_pignon', 'Roulement de pignon'), ('roulement_differentiel', 'Roulement de différentiel'), ('cage_roulement', 'Cage de roulement'), ('cale_reglage', 'Cale de réglage'), ('entretoise', 'Entretoise'), ('joint_spy', 'Joint spi'), ('joint_carter', 'Joint de carter'), ('joint_etancheite', 'Joint d’étanchéité'), ('bride_pont', 'Bride de pont'), ('vis_couronne', 'Vis de couronne'), ('boulonnerie_pont', 'Boulonnerie de pont'), ('kit_roulements_pont', 'Kit roulements de pont'), ('kit_joints_pont', 'Kit joints de pont'), ('kit_revision_pont', 'Kit révision de pont')], max_length=60, verbose_name='Type de pièce de pont')),
                ('voiture_modele', models.ManyToManyField(blank=True, related_name='pieces_pont', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Pièce de pont',
                'verbose_name_plural': 'Pièces de pont',
            },
            bases=('piece.piece',),
        ),
    ]
