# Generated by Django 5.2.10 on 2026-04-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statsfournisseur',
            options={'verbose_name': 'Statistique fournisseur', 'verbose_name_plural': 'Statistiques fournisseurs'},
        ),
    ]
