# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricite',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_electricite', models.CharField(choices=[('alternateur', 'Alternateur'), ('batterie', 'Batterie'), ('demarreur', 'Démarreur'), ('leve_vitre_avg', 'Lève-vitre avant gauche'), ('leve_vitre_avd', 'Lève-vitre avant droit'), ('leve_vitre_arg', 'Lève-vitre arrière gauche'), ('leve_vitre_ard', 'Lève-vitre arrière droit'), ('pompe_lave_glace_av', 'Pompe lave-glace avant'), ('pompe_lave_glace_ar', 'Pompe lave-glace arrière'), ('klaxon', 'Klaxon')], max_length=50)),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='electricites', to='voiture_moteur.moteurvoiture')),
            ],
            options={
                'verbose_name': 'Pièce électricité',
                'verbose_name_plural': 'Pièces électricité',
            },
            bases=('piece.piece',),
        ),
    ]
