# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceSilentBloc',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_silent_bloc', models.CharField(choices=[('silent_bloc_triangle_sup', 'Silent-bloc de triangle supérieur'), ('silent_bloc_triangle_inf', 'Silent-bloc de triangle inférieur'), ('silent_bloc_bras_suspension', 'Silent-bloc de bras de suspension'), ('silent_bloc_train_av', 'Silent-bloc de train avant'), ('silent_bloc_train_ar', 'Silent-bloc de train arrière'), ('silent_bloc_barre_stab', 'Silent-bloc de barre stabilisatrice'), ('silent_bloc_berceau', 'Silent-bloc de berceau'), ('silent_bloc_pont', 'Silent-bloc de pont'), ('silent_bloc_boite', 'Silent-bloc de boîte de vitesses'), ('silent_bloc_transmission', 'Silent-bloc de transmission'), ('silent_bloc_arbre_transmission', 'Silent-bloc d’arbre de transmission'), ('silent_bloc_moteur', 'Silent-bloc moteur'), ('support_moteur', 'Support moteur'), ('support_boite', 'Support de boîte'), ('silent_bloc_chassis', 'Silent-bloc de châssis'), ('silent_bloc_carrosserie', 'Silent-bloc de carrosserie'), ('silent_bloc_echappement', 'Silent-bloc d’échappement'), ('silent_bloc_direction', 'Silent-bloc de direction'), ('kit_silent_bloc', 'Kit de silent-blocs'), ('kit_silent_bloc_train_av', 'Kit silent-blocs train avant'), ('kit_silent_bloc_train_ar', 'Kit silent-blocs train arrière')], max_length=70, verbose_name='Type de silent-bloc')),
                ('voiture_modele', models.ManyToManyField(blank=True, related_name='pieces_silent_bloc', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Silent-bloc',
                'verbose_name_plural': 'Silent-blocs',
            },
            bases=('piece.piece',),
        ),
    ]
