# Generated by Django 5.2.10 on 2026-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece_silent_bloc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecesilentbloc',
            name='type_piece_silent_bloc',
            field=models.CharField(choices=[('silent_bloc_triangle_sup', 'Silent-bloc de triangle supérieur'), ('silent_bloc_triangle_inf', 'Silent-bloc de triangle inférieur'), ('silent_bloc_bras_suspension', 'Silent-bloc de bras de suspension'), ('silent_bloc_train_av', 'Silent-bloc de train avant'), ('silent_bloc_train_ar', 'Silent-bloc de train arrière'), ('silent_bloc_barre_stab', 'Silent-bloc de barre stabilisatrice'), ('silent_bloc_berceau', 'Silent-bloc de berceau'), ('silent_bloc_pont', 'Silent-bloc de pont'), ('silent_bloc_boite', 'Silent-bloc de boîte de vitesse'), ('silent_bloc_transmission', 'Silent-bloc de transmission'), ('silent_bloc_arbre_transmission', 'Silent-bloc d’arbre de transmission'), ('silent_bloc_moteur', 'Silent-bloc moteur'), ('support_moteur', 'Support moteur'), ('support_boite', 'Support de boîte'), ('silent_bloc_chassis', 'Silent-bloc de châssis'), ('silent_bloc_carrosserie', 'Silent-bloc de carrosserie'), ('silent_bloc_echappement', 'Silent-bloc d’échappement'), ('silent_bloc_direction', 'Silent-bloc de direction'), ('kit_silent_bloc', 'Kit de silent-blocs'), ('kit_silent_bloc_train_av', 'Kit silent-blocs train avant'), ('kit_silent_bloc_train_ar', 'Kit silent-blocs train arrière')], max_length=70, verbose_name='Type de silent-bloc'),
        ),
    ]
