# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceSuspension',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_suspension', models.CharField(choices=[('amortisseur_av', 'Amortisseur avant'), ('amortisseur_ar', 'Amortisseur arrière'), ('amortisseur_gd', 'Amortisseur G/D'), ('ressort_av', 'Ressort avant'), ('ressort_ar', 'Ressort arrière'), ('coupelle_amortisseur', 'Coupelle d’amortisseur'), ('butée_suspension', 'Butée de suspension'), ('soufflet_amortisseur', 'Soufflet d’amortisseur'), ('silent_bloc_suspension', 'Silent bloc de suspension'), ('kit_suspension', 'Kit de suspension'), ('cales_ressort', 'Cales de ressort'), ('correcteur_assiette', 'Correcteur d’assiette'), ('suspension_hydraulique', 'Suspension hydraulique'), ('suspension_pneumatique', 'Suspension pneumatique')], max_length=50, verbose_name='Type de pièce suspension')),
                ('voiture_modele', models.ManyToManyField(blank=True, related_name='pieces_suspension', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Pièce de suspension',
                'verbose_name_plural': 'Pièces de suspension',
            },
            bases=('piece.piece',),
        ),
    ]
