# Generated by Django 5.2.10 on 2026-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essuyage', '0003_alter_essuyage_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essuyage',
            name='liquide_lave_glace_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantité ajoutée en litres', max_digits=6, verbose_name='Quantité'),
        ),
    ]
