# Generated by Django 5.2.10 on 2026-08-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essuyage', '0004_alter_essuyage_liquide_lave_glace_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='essuyage',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
