# Generated by Django 5.2.10 on 2026-08-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essuyage', '0005_essuyage_kilometrage_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essuyage',
            name='maintenance',
        ),
    ]
