# Generated by Django 5.2.10 on 2026-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essuyage', '0007_essuyage_serrage_roues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essuyage',
            name='liquide_lave_glace',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Liquide lave-glace'),
        ),
    ]
