# Generated by Django 5.2.10 on 2026-09-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essuyage', '0008_alter_essuyage_liquide_lave_glace'),
    ]

    operations = [
        migrations.AddField(
            model_name='essuyage',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
