# Generated by Django 5.2.10 on 2026-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essuyage', '0012_alter_essuyage_balai_arriere_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essuyage',
            name='liquide_lave_glace',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'A Remplacer')], default='BON', max_length=25, verbose_name='Liquide de lave-glace'),
        ),
    ]
