# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilentBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit')], max_length=10, verbose_name='Emplacement')),
                ('type_bloc', models.CharField(choices=[('TRIANGLE', 'Triangle'), ('TRIANGLE_SUP', 'Triangle supérieur'), ('MULTI_BRAS', 'Suspension multi bras'), ('BARRE_STAB_AV', 'Barre stabilisatrice AV'), ('BARRE_STAB_AR', 'Barre stabilisatrice AR'), ('MOTEUR', 'Moteur'), ('BOITE_VITESSE', 'Boite vitesse'), ('PENDULAIRE', 'Pendulaire')], max_length=20, verbose_name='Type de silentbloc')),
                ('etat', models.CharField(choices=[('BON', 'Bon'), ('USE', 'Usé'), ('HS', 'Hors service')], max_length=10, verbose_name='État')),
                ('commentaire', models.TextField(blank=True, verbose_name='Observation')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='VERT', max_length=10, verbose_name='État visuel / Tag')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silentblocs', to='maintenance.maintenance', verbose_name='Maintenance')),
            ],
        ),
    ]
