# Generated by Django 5.2.10 on 2026-03-27 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('silent_blocs', '0001_initial'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='silentbloc',
            options={'verbose_name': 'Silent bloc', 'verbose_name_plural': 'Silent blocs'},
        ),
        migrations.RemoveField(
            model_name='silentbloc',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='silentbloc',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='silentbloc',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='silentbloc',
            name='type_bloc',
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='kilometrage_silent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du contrôle des silent blocs'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs amortisseur arrière droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs amortisseur arrière gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs amortisseur avant droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs amortisseur avant gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs barre stabilisatrice arrière'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs barre stabilisatrice avant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs moteur'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de boite de vitesse'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_inf_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs moteur pendulaire'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de suspension multi-bras arrière droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de suspension multi-bras arrière gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de suspension multi-bras avant droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de suspension multi-bras avant gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle inférieur arrière droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle inférieur arrière gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle inférieur avant droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle inférieur avant gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle supérieur arrière droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle supérieur arrière gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle supérieur avant droit'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent_blocs de triangle supérieur avant gauche'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='tech_nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='tech_role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silent_tech_societe', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='tech_technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silent_techs', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silent_exemplaire', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_silent'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SilentBloc', to='maintenance.maintenance', verbose_name='Silent bloc'),
        ),
    ]
