# Generated by Django 5.2.10 on 2026-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0002_alter_silentbloc_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avg',
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_bloc_amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc amortisseur avant gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc amortisseur arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc amortisseur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc amortisseur avant droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent blocs barre stabilisatrice arrière'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent blocs barre stabilisatrice avant'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc moteur'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de boite de vitesse'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_inf_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc moteur pendulaire'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de suspension multi-bras arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de suspension multi-bras arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de suspension multi-bras avant droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de suspension multi-bras avant gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle inférieur arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle inférieur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle inférieur avant droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle inférieur avant gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle supérieur arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle supérieur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle supérieur avant droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='silent bloc de triangle supérieur avant gauche'),
        ),
    ]
