# Generated by Django 5.2.10 on 2026-04-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0003_remove_maindoeuvre_temps_maindoeuvre_temps_minutes'),
        ('silent_blocs', '0003_remove_silentbloc_silent_blocs_amortisseur_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentbloc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silent_blocs', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
    ]
