# Generated by Django 5.2.10 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0004_silentbloc_created_at_silentbloc_main_oeuvre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentbloc',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
