# Generated by Django 5.2.10 on 2026-06-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0005_alter_silentbloc_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentbloc',
            name='kilometrage_silent',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du contrôle des silent blocs'),
            preserve_default=False,
        ),
    ]
