# Generated by Django 5.2.10 on 2026-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0006_alter_silentbloc_kilometrage_silent'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentbloc',
            name='silent_bloc_amortisseur_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_bloc_amortisseur_avg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_ard_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_arg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avd_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_ar_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_av_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_avg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_inf_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_inf_arg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_ard_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_arg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avd_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_ard_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_arg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avd_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_ard_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_arg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avd_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avg_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
