# Generated by Django 5.2.10 on 2026-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0010_silentbloc_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentbloc',
            name='silent_bloc_amortisseur_avg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_ard_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_arg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avd_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_ar_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_av_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_avg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_moteur_inf_arg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_ard_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_arg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avd_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_ard_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_arg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avd_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_ard_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_arg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avd_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avg_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_bloc_amortisseur_avg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_ard_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_arg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avd_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_ar_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_av_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_avg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_inf_arg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_ard_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_arg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avd_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_ard_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_arg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avd_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_ard_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_arg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avd_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avg_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
