# Generated by Django 5.2.10 on 2026-08-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0012_alter_silentbloc_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentbloc',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
