# Generated by Django 5.2.10 on 2026-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0014_silentbloc_serrage_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentbloc',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
