# Generated by Django 5.2.10 on 2026-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0016_silentbloc_kilometres_boite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentbloc',
            name='kilometres_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='kilometres_embrayage_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback embrayage'),
        ),
    ]
