# Generated by Django 5.2.10 on 2026-10-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0017_silentbloc_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_echappement',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Silent blocs d'échappement"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_echappement_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_echappement_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='silentbloc',
            name='silent_blocs_echappement_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_bloc_amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc amortisseur avant gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc amortisseur arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc amortisseur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc amortisseur avant droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent blocs barre stabilisatrice arrière'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent blocs barre stabilisatrice avant'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc moteur'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de boite de vitesse'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_inf_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc moteur pendulaire'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de suspension multi-bras arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de suspension multi-bras arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de suspension multi-bras avant droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_multi_bras_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de suspension multi-bras avant gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de triangle inférieur arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de triangle inférieur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_inf_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de triangle inférieur avant gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de triangle supérieur arrière droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de triangle supérieur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de triangle supérieur avant droit'),
        ),
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_triangle_sup_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de triangle supérieur avant gauche'),
        ),
    ]
