# Generated by Django 5.2.10 on 2026-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_blocs', '0018_silentbloc_silent_blocs_echappement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentbloc',
            name='silent_blocs_moteur_boite_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent bloc de boîte de vitesse'),
        ),
    ]
