# Generated by Django 5.2.10 on 2026-02-04 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiturePneus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturier', models.CharField(max_length=100)),
                ('emplacement', models.CharField(choices=[('avant', 'Avant'), ('arriere', 'Arrière'), ('avant_arriere', 'Avant et Arrière')], max_length=50)),
                ('type_pneus', models.CharField(choices=[('ete', 'Été'), ('pluie', 'Pluie'), ('semi_slick', 'Semi-slick'), ('slick', 'Slick'), ('4saisons', '4 saisons'), ('hiver', 'Hiver')], max_length=20)),
                ('nom_type', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_oem', models.CharField(blank=True, max_length=50, null=True)),
                ('pneus_largeur', models.CharField(default='175', help_text='175 mm', max_length=15)),
                ('pneus_hauteur', models.CharField(default='65', help_text='65 %', max_length=15)),
                ('pneus_jante', models.CharField(default='15', help_text='15 pouces', max_length=15)),
                ('kilometre_pneus_av', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres pneus avant')),
                ('kilometre_pneus_ar', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres pneus arrière')),
                ('indice_vitesse', models.CharField(choices=[('Q', 'Q (160 km/h)'), ('R', 'R (170 km/h)'), ('S', 'S (180 km/h)'), ('T', 'T (190 km/h)'), ('H', 'H (210 km/h)'), ('V', 'V (240 km/h)'), ('W', 'W (270 km/h)'), ('Y', 'Y (300 km/h)'), ('ZR W', 'ZR W (>270 km/h)'), ('ZR Y', 'ZR Y (>300 km/h)'), ('ZR', 'ZR (historique >240 km/h)')], default='T', max_length=10, verbose_name='Indice de vitesse')),
                ('indice_charge', models.CharField(choices=[('60', '60 (250 kg)'), ('62', '62 (265 kg)'), ('64', '64 (280 kg)'), ('68', '68 (315 kg)'), ('70', '70 (335 kg)'), ('73', '73 (365 kg)'), ('75', '75 (387 kg)'), ('78', '78 (425 kg)'), ('81', '81 (450 kg)'), ('84', '84 (500 kg)'), ('87', '87 (545 kg)'), ('91', '91 (615 kg)'), ('94', '94 (670 kg)'), ('97', '97 (730 kg)'), ('100', '100 (800 kg)'), ('103', '103 (875 kg)'), ('106', '106 (950 kg)'), ('109', '109 (1030 kg)'), ('112', '112 (1120 kg)'), ('115', '115 (1215 kg)'), ('118', '118 (1320 kg)')], default='91', max_length=10, verbose_name='Indice de charge')),
                ('date_remplacement', models.DateField(blank=True, null=True)),
                ('kilometre_remplacement', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_trains_av', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('nombre_trains_ar', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='pneus', to='voiture_exemplaire.voitureexemplaire')),
                ('voitures_modeles', models.ManyToManyField(blank=True, related_name='pneus', to='voiture_modele.voituremodele')),
            ],
        ),
    ]
