# Generated by Django 5.2.9 on 2025-12-19 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseur', '0001_initial'),
        ('societe', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiturePneus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_pneus', models.CharField(choices=[('ete', 'Été'), ('pluie', 'Pluie'), ('semi_slick', 'Semi-slick'), ('slick', 'Slick'), ('4saisons', '4 saisons'), ('hiver', 'Hiver')], max_length=20)),
                ('pneus_avant', models.CharField(help_text='Format xxx/xx/xx', max_length=15)),
                ('pneus_arriere', models.CharField(help_text='Format xxx/xx/xx', max_length=15)),
                ('kilometre_pneus', models.PositiveIntegerField(default=0)),
                ('date_remplacement', models.DateField(blank=True, null=True)),
                ('kilometre_remplacement', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_trains_av', models.PositiveSmallIntegerField(default=1)),
                ('nombre_trains_ar', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pneus', to='fournisseur.fournisseur')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pneus', to='societe.societe')),
                ('voiture_modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations_pneus', to='voiture_modele.voituremodele')),
            ],
        ),
    ]
