# Generated by Django 5.2.9 on 2025-12-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0002_initial'),
        ('voiture_pneus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturepneus',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pneus', to='voiture_exemplaire.voitureexemplaire'),
        ),
    ]
