# Generated by Django 5.2.10 on 2026-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_pneus', '0002_voiturepneus_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiturepneus',
            name='indice_charge',
            field=models.CharField(choices=[('60', '60 (250 kg)'), ('62', '62 (265 kg)'), ('64', '64 (280 kg)'), ('68', '68 (315 kg)'), ('70', '70 (335 kg)'), ('73', '73 (365 kg)'), ('75', '75 (387 kg)'), ('78', '78 (425 kg)'), ('81', '81 (450 kg)'), ('84', '84 (500 kg)'), ('88', '88 (560 kg)'), ('91', '91 (615 kg)'), ('94', '94 (670 kg)'), ('97', '97 (730 kg)'), ('100', '100 (800 kg)'), ('103', '103 (875 kg)'), ('106', '106 (950 kg)'), ('109', '109 (1030 kg)'), ('112', '112 (1120 kg)'), ('115', '115 (1215 kg)'), ('118', '118 (1320 kg)')], default='91', max_length=10, verbose_name='Indice de charge'),
        ),
    ]
