# Generated by Django 5.2.10 on 2026-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_pneus', '0004_voiturepneus_remarques_voiturepneus_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiturepneus',
            name='pneus_hauteur',
            field=models.CharField(default='65', max_length=15, verbose_name='Hauteur du pneu'),
        ),
        migrations.AlterField(
            model_name='voiturepneus',
            name='pneus_jante',
            field=models.CharField(default='15', max_length=15, verbose_name='Diamètre de la jante en pouces'),
        ),
        migrations.AlterField(
            model_name='voiturepneus',
            name='pneus_largeur',
            field=models.CharField(default='175', max_length=15, verbose_name='Largeur du pneu'),
        ),
    ]
