# Generated by Django 5.2.10 on 2026-02-12 08:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0002_voitureexemplaire_societe'),
        ('voiture_marque', '0001_initial'),
        ('voiture_modele', '0002_voituremodele_societe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, verbose_name='Immatriculation')),
                ('type_carburant', models.CharField(choices=[('ELECTRICITE', 'Electricite')], editable=False, max_length=15, verbose_name='Type de carburant')),
                ('volume_max', models.FloatField(verbose_name='Kilos Watt max')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la recharge')),
                ('kW', models.FloatField(verbose_name='Kilos Watt')),
                ('prix_recharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de la recharge (€)')),
                ('prix_watt', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Prix au kilo Watt (€)')),
                ('validation', models.BooleanField(default=True, verbose_name='Validation')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricite', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
                ('voiture_marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricite', to='voiture_marque.voituremarque', verbose_name='Marque')),
                ('voiture_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricite', to='voiture_modele.voituremodele', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Electricite',
                'verbose_name_plural': 'Electricites',
                'ordering': ['-date'],
            },
        ),
    ]
