# Generated by Django 5.2.10 on 2026-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0003_electricite_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricite',
            name='kilometrage_electicite',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilométrage'),
        ),
    ]
