# Generated by Django 5.2.10 on 2026-02-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0004_electricite_kilometrage_electicite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricite',
            old_name='kilometrage_electicite',
            new_name='kilometrage_electricite',
        ),
    ]
