# Generated by Django 5.2.10 on 2026-02-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0005_rename_kilometrage_electicite_electricite_kilometrage_electricite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricite',
            name='kilometrage_electricite',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilométrage recharge'),
        ),
    ]
