# Generated by Django 5.2.10 on 2026-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0008_rechargecarburant_electricite_montant_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricite',
            name='nom_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
