# Generated by Django 5.2.10 on 2026-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0009_electricite_nom_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricite',
            name='type_carburant',
            field=models.CharField(choices=[('ELECTRICITE', 'Electricite')], default='ELECTRICITE', max_length=15, verbose_name='Type de carburant'),
        ),
    ]
