# Generated by Django 5.2.10 on 2026-05-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0011_electricite_created_at_electricite_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricite',
            old_name='volume_max',
            new_name='capacite_batterie',
        ),
    ]
