# Generated by Django 5.2.10 on 2026-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0014_electricite_kilometres_chassis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricite',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
