# Generated by Django 5.2.10 on 2026-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0015_electricite_kilometrage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricite',
            name='taille_batterie',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacité en KW'),
        ),
    ]
