# Generated by Django 5.2.10 on 2026-03-29 10:02

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleBoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometrage_checkup_boite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du Checkup')),
                ('embrayage_disque', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name="Disque d'embrayage")),
                ('embrayage_plateau', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name="Plateau d'embrayage")),
                ('arbre_primaire', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Arbre primaire')),
                ('arbre_secondaire', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Arbre secondaire')),
                ('roulement_primaire', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Roulement arbre primaire')),
                ('roulement_secondaire', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Roulement arbre secondaire')),
                ('roulement_differentiel', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Roulement différentiel')),
                ('vitesse_1', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 1ère vitesse')),
                ('vitesse_2', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 2ème vitesse')),
                ('vitesse_3', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 3ème vitesse')),
                ('vitesse_4', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 4ème vitesse')),
                ('vitesse_5', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 5ème vitesse')),
                ('vitesse_6', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 6ème vitesse (si existante)')),
                ('vitesse_7', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 7ème vitesse (si existante)')),
                ('vitesse_8', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon 8ème vitesse (si existante)')),
                ('synchros', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Synchros')),
                ('fourchettes', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Fourchettes')),
                ('huile_manuelle_quantite', models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres")),
                ('huile_manuelle_qualite', models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='75W', max_length=25, verbose_name="Qualité de l'huile")),
                ('convertisseur_couple', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Convertisseur de couple')),
                ('embrayages_auto', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Embrayages automatiques')),
                ('pompes_huile', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pompes à huile')),
                ('valves', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Valves de contrôle')),
                ('arbre_torque', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Arbre de couple')),
                ('arbre_secondaire_auto', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Arbre secondaire')),
                ('roulement_auto', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Roulements internes')),
                ('huile_auto_quantite', models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres")),
                ('huile_auto_qualite', models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='ATF_III', max_length=25, verbose_name="Qualité de l'huile")),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_boite', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_boite', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_boite', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_boite', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_checkup')),
            ],
            options={
                'verbose_name': 'Contrôle boite',
                'verbose_name_plural': 'Contrôles boites',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
