# Generated by Django 5.2.10 on 2026-03-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controleboite',
            old_name='arbre_secondaire',
            new_name='auto_arbre_secondaire_auto',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='arbre_torque',
            new_name='auto_arbre_torque',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='convertisseur_couple',
            new_name='auto_convertisseur_couple',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='embrayages_auto',
            new_name='auto_embrayages_auto',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='pompes_huile',
            new_name='auto_pompes_huile',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='valves',
            new_name='auto_valves',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='huile_auto_qualite',
            new_name='autohuile_auto_qualite',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='huile_auto_quantite',
            new_name='autohuile_auto_quantite',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='roulement_auto',
            new_name='autoroulement_auto',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='arbre_primaire',
            new_name='bte_arbre_primaire',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='arbre_secondaire_auto',
            new_name='bte_arbre_secondaire',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='embrayage_disque',
            new_name='bte_embrayage_disque',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='embrayage_plateau',
            new_name='bte_embrayage_plateau',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='roulement_differentiel',
            new_name='roulement_bte_differentiel',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='roulement_primaire',
            new_name='roulement_bte_primaire',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='roulement_secondaire',
            new_name='roulement_bte_secondaire',
        ),
    ]
