# Generated by Django 5.2.10 on 2026-03-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0003_rename_autohuile_auto_qualite_controleboite_auto_huile_auto_qualite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controleboite',
            old_name='auto_arbre_secondaire_auto',
            new_name='auto_b_arbre_secondaire_auto',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='auto_arbre_torque',
            new_name='auto_b_arbre_torque',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='auto_convertisseur_couple',
            new_name='auto_b_convertisseur_couple',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='auto_embrayages_auto',
            new_name='auto_b_embrayages_auto',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='auto_pompes_huile',
            new_name='auto_b_pompes_huile',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='auto_roulement_auto',
            new_name='auto_b_roulement_auto',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='auto_valves',
            new_name='auto_b_valves',
        ),
    ]
