# Generated by Django 5.2.10 on 2026-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0004_rename_auto_arbre_secondaire_auto_controleboite_auto_b_arbre_secondaire_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleboite',
            name='kilometrage_checkup_boite',
        ),
        migrations.AddField(
            model_name='controleboite',
            name='kilometrage_controle_boite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du controle'),
        ),
    ]
