# Generated by Django 5.2.10 on 2026-03-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0005_remove_controleboite_kilometrage_checkup_boite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controleboite',
            old_name='bte_arbre_primaire',
            new_name='bte_a_primaire',
        ),
        migrations.RenameField(
            model_name='controleboite',
            old_name='bte_arbre_secondaire',
            new_name='bte_a_secondaire',
        ),
    ]
