# Generated by Django 5.2.10 on 2026-03-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0006_rename_bte_arbre_primaire_controleboite_bte_a_primaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_b_arbre_secondaire_auto',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_b_arbre_torque',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_b_convertisseur_couple',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_b_embrayages_auto',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_b_pompes_huile',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_b_roulement_auto',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_b_valves',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_huile_auto_qualite',
        ),
        migrations.RemoveField(
            model_name='controleboite',
            name='auto_huile_auto_quantite',
        ),
    ]
