# Generated by Django 5.2.10 on 2026-04-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0007_remove_controleboite_auto_b_arbre_secondaire_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleboite',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
