# Generated by Django 5.2.10 on 2026-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0009_controleboite_created_at_controleboite_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleboite',
            name='vitesse_r',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pignon de marche arrière'),
        ),
    ]
