# Generated by Django 5.2.10 on 2026-05-26 12:23

import maintenance.niveaux.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0011_controleboite_main_oeuvre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleboite',
            name='bte_a_primaire',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Arbre primaire'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='bte_a_secondaire',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Arbre secondaire'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='bte_embrayage_disque',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Disque d'embrayage"),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='bte_embrayage_plateau',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Plateau d'embrayage"),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='fourchettes',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fourchettes'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='man_huile_manuelle_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90')], default='75W', max_length=25, verbose_name="Qualité de l'huile"),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='man_huile_manuelle_quantite',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='roulement_bte_differentiel',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Roulement différentiel'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='roulement_bte_primaire',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Roulement arbre primaire'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='roulement_bte_secondaire',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Roulement arbre secondaire'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='synchros',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Synchros'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_1',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 1ère vitesse'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_2',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 2ème vitesse'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_3',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 3ème vitesse'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_4',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 4ème vitesse'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_5',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 5ème vitesse'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_6',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 6ème vitesse (si existante)'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_7',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 7ème vitesse (si existante)'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_8',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon 8ème vitesse (si existante)'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_r',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pignon de marche arrière'),
        ),
    ]
