# Generated by Django 5.2.10 on 2026-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0013_alter_controleboite_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleboite',
            name='kilometrage_controle_boite',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du controle'),
            preserve_default=False,
        ),
    ]
