# Generated by Django 5.2.10 on 2026-07-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0017_alter_controleboite_man_huile_manuelle_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleboite',
            name='man_huile_manuelle',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Huile de boite de vitesse'),
        ),
    ]
