# Generated by Django 5.2.10 on 2026-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0022_alter_controleboite_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleboite',
            name='bte_a_primaire_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='bte_a_secondaire_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='bte_embrayage_disque_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='bte_embrayage_plateau_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='fourchettes_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='roulement_bte_differentiel_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='roulement_bte_primaire_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='roulement_bte_secondaire_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='synchros_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_2_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_3_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_4_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_5_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_6_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_7_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_8_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_r_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
