# Generated by Django 5.2.10 on 2026-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0023_alter_controleboite_bte_a_primaire_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleboite',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
