# Generated by Django 5.2.10 on 2026-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0025_controleboite_serrage_roues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleboite',
            name='vitesse_1_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
