# Generated by Django 5.2.10 on 2026-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0026_alter_controleboite_vitesse_1_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleboite',
            name='man_huile_manuelle_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF_DSG', 'ATF DSG'), ('ATF_DCT', 'ATF DCT'), ('ATF_CVT', 'ATF CVT'), ('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('ATF_MERCON', 'ATF Mercon'), ('ATF_MERCON_V', 'ATF Mercon V'), ('ATF_MERCON_LV', 'ATF Mercon LV'), ('ATF_MULTI', 'ATF Multi Vehicle'), ('ATF_WS', 'ATF Toyota WS'), ('ATF_ZF_LIFEGUARD', 'ZF Lifeguard'), ('ATF_MOPAR', 'Mopar ATF+4'), ('ATF_AISIN', 'Aisin ATF'), ('ATF_MBV236', 'Mercedes MB 236.x'), ('ATF_VOLVO', 'Volvo ATF'), ('ATF_HONDA', 'Honda ATF DW-1'), ('ATF_NISSAN', 'Nissan Matic'), ('PORSCHE_PDK', 'Porsche PDK'), ('PORSCHE_DCT', 'Porsche DCT'), ('PORSCHE_TIPTRONIC', 'Porsche Tiptronic'), ('VAG_DSG_DQ250', 'VAG DSG DQ250'), ('VAG_DSG_DQ381', 'VAG DSG DQ381'), ('VAG_DSG_DQ500', 'VAG DSG DQ500'), ('VAG_DSG_DQ200', 'VAG DSG DQ200'), ('VAG_S_TRONIC', 'Audi S tronic'), ('VAG_MULTITRONIC', 'Audi Multitronic'), ('VAG_TIPTRONIC', 'VAG Tiptronic'), ('FORD_MERCON', 'Ford Mercon'), ('FORD_MERCON_V', 'Ford Mercon V'), ('FORD_MERCON_LV', 'Ford Mercon LV'), ('FORD_MERCON_ULV', 'Ford Mercon ULV'), ('FORD_POWERSHIFT', 'Ford PowerShift'), ('FORD_CVT', 'Ford CVT'), ('ALFA_TCT', 'Alfa Romeo TCT'), ('ALFA_SELESPEED', 'Alfa Romeo Selespeed'), ('ALFA_ATF', 'Alfa Romeo ATF'), ('ALFA_TUTELA', 'Alfa Romeo Tutela'), ('FERRARI_DCT', 'Ferrari DCT'), ('FERRARI_F1', 'Ferrari F1'), ('FERRARI_GETRAG', 'Ferrari Getrag'), ('FERRARI_ATF', 'Ferrari ATF')], default='75W', max_length=25, verbose_name="Qualité de l'huile"),
        ),
    ]
