# Generated by Django 5.2.10 on 2026-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0027_alter_controleboite_man_huile_manuelle_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleboite',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
