# Generated by Django 5.2.10 on 2026-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boite_de_vitesse', '0034_controleboite_bte_embrayage_disque_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleboite',
            name='man_huile_manuelle',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Huile de boîte de vitesse'),
        ),
    ]
