# Generated by Django 5.2.10 on 2026-07-14 11:37

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maindoeuvre', '0011_maindoeuvre_kilometres_chassis'),
        ('maintenance', '0014_alter_maintenance_type_maintenance'),
        ('societe', '0006_alter_societe_max_utilisateurs'),
        ('voiture_exemplaire', '0024_voitureexemplaire_kilometres_rodage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climatisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres châssis')),
                ('kilometrage_clim', models.PositiveIntegerField(verbose_name='Kilométrage au moment du contrôle de la climatisation')),
                ('pays', models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], default='BE', max_length=5, verbose_name='Pays')),
                ('type_gaz', models.CharField(choices=[('R134A', 'R134a'), ('R1234YF', 'R1234yf'), ('R744', 'R744 / CO₂'), ('AUTRE', 'Autre')], default='R134A', max_length=20, verbose_name='Type de gaz')),
                ('autre_type_gaz', models.CharField(blank=True, max_length=100, verbose_name='Autre type de gaz')),
                ('poids_gaz_constructeur', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Poids de gaz préconisé par le constructeur en grammes')),
                ('poids_gaz_recupere', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Poids de gaz récupéré en grammes')),
                ('poids_gaz_injecte', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Poids de gaz injecté en grammes')),
                ('qualite_gaz', models.CharField(choices=[('BONNE', 'Bonne'), ('CONTAMINE', 'Contaminé'), ('HUMIDE', "Présence d'humidité"), ('INCONNUE', 'Inconnue')], default='INCONNUE', max_length=25, verbose_name='Qualité du gaz')),
                ('pourcentage_purete_gaz', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Pureté du gaz en pourcentage')),
                ('ajout_huile', models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait'), ('NON_NECESSAIRE', 'Non nécessaire')], default='A_FAIRE', max_length=25, verbose_name="Ajout d'huile de climatisation")),
                ('quantite_huile_recuperee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Quantité d'huile récupérée en millilitres")),
                ('quantite_huile_injectee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Quantité d'huile injectée en millilitres")),
                ('type_huile', models.CharField(blank=True, max_length=100, verbose_name="Type d'huile")),
                ('ajout_traceur', models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait'), ('NON_NECESSAIRE', 'Non nécessaire')], default='A_FAIRE', max_length=25, verbose_name='Ajout de traceur')),
                ('quantite_traceur', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantité de traceur en millilitres')),
                ('mise_sous_vide', models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait'), ('NON_NECESSAIRE', 'Non nécessaire')], default='A_FAIRE', max_length=25, verbose_name='Mise sous vide')),
                ('duree_mise_sous_vide_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée de mise sous vide en minutes')),
                ('pression_vide_atteinte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pression de vide atteinte')),
                ('tenue_du_vide', models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait'), ('NON_NECESSAIRE', 'Non nécessaire')], default='A_FAIRE', max_length=25, verbose_name='Contrôle de tenue du vide')),
                ('controle_fuites', models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait'), ('NON_NECESSAIRE', 'Non nécessaire')], default='A_FAIRE', max_length=25, verbose_name='Contrôle des fuites')),
                ('resultat_fuites', models.CharField(choices=[('AUCUNE', 'Aucune fuite'), ('FAIBLE', 'Fuite faible'), ('IMPORTANTE', 'Fuite importante'), ('NON_CONTROLEE', 'Non contrôlée')], default='NON_CONTROLEE', max_length=25, verbose_name='Résultat du contrôle des fuites')),
                ('methode_controle_fuites', models.CharField(blank=True, help_text='Exemple : traceur UV, azote hydrogéné, détecteur électronique.', max_length=100, verbose_name='Méthode de contrôle des fuites')),
                ('emplacement_fuite', models.TextField(blank=True, null=True, verbose_name='Emplacement de la fuite')),
                ('tuyaux', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Tuyaux de climatisation')),
                ('tuyaux_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA des tuyaux")),
                ('tuyaux_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('valves', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Valves de climatisation')),
                ('valves_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA des valves")),
                ('valves_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('deshydrateur', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Déshydrateur')),
                ('deshydrateur_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA du déshydrateur")),
                ('deshydrateur_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('condenseur', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Condenseur')),
                ('condenseur_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA du condenseur")),
                ('condenseur_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('compresseur', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Compresseur de climatisation')),
                ('compresseur_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA du compresseur")),
                ('compresseur_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('evaporateur', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Évaporateur')),
                ('evaporateur_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA de l'évaporateur")),
                ('evaporateur_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('pression_basse', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Pression basse')),
                ('pression_haute', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Pression haute')),
                ('temperature_air_entree', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Température d'air à l'entrée en °C")),
                ('temperature_air_sortie', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Température d'air à la sortie en °C")),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climatisation', to='maindoeuvre.maindoeuvre', verbose_name="Main d'œuvre")),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climatisation', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climatisation', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climatisation', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climatisation', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Climatisation',
                'verbose_name_plural': 'Climatisations',
                'ordering': ['-date'],
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
