# Generated by Django 5.2.10 on 2026-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatisation',
            name='recharge',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Recharge de gaz'),
        ),
        migrations.AddField(
            model_name='climatisation',
            name='recharge_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='climatisation',
            name='recharge_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité en grammes'),
        ),
    ]
