# Generated by Django 5.2.10 on 2026-07-27 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0003_climatisation_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatisation',
            name='taux_horaire',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0 €/h'), (Decimal('20.00'), '20 €/h'), (Decimal('25.00'), '25 €/h'), (Decimal('30.00'), '30 €/h'), (Decimal('35.00'), '35 €/h'), (Decimal('40.00'), '40 €/h'), (Decimal('45.00'), '45 €/h'), (Decimal('50.00'), '50 €/h'), (Decimal('60.00'), '60 €/h'), (Decimal('70.00'), '70 €/h'), (Decimal('80.00'), '80 €/h'), (Decimal('90.00'), '90 €/h'), (Decimal('100.00'), '100 €/h'), (Decimal('110.00'), '110 €/h'), (Decimal('115.00'), '115 €/h'), (Decimal('120.00'), '120 €/h'), (Decimal('1250.00'), '125 €/h'), (Decimal('130.00'), '130 €/h')], decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Taux horaire'),
        ),
    ]
