# Generated by Django 5.2.10 on 2026-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0004_alter_climatisation_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatisation',
            name='recharge_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
