# Generated by Django 5.2.10 on 2026-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0005_alter_climatisation_recharge_quantite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatisation',
            old_name='quantite_traceur',
            new_name='ajout_traceur_quantite',
        ),
        migrations.AddField(
            model_name='climatisation',
            name='ajout_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='climatisation',
            name='ajout_huile_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='climatisation',
            name='ajout_traceur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='climatisation',
            name='mise_sous_vide_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix HTVA'),
        ),
        migrations.AddField(
            model_name='climatisation',
            name='mise_sous_vide_quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantité'),
        ),
    ]
