# Generated by Django 5.2.10 on 2026-07-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0006_rename_quantite_traceur_climatisation_ajout_traceur_quantite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatisation',
            old_name='type_huile',
            new_name='ajout_huile_type_huile',
        ),
        migrations.RemoveField(
            model_name='climatisation',
            name='quantite_huile_injectee',
        ),
    ]
