# Generated by Django 5.2.10 on 2026-07-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0007_rename_type_huile_climatisation_ajout_huile_type_huile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatisation',
            name='quantite_huile_recuperee',
        ),
        migrations.AddField(
            model_name='climatisation',
            name='ajout_huile_quantite_huile_recuperee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name="Quantité d'huile récupérée en millilitres"),
        ),
        migrations.AlterField(
            model_name='climatisation',
            name='ajout_huile_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité de traceur en millilitres'),
        ),
        migrations.AlterField(
            model_name='climatisation',
            name='ajout_traceur_quantite',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Quantité de traceur en millilitres'),
        ),
    ]
