# Generated by Django 5.2.10 on 2026-07-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0009_alter_climatisation_ajout_huile_quantite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatisation',
            old_name='ajout_traceur',
            new_name='traceur',
        ),
        migrations.RenameField(
            model_name='climatisation',
            old_name='ajout_traceur_prix',
            new_name='traceur_prix',
        ),
        migrations.RenameField(
            model_name='climatisation',
            old_name='ajout_traceur_quantite',
            new_name='traceur_quantite',
        ),
    ]
