# Generated by Django 5.2.10 on 2026-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0013_climatisation_compresseur_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatisation',
            name='ajout_huile_quantite',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name="Quantité d'huile ajoutée en millilitres"),
        ),
    ]
