# Generated by Django 5.2.10 on 2026-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0015_alter_climatisation_ajout_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatisation',
            name='tuyaux_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
    ]
