# Generated by Django 5.2.10 on 2026-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0017_alter_climatisation_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatisation',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
