# Generated by Django 5.2.10 on 2026-09-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0018_climatisation_kilometrage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatisation',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
