# Generated by Django 5.2.10 on 2026-10-05 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0022_alter_climatisation_compresseur_fabricant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatisation',
            name='ajout_huile_type_huile',
        ),
        migrations.AlterField(
            model_name='climatisation',
            name='ajout_huile_quantite',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='0.015', max_digits=8, validators=[django.core.validators.StepValueValidator(0.001)], verbose_name="Quantité d'huile ajoutée en millilitres"),
        ),
        migrations.AlterField(
            model_name='climatisation',
            name='traceur_quantite',
            field=models.DecimalField(decimal_places=3, default=0, help_text='0.015', max_digits=8, validators=[django.core.validators.StepValueValidator(0.001)], verbose_name="Quantité d'huile ajoutée en millilitres"),
        ),
    ]
