# Generated by Django 5.2.10 on 2026-10-09 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatisation', '0024_climatisation_ajout_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatisation',
            name='traceur_quantite',
            field=models.DecimalField(decimal_places=3, default=0, help_text='0.015', max_digits=8, validators=[django.core.validators.StepValueValidator(0.001)], verbose_name='Quantité de traceur ajouté en millilitres'),
        ),
    ]
