# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrosserie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_societe', models.CharField(max_length=100, verbose_name='Nom de la société')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('numero_tva', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de TVA')),
            ],
            options={
                'verbose_name': 'Carrosserie',
                'verbose_name_plural': 'Carrosseries',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pare_chocs', models.BooleanField(default=False, verbose_name='Pare-chocs')),
                ('bouclier', models.BooleanField(default=False, verbose_name='Bouclier')),
                ('pare_brise', models.BooleanField(default=False, verbose_name='Pare-brise')),
                ('vitre_porte', models.BooleanField(default=False, verbose_name='Vitre de porte')),
                ('lunette', models.BooleanField(default=False, verbose_name='Lunette')),
                ('retroviseur', models.BooleanField(default=False, verbose_name='Rétroviseur')),
                ('aile', models.BooleanField(default=False, verbose_name='Aile')),
                ('elargisseur_aile', models.BooleanField(default=False, verbose_name='Élargisseur d’aile')),
                ('bas_de_caisse', models.BooleanField(default=False, verbose_name='Bas de caisse')),
                ('support_radiateur', models.BooleanField(default=False, verbose_name='Support de radiateur')),
                ('support_pare_choc', models.BooleanField(default=False, verbose_name='Support de pare-chocs')),
                ('porte', models.BooleanField(default=False, verbose_name='Porte')),
                ('poignee_porte', models.BooleanField(default=False, verbose_name='Poignée de porte')),
                ('coffre_haillon', models.BooleanField(default=False, verbose_name='Coffre / hayon')),
                ('joint_coffre', models.BooleanField(default=False, verbose_name='Joint de coffre')),
                ('joint_porte', models.BooleanField(default=False, verbose_name='Joint de porte')),
                ('coquille_aile', models.BooleanField(default=False, verbose_name='Coquille d’aile')),
                ('clips', models.BooleanField(default=False, verbose_name='Clips')),
                ('visserie', models.BooleanField(default=False, verbose_name='Visserie')),
                ('capot', models.BooleanField(default=False, verbose_name='Capot')),
                ('montant_devis', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant du devis')),
                ('montant_facture', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la facture')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('carrosserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='carrosserie.carrosserie', verbose_name='Carrosserie')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
    ]
