# Generated by Django 5.2.10 on 2026-02-04 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrosserie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_societe', models.CharField(max_length=100, verbose_name='Nom de la société')),
                ('responsable_nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable nom')),
                ('responsable_prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable prenom')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('numero_tva', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de TVA')),
                ('peppol_id', models.CharField(blank=True, help_text='Identifiant Peppol, ex : 0208:BE0123456789', max_length=50, null=True, verbose_name='Identifiant Peppol')),
            ],
            options={
                'verbose_name': 'Carrosserie',
                'verbose_name_plural': 'Carrosseries',
            },
        ),
    ]
