# Generated by Django 5.2.10 on 2026-02-14 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrosserie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrosserie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
