# Generated by Django 5.2.10 on 2026-02-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0004_adresse_unique_adresse_par_societe'),
        ('carrosserie', '0003_carrosserie_numero_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserie',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresse.adresse'),
        ),
    ]
