# Generated by Django 5.2.10 on 2026-02-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie', '0004_alter_carrosserie_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrosserie',
            name='pays',
        ),
    ]
