# Generated by Django 5.2.10 on 2026-02-22 13:25

import carrosserie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie', '0006_alter_carrosserie_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserie',
            name='numero_iban',
            field=models.CharField(blank=True, max_length=36, null=True, validators=[carrosserie.models.validate_iban]),
        ),
    ]
