# Generated by Django 5.2.10 on 2026-02-22 13:28

import carrosserie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosserie', '0007_alter_carrosserie_numero_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserie',
            name='numero_iban',
            field=models.CharField(blank=True, max_length=44, null=True, validators=[carrosserie.models.validate_iban]),
        ),
        migrations.AlterField(
            model_name='carrosserie',
            name='responsable_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du responsable'),
        ),
        migrations.AlterField(
            model_name='carrosserie',
            name='responsable_prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prenom du responsable'),
        ),
    ]
