# Generated by Django 5.2.10 on 2026-09-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0007_adresse_societe'),
        ('carrosserie', '0009_carrosserie_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosserie',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='carrosserie', to='adresse.adresse'),
        ),
    ]
