# Generated by Django 5.2.10 on 2026-02-04 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureEmbrayage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fabricant', models.CharField(blank=True, max_length=30, null=True)),
                ('oem', models.CharField(blank=True, max_length=50, null=True)),
                ('type_embrayage', models.CharField(blank=True, choices=[('MONDISQUE', 'Monodisque'), ('MULTIDISQUE', 'Multidisque'), ('AUTOMATIQUE', 'Automatique'), ('HYDRAULIQUE', 'Hydraulique'), ('MECANIQUE', 'Mécanique')], default='MONDISQUE', max_length=20, null=True)),
                ('volant_moteur', models.CharField(blank=True, choices=[('MONOMASSE', 'Monomasse'), ('BIMASSE', 'Bimasse'), ('ALLEGE', 'Allégé / Performance'), ('SEGMENTE', 'Segmenté / Compétition')], default='MONOMASSE', max_length=30, null=True)),
                ('plateau_pression', models.CharField(blank=True, choices=[('CLASSIQUE', 'Classique (mono-disque)'), ('CONCENTRIQUES', 'Ressorts concentriques'), ('HELICOIDAUX', 'Ressorts hélicoïdaux'), ('RENFORCE', 'Renforcé / Compétition'), ('BIMASSE', 'Bimasse (pour volant moteur DMF)')], default='CLASSIQUE', max_length=30, null=True)),
                ('kilometrage_embrayage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('numero_embrayage', models.PositiveSmallIntegerField(blank=True, default=1, help_text='1 à 10 (incrémenté à chaque remplacement)', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='embrayages', to='voiture_exemplaire.voitureexemplaire')),
                ('voitures_modeles', models.ManyToManyField(blank=True, related_name='embrayages', to='voiture_modele.voituremodele')),
            ],
        ),
    ]
