# Generated by Django 5.2.10 on 2026-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0002_voitureembrayage_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureembrayage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='voitureembrayage',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voitureembrayage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='plateau_pression',
            field=models.CharField(blank=True, choices=[('CLASSIQUE', 'Classique (mono-disque)'), ('CONCENTRIQUES', 'Ressorts concentriques'), ('HELICOIDAUX', 'Ressorts hélicoïdaux'), ('RENFORCE', 'Renforcé / Compétition'), ('BIMASSE', 'Bimasse (pour volant moteur DMF)'), ('AUTOMATIQUE', 'Automatique / non présent')], default='CLASSIQUE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='volant_moteur',
            field=models.CharField(blank=True, choices=[('MONOMASSE', 'Monomasse'), ('BIMASSE', 'Bimasse'), ('ALLEGE', 'Allégé / Performance'), ('SEGMENTE', 'Segmenté / Compétition'), ('AUTOMATIQUE', 'Automatique / Plaque flexible')], default='MONOMASSE', max_length=30, null=True),
        ),
    ]
