# Generated by Django 5.2.10 on 2026-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0003_voitureembrayage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureembrayage',
            name='Kilometre_remplacement_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='voitureembrayage',
            name='butee_embrayage',
            field=models.CharField(blank=True, choices=[('MECANIQUE', 'Mécanique'), ('HYDRAULIQUE', 'Hydraulique'), ('AROULEMENT', 'A roulement'), ('CONCENTRIQUES', 'Concentriques'), ('ACABLE', 'A cable')], default='AROULEMENT', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voitureembrayage',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
