# Generated by Django 5.2.10 on 2026-04-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0004_voitureembrayage_kilometre_remplacement_embrayage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voitureembrayage',
            old_name='Kilometre_remplacement_embrayage',
            new_name='Kilometres_remplacement_embrayage',
        ),
        migrations.RenameField(
            model_name='voitureembrayage',
            old_name='kilometrage_embrayage',
            new_name='kilometres_embrayage',
        ),
    ]
