# Generated by Django 5.2.10 on 2026-04-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0005_rename_kilometre_remplacement_embrayage_voitureembrayage_kilometres_remplacement_embrayage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voitureembrayage',
            old_name='Kilometres_remplacement_embrayage',
            new_name='kilometres_remplacement_embrayage',
        ),
    ]
