# Generated by Django 5.2.10 on 2026-04-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0006_rename_kilometres_remplacement_embrayage_voitureembrayage_kilometres_remplacement_embrayage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voitureembrayage',
            name='kilometres_embrayage',
        ),
        migrations.RemoveField(
            model_name='voitureembrayage',
            name='kilometres_remplacement_embrayage',
        ),
    ]
