# Generated by Django 5.2.10 on 2026-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0007_remove_voitureembrayage_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureembrayage',
            name='butee_embrayage',
            field=models.CharField(blank=True, choices=[('MECANIQUE', 'Mécanique'), ('HYDRAULIQUE', 'Hydraulique'), ('AROULEMENT', 'A roulement'), ('CONCENTRIQUES', 'Concentriques'), ('ACABLE', 'A cable'), ('AUTOMATIQUE', 'Automatique, sans butée')], default='AROULEMENT', max_length=30, null=True),
        ),
    ]
