# Generated by Django 5.2.10 on 2026-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0008_alter_voitureembrayage_butee_embrayage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureembrayage',
            name='plateau_pression',
            field=models.CharField(blank=True, choices=[('CLASSIQUE', 'Classique (mono-disque)'), ('CONCENTRIQUES', 'Ressorts concentriques'), ('HELICOIDAUX', 'Ressorts hélicoïdaux'), ('RENFORCE', 'Renforcé / Compétition'), ('BIMASSE', 'Bi-masse (pour volant moteur DMF)'), ('AUTOMATIQUE', 'Automatique / non présent')], default='CLASSIQUE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='type_embrayage',
            field=models.CharField(blank=True, choices=[('MONDISQUE', 'Mono-disque'), ('MULTIDISQUE', 'Multi-disque'), ('AUTOMATIQUE', 'Automatique'), ('HYDRAULIQUE', 'Hydraulique'), ('MECANIQUE', 'Mécanique')], default='MONDISQUE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='volant_moteur',
            field=models.CharField(blank=True, choices=[('MONOMASSE', 'Mono-masse'), ('BIMASSE', 'Bi-masse'), ('ALLEGE', 'Allégé / Performance'), ('SEGMENTE', 'Segmenté / Compétition'), ('AUTOMATIQUE', 'Automatique / Plaque flexible')], default='MONOMASSE', max_length=30, null=True),
        ),
    ]
