# Generated by Django 5.2.10 on 2026-10-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_embrayage', '0009_alter_voitureembrayage_plateau_pression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureembrayage',
            name='type_lubrification',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('SEC', 'Sec'), ('BAIN_HUILE', "Bain d'huile")], default='CHOISIR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='butee_embrayage',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('MECANIQUE', 'Mécanique'), ('HYDRAULIQUE', 'Hydraulique'), ('AROULEMENT', 'A roulement'), ('CONCENTRIQUES', 'Concentriques'), ('ACABLE', 'A cable'), ('AUTOMATIQUE', 'Automatique, sans butée')], default='CHOISIR', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='plateau_pression',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('CLASSIQUE', 'Classique (mono-disque)'), ('CONCENTRIQUES', 'Ressorts concentriques'), ('HELICOIDAUX', 'Ressorts hélicoïdaux'), ('RENFORCE', 'Renforcé / Compétition'), ('BIMASSE', 'Bi-masse (pour volant moteur DMF)'), ('AUTOMATIQUE', 'Automatique / non présent')], default='CHOISIR', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='type_embrayage',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('MONDISQUE', 'Mono-disque'), ('MULTIDISQUE', 'Multi-disque'), ('AUTOMATIQUE', 'Automatique'), ('HYDRAULIQUE', 'Hydraulique'), ('MECANIQUE', 'Mécanique')], default='CHOISIR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voitureembrayage',
            name='volant_moteur',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('MONOMASSE', 'Mono-masse'), ('BIMASSE', 'Bi-masse'), ('ALLEGE', 'Allégé / Performance'), ('SEGMENTE', 'Segmenté / Compétition'), ('AUTOMATIQUE', 'Automatique / Plaque flexible')], default='CHOISIR', max_length=30, null=True),
        ),
    ]
