# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id_investissement', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(choices=[('PONT', 'Pont'), ('MACHINE_GEOMETRIE', 'Machine de géométrie'), ('MACHINE_PNEUS', 'Machine à pneus'), ('EQUILIBREUSE', 'Équilibreuse'), ('COMPRESSEUR', 'Compresseur'), ('BOOSTER_BATTERIE', 'Booster batterie'), ('BOOSTER_PNEUS', 'Booster pneus'), ('TUYAUX_AIR', 'Tuyaux pression d’air'), ('CONNECTEURS', 'Connecteurs'), ('MOBILIER', 'Mobilier'), ('ORDINATEUR', 'Ordinateur'), ('APPAREIL_DIAGNOSTIC', 'Appareil de diagnostic')], max_length=50, verbose_name='Libellé')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails')),
                ('temps_amortissement', models.PositiveIntegerField(help_text="Durée d'amortissement en mois ou années", verbose_name="Durée d'amortissement")),
                ('type_amortissement', models.CharField(choices=[('LINEAIRE', 'Linéaire'), ('DEGRESSIF', 'Dégressif'), ('AUTRE', 'Autre')], default='LINEAIRE', max_length=20, verbose_name="Type d'amortissement")),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='fournisseur.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
            },
        ),
    ]
