# Generated by Django 5.2.9 on 2025-12-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_apprentis_maintenance_chef_mecanicien'),
        ('piece_fluides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.FloatField(help_text='Quantité ajoutée ou retirée', verbose_name='Quantité utilisée (L)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('piece_fluides', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piece_fluides.fluide', verbose_name='Fluide')),
            ],
        ),
    ]
