# Generated by Django 5.2.10 on 2026-03-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('niveaux', '0001_initial'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Contrôle général', 'verbose_name_plural': 'Contrôles généraux'},
        ),
        migrations.RemoveField(
            model_name='niveau',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='niveau',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='boite_niveau_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='75W', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='boite_niveau_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='kilometrage_checkup',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment des niveaux'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='niveau',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='moteur_niveau_huile_qualite',
            field=models.CharField(choices=[('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='moteur_niveau_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='pont_niveau_huile_qualite',
            field=models.CharField(choices=[('75W140', '75W140')], default='75W140', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='pont_niveau_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='refroidissement_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'eau"),
        ),
        migrations.AddField(
            model_name='niveau',
            name='refroidissement_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité de liquide de refroidissement'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='refroidissement_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='remarques',
            field=models.TextField(blank=True, verbose_name='Commentaire niveaux'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='tech_nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='tech_role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux_tech_societe', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='tech_technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux_techs', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveau_exemplaire', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_niveaux'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Niveaux', to='maintenance.maintenance', verbose_name='Niveaux'),
        ),
    ]
