# Generated by Django 5.2.10 on 2026-03-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0002_alter_niveau_options_remove_niveau_commentaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niveau',
            old_name='kilometrage_checkup',
            new_name='kilometrage_niveaux',
        ),
    ]
