# Generated by Django 5.2.10 on 2026-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0004_remove_niveau_piece_fluides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='frein_liquide_qualite',
            field=models.CharField(choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=25, verbose_name='Qualité de liquide de freins'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='frein_liquide_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de freins ajoutée en litres'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='lave_glace_qualite',
            field=models.CharField(choices=[('HIVER', 'Hiver'), ('ETE', 'Eté')], default='HIVER', max_length=25, verbose_name='Qualité de liquide de lave glace'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='lave_glace_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de lave glace ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='refroidissement_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
