# Generated by Django 5.2.10 on 2026-03-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0005_niveau_frein_liquide_etat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
    ]
