# Generated by Django 5.2.10 on 2026-04-04 14:51

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0007_niveau_created_at_niveau_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='boite_niveau_huile_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='frein_liquide_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name='Quantité de liquide de freins ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='lave_glace_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name='Quantité de liquide de lave glace ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='moteur_niveau_huile_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='pont_niveau_huile_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='refroidissement_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
    ]
