# Generated by Django 5.2.10 on 2026-04-27 10:50

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0008_alter_niveau_boite_niveau_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='direction_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='direction_liquide_qualite',
            field=models.CharField(choices=[('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('CHF_1_PLUS', 'CHF 1+'), ('CHF_LIFEGUARD', 'CHF Lifeguard Fluid'), ('PORSCHE_CHF_11S', 'Porsche / Pentosin CHF 11S (direction assistée)'), ('PORSCHE_CHF_202', 'Porsche / Pentosin CHF 202 (hydraulique moderne)'), ('PORSCHE_ATF_D3', 'Porsche ATF Dexron III (anciens modèles)'), ('BMW_CHF_11S', 'BMW / Pentosin CHF 11S (direction assistée)'), ('BMW_CHF_202', 'BMW / Pentosin CHF 202 (direction assistée moderne)'), ('BMW_CHF_7_1', 'BMW CHF 7.1 (anciens systèmes hydrauliques)'), ('BMW_ATF_D3', 'BMW ATF Dexron III (anciens modèles direction assistée)'), ('RENAULT_MATIC_D2', 'Renaultmatic D2 (ELF)'), ('RENAULT_MATIC_D3_SYN', 'Renaultmatic D3 SYN (ELF)'), ('ELF_MATIC_G3', 'ELF Matic G3'), ('RENAULT_PSF_D3', 'Renault PSF Dexron III (direction assistée hydraulique)'), ('RENAULT_ELF_PSF', 'Renault / ELF liquide direction assistée'), ('PSF_HYUNDAI_KIA', 'PSF Hyundai / Kia'), ('PSF_TOYOTA', 'PSF Toyota'), ('PSF_HONDA', 'PSF Honda'), ('UNIVERSAL_PSF', 'Liquide direction assistée universel')], default='CHF_7_1', max_length=25, verbose_name='Qualité de liquide de direction'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='direction_liquide_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name='Quantité de liquide de direction ajoutée en litres'),
        ),
    ]
