# Generated by Django 5.2.10 on 2026-05-29 13:23
from django.core.validators import StepValueValidator

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0011_alter_niveau_boite_niveau_huile_qualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='moteur_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
    ]
