# Generated by Django 5.2.10 on 2026-05-29 13:25

from decimal import Decimal

from django.core.validators import StepValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("niveaux", "0012_alter_niveau_moteur_niveau_huile_quantite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niveau",
            name="boite_niveau_huile_quantite",
            field=models.DecimalField(
                max_digits=4,
                decimal_places=1,
                default=Decimal("0.0"),
                validators=[StepValueValidator(Decimal("0.1"))],
                verbose_name="Quantité d'huile ajoutée en litres",
            ),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="direction_liquide_quantite",
            field=models.DecimalField(
                max_digits=4,
                decimal_places=1,
                default=Decimal("0.0"),
                validators=[StepValueValidator(Decimal("0.1"))],
                verbose_name="Quantité de liquide de direction ajoutée en litres",
            ),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="frein_liquide_quantite",
            field=models.DecimalField(
                max_digits=4,
                decimal_places=1,
                default=Decimal("0.0"),
                validators=[StepValueValidator(Decimal("0.1"))],
                verbose_name="Quantité de liquide de freins ajoutée en litres",
            ),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="lave_glace_quantite",
            field=models.DecimalField(
                max_digits=4,
                decimal_places=1,
                default=Decimal("0.0"),
                validators=[StepValueValidator(Decimal("0.1"))],
                verbose_name="Quantité de liquide de lave glace ajoutée en litres",
            ),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="pont_niveau_huile_quantite",
            field=models.DecimalField(
                max_digits=4,
                decimal_places=1,
                default=Decimal("0.0"),
                validators=[StepValueValidator(Decimal("0.1"))],
                verbose_name="Quantité d'huile ajoutée en litres",
            ),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="refroidissement_quantite",
            field=models.DecimalField(
                max_digits=4,
                decimal_places=1,
                default=Decimal("0.0"),
                validators=[StepValueValidator(Decimal("0.1"))],
                verbose_name="Quantité de liquide de refroidissement ajoutée en litres",
            ),
        ),
    ]