# Generated by Django 5.2.10 on 2026-05-29 13:27
from django.core.validators import StepValueValidator

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0013_alter_niveau_boite_niveau_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[StepValueValidator(0.1)],verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='direction_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[StepValueValidator(0.1)], verbose_name='Quantité de liquide de direction ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='lave_glace_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[StepValueValidator(0.1)], verbose_name='Quantité de liquide de lave glace ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='moteur_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4,validators=[StepValueValidator(0.1)],verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='pont_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='refroidissement_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[StepValueValidator(0.1)], verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
    ]
