# Generated by Django 5.2.10 on 2026-05-29 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0014_alter_niveau_boite_niveau_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='frein_liquide_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de freins ajoutée en litres'),
        ),
    ]
