# Generated by Django 5.2.10 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0015_alter_niveau_frein_liquide_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
