# Generated by Django 5.2.10 on 2026-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0018_alter_niveau_boite_niveau_huile_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='moteur_niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='MOBIL', max_length=30, verbose_name='Fabricant'),
        ),
    ]
