# Generated by Django 5.2.10 on 2026-07-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0020_niveau_boite_niveau_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niveau',
            old_name='lave_glace_fabricant',
            new_name='lave_glace_liquide_fabricant',
        ),
        migrations.RenameField(
            model_name='niveau',
            old_name='lave_glace_huile_prix',
            new_name='lave_glace_liquide_prix',
        ),
        migrations.RenameField(
            model_name='niveau',
            old_name='lave_glace_qualite',
            new_name='lave_glace_liquide_qualite',
        ),
        migrations.RenameField(
            model_name='niveau',
            old_name='lave_glace_quantite',
            new_name='lave_glace_liquide_quantite',
        ),
    ]
