# Generated by Django 5.2.10 on 2026-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0031_alter_niveau_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
