# Generated by Django 5.2.10 on 2026-08-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0032_niveau_kilometrage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile de boite"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='direction_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile moteur"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile de pont"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='refroidissement_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
