# Generated by Django 5.2.10 on 2026-09-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0034_alter_niveau_refroidissement_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
