# Generated by Django 5.2.10 on 2026-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveaux', '0041_alter_niveau_boite_niveau_huile_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name="Niveau d'huile de boite"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='direction_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name="Niveau d'huile moteur"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name="Niveau d'huile de pont"),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='refroidissement_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
