# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocieteCliente',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='client.client')),
                ('id_societe_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directeur', models.CharField(max_length=100, verbose_name='Directeur')),
                ('numero_tva', models.CharField(max_length=20, unique=True, verbose_name='Numéro de TVA')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('peppol_id', models.CharField(help_text='Identifiant Peppol du client, ex: 0208:BE0987654321', max_length=50)),
                ('code_pays', models.CharField(default='BE', max_length=2)),
                ('numero_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de TVA (%)')),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
            bases=('client.client',),
        ),
    ]
