# Generated by Django 5.2.9 on 2025-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societecliente',
            name='numero_entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='societecliente',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de TVA (%)'),
        ),
    ]
