# Generated by Django 5.2.9 on 2025-12-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_age_client_historique_client_location_and_more'),
        ('societe_cliente', '0002_societecliente_numero_entreprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societecliente',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='societecliente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='societecliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='societecliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='societecliente',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='societecliente',
            name='numero_telephone',
        ),
        migrations.AddField(
            model_name='societecliente',
            name='client_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='client.client'),
            preserve_default=False,
        ),
    ]
