# Generated by Django 5.2.10 on 2026-04-19 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseur', '0007_delete_achat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatMds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_facture', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence facture')),
                ('achat_montant_htva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HTVA')),
                ('achat_tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('date_facture', models.DateField(verbose_name='Date facture')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='fournisseur.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_facture'],
            },
        ),
    ]
