# Generated by Django 5.2.10 on 2026-04-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat_mds', '0001_initial'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatmds',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats_mds', to='societe.societe'),
        ),
    ]
