# Generated by Django 5.2.10 on 2026-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat_mds', '0002_achatmds_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatmds',
            name='libelle_facture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé'),
        ),
    ]
