# Generated by Django 5.2.10 on 2026-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat_mds', '0003_achatmds_libelle_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatmds',
            name='achat_tva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de TVA (%)'),
        ),
        migrations.AlterField(
            model_name='achatmds',
            name='date_facture',
            field=models.DateField(verbose_name='Date de la facture'),
        ),
        migrations.AlterField(
            model_name='achatmds',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
    ]
