# Generated by Django 5.2.10 on 2026-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat_mds', '0004_alter_achatmds_achat_tva_alter_achatmds_date_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatmds',
            name='transport_montant_htva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant HTVA du transport'),
        ),
    ]
