# Generated by Django 5.2.10 on 2026-03-28 14:33

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
        ('voiture_pneus', '0003_alter_voiturepneus_indice_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlePneus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometrage_pneus', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du contrôle des pneus')),
                ('pneu_bande_avd', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu avant droit')),
                ('pneu_bande_avg', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu avant gauche')),
                ('pneu_bande_ard', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu arrière droit')),
                ('pneu_bande_arg', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu arrière gauche')),
                ('pneu_epaisseur_avd', models.FloatField(default=0.0, verbose_name='Épaisseur du pneu avant droit (mm)')),
                ('pneu_epaisseur_avg', models.FloatField(default=0.0, verbose_name='Épaisseur du pneu avant gauche (mm)')),
                ('pneu_epaisseur_ard', models.FloatField(default=0.0, verbose_name='Épaisseur du pneu arrière droit (mm)')),
                ('pneu_epaisseur_arg', models.FloatField(default=0.0, verbose_name='Épaisseur du pneu arrière gauche (mm)')),
                ('pneu_sidewall_avd', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flancs du pneu avant droit')),
                ('pneu_sidewall_avg', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flancs du pneu avant gauche')),
                ('pneu_sidewall_ard', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flancs du pneu arrière droit')),
                ('pneu_sidewall_arg', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='flancs du pneu arrière gauche')),
                ('pneu_pression_bar_avd', models.FloatField(default=2.4, verbose_name='Pression du pneu avant droit en bar')),
                ('pneu_pression_bar_avg', models.FloatField(default=2.4, verbose_name='Pression du pneu avant gauche en bar')),
                ('pneu_pression_bar_ard', models.FloatField(default=2.4, verbose_name='Pression du pneu arrière droit en bar')),
                ('pneu_pression_bar_arg', models.FloatField(default=2.4, verbose_name='Pression du pneu arrière gauche en bar')),
                ('pneu_train_av', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='NON', max_length=25, verbose_name='Train avant à remplacer')),
                ('pneu_train_av_nombre', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Nombre de trains avant montés')),
                ('pneu_train_ar', models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='NON', max_length=25, verbose_name='Train arrière à remplacer')),
                ('pneu_train_ar_nombre', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Nombre de trains arrières montés')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_pneus', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_pneus_societe', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_pneus_techs', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_pneus', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_checkup')),
                ('voiture_pneus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_Pneus', to='voiture_pneus.voiturepneus', verbose_name='Pneus')),
            ],
            options={
                'verbose_name': 'Contrôle pneus',
                'verbose_name_plural': 'Contrôles pneus',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
