# Generated by Django 5.2.10 on 2026-04-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0003_remove_maindoeuvre_temps_maindoeuvre_temps_minutes'),
        ('pneus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepneus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneus', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
