# Generated by Django 5.2.10 on 2026-05-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0002_controlepneus_created_at_controlepneus_main_oeuvre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepneus',
            name='remplacement_effectue',
            field=models.BooleanField(default=False, verbose_name='Remplacement effectué'),
        ),
    ]
