# Generated by Django 5.2.10 on 2026-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0004_alter_controlepneus_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlepneus',
            name='kilometrage_pneus',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du contrôle des pneus'),
            preserve_default=False,
        ),
    ]
