# Generated by Django 5.2.10 on 2026-07-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0005_alter_controlepneus_kilometrage_pneus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlepneus',
            name='pneu_epaisseur_ard',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu arrière droit (mm)'),
        ),
        migrations.AlterField(
            model_name='controlepneus',
            name='pneu_epaisseur_arg',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu arrière gauche (mm)'),
        ),
        migrations.AlterField(
            model_name='controlepneus',
            name='pneu_epaisseur_avd',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu avant droit (mm)'),
        ),
        migrations.AlterField(
            model_name='controlepneus',
            name='pneu_epaisseur_avg',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu avant gauche (mm)'),
        ),
    ]
