# Generated by Django 5.2.10 on 2026-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0008_controlepneus_taux_horaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlepneus',
            name='pneu_train_ar_nombre',
        ),
        migrations.RemoveField(
            model_name='controlepneus',
            name='pneu_train_av_nombre',
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='pneu_train_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='pneu_train_ar_quantite',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='pneu_train_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='pneu_train_av_quantite',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Quantité'),
        ),
    ]
