# Generated by Django 5.2.10 on 2026-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0010_controlepneus_pneu_train_ar_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlepneus',
            name='pneu_train_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneus arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlepneus',
            name='pneu_train_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pneus avant à remplacer'),
        ),
    ]
