# Generated by Django 5.2.10 on 2026-08-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0012_alter_controlepneus_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepneus',
            name='valve_pneu',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Valves de pneu'),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='valve_pneu_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='valve_pneu_quantite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantité'),
        ),
    ]
