# Generated by Django 5.2.10 on 2026-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0013_controlepneus_valve_pneu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepneus',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
        migrations.AddField(
            model_name='controlepneus',
            name='valve_pneu_type',
            field=models.CharField(choices=[('caoutchouc', 'Valve caoutchouc'), ('metallique', 'Valve métallique'), ('tpms_caoutchouc', 'Valve TPMS caoutchouc'), ('tpms_metallique', 'Valve TPMS métallique'), ('haute_pression', 'Valve haute pression'), ('moto', 'Valve moto')], default='caoutchouc', max_length=25, verbose_name='type de valves de pneu'),
        ),
    ]
