# Generated by Django 5.2.10 on 2026-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0014_controlepneus_serrage_roues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepneus',
            name='masse_equilibrage',
            field=models.CharField(choices=[('clip_acier', 'Masse à clipser en acier'), ('clip_zinc', 'Masse à clipser en zinc'), ('clip_plomb', 'Masse à clipser en plomb'), ('adhesive_acier', 'Masse adhésive en acier'), ('adhesive_zinc', 'Masse adhésive en zinc'), ('adhesive_plomb', 'Masse adhésive en plomb'), ('moto', "Masse d'équilibrage moto"), ('camion', "Masse d'équilibrage poids lourd"), ('autre', 'Autre')], default='clip_zinc', max_length=25, verbose_name="Type de masses d'équilibrage"),
        ),
    ]
