# Generated by Django 5.2.10 on 2026-08-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pneus', '0018_alter_controlepneus_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepneus',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
