# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceTransmission',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_transmission', models.CharField(choices=[('cardan_av_g', 'Cardan avant gauche'), ('cardan_av_d', 'Cardan avant droit'), ('cardan_ar_g', 'Cardan arrière gauche'), ('cardan_ar_d', 'Cardan arrière droit'), ('noix_cardan', 'Noix de cardan'), ('tulipe_cardan', 'Tulipe de cardan'), ('joint_homocinetique_ext', 'Joint homocinétique extérieur'), ('joint_homocinetique_int', 'Joint homocinétique intérieur'), ('tripode', 'Tripode'), ('galet_tripode', 'Galet de tripode'), ('etoile_cardan', 'Étoile de cardan'), ('cage_billes', 'Cage à billes'), ('billes_cardan', 'Billes de cardan'), ('axe_cardan', 'Axe de cardan'), ('soufflet_cardan_int', 'Soufflet de cardan intérieur'), ('soufflet_cardan_ext', 'Soufflet de cardan extérieur'), ('collier_serrage', 'Collier de serrage'), ('joint_etancheite', 'Joint d’étanchéité'), ('circlip', 'Circlip'), ('graisse_cardan', 'Graisse de cardan'), ('arbre_transmission', 'Arbre de transmission'), ('palier_arbre_transmission', 'Palier d’arbre de transmission'), ('support_palier', 'Support de palier'), ('croisillon', 'Croisillon'), ('flector', 'Flector'), ('bride_transmission', 'Bride de transmission'), ('kit_soufflet_cardan', 'Kit soufflet de cardan'), ('kit_joint_cardan', 'Kit joint de cardan'), ('kit_cardan_complet', 'Kit cardan complet'), ('kit_arbre_transmission', 'Kit arbre de transmission')], max_length=70, verbose_name='Type de pièce de transmission')),
                ('voiture_modele', models.ManyToManyField(blank=True, related_name='pieces_transmission', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Pièce de transmission',
                'verbose_name_plural': 'Pièces de transmission',
            },
            bases=('piece.piece',),
        ),
    ]
