# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluide',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_fluide', models.CharField(choices=[('HUILE_MOTEUR', 'Huile moteur'), ('HUILE_BOITE', 'Huile de boîte'), ('HUILE_PONT', 'Huile de pont'), ('LDR', 'Liquide de refroidissement'), ('LAVE_GLACE', 'Lave-glace'), ('LIQ_FREIN', 'Liquide de frein'), ('HUILE_DIR', 'Huile de direction')], max_length=30, verbose_name='Type de fluide')),
                ('nom_fluide', models.CharField(max_length=100, verbose_name='Nom du fluide')),
                ('qualite_fluide', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualité du fluide')),
            ],
            options={
                'verbose_name': 'Fluide',
                'verbose_name_plural': 'Fluides',
            },
            bases=('piece.piece',),
        ),
        migrations.CreateModel(
            name='InventaireFluide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.FloatField(help_text='+ entrée / - sortie (litres)', verbose_name='Variation')),
                ('stock_apres', models.FloatField(default=0.0, verbose_name='Stock après')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('fluide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires_fluide', to='piece_fluides.fluide', verbose_name='Fluide')),
            ],
        ),
    ]
