# Generated by Django 5.2.10 on 2026-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece_fluides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluide',
            name='quantite_fluide',
            field=models.FloatField(default=0, verbose_name='Quantité ajoutée en litres'),
        ),
    ]
