# Generated by Django 5.2.10 on 2026-03-29 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, verbose_name='Immatriculation')),
                ('date_intervention', models.DateField(verbose_name="Date d'intervention")),
                ('date_derniere_intervention', models.DateField(blank=True, null=True, verbose_name='Date de la dernière intervention')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='Étiquette')),
                ('kilometres_total', models.PositiveIntegerField(default=0, verbose_name='Kilométrage total')),
                ('kilometres_derniere_intervention', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage à la dernière intervention')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage châssis')),
                ('kilometres_moteur', models.PositiveIntegerField(default=0, verbose_name='Kilométrage moteur')),
                ('kilometres_boite', models.PositiveIntegerField(default=0, verbose_name='Kilométrage boîte')),
                ('type_maintenance', models.CharField(blank=True, choices=[('boite', 'Boite'), ('entretien', 'Entretien'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('nettoyage_exterieur', 'Nettoyage extérieur'), ('nettoyage_interieur', 'Nettoyage intérieur'), ('niveaux', 'Niveaux'), ('autres', 'Autres interventions')], max_length=50, null=True, verbose_name='Type de maintenance')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autres_interventions', to='societe.societe')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autres_interventions', to='voiture_exemplaire.voitureexemplaire', verbose_name='Voiture exemplaire')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
        ),
    ]
