# Generated by Django 5.2.10 on 2026-03-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autres_interventions', '0001_initial'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintenance',
            new_name='AutresInterventions',
        ),
    ]
