# Generated by Django 5.2.10 on 2026-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autres_interventions', '0002_rename_maintenance_autresinterventions'),
    ]

    operations = [
        migrations.AddField(
            model_name='autresinterventions',
            name='kilometres_remplacement_moteur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
