# Generated by Django 5.2.10 on 2026-05-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autres_interventions', '0003_autresinterventions_kilometres_remplacement_moteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autresinterventions',
            name='kilometres_remplacement_moteur',
        ),
    ]
