# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronique',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_electronique', models.CharField(choices=[('debitmetre', 'Débitmètre'), ('sonde_temp_eau', 'Sonde de température eau'), ('sonde_temp_huile', 'Sonde de température d’huile'), ('capteur_cliquetis', 'Capteur de cliquetis'), ('sonde_lambda', 'Sonde lambda'), ('capteur_aac', "Capteur d'arbre à came"), ('capteur_vilebrequin', 'Capteur vilebrequin'), ('sonde_press_filtre_particule', 'Sonde de pression filtre à particules'), ('vanne_egr', 'Vanne EGR'), ('boitier_papillon', 'Boîtier papillon'), ('electrovanne_turbo', 'Électrovanne de turbo'), ('sonde_press_turbo', 'Sonde pression turbo'), ('capteur_abs', 'Capteur ABS'), ('accelerateur', 'Accélérateur'), ('contacteur_feux_stop', 'Contacteur feux stop'), ('calculateur_abs', 'Calculateur ABS'), ('calculateur_moteur', 'Calculateur moteur'), ('boitier_servitude_int', 'Boîtier servitude intérieur'), ('fusibles', 'Fusibles'), ('boitier_additionnel', 'Boîtier additionnel'), ('radar_recul', 'Radar de recul'), ('capteur_pression_pneus', 'Capteur pression pneus'), ('capteur_pression_adm', 'Capteur pression admission'), ('regulateur_pression_carb', 'Régulateur pression carburant'), ('capteur_niveau_huile', 'Capteur niveau huile'), ('capteur_niveau_liquide_freins', 'Capteur niveau liquide freins'), ('calculateur_bdv', 'Calculateur boîte de vitesses'), ('relais_prechauffage', 'Relais de préchauffage'), ('relais', 'Relais'), ('resistance_chauffage', 'Résistance de chauffage'), ('capteur_temp_adm', 'Capteur de température d’admission'), ('capteur_emb', 'Capteur d’embrayage')], max_length=50)),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='electroniques', to='voiture_moteur.moteurvoiture')),
            ],
            options={
                'verbose_name': 'Pièce électronique',
                'verbose_name_plural': 'Pièces électroniques',
            },
            bases=('piece.piece',),
        ),
    ]
