# Generated by Django 5.2.10 on 2026-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece_electronique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronique',
            name='type_piece_electronique',
            field=models.CharField(choices=[('debitmetre', 'Débitmètre'), ('sonde_temp_eau', 'Sonde de température eau'), ('sonde_temp_huile', 'Sonde de température d’huile'), ('capteur_cliquetis', 'Capteur de cliquetis'), ('sonde_lambda', 'Sonde lambda'), ('capteur_aac', "Capteur d'arbre à came"), ('capteur_vilebrequin', 'Capteur vilebrequin'), ('sonde_press_filtre_particule', 'Sonde de pression filtre à particules'), ('vanne_egr', 'Vanne EGR'), ('boitier_papillon', 'Boîtier papillon'), ('electrovanne_turbo', 'Électrovanne de turbo'), ('sonde_press_turbo', 'Sonde pression turbo'), ('capteur_abs', 'Capteur ABS'), ('accelerateur', 'Accélérateur'), ('contacteur_feux_stop', 'Contacteur feux stop'), ('calculateur_abs', 'Calculateur ABS'), ('calculateur_moteur', 'Calculateur moteur'), ('boitier_servitude_int', 'Boîtier servitude intérieur'), ('fusibles', 'Fusibles'), ('boitier_additionnel', 'Boîtier additionnel'), ('radar_recul', 'Radar de recul'), ('capteur_pression_pneus', 'Capteur pression pneus'), ('capteur_pression_adm', 'Capteur pression admission'), ('regulateur_pression_carb', 'Régulateur pression carburant'), ('capteur_niveau_huile', 'Capteur niveau huile'), ('capteur_niveau_liquide_freins', 'Capteur niveau liquide freins'), ('calculateur_bdv', 'Calculateur de boîte de vitesse'), ('relais_prechauffage', 'Relais de préchauffage'), ('relais', 'Relais'), ('resistance_chauffage', 'Résistance de chauffage'), ('capteur_temp_adm', 'Capteur de température d’admission'), ('capteur_emb', 'Capteur d’embrayage')], max_length=50),
        ),
    ]
