# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainArriere',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_train', models.CharField(choices=[('pont', 'Pont'), ('berceau', 'Berceau'), ('barre_torsion', 'Barre de torsion'), ('triangle_sup_g', 'Triangle supérieur gauche'), ('triangle_sup_d', 'Triangle supérieur droit'), ('triangle_inf_g', 'Triangle inférieur gauche'), ('triangle_inf_d', 'Triangle inférieur droit'), ('silent_bloc', 'Silent bloc'), ('kit_silent_bloc', 'Kit silent bloc'), ('roulement_roue', 'Roulement de roue'), ('moyeu', 'Moyeu'), ('porte_fusee', 'Porte fusée'), ('fusee', 'Fusée'), ('amortisseur_gd', 'Amortisseur G/D'), ('ressort', 'Ressort'), ('barre_stabilisatrice', 'Barre stabilisatrice'), ('biellette_barre_stab', 'Biellette de barre stabilisatrice'), ('train_ar_directeur_gd', 'Train AR directeur G/D'), ('cardan_g', 'Cardan G'), ('cardan_d', 'Cardan D'), ('arbre_transmission', 'Arbre de transmission')], max_length=50, verbose_name='Type de pièce train arrière')),
                ('voiture_modele', models.ManyToManyField(blank=True, related_name='train_arriere', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Pièce train arrière',
                'verbose_name_plural': 'Pièces train arrière',
            },
            bases=('piece.piece',),
        ),
    ]
