# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceFreins',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_frein', models.CharField(choices=[('machoire_frein_avg', 'Étrier de frein AVG'), ('machoire_frein_avd', 'Étrier de frein AVD'), ('machoire_frein_arg', 'Étrier de frein ARG'), ('machoire_frein_ard', 'Étrier de frein ARD'), ('support_machoire_av', 'Support étrier avant'), ('support_machoire_ar', 'Support étrier arrière'), ('kit_reparation_machoire', 'Kit réparation étrier'), ('plaquettes_av', 'Plaquettes AV'), ('plaquettes_ar', 'Plaquettes AR'), ('disques_av', 'Disques AV'), ('disques_ar', 'Disques AR'), ('epaisseur_av', 'Épaisseur AV'), ('epaisseur_ar', 'Épaisseur AR'), ('epaisseur_min_av', 'Épaisseur min AV'), ('epaisseur_min_ar', 'Épaisseur min AR'), ('porte_etrier', 'Porte étrier'), ('pompe_abs', 'Pompe ABS'), ('liquide_qualite', 'Liquide qualité'), ('servo_frein', 'Servo-frein'), ('maitre_cylindre', 'Maître-cylindre'), ('cylindre_recepteur', 'Cylindre récepteur AV/AR G/D'), ('petites_fournitures', 'Petites fournitures freins'), ('graisse', 'Graisse'), ('soufflet', 'Soufflet'), ('coulisseaux', 'Coulisseaux'), ('visserie', 'Visserie'), ('flexibles', 'Flexibles'), ('tuyau', 'Tuyau'), ('nippe', 'Nippe'), ('master_vac', 'Master vac'), ('ressort_av', 'Ressort avant'), ('ressort_ar', 'Ressort arrière'), ('temoin_usure_av', 'Témoin usure avant'), ('temoin_usure_ar', 'Témoin usure arrière'), ('cable_frein', 'Cable frein à main')], max_length=50, verbose_name='Type de pièce de freinage')),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='freinages', to='voiture_moteur.moteurvoiture', verbose_name='Moteurs compatibles')),
            ],
            options={
                'verbose_name': 'Pièce de freinage',
                'verbose_name_plural': 'Pièces de freinage',
            },
            bases=('piece.piece',),
        ),
    ]
