# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainAvant',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_train', models.CharField(choices=[('berceau', 'Berceau'), ('cardan_g', 'Cardan G'), ('cardan_d', 'Cardan D'), ('triangle_sup_g', 'Triangle supérieur gauche'), ('triangle_sup_d', 'Triangle supérieur droit'), ('triangle_inf_g', 'Triangle inférieur gauche'), ('triangle_inf_d', 'Triangle inférieur droit'), ('multi_bras_g', 'Multi-bras G'), ('multi_bras_d', 'Multi-bras D'), ('barres_torsion', 'Barres de torsion'), ('silent_bloc', 'Silent bloc'), ('kit_silent_bloc', 'Kit silent bloc'), ('roulement_roue', 'Roulement de roue'), ('moyeu', 'Moyeu'), ('porte_fusee', 'Porte fusée'), ('fusee', 'Fusée'), ('amortisseur_gd', 'Amortisseur G/D'), ('ressort', 'Ressort'), ('roulement_suspension', 'Roulement de suspension'), ('barre_stabilisatrice', 'Barre stabilisatrice'), ('biellette_barre_stab', 'Biellette de barre stabilisatrice')], max_length=50, verbose_name='Type de pièce train avant')),
                ('voiture_modele', models.ManyToManyField(blank=True, related_name='train_avant', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Pièce train avant',
                'verbose_name_plural': 'Pièces train avant',
            },
            bases=('piece.piece',),
        ),
    ]
