# Generated by Django 5.2.10 on 2026-05-01 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_maintenance_kilometres_dernier_entretien'),
        ('remplacement_moteur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='nombre_moteur',
            new_name='remplacement_nombre_moteur',
        ),
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='numero_moteur',
            new_name='remplacement_numero_moteur',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='societe',
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_moteur', to='maintenance.maintenance'),
        ),
    ]
