# Generated by Django 5.2.10 on 2026-05-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0002_rename_nombre_moteur_remplacementmoteur_remplacement_nombre_moteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='annee_production',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='est_apres_2010',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='mois_production',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='numero_vin',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='vin_simplifie',
        ),
    ]
