# Generated by Django 5.2.10 on 2026-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0009_remplacementmoteur_pays_remplacementmoteur_remarques'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='nombre_remplacements',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
