# Generated by Django 5.2.10 on 2026-05-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0010_remplacementmoteur_nombre_remplacements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='prix_moteur',
            new_name='prix_moteurs',
        ),
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='remplacement_nombre_moteur',
            new_name='remplacement_nombre_moteurs',
        ),
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='remplacement_numero_moteur',
            new_name='remplacement_numero_moteurs',
        ),
    ]
