# Generated by Django 5.2.10 on 2026-05-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0011_rename_prix_moteur_remplacementmoteur_prix_moteurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='type_utilisation',
        ),
    ]
