# Generated by Django 5.2.10 on 2026-05-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0012_remove_remplacementmoteur_proprietaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='nombre_remplacements',
            new_name='nombre_remplacements_moteurs',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='remplacement_nombre_moteurs',
        ),
    ]
