# Generated by Django 5.2.10 on 2026-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0013_rename_nombre_remplacements_remplacementmoteur_nombre_remplacements_moteurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='nombre_remplacements_moteurs',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de remplacements'),
        ),
    ]
