# Generated by Django 5.2.10 on 2026-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0014_alter_remplacementmoteur_nombre_remplacements_moteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='nombre_remplacements_moteurs',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de remplacements'),
        ),
    ]
