# Generated by Django 5.2.10 on 2026-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0015_alter_remplacementmoteur_nombre_remplacements_moteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometrage_checkup',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du remplacement'),
        ),
    ]
