# Generated by Django 5.2.10 on 2026-05-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0017_remove_remplacementmoteur_kilometrage_checkup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='kilometres_moteur',
            new_name='kilometrage_moteur',
        ),
    ]
