# Generated by Django 5.2.10 on 2026-05-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0018_rename_kilometres_moteur_remplacementmoteur_kilometrage_moteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='kilometrage_moteur',
            new_name='kilometres_moteur',
        ),
    ]
