# Generated by Django 5.2.10 on 2026-05-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0019_rename_kilometrage_moteur_remplacementmoteur_kilometres_moteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='client',
        ),
    ]
