# Generated by Django 5.2.10 on 2026-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0020_remove_remplacementmoteur_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='tva',
            field=models.DecimalField(choices=[('BE', 21), ('LU', 16), ('DE', 19)], decimal_places=2, default=21.0, max_digits=5, verbose_name='TVA'),
        ),
    ]
