# Generated by Django 5.2.10 on 2026-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0021_remplacementmoteur_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='nombre_remplacements_moteurs',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Nombre de remplacements'),
        ),
    ]
