# Generated by Django 5.2.10 on 2026-06-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0022_alter_remplacementmoteur_nombre_remplacements_moteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='kilometres_remplacement_moteur',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilomètres au remplacement moteur'),
            preserve_default=False,
        ),
    ]
