# Generated by Django 5.2.10 on 2026-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0023_alter_remplacementmoteur_kilometres_remplacement_moteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='kilometres_remplacement_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres au remplacement moteur'),
        ),
    ]
