# Generated by Django 5.2.10 on 2026-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0024_alter_remplacementmoteur_kilometres_remplacement_moteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
