# Generated by Django 5.2.10 on 2026-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0025_alter_remplacementmoteur_moteur_niveau_huile_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='nombre_moteurs_total',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Nombre de moteurs montés'),
        ),
    ]
