# Generated by Django 5.2.10 on 2026-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0027_remplacementmoteur_taux_horaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='prix_moteurs',
            new_name='moteurs_niveau_huile_prix',
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='moteurs_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix moteur'),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='refroidissement_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix moteur'),
        ),
    ]
