# Generated by Django 5.2.10 on 2026-07-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0028_rename_prix_moteurs_remplacementmoteur_moteurs_niveau_huile_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='moteurs_niveau_huile_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='moteurs_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat HTVA"),
        ),
    ]
