# Generated by Django 5.2.10 on 2026-07-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0030_alter_remplacementmoteur_moteurs_niveau_huile_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='nombre_moteurs_total',
            new_name='nombre_moteurs_montes',
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='moteur_quantite',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Quantité'),
        ),
    ]
