# Generated by Django 5.2.10 on 2026-07-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0031_rename_nombre_moteurs_total_remplacementmoteur_nombre_moteurs_montes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='moteur_niveau_huile_etat',
            new_name='niveau_huile_etat',
        ),
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='moteurs_niveau_huile_prix',
            new_name='niveau_huile_prix',
        ),
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='moteur_niveau_huile_qualite',
            new_name='niveau_huile_qualite',
        ),
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='moteur_niveau_huile_quantite',
            new_name='niveau_huile_quantite',
        ),
    ]
