# Generated by Django 5.2.10 on 2026-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0034_alter_remplacementmoteur_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
