# Generated by Django 5.2.10 on 2026-08-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0036_alter_remplacementmoteur_niveau_huile_fabricant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='remplacement_effectue',
            field=models.BooleanField(default=False, verbose_name='Remplacement effectué et remise à zéro'),
        ),
    ]
