# Generated by Django 5.2.10 on 2026-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0038_alter_remplacementmoteur_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='pays',
            field=models.CharField(choices=[('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('CZ', 'Tchéquie'), ('DE', 'Allemagne'), ('DK', 'Danemark'), ('EE', 'Estonie'), ('ES', 'Espagne'), ('FI', 'Finlande'), ('FR', 'France'), ('GR', 'Grèce'), ('HR', 'Croatie'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('IT', 'Italie'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('LV', 'Lettonie'), ('MT', 'Malte'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SE', 'Suède'), ('SI', 'Slovénie'), ('SK', 'Slovaquie')], max_length=5),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='tva',
            field=models.DecimalField(choices=[('AT', 20), ('BE', 21), ('BG', 20), ('CY', 19), ('CZ', 21), ('DE', 19), ('DK', 25), ('EE', 24), ('ES', 21), ('FI', 25.5), ('FR', 20), ('GR', 24), ('HR', 25), ('HU', 27), ('IE', 23), ('IT', 22), ('LT', 21), ('LU', 17), ('LV', 21), ('MT', 18), ('NL', 21), ('PL', 23), ('PT', 23), ('RO', 21), ('SE', 25), ('SI', 22), ('SK', 23)], decimal_places=2, default=21.0, max_digits=5, verbose_name='TVA'),
        ),
    ]
