# Generated by Django 5.2.10 on 2026-08-21 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0041_alter_remplacementmoteur_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_quantite',
            field=models.FloatField(default=0, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
    ]
