# Generated by Django 5.2.10 on 2026-08-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0042_alter_remplacementmoteur_refroidissement_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='variation_kilometres',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculé automatiquement : total - dernier entretien', verbose_name='Variation de kilomètres depuis le dernier entretien'),
        ),
    ]
