# Generated by Django 5.2.10 on 2026-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0044_remove_remplacementmoteur_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
