# Generated by Django 5.2.10 on 2026-09-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0048_alter_remplacementmoteur_refroidissement_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometres_boite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometres_boite_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback boite'),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometres_moteur_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback moteur'),
        ),
    ]
