# Generated by Django 5.2.10 on 2026-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0049_remplacementmoteur_kilometres_boite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometres_remplacement',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres au moment du remplacement'),
        ),
    ]
