# Generated by Django 5.2.10 on 2026-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0050_remplacementmoteur_kilometres_remplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='variation_kilometres',
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
