# Generated by Django 5.2.10 on 2026-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0052_alter_remplacementmoteur_kilometres_moteur_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometres_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometres_embrayage_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback embrayage'),
        ),
    ]
