# Generated by Django 5.2.10 on 2026-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0054_alter_remplacementmoteur_niveau_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='moteur_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('ALFA_ROMEO', 'Alfa Romeo'), ('ALPINE', 'Alpine'), ('ASTON_MARTIN', 'Aston Martin'), ('AUDI', 'Audi'), ('BENTLEY', 'Bentley'), ('BMW', 'BMW'), ('BUGATTI', 'Bugatti'), ('CITROEN', 'Citroën'), ('DACIA', 'Dacia'), ('FERRARI', 'Ferrari'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('JAGUAR', 'Jaguar'), ('KIA', 'Kia'), ('LAMBORGHINI', 'Lamborghini'), ('LAND_ROVER', 'Land Rover'), ('LEXUS', 'Lexus'), ('LOTUS', 'Lotus'), ('MASERATI', 'Maserati'), ('MAZDA', 'Mazda'), ('MCLAREN', 'McLaren'), ('MERCEDES', 'Mercedes-Benz'), ('MINI', 'Mini'), ('MITSUBISHI', 'Mitsubishi'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('PEUGEOT', 'Peugeot'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('ROLLS_ROYCE', 'Rolls-Royce'), ('SEAT', 'Seat'), ('SKODA', 'Škoda'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('TOYOTA', 'Toyota'), ('VOLKSWAGEN', 'Volkswagen'), ('VOLVO', 'Volvo'), ('AMG', 'AMG'), ('BMW_M', 'BMW M'), ('COSWORTH', 'Cosworth'), ('COTAL', 'Cotal'), ('GORDINI', 'Gordini'), ('HART', 'Hart'), ('ILMOR', 'Ilmor'), ('JUDD', 'Judd'), ('MECACHROME', 'Mecachrome'), ('MUGEN', 'Mugen'), ('NISMO', 'Nismo'), ('ORECA', 'Oreca'), ('AER', 'AER'), ('ALPINA', 'Alpina'), ('ABARTH', 'Abarth'), ('HPD', 'HPD (Honda Performance Development)'), ('TRD', 'TRD (Toyota Racing Development)'), ('YAMAHA', 'Yamaha'), ('ROTAX', 'Rotax'), ('CUMMINS', 'Cummins'), ('PERKINS', 'Perkins'), ('DEUTZ', 'Deutz'), ('VM_MOTORI', 'VM Motori'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='niveau_huile_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='niveau_huile_qualite',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='CHOISIR', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('ABRO', 'ABRO'), ('AISIN', 'AISIN'), ('ARECA', 'Areca'), ('BARDAHL', 'Bardahl'), ('BASF_GLYSANTIN', 'BASF Glysantin'), ('BEL_RAY', 'Bel-Ray'), ('BIZOL', 'BIZOL'), ('BMW', 'BMW'), ('BOLK', 'BOLK'), ('BOSCH', 'Bosch'), ('CASTROL', 'Castrol'), ('CHAMPION', 'Champion'), ('COMMA', 'Comma'), ('ELF', 'ELF'), ('EUROL', 'Eurol'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('FUCHS', 'Fuchs'), ('GATES', 'Gates'), ('GENERAL_MOTORS', 'General Motors'), ('HEPU', 'HEPU'), ('HOLTS', 'Holts'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('IGOL', 'Igol'), ('IPONE', 'IPONE'), ('K2', 'K2'), ('KIA', 'Kia'), ('LIQUI_MOLY', 'Liqui Moly'), ('MANNOL', 'Mannol'), ('MAZDA', 'Mazda'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('MEYLE', 'Meyle'), ('MILLERS_OILS', 'Millers Oils'), ('MITSUBISHI', 'Mitsubishi'), ('MOBIL', 'Mobil'), ('MOPAR', 'Mopar'), ('MOTIP', 'Motip'), ('MOTOREX', 'Motorex'), ('MOTUL', 'Motul'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('ORLEN', 'Orlen'), ('PEMCO', 'Pemco'), ('PEUGEOT_CITROEN', 'Peugeot Citroën'), ('PETRONAS', 'Petronas'), ('PORSCHE', 'Porsche'), ('PRESTONE', 'Prestone'), ('PUTOLINE', 'Putoline'), ('RAVENOL', 'Ravenol'), ('REPSOL', 'Repsol'), ('RENAULT', 'Renault'), ('ROWE', 'ROWE'), ('SHELL', 'Shell'), ('SONAX', 'Sonax'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('SWAG', 'SWAG'), ('TEXACO', 'Texaco'), ('TOTALENERGIES', 'TotalEnergies'), ('TOYOTA', 'Toyota'), ('TRIPLE_QX', 'Triple QX'), ('VALEO', 'Valeo'), ('VALVOLINE', 'Valvoline'), ('VAG', 'VAG'), ('VOLVO', 'Volvo'), ('WOLF', 'Wolf'), ('XENUM', 'Xenum'), ('YACCO', 'Yacco'), ('YAMAHA', 'Yamaha'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_qualite',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('G11', 'G 11 VAG'), ('G12', 'G 12 VAG'), ('G12_PLUS', 'G 12+ VAG'), ('G12_PLUS_PLUS', 'G 12++ VAG'), ('G13', 'G 13'), ('G48', 'G 48 BMW'), ('MB_325_0', 'MB 325.0 Mercedes'), ('MB_325_3', 'MB 325.3 Mercedes'), ('MB_325_5', 'MB 325.5 Mercedes'), ('TYPE_D', 'Type D Renault'), ('PSA_B71_5110', 'B71 5110 PSA'), ('WSS_M97B44_D', 'WSS-M97B44-D Ford'), ('WSS_M97B51_A1', 'WSS-M97B51-A1 Ford'), ('DEX_COOL', 'Dex-Cool GM'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Qualité de liquide de refroidissement'),
        ),
    ]
