# Generated by Django 5.2.10 on 2026-09-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0055_remplacementmoteur_moteur_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='moteur_fabricant',
            new_name='moteurs_fabricant',
        ),
    ]
