# Generated by Django 5.2.10 on 2026-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0056_rename_moteur_fabricant_remplacementmoteur_moteurs_fabricant'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
