# Generated by Django 5.2.10 on 2026-10-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0058_alter_remplacementmoteur_moteurs_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='moteurs_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name="Prix d'achat du moteur HTVA"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='niveau_huile_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name="Prix d'achat de l'huile HTVA"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name="Prix d'achat du liquide de refroidissement HTVA"),
        ),
    ]
