# Generated by Django 5.2.10 on 2026-10-06 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0060_alter_remplacementmoteur_niveau_huile_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementmoteur',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='frein_liquide_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='frein_liquide_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='frein_liquide_qualite',
            field=models.CharField(choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=25, verbose_name='Qualité de liquide de freins'),
        ),
        migrations.AddField(
            model_name='remplacementmoteur',
            name='frein_liquide_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='moteurs_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='niveau_huile_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name="Prix d'achat HTVA"),
        ),
    ]
