# Generated by Django 5.2.10 on 2026-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0061_remplacementmoteur_frein_liquide_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='niveau_huile_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='refroidissement_etat',
            field=models.CharField(choices=[('BON', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
