# Generated by Django 5.2.10 on 2026-04-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_ar', '0002_voiturefreinsar_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturefreinsar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='voiturefreinsar',
            name='numero_oem_disques_av',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro OEM disque AR (mm)'),
        ),
        migrations.AddField(
            model_name='voiturefreinsar',
            name='numero_oem_plaquettes_ar',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro OEM plaquette AR (mm)'),
        ),
        migrations.AddField(
            model_name='voiturefreinsar',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='voiturefreinsar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
