# Generated by Django 5.2.10 on 2026-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_ar', '0003_voiturefreinsar_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiturefreinsar',
            name='numero_oem_disques_av',
        ),
        migrations.AddField(
            model_name='voiturefreinsar',
            name='numero_oem_disques_ar',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro OEM disque AR'),
        ),
    ]
