# Generated by Django 5.2.10 on 2026-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_ar', '0004_remove_voiturefreinsar_numero_oem_disques_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiturefreinsar',
            name='numero_oem_disques_ar',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='N° OEM disque AR'),
        ),
        migrations.AlterField(
            model_name='voiturefreinsar',
            name='numero_oem_plaquettes_ar',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='N° OEM plaquette AR (mm)'),
        ),
    ]
