# Generated by Django 5.2.10 on 2026-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_ar', '0006_alter_voiturefreinsar_taille_disque_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiturefreinsar',
            name='numero_oem_plaquettes_ar',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='N° OEM plaquette AR'),
        ),
    ]
