# Generated by Django 5.2.10 on 2026-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_ar', '0007_alter_voiturefreinsar_numero_oem_plaquettes_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturefreinsar',
            name='frein_ar_matiere',
            field=models.CharField(choices=[('ACIER', 'Acier'), ('CARBONE', 'Carbone'), ('CERAMIQUE', 'Céramique'), ('COMPOSITE', 'Composite')], default='ACIER', max_length=25, verbose_name='Matière des disques arrière'),
        ),
        migrations.AddField(
            model_name='voiturefreinsar',
            name='plaquette_ar_matiere',
            field=models.CharField(choices=[('ORGANIC', 'Organique (NAO)'), ('LOW_METALLIC', 'Semi-métallique'), ('METALLIC', 'Métallique'), ('CERAMIC', 'Céramique haute performance')], default='ORGANIC', max_length=25, verbose_name='Matière des plaquettes avant'),
        ),
        migrations.AddField(
            model_name='voiturefreinsar',
            name='type_disques_ar',
            field=models.CharField(choices=[('MONOBLOC_PLEIN', 'Plein (monobloc)'), ('VENTILE', 'Ventilé'), ('RAINURE', 'Rainuré'), ('PERCE', 'Percé'), ('RAINURE_PERCE', 'Rainuré et percé')], default='MONOBLOC_PLEIN', max_length=25, verbose_name='Type disque arrière'),
        ),
    ]
