# Generated by Django 5.2.10 on 2026-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_ar', '0008_voiturefreinsar_frein_ar_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiturefreinsar',
            name='plaquette_ar_matiere',
            field=models.CharField(choices=[('ORGANIC', 'Organique (NAO)'), ('LOW_METALLIC', 'Semi-métallique'), ('METALLIC', 'Métallique'), ('CERAMIC', 'Céramique haute performance'), ('CHOISIR', 'Choisir')], default='ORGANIC', max_length=25, verbose_name='Matière des plaquettes avant'),
        ),
    ]
