# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_pneus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiturePneusHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kilometres_effectues', models.PositiveIntegerField()),
                ('date_remplacement', models.DateField(auto_now_add=True)),
                ('numero_remplacement', models.PositiveSmallIntegerField()),
                ('voiture_pneus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='voiture_pneus.voiturepneus')),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='historique_pneus', to='voiture_exemplaire.voitureexemplaire')),
            ],
        ),
    ]
