# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_particulier', '0001_initial'),
        ('voiture_marque', '0001_initial'),
        ('voiture_modele', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureExemplaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('pays', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Numéro VIN')),
                ('type_utilisation', models.CharField(choices=[('societe', 'Société'), ('client', 'Client'), ('prive', 'Privé'), ('location', 'Location')], default='client', max_length=10)),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometres_total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometres_derniere_intervention', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('variation_kilometres', models.PositiveIntegerField(default=0, editable=False, help_text='Calculé automatiquement : total - dernière intervention')),
                ('date_derniere_intervention', models.DateField(blank=True, null=True)),
                ('annee_production', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)])),
                ('mois_production', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('numero_moteur', models.CharField(blank=True, max_length=50, null=True)),
                ('date_mise_en_circulation', models.DateField(blank=True, null=True)),
                ('kilometres_moteur', models.PositiveIntegerField(default=0)),
                ('nombre_moteurs', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('kilometres_boite_vitesse', models.PositiveIntegerField(default=0)),
                ('nombre_boites_vitesse', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('kilometres_embrayage', models.PositiveIntegerField(default=0)),
                ('nombre_embrayages', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('code_couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxe_mise_en_circulation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxe_roulage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_proprietaires', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('part_proprietaires_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='client_particulier.clientparticulier')),
                ('last_maintained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretien_voitures', to=settings.AUTH_USER_MODEL)),
                ('voiture_marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voitures', to='voiture_marque.voituremarque')),
                ('voiture_modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voitures', to='voiture_modele.voituremodele')),
            ],
        ),
    ]
