# Generated by Django 5.2.10 on 2026-02-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='societe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='societe.societe'),
            preserve_default=False,
        ),
    ]
