# Generated by Django 5.2.9 on 2025-12-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='voiture_modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voitures', to='voiture_modele.voituremodele'),
        ),
    ]
