# Generated by Django 6.0 on 2026-01-09 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0002_alter_voitureexemplaire_nombre_proprietaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='nombre_proprietaires',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
