# Generated by Django 5.2.10 on 2026-02-13 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0002_voitureexemplaire_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='vin_simplifie',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='VIN simplifié'),
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='numero_vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro VIN doit contenir exactement 17 caractères alphanumériques (lettres A-H, J-N, P, R-Z et chiffres).', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='Numéro VIN'),
        ),
    ]
