# Generated by Django 5.2.10 on 2026-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0003_voitureexemplaire_vin_simplifie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='annee_production',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Année de production'),
        ),
    ]
