# Generated by Django 5.2.10 on 2026-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0004_alter_voitureexemplaire_annee_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='est_avant_2010',
            field=models.BooleanField(default=False),
        ),
    ]
