# Generated by Django 5.2.10 on 2026-03-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0005_voitureexemplaire_est_avant_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='type_utilisation',
            field=models.CharField(choices=[('societe', 'Société'), ('client', 'Client'), ('prive', 'Privé'), ('location', 'Location'), ('interne', 'Interne')], default='client', max_length=10),
        ),
    ]
