# Generated by Django 5.2.10 on 2026-03-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0006_alter_voitureexemplaire_type_utilisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='est_avant_2010',
            field=models.BooleanField(default=True),
        ),
    ]
