# Generated by Django 5.2.10 on 2026-03-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0007_alter_voitureexemplaire_est_avant_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voitureexemplaire',
            old_name='est_avant_2010',
            new_name='est_apres_2010',
        ),
    ]
