# Generated by Django 5.2.10 on 2026-03-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0008_rename_est_avant_2010_voitureexemplaire_est_apres_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='pays',
            field=models.CharField(blank=True, choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=20, null=True),
        ),
    ]
