# Generated by Django 5.2.10 on 2026-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0009_alter_voitureexemplaire_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
    ]
