# Generated by Django 5.2.10 on 2026-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='pays',
            field=models.CharField(blank=True, choices=[('Belgique', 'Belgique'), ('Luxembourg', 'Luxembourg'), ('Allemagne', 'Allemagne')], max_length=20, null=True),
        ),
    ]
