# Generated by Django 5.2.10 on 2026-04-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0011_alter_voitureexemplaire_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
