# Generated by Django 5.2.10 on 2026-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0013_rename_kilometres_derniere_intervention_voitureexemplaire_kilometres_derniere_entretien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voitureexemplaire',
            old_name='kilometres_derniere_entretien',
            new_name='kilometres_dernier_entretien',
        ),
        migrations.RemoveField(
            model_name='voitureexemplaire',
            name='nombre_boites_vitesse',
        ),
        migrations.RemoveField(
            model_name='voitureexemplaire',
            name='nombre_embrayages',
        ),
        migrations.RemoveField(
            model_name='voitureexemplaire',
            name='nombre_moteurs',
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='kilometres_boite_vitesse',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='kilometres_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='kilometres_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
