# Generated by Django 5.2.10 on 2026-04-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0014_rename_kilometres_derniere_entretien_voitureexemplaire_kilometres_dernier_entretien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voitureexemplaire',
            old_name='kilometres_boite_vitesse',
            new_name='kilometres_boite',
        ),
    ]
