# Generated by Django 5.2.10 on 2026-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0016_alter_voitureexemplaire_variation_kilometres'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='kilometres_remplacement_boite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='voitureexemplaire',
            name='kilometres_remplacement_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='voitureexemplaire',
            name='kilometres_remplacement_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
