# Generated by Django 5.2.10 on 2026-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='nombre_remplacements_moteurs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
