# Generated by Django 5.2.10 on 2026-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0018_voitureexemplaire_nombre_remplacements_moteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='nombre_remplacements_boites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
