# Generated by Django 5.2.10 on 2026-05-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_boite', '0005_remove_voitureboite_numero_boite_1_10_and_more'),
        ('voiture_exemplaire', '0019_voitureexemplaire_nombre_remplacements_boites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='voiture_boite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voitures', to='voiture_boite.voitureboite'),
        ),
    ]
