# Generated by Django 5.2.10 on 2026-05-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0020_alter_voitureexemplaire_voiture_boite'),
        ('voiture_moteur', '0005_remove_moteurvoiture_kilometres_moteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='voiture_moteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voitures', to='voiture_moteur.moteurvoiture'),
        ),
    ]
