# Generated by Django 5.2.10 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0021_alter_voitureexemplaire_voiture_moteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres châssis'),
        ),
    ]
