# Generated by Django 5.2.10 on 2026-07-04 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0022_alter_voitureexemplaire_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='immatriculation',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='numero_vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro VIN doit contenir exactement 17 caractères alphanumériques (lettres A-H, J-N, P, R-Z et chiffres).', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='Numéro VIN'),
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='vin_simplifie',
            field=models.CharField(editable=False, max_length=10, verbose_name='VIN simplifié'),
        ),
    ]
