# Generated by Django 5.2.10 on 2026-07-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0023_alter_voitureexemplaire_immatriculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='kilometres_rodage',
            field=models.PositiveIntegerField(choices=[(1000, '1000 km'), (2000, '2000 km'), (3000, '3000 km'), (4000, '4000 km'), (5000, '5000 km')], default=1000, verbose_name='Kilométrage de rodage'),
        ),
    ]
