# Generated by Django 5.2.10 on 2026-08-15 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0024_voitureexemplaire_kilometres_rodage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='est_apres_2010',
            field=models.BooleanField(default=True, editable=False, verbose_name='Véhicule de 2010 ou après'),
        ),
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='mois_production',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois de production'),
        ),
    ]
