# Generated by Django 5.2.10 on 2026-09-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0025_alter_voitureexemplaire_est_apres_2010_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
