# Generated by Django 5.2.10 on 2026-09-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0027_voitureexemplaire_kilometres_boite_rollback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voitureexemplaire',
            old_name='kilometres_rollback_moteur',
            new_name='kilometres_moteur_rollback',
        ),
    ]
