# Generated by Django 5.2.10 on 2026-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0028_rename_kilometres_rollback_moteur_voitureexemplaire_kilometres_moteur_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='kilometres_embrayage_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback embrayage'),
        ),
    ]
