# Generated by Django 5.2.10 on 2026-09-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0029_voitureexemplaire_kilometres_embrayage_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='kilometres_entretien_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback entretien'),
        ),
    ]
