# Generated by Django 5.2.10 on 2026-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0030_voitureexemplaire_kilometres_entretien_rollback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voitureexemplaire',
            name='pays',
            field=models.CharField(blank=True, choices=[('Belgique', 'Belgique'), ('Luxembourg', 'Luxembourg'), ('Pays-Bas', 'Pays-Bas'), ('Allemagne', 'Allemagne'), ('France', 'France'), ('Autriche', 'Autriche'), ('Irlande', 'Irlande'), ('Italie', 'Italie'), ('Espagne', 'Espagne'), ('Portugal', 'Portugal'), ('Grèce', 'Grèce'), ('Chypre', 'Chypre'), ('Malte', 'Malte'), ('Danemark', 'Danemark'), ('Suède', 'Suède'), ('Finlande', 'Finlande'), ('Estonie', 'Estonie'), ('Lettonie', 'Lettonie'), ('Lituanie', 'Lituanie'), ('Pologne', 'Pologne'), ('Tchéquie', 'Tchéquie'), ('Slovaquie', 'Slovaquie'), ('Hongrie', 'Hongrie'), ('Slovénie', 'Slovénie'), ('Croatie', 'Croatie'), ('Roumanie', 'Roumanie'), ('Bulgarie', 'Bulgarie'), ('Royaume-Uni', 'Royaume-Uni'), ('Norvège', 'Norvège'), ('Suisse', 'Suisse')], max_length=20, null=True),
        ),
    ]
