# Generated by Django 5.2.10 on 2026-10-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0031_alter_voitureexemplaire_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureexemplaire',
            name='cote_conduite',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('GAUCHE', 'Conduite à gauche'), ('CONDUITE', 'Conduite à droite')], default='GAUCHE', max_length=25, null=True, verbose_name='Coté conducteur'),
        ),
    ]
