# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJante',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('largeur', models.DecimalField(decimal_places=1, help_text='Largeur en pouces, ex: 7, 7.5, 8', max_digits=4)),
                ('taille', models.PositiveIntegerField(help_text='Diamètre en pouces')),
                ('entraxe', models.CharField(help_text='Ex: 5x100', max_length=20)),
                ('alesage', models.PositiveIntegerField(help_text='Diamètre central en mm')),
                ('deport_et', models.IntegerField(help_text='Déport ET en mm')),
            ],
            options={
                'verbose_name': 'Jante',
                'verbose_name_plural': 'Jantes',
            },
            bases=('piece.piece',),
        ),
    ]
