# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_distribution', models.CharField(choices=[('courroie_distribution', 'Courroie de distribution'), ('chaine_distribution', 'Chaîne de distribution'), ('galet_tendeur', 'Galet tendeur'), ('galet_libre', 'Galet libre'), ('pompe_eau', 'Pompe à eau'), ('guide_chaine', 'Guide de chaîne'), ('joint_culot', 'Joint de culot'), ('tendeur_hydraulique', 'Tendeur hydraulique'), ('cache_distribution', 'Cache distribution')], max_length=50, verbose_name='Type de pièce de distribution')),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='distributions', to='voiture_moteur.moteurvoiture', verbose_name='Moteurs compatibles')),
            ],
            options={
                'verbose_name': 'Pièce de distribution',
                'verbose_name_plural': 'Pièces de distribution',
            },
            bases=('piece.piece',),
        ),
    ]
