# Generated by Django 5.2.10 on 2026-08-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0019_alter_maintenance_type_maintenance'),
        ('voiture_exemplaire', '0025_alter_voitureexemplaire_est_apres_2010_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allumage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('kilometres_chassis', models.PositiveIntegerField(default=0, verbose_name='Kilomètres châssis')),
                ('kilometrage_allumage', models.PositiveIntegerField(verbose_name="Kilométrage au moment du controle de l'allumage")),
                ('date_controle', models.DateField(auto_now_add=True, verbose_name='Date du contrôle')),
                ('bougies_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=20, verbose_name='État des bougies')),
                ('bougies_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant des bougies')),
                ('bougies_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence des bougies')),
                ('bougies_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité de bougies')),
                ('bougies_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire des bougies HTVA')),
                ('bobines_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=20, verbose_name="État des bobines d'allumage")),
                ('bobines_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name="Fabricant des bobines d'allumage")),
                ('bobines_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name="Référence des bobines d'allumage")),
                ('bobines_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de bobines d'allumage")),
                ('bobines_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire des bobines HTVA')),
                ('faisceau_allumage_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=20, verbose_name="État du faisceau d'allumage")),
                ('faisceau_allumage_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name="Fabricant du faisceau d'allumage")),
                ('faisceau_allumage_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de faisceaux d'allumage")),
                ('faisceau_allumage_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix du faisceau d'allumage HTVA")),
                ('tete_allumeur_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=20, verbose_name="État de la tête d'allumeur")),
                ('tete_allumeur_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name="Fabricant de la tête d'allumeur")),
                ('tete_allumeur_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de têtes d'allumeur")),
                ('tete_allumeur_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix de la tête d'allumeur HTVA")),
                ('rotor_allumeur_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=20, verbose_name="État du rotor d'allumeur")),
                ('rotor_allumeur_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name="Fabricant du rotor d'allumeur")),
                ('rotor_allumeur_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de rotors d'allumeur")),
                ('rotor_allumeur_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix du rotor d'allumeur HTVA")),
                ('module_allumage_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=20, verbose_name="État du module d'allumage")),
                ('module_allumage_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name="Fabricant du module d'allumage")),
                ('module_allumage_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de modules d'allumage")),
                ('module_allumage_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix du module d'allumage HTVA")),
                ('capteur_vilebrequin_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=20, verbose_name='État du capteur de vilebrequin')),
                ('capteur_vilebrequin_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant du capteur de vilebrequin')),
                ('capteur_vilebrequin_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité de capteurs de vilebrequin')),
                ('capteur_vilebrequin_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix du capteur de vilebrequin HTVA')),
                ('capteur_arbre_cames_etat', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=20, verbose_name="État du capteur d'arbre à cames")),
                ('capteur_arbre_cames_fabricant', models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name="Fabricant du capteur d'arbre à cames")),
                ('capteur_arbre_cames_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de capteurs d'arbre à cames")),
                ('capteur_arbre_cames_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix du capteur d'arbre à cames HTVA")),
                ('pays', models.CharField(choices=[('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('CZ', 'Tchéquie'), ('DE', 'Allemagne'), ('DK', 'Danemark'), ('EE', 'Estonie'), ('ES', 'Espagne'), ('FI', 'Finlande'), ('FR', 'France'), ('GR', 'Grèce'), ('HR', 'Croatie'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('IT', 'Italie'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('LV', 'Lettonie'), ('MT', 'Malte'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SE', 'Suède'), ('SI', 'Slovénie'), ('SK', 'Slovaquie')], default='BE', max_length=5, verbose_name='Pays')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allumage', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allumages', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
        ),
    ]
