# Generated by Django 5.2.10 on 2026-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allumage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allumage',
            old_name='date_controle',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='bobines_prix_achat',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='bougies_prix_achat',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='capteur_arbre_cames_prix_achat',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='capteur_vilebrequin_prix_achat',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='faisceau_allumage_prix_achat',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='module_allumage_prix_achat',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='rotor_allumeur_prix_achat',
        ),
        migrations.RemoveField(
            model_name='allumage',
            name='tete_allumeur_prix_achat',
        ),
        migrations.AddField(
            model_name='allumage',
            name='bobines_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='allumage',
            name='bougies_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='allumage',
            name='capteur_arbre_cames_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='allumage',
            name='capteur_vilebrequin_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='allumage',
            name='faisceau_allumage_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='allumage',
            name='module_allumage_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='allumage',
            name='rotor_allumeur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='allumage',
            name='tete_allumeur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='bobines_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='bobines_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='bobines_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='bougies_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='bougies_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='bougies_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='capteur_arbre_cames_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='capteur_arbre_cames_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='capteur_vilebrequin_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='capteur_vilebrequin_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='faisceau_allumage_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='faisceau_allumage_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='module_allumage_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='module_allumage_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='rotor_allumeur_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='rotor_allumeur_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='tete_allumeur_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('OEM', 'Origine constructeur (OEM)'), ('BOSCH', 'Bosch'), ('NGK', 'NGK'), ('BERU', 'Beru'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('BREMBO', 'Brembo'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CHAMPION', 'Champion'), ('BREMI', 'Bremi'), ('HITACHI', 'Hitachi'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('FACET', 'Facet'), ('ERA', 'ERA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='allumage',
            name='tete_allumeur_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
