# Generated by Django 5.2.10 on 2026-09-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allumage', '0007_allumage_serrage_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='allumage',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
