# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adresse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du fournisseur')),
                ('numero_tva', models.CharField(max_length=20, unique=True, verbose_name='Numéro de TVA')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('peppol_id', models.CharField(help_text='Identifiant Peppol, ex : 0208:BE0123456789', max_length=50, verbose_name='Identifiant Peppol')),
                ('country_code', models.CharField(default='BE', help_text='ISO 3166-1 alpha-2', max_length=2, verbose_name='Code pays')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adresse.adresse', verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'indexes': [models.Index(fields=['numero_tva'], name='fournisseur_numero__17e42b_idx'), models.Index(fields=['peppol_id'], name='fournisseur_peppol__cd46e4_idx')],
            },
        ),
    ]
