# Generated by Django 5.2.10 on 2026-04-12 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0005_alter_adresse_societe'),
        ('fournisseur', '0003_remove_fournisseur_is_active_fournisseur_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
