# Generated by Django 5.2.10 on 2026-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0004_alter_fournisseur_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='achat_mds',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Achat Marchandise'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='achat_montant_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Achat Montant HTVA'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='achat_total_tvac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='achat_tva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de TVA'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_facture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Facturation'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Paiement'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
