# Generated by Django 5.2.10 on 2026-04-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0006_remove_fournisseur_achat_mds_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achat',
        ),
    ]
