# Generated by Django 5.2.10 on 2026-04-20 13:00

import societe_cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0007_delete_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[societe_cliente.models.validate_iban], verbose_name='Numéro de compte bancaire'),
        ),
    ]
