# Generated by Django 5.2.10 on 2026-05-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0005_alter_adresse_societe'),
        ('fournisseur', '0009_alter_fournisseur_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
