# Generated by Django 5.2.10 on 2026-09-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0007_adresse_societe'),
        ('fournisseur', '0010_alter_fournisseur_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fournisseurs', to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
