# Generated by Django 5.2.10 on 2026-10-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardan',
            name='noix_cardan',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('REPARE', 'Réparé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Noix de cardan'),
        ),
        migrations.AddField(
            model_name='cardan',
            name='noix_cardan_cote',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AVG', 'AVG'), ('AVD', 'AVD'), ('ARG', 'ARG'), ('ARD', 'ARD')], default='CHOISIR', max_length=25, verbose_name='Côté'),
        ),
        migrations.AddField(
            model_name='cardan',
            name='noix_cardan_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CONSTRUCTEUR_OEM', 'Constructeur (OEM)'), ('GKN', 'GKN / Löbro / Spidan'), ('NTN_SNR', 'NTN-SNR'), ('SKF', 'SKF'), ('ZF', 'ZF / Lemförder'), ('DANA', 'Dana / Spicer'), ('NEAPCO', 'Neapco'), ('IFA', 'IFA Rotorion'), ('HYUNDAI_WIA', 'Hyundai WIA'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('METELLI', 'Metelli'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('DELPHI', 'Delphi'), ('CORTECO', 'Corteco'), ('FAG', 'FAG / Schaeffler'), ('RIDEX', 'RIDEX'), ('BLUE_PRINT', 'Blue Print'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('SWAG', 'SWAG'), ('MAPCO', 'MAPCO'), ('JAPANPARTS', 'Japanparts'), ('DRIVESHAFT_SHOP', 'The Driveshaft Shop'), ('RCV', 'RCV Performance'), ('QA1', 'QA1'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='cardan',
            name='noix_cardan_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='cardan',
            name='noix_cardan_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
