# Generated by Django 5.2.10 on 2026-05-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_particulier', '0009_delete_clientpilotage'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPilotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('EXPERT', 'Expert'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='DEBUTANT', max_length=20, verbose_name='Niveau')),
                ('historique', models.TextField(blank=True, null=True, verbose_name='Historique pilotage')),
                ('location', models.TextField(blank=True, null=True, verbose_name='historique des locations')),
                ('client_particulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_particulier.clientparticulier', verbose_name='Client pilotage')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_pilotage', to='societe.societe')),
            ],
            options={
                'verbose_name': 'Client pilotage',
                'verbose_name_plural': 'Clients pilotages',
            },
        ),
    ]
