# Generated by Django 5.2.10 on 2026-05-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_particulier', '0009_delete_clientpilotage'),
        ('client_pilotage', '0001_initial'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientpilotage',
            index=models.Index(fields=['societe'], name='client_pilo_societe_5ef4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpilotage',
            index=models.Index(fields=['niveau'], name='client_pilo_niveau_37422e_idx'),
        ),
    ]
