# Generated by Django 5.2.10 on 2026-05-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0005_alter_adresse_societe'),
        ('client_pilotage', '0002_clientpilotage_client_pilo_societe_5ef4d9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpilotage',
            name='adresse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
