# Generated by Django 5.2.10 on 2026-07-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_pilotage', '0004_alter_clientpilotage_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpilotage',
            name='niveau',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('PRO', 'Pro'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='DEBUTANT', max_length=20, verbose_name='Niveau de pilotage'),
        ),
    ]
