# Generated by Django 5.2.10 on 2026-09-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_pilotage', '0005_alter_clientpilotage_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpilotage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='clientpilotage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
