# Generated by Django 5.2.10 on 2026-05-15 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0018_voitureexemplaire_nombre_remplacements_moteurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echappement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometrage_echappement', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage échappement')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du plein')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echappement', to='societe.societe', verbose_name='Societe')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echappement', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echappement', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Echappement',
                'verbose_name_plural': 'Échappements',
                'ordering': ['-date'],
            },
        ),
    ]
