# Generated by Django 5.2.10 on 2026-07-10 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0001_initial'),
        ('maindoeuvre', '0011_maindoeuvre_kilometres_chassis'),
        ('maintenance', '0013_alter_maintenance_type_maintenance'),
        ('societe', '0006_alter_societe_max_utilisateurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='echappement',
            name='capteur_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Capteur de pression différentielle du filtre à particules'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='capteur_fap_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='capteur_fap_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='catalyseur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Catalyseur'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='catalyseur_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='catalyseur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='collecteur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Collecteur'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='collecteur_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='collecteur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='courroie_accessoires',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Courroie d'accessoires"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='courroie_accessoires_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='courroie_accessoires_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='filtre_particules',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Filtre à particules'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='filtre_particules_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='filtre_particules_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echappement', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echappement', to='maintenance.maintenance'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='pays',
            field=models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], default='BE', max_length=5),
        ),
        migrations.AddField(
            model_name='echappement',
            name='pot_denox',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pot DeNOx'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='pot_denox_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='pot_denox_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silencieux',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silencieux'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silencieux_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silencieux_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_amont',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Sonde de température avant le filtre à particules'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_amont_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_amont_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_aval',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Sonde de température après le filtre à particules'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_aval_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_aval_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_amont',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Sonde Lambda amont'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_amont_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_amont_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_aval',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Sonde Lambda aval'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_aval_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_aval_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tech_nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tech_role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echappement', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tech_technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echappement', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echappements', to='societe.societe', verbose_name='Societe'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echappement_user', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
