# Generated by Django 5.2.10 on 2026-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0002_echappement_capteur_fap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echappement',
            old_name='courroie_accessoires_quantite',
            new_name='injecteur_ad_quantite',
        ),
        migrations.RenameField(
            model_name='echappement',
            old_name='courroie_accessoires_prix_achat',
            new_name='ligne_complete_prix_achat',
        ),
        migrations.RemoveField(
            model_name='echappement',
            name='courroie_accessoires',
        ),
        migrations.AddField(
            model_name='echappement',
            name='colmatage_fap',
            field=models.PositiveIntegerField(default=0, verbose_name='Taux de colmatage du FAP en pourcent'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='injecteur_ad',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Injecteur d'AdBlue"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='injecteur_ad_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix achat htva'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='ligne_complete',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Ligne complete'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='ligne_complete_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='regeneration_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Régénération du FAP'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='regeneration_fap_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix htva'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='regeneration_fap_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tuyau_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Tuyaux du capteur de pression différentielle'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tuyau_fap_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tuyau_fap_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
