# Generated by Django 5.2.10 on 2026-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0003_rename_courroie_accessoires_quantite_echappement_injecteur_ad_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echappement',
            name='collier',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Collier de serrage'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='collier_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix achat htva'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='collier_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='joint',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Joints'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='joint_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix achat htva'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='joint_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silent_bloc',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Silent Bloc'),
        ),
    ]
