# Generated by Django 5.2.10 on 2026-07-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0004_echappement_collier_echappement_collier_achat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echappement',
            old_name='capteur_fap_achat',
            new_name='capteur_fap_prix_achat',
        ),
        migrations.RenameField(
            model_name='echappement',
            old_name='collier_achat',
            new_name='collier_prix_achat',
        ),
        migrations.RenameField(
            model_name='echappement',
            old_name='injecteur_ad_achat',
            new_name='injecteur_ad_prix_achat',
        ),
        migrations.RenameField(
            model_name='echappement',
            old_name='joint_achat',
            new_name='joint_prix_achat',
        ),
        migrations.RenameField(
            model_name='echappement',
            old_name='regeneration_fap_achat',
            new_name='regeneration_fap_prix_achat',
        ),
        migrations.RenameField(
            model_name='echappement',
            old_name='sonde_fap_aval_achat',
            new_name='sonde_fap_aval_prix_achat',
        ),
        migrations.RenameField(
            model_name='echappement',
            old_name='tuyau_fap_achat',
            new_name='tuyau_fap_prix_achat',
        ),
        migrations.AddField(
            model_name='echappement',
            name='manchon',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Manchon'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='manchon_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix achat htva'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='manchon_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silent_bloc_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix achat htva'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silent_bloc_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
