# Generated by Django 5.2.10 on 2026-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0005_rename_capteur_fap_achat_echappement_capteur_fap_prix_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echappement',
            name='cendre_fap',
            field=models.PositiveIntegerField(default=0, verbose_name='Taux de cendres du FAP en pourcent'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='suie_fap',
            field=models.PositiveIntegerField(default=0, verbose_name='Taux de suies du FAP en pourcent'),
        ),
    ]
