# Generated by Django 5.2.10 on 2026-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0006_echappement_cendre_fap_echappement_suie_fap'),
    ]

    operations = [
        migrations.AddField(
            model_name='echappement',
            name='valve',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Valve d'échappement"),
        ),
        migrations.AddField(
            model_name='echappement',
            name='valve_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix achat htva'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='valve_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='cendre_fap',
            field=models.PositiveIntegerField(default=0, verbose_name='Poids des cendres du FAP'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='suie_fap',
            field=models.PositiveIntegerField(default=0, verbose_name='Poids des suies du FAP'),
        ),
    ]
