# Generated by Django 5.2.10 on 2026-07-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0007_echappement_valve_echappement_valve_prix_achat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echappement',
            old_name='tag',
            new_name='tag_echappement',
        ),
    ]
