# Generated by Django 5.2.10 on 2026-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0010_alter_echappement_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='echappement',
            name='capteur_fap_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='catalyseur_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='collecteur_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='collier_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='filtre_particules_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='injecteur_ad_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='joint_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='ligne_complete_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='mancon_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='pot_denox_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silencieux_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='silent_bloc_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_amont_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_fap_aval_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_amont_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='sonde_lambda_aval_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='tuyau_fap_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='echappement',
            name='valve_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='pays',
            field=models.CharField(choices=[('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('CZ', 'Tchéquie'), ('DE', 'Allemagne'), ('DK', 'Danemark'), ('EE', 'Estonie'), ('ES', 'Espagne'), ('FI', 'Finlande'), ('FR', 'France'), ('GR', 'Grèce'), ('HR', 'Croatie'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('IT', 'Italie'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('LV', 'Lettonie'), ('MT', 'Malte'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SE', 'Suède'), ('SI', 'Slovénie'), ('SK', 'Slovaquie')], default='BE', max_length=5),
        ),
    ]
