# Generated by Django 5.2.10 on 2026-08-11 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0011_echappement_capteur_fap_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echappement',
            name='capteur_fap_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='catalyseur_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='collecteur_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='collier_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='filtre_particules_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='injecteur_ad_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='joint_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='ligne_complete_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='mancon_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='pot_denox_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='silencieux_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='silent_bloc_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('LEMFORDER', 'Lemförder'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('TRW', 'TRW'), ('MOOG', 'Moog'), ('SACHS', 'Sachs'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('DELPHI', 'Delphi'), ('SIDEM', 'Sidem'), ('CORTECO', 'Corteco'), ('SWAG', 'SWAG'), ('VAICO', 'Vaico'), ('MAPCO', 'Mapco'), ('OPTIMAL', 'Optimal'), ('BIRTH', 'Birth'), ('SASIC', 'Sasic'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('POWERFLEX', 'Powerflex'), ('SUPERPRO', 'SuperPro'), ('STRONGFLEX', 'Strongflex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_fap_amont_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_fap_aval_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_lambda_amont_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_lambda_aval_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='taux_horaire',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0,00 €'), (Decimal('25.00'), '25,00 €'), (Decimal('30.00'), '30,00 €'), (Decimal('35.00'), '35,00 €'), (Decimal('40.00'), '40,00 €'), (Decimal('45.00'), '45,00 €'), (Decimal('50.00'), '50,00 €'), (Decimal('55.00'), '55,00 €'), (Decimal('60.00'), '60,00 €'), (Decimal('65.00'), '65,00 €'), (Decimal('70.00'), '70,00 €'), (Decimal('75.00'), '75,00 €'), (Decimal('80.00'), '80,00 €'), (Decimal('85.00'), '85,00 €'), (Decimal('90.00'), '90,00 €'), (Decimal('95.00'), '95,00 €'), (Decimal('100.00'), '100,00 €'), (Decimal('105.00'), '105,00 €'), (Decimal('11.00'), '110,00 €'), (Decimal('115.00'), '115,00 €'), (Decimal('120.00'), '120,00 €'), (Decimal('125.00'), '125,00 €'), (Decimal('130.00'), '130,00 €')], decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Taux horaire'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='tuyau_fap_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('AKRAPOVIC', 'Akrapovič'), ('REMUS', 'Remus'), ('SUPERSPRINT', 'Supersprint'), ('MILLTEK', 'Milltek Sport'), ('MAGNAFLOW', 'MagnaFlow'), ('BORLA', 'Borla'), ('EISENMANN', 'Eisenmann'), ('FOX', 'FOX'), ('BASTUCK', 'Bastuck'), ('RAGAZZON', 'Ragazzon'), ('SCORPION', 'Scorpion'), ('COBRA', 'Cobra Sport'), ('MIVV', 'MIVV'), ('ARROW', 'Arrow'), ('BOSAL', 'Bosal'), ('WALKER', 'Walker'), ('EBERSPACHER', 'Eberspächer'), ('IMASAF', 'IMASAF'), ('ERNST', 'Ernst'), ('POLMO', 'Polmo'), ('BMW', 'BMW'), ('PORSCHE', 'Porsche'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='valve_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
