# Generated by Django 5.2.10 on 2026-08-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0012_alter_echappement_capteur_fap_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echappement',
            old_name='mancon_fabricant',
            new_name='manchon_fabricant',
        ),
    ]
