# Generated by Django 5.2.10 on 2026-08-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0014_alter_echappement_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echappement',
            name='capteur_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Capteur de pression différentielle du filtre à particules'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='catalyseur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Catalyseur'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='collecteur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Collecteur'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='collier',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Collier de serrage'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='filtre_particules',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name='Filtre à particules'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='injecteur_ad',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name="Injecteur d'AdBlue"),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='joint',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Joints'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='ligne_complete',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Ligne complete'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='manchon',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Manchon'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='pot_denox',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name='Pot DeNOx'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='regeneration_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Régénération du FAP'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='silencieux',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Silencieux'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='silent_bloc',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Silent Bloc'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_fap_amont',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name='Sonde de température avant le filtre à particules'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_fap_aval',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name='Sonde de température après le filtre à particules'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_lambda_amont',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Sonde Lambda amont'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='sonde_lambda_aval',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Sonde Lambda aval'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='tuyau_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name='Tuyaux du capteur de pression différentielle'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='valve',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Valve d'échappement"),
        ),
    ]
