# Generated by Django 5.2.10 on 2026-08-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0016_alter_echappement_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echappement',
            name='capteur_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name='Capteur de pression différentielle du filtre à particules'),
        ),
        migrations.AlterField(
            model_name='echappement',
            name='regeneration_fap',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='NON_PRESENT', max_length=25, verbose_name='Régénération du FAP'),
        ),
    ]
