# Generated by Django 5.2.10 on 2026-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0017_alter_echappement_capteur_fap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echappement',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
