# Generated by Django 5.2.10 on 2026-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echappement', '0021_echappement_kilometres_boite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echappement',
            name='kilometrage_echappement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilométrage du contrôle'),
        ),
    ]
