# Generated by Django 5.2.10 on 2026-02-04 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adresse', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('apprenti', 'Apprenti'), ('mécanicien', 'Mécanicien'), ('magasinier', 'Magasinier'), ('carrossier', 'Carrossier'), ('chef mécanicien', 'Chef Mécanicien'), ('instructeur', 'Instructeur'), ('instructeur externe', 'Instructeur Externe'), ('vendeur', 'Vendeur'), ('comptable', 'Comptable'), ('direction', 'Direction')], default='apprenti', max_length=30, verbose_name='Rôle')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('email_google', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_entreprise', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('salaire_brut_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_brut_employeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_jours_preste', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nombre_heures_preste', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('taux_charges_patronales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salaire_majore', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taux_precompte_professionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_onss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salaire_net_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conges_payes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='adresse.adresse')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='utilisateurs_set', to='auth.group', verbose_name='groups')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='societe.societe', to_field='id_societe')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='utilisateurs_set', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanicien',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('utilisateurs.utilisateur',),
        ),
    ]
