# Generated by Django 5.2.10 on 2026-04-28 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDoeuvre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temps', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temps presté (heures)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_oeuvres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Main d'oeuvre",
                'verbose_name_plural': "Main d'oeuvres",
            },
        ),
    ]
