# Generated by Django 5.2.10 on 2026-04-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0006_alter_entretien_main_oeuvre'),
        ('utilisateurs', '0002_maindoeuvre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainDoeuvre',
        ),
    ]
