# Generated by Django 6.0 on 2026-01-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0001_initial'),
        ('societe', '0001_initial'),
        ('utilisateurs', '0002_alter_utilisateur_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='adresse.adresse'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='societe.societe'),
        ),
    ]
