# Generated by Django 6.0 on 2026-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_adresse_alter_utilisateur_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('apprenti', 'Apprenti'), ('mécanicien', 'Mécanicien'), ('magasinier', 'Magasinier'), ('carrossier', 'Carrossier'), ('chef mécanicien', 'Chef Mécanicien'), ('instructeur', 'Instructeur'), ('instructeur externe', 'Instructeur Externe'), ('vendeur', 'Vendeur'), ('comptable', 'Comptable'), ('direction', 'Direction')], default='apprenti', max_length=30, verbose_name='Rôle'),
        ),
    ]
