# Generated by Django 5.2.10 on 2026-05-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_delete_maindoeuvre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('apprentis', 'Apprenti'), ('mecanicien', 'Mécanicien'), ('magasinier', 'Magasinier'), ('carrossier', 'Carrossier'), ('chef_mecanicien', 'Chef Mécanicien'), ('instructeur', 'Instructeur'), ('instructeur externe', 'Instructeur Externe'), ('vendeur', 'Vendeur'), ('comptable', 'Comptable'), ('direction', 'Direction')], default='apprentis', max_length=30, verbose_name='Rôle'),
        ),
    ]
