# Generated by Django 5.2.10 on 2026-06-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_userlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='email_google',
            new_name='email',
        ),
    ]
