# Generated by Django 5.2.10 on 2026-07-08 09:28

import client_atelier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_rename_email_google_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='numero_compte_bancaire',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[client_atelier.models.validate_iban]),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numero_registre_national',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
