# Generated by Django 5.2.10 on 2026-07-08 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_utilisateur_numero_compte_bancaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='conges_payes',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='nombre_heures_preste',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='nombre_jours_preste',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='salaire_brut_employeur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='salaire_brut_heure',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='salaire_majore',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='salaire_net_mois',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='salaire_total',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='taux_charges_patronales',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='taux_onss',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='taux_precompte_professionnel',
        ),
        migrations.CreateModel(
            name='PaieUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('salaire_brut_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire brut / heure')),
                ('salaire_brut_employeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire brut employeur')),
                ('nombre_jours_preste', models.PositiveIntegerField(default=0, verbose_name='Nombre de jours prestés')),
                ('nombre_heures_preste', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Nombre d'heures prestées")),
                ('taux_charges_patronales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux charges patronales')),
                ('taux_precompte_professionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux précompte professionnel')),
                ('taux_onss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux ONSS')),
                ('salaire_net_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire net du mois')),
                ('conges_payes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Congés payés')),
                ('salaire_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salaire total')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paie utilisateur',
                'verbose_name_plural': 'Paies utilisateurs',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('utilisateur', 'mois', 'annee')},
            },
        ),
    ]
