# Generated by Django 5.2.10 on 2026-07-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_remove_utilisateur_conges_payes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='salaire_brut_heure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire brut / heure'),
        ),
    ]
