# Generated by Django 5.2.10 on 2026-04-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeometrieVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrossage_avant_droit', models.FloatField(verbose_name='Carrossage avant droit (°)')),
                ('carrossage_avant_gauche', models.FloatField(verbose_name='Carrossage avant gauche (°)')),
                ('carrossage_arriere_droit', models.FloatField(verbose_name='Carrossage arrière (°)')),
                ('carrossage_arriere_gauche', models.FloatField(verbose_name='Carrossage arrière (°)')),
                ('chasse_droite', models.FloatField(verbose_name='Chasse à droite (°)')),
                ('chasse_gauche', models.FloatField(verbose_name='Chasse à gauche (°)')),
                ('pincement_avant_droit', models.FloatField(verbose_name='Pincement avant droit(°)')),
                ('pincement_avant', models.FloatField(verbose_name='Pincement avant gauche(°)')),
                ('pincement_arriere_droit', models.FloatField(verbose_name='Pincement arrière droit (°)')),
                ('pincement_arriere_gauche', models.FloatField(verbose_name='Pincement arrière gauche (°)')),
                ('poussee_arriere', models.FloatField(verbose_name='Poussée du train arrière (°)')),
                ('angle_pivot', models.FloatField(verbose_name='Angle pivot (°)')),
                ('hauteur_caisse', models.FloatField(verbose_name='Hauteur de caisse (mm)')),
                ('debattement_suspension_avant', models.FloatField(verbose_name='Débattement avant (mm)')),
                ('debattement_suspension_arriere', models.FloatField(verbose_name='Débattement arrière (mm)')),
                ('raideur_ressort_avant', models.FloatField(verbose_name='Raideur ressort avant')),
                ('raideur_ressort_arriere', models.FloatField(verbose_name='Raideur ressort arrière')),
                ('amortissement_avant', models.FloatField(verbose_name='Amortissement avant')),
                ('amortissement_arriere', models.FloatField(verbose_name='Amortissement arrière')),
            ],
        ),
    ]
