# Generated by Django 5.2.10 on 2026-04-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0001_initial'),
        ('maintenance', '0003_maintenance_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0012_alter_voitureexemplaire_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geometrievoiture',
            options={'verbose_name': 'Contrôle Géometrie', 'verbose_name_plural': 'Contrôles Géometrie'},
        ),
        migrations.RemoveField(
            model_name='geometrievoiture',
            name='amortissement_arriere',
        ),
        migrations.RemoveField(
            model_name='geometrievoiture',
            name='amortissement_avant',
        ),
        migrations.RemoveField(
            model_name='geometrievoiture',
            name='pincement_avant',
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='amortissement_arriere_compression',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amortissement arrière compression'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='amortissement_arriere_rebond',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amortissement arrière rebond'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='amortissement_avant_compression',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amortissement avant compression'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='amortissement_avant_rebond',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amortissement avant rebond'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='amortisseur_marque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque des amortisseurs'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='kilometrage_geometrie',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment de la géometrie'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometrie', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pincement_avant_gauche',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Pincement avant gauche (°)'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='tag',
            field=models.CharField(choices=[('WHITE', 'Blanc'), ('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='WHITE', max_length=10, verbose_name='État visuel / Tag'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='tech_nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='tech_role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometrie', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='tech_technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometrie', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometrie', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres checkup'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='angle_pivot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Angle pivot (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='carrossage_arriere_droit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Carrossage arrière droit (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='carrossage_arriere_gauche',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Carrossage arrière gauche (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='carrossage_avant_droit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Carrossage avant droit (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='carrossage_avant_gauche',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Carrossage avant gauche (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='chasse_droite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Chasse à droite (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='chasse_gauche',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Chasse à gauche (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='pincement_arriere_droit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Pincement arrière droit (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='pincement_arriere_gauche',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Pincement arrière gauche (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='pincement_avant_droit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Pincement avant droit (°)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='poussee_arriere',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Poussée du train arrière (°)'),
        ),
    ]
