# Generated by Django 5.2.10 on 2026-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0002_alter_geometrievoiture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrievoiture',
            name='debattement_suspension_arriere',
            field=models.FloatField(blank=True, null=True, verbose_name='Débattement arrière (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='debattement_suspension_avant',
            field=models.FloatField(blank=True, null=True, verbose_name='Débattement avant (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='hauteur_caisse',
            field=models.FloatField(blank=True, null=True, verbose_name='Hauteur de caisse (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='raideur_ressort_arriere',
            field=models.FloatField(blank=True, null=True, verbose_name='Raideur ressort arrière'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='raideur_ressort_avant',
            field=models.FloatField(blank=True, null=True, verbose_name='Raideur ressort avant'),
        ),
    ]
