# Generated by Django 5.2.10 on 2026-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0005_alter_geometrievoiture_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrievoiture',
            name='kilometrage_geometrie',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment de la géometrie'),
            preserve_default=False,
        ),
    ]
