# Generated by Django 5.2.10 on 2026-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0007_geometrievoiture_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrievoiture',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
    ]
