# Generated by Django 5.2.10 on 2026-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0012_alter_geometrievoiture_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrievoiture',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
