# Generated by Django 5.2.10 on 2026-09-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0014_geometrievoiture_serrage_roues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometrievoiture',
            name='hauteur_caisse',
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='hauteur_caisse_ard',
            field=models.FloatField(blank=True, null=True, verbose_name='Hauteur de caisse ARD (mm)'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='hauteur_caisse_arg',
            field=models.FloatField(blank=True, null=True, verbose_name='Hauteur de caisse ARG (mm)'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='hauteur_caisse_avd',
            field=models.FloatField(blank=True, null=True, verbose_name='Hauteur de caisse AVD (mm)'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='hauteur_caisse_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Hauteur de caisse AVG (mm)'),
        ),
    ]
