# Generated by Django 5.2.10 on 2026-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0015_remove_geometrievoiture_hauteur_caisse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrievoiture',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
