# Generated by Django 5.2.10 on 2026-10-03 11:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0018_geometrievoiture_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_bande_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu arrière droit'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_bande_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu arrière gauche'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_bande_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu avant droit'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_bande_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Bande de roulement du pneu avant gauche'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_pression_bar_ard',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_pression_bar_arg',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_pression_bar_avd',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AddField(
            model_name='geometrievoiture',
            name='pneu_pression_bar_avg',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu avant gauche en bar'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_arriere_compression',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement arrière compression (clic)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_arriere_rebond',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement arrière rebond (clic)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_avant_compression',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement avant compression (clic)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_avant_rebond',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement avant rebond (clic)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='debattement_suspension_arriere',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Débattement arrière (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='debattement_suspension_avant',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Débattement avant (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='hauteur_caisse_ard',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hauteur de caisse ARD (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='hauteur_caisse_arg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hauteur de caisse ARG (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='hauteur_caisse_avd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hauteur de caisse AVD (mm)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='hauteur_caisse_avg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hauteur de caisse AVG (mm)'),
        ),
    ]
