# Generated by Django 5.2.10 on 2026-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0019_geometrievoiture_pneu_bande_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortisseur_marque',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('Bilstein', 'Bilstein'), ('Boge', 'Boge'), ('Eibach', 'Eibach'), ('Fox', 'Fox'), ('Gabriel', 'Gabriel'), ('H&R', 'H&R'), ('Koni', 'Koni'), ('KW', 'KW'), ('KYB', 'KYB (Kayaba)'), ('Magneti Marelli', 'Magneti Marelli'), ('Meyle', 'Meyle'), ('Monroe', 'Monroe'), ('Öhlins', 'Öhlins'), ('Rancho', 'Rancho'), ('Sachs', 'Sachs (ZF)'), ('Showa', 'Showa'), ('Tein', 'Tein'), ('Tokico', 'Tokico'), ('Origine', 'Origine constructeur'), ('Autre', 'Autre')], default='CHOISIR', max_length=255, null=True, verbose_name='Marque des amortisseurs'),
        ),
    ]
