# Generated by Django 5.2.10 on 2026-10-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometrie', '0020_alter_geometrievoiture_amortisseur_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_arriere_compression',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement arrière compression (clics)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_arriere_rebond',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement arrière rebond (clics)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_avant_compression',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement avant compression (clics)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortissement_avant_rebond',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amortissement avant rebond (clics)'),
        ),
        migrations.AlterField(
            model_name='geometrievoiture',
            name='amortisseur_marque',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('Bilstein', 'Bilstein'), ('Boge', 'Boge'), ('Eibach', 'Eibach'), ('Fox', 'Fox'), ('Gabriel', 'Gabriel'), ('H&R', 'H&R'), ('Koni', 'Koni'), ('KW', 'KW'), ('KYB', 'KYB (Kayaba)'), ('Magneti Marelli', 'Magneti Marelli'), ('Meyle', 'Meyle'), ('Monroe', 'Monroe'), ('Öhlins', 'Öhlins'), ('Rancho', 'Rancho'), ('Sachs', 'Sachs (ZF)'), ('Showa', 'Showa'), ('Tein', 'Tein'), ('Tokico', 'Tokico'), ('Origine', 'Origine constructeur (OEM)'), ('Autre', 'Autre')], default='CHOISIR', max_length=255, null=True, verbose_name='Marque des amortisseurs'),
        ),
    ]
