# Generated by Django 5.2.10 on 2026-10-10 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0010_alter_societe_numero_tel'),
        ('voiture_exemplaire', '0032_voitureexemplaire_cote_conduite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('type_maintenance', models.CharField(choices=[('checkup', 'Check-up'), ('entretien', 'Entretien'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('nettoyage_exterieur', 'Nettoyage extérieur'), ('nettoyage_interieur', 'Nettoyage intérieur'), ('niveaux', 'Niveaux'), ('autres', 'Autres interventions'), ('checkup_track', 'Check-up piste'), ('ABS', 'ABS'), ('remplacement_boite', 'Remplacement boîte'), ('jeux_pieces', 'Jeux pieces'), ('silent_bloc', 'Silent bloc'), ('BOITE', 'Boite'), ('BOITE_AUTO', 'Boite automatique'), ('ADMISSION', 'Admission'), ('TURBO', 'Turbo'), ('CARROSSERIE_INTERNE', 'Carrosserie interne'), ('REMPLACEMENT_MOTEUR', 'Remplacement moteur'), ('COURROIE_DISTRI', 'Courroie de distribution'), ('RODAGE', 'Rodage'), ('COURROIE_ACCESS', "Courroie d'accessoires"), ('ECHAPPEMENT', 'Echappement'), ('CLIMATISATION', 'Climatisation'), ('ALTERNATEUR', 'Alternateur'), ('REFROIDISSEMENT', 'Refroidissement'), ('EMBRAYAGE', 'Embrayage'), ('ALLUMAGE', 'Allumage'), ('ESSUYAGE', 'Essuyage'), ('INJECTION', 'Injection'), ('GEOMETRIE', 'Géométrie'), ('ECLAIRAGE', 'Eclairage'), ('CARDAN', 'Cardan')], max_length=50, verbose_name='Maintenance')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='Tag')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=10, verbose_name='Statut')),
                ('prete_pour', models.CharField(blank=True, help_text='Ex. : roulage Spa-Francorchamps du 18/10', max_length=255, verbose_name='Prête pour')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_taches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_taches', to='societe.societe', verbose_name='Société')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_taches', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_taches', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': "Tâche d'agenda",
                'verbose_name_plural': 'Agenda',
                'ordering': ['date', 'technicien__nom', 'id'],
            },
        ),
    ]
