# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_direction', models.CharField(choices=[('cremaillere_direction', 'Crémaillère de direction'), ('pompe_direction', 'Pompe de direction'), ('biellette_direction_g', 'Biellette de direction gauche'), ('biellette_direction_d', 'Biellette de direction droite'), ('rotule_direction_g', 'Rotule de direction gauche'), ('rotule_direction_d', 'Rotule de direction droite'), ('soufflets', 'Soufflets'), ('durite_direction', 'Durite de direction'), ('huile_direction_quantite', 'Huile de direction (quantité)'), ('huile_direction_qualite', 'Huile de direction (qualité)'), ('reservoir', 'Réservoir')], max_length=50, verbose_name='Type de pièce de direction')),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='directions', to='voiture_moteur.moteurvoiture', verbose_name='Moteurs compatibles')),
            ],
            options={
                'verbose_name': 'Pièce de direction',
                'verbose_name_plural': 'Pièces de direction',
            },
            bases=('piece.piece',),
        ),
    ]
