from django.core.management.base import BaseCommand
from django_tenants.utils import tenant_context
from societe.models import Societe
from voiture.voiture_boite.models import VoitureBoite, TypeBoite, TypeEntretienBoite
from voiture.voiture_modele.models import VoitureModele


class Command(BaseCommand):
    help = "Ajoute des boîtes de vitesses pour le tenant 'db-solution'"

    def handle(self, *args, **options):
        try:
            tenant = Societe.objects.get(slug="db-solution")
        except Societe.DoesNotExist:
            self.stdout.write(self.style.ERROR("Tenant 'db-solution' introuvable !"))
            return

        with tenant_context(tenant):
            modele = VoitureModele.objects.first()
            if not modele:
                self.stdout.write(self.style.ERROR("Aucun VoitureModele trouvé."))
                return

            # Données boîtes
            boites_data = [
                {
                    "fabricant": "Abarth",
                    "nom_du_type": "TCT 5 rapports",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 5,
                    "qualite_huile": "Abarth Fluid",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Abarth",
                    "nom_du_type": "TCT 6 rapports",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "Abarth Fluid",
                    "quantite_huile_l": 6.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Abarth",
                    "nom_du_type": "Manuelle 5 rapports",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Acura",
                    "nom_du_type": "Automatic 6-speed",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "Honda ATF-Z1",
                    "quantite_huile_l": 3.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Boîte automatique 9 rapports sur RDX / MDX
                {
                    "fabricant": "Acura",
                    "nom_du_type": "Automatic 9-speed",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 9,
                    "qualite_huile": "Honda ATF-Z1",
                    "quantite_huile_l": 3.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Boîte manuelle 6 rapports sur Civic Type R (badgé Acura en certaines régions)
                {
                    "fabricant": "Acura",
                    "nom_du_type": "Manual 6-speed",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 6,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Acura",
                    "nom_du_type": "Manual 5-speed Integra GS-R",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Acura",
                    "nom_du_type": "Automatic 4-speed TL 3.2",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 4,
                    "qualite_huile": "Honda ATF-Z1",
                    "quantite_huile_l": 3.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Acura",
                    "nom_du_type": "Automatic 5-speed MDX 2001",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 5,
                    "qualite_huile": "Honda ATF-Z1",
                    "quantite_huile_l": 3.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Alpha Romeo",
                    "nom_du_type": "Manual 5-speed 147 / 156",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Alpha Romeo",
                    "nom_du_type": "Manual 6-speed 159 / Brera / Spider",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 6,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.8,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Boîtes automatiques / TCT
                {
                    "fabricant": "Alpha Romeo",
                    "nom_du_type": "TCT 6-speed Giulietta / 4C",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "TCT Fluid",
                    "quantite_huile_l": 6.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Alpha Romeo",
                    "nom_du_type": "ZF 8-speed Giulia",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                {
                    "fabricant": "Alpine",
                    "nom_du_type": "Manual 4-speed A110 Classic",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Alpine",
                    "nom_du_type": "Manual 5-speed A110 Classic",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Alpine",
                    "nom_du_type": "DCT 7-speed A110 Modern",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "ATF / DCT Fluid",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # Anciennes manuelles
                {
                    "fabricant": "Aston Martin",
                    "nom_du_type": "Manual 5-speed V8 Vantage Classic",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Aston Martin",
                    "nom_du_type": "Manual 5-speed DB7",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Récentes Touchtronic / automatiques
                {
                    "fabricant": "Aston Martin",
                    "nom_du_type": "Touchtronic 6-speed DB9",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 3.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Aston Martin",
                    "nom_du_type": "ZF 8-speed DB11 / Vantage / DBS",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Aston Martin",
                    "nom_du_type": "ZF 9-speed DBX",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 9,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 8.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Valhalla DCT
                {
                    "fabricant": "Aston Martin",
                    "nom_du_type": "DCT 8-speed Valhalla",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "DCT Fluid",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # A3 1ère gen
                {
                    "fabricant": "Audi",
                    "nom_du_type": "Manual 5-speed A3 1ère gen",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.3,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # A3 2ème gen DSG
                {
                    "fabricant": "Audi",
                    "nom_du_type": "DSG 6-speed A3 2ème gen",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "DSG Fluid",
                    "quantite_huile_l": 6.3,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # A4 manuelle et S-Tronic
                {
                    "fabricant": "Audi",
                    "nom_du_type": "Manual 5-speed A4 1ère gen",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Audi",
                    "nom_du_type": "S-Tronic 6-speed A4 2ème gen",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "DSG Fluid",
                    "quantite_huile_l": 6.3,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },



                {
                    "fabricant": "Audi S",
                    "nom_du_type": "S-Tronic 6-speed S3 1ère gen",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "DSG Fluid",
                    "quantite_huile_l": 6.3,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Audi S",
                    "nom_du_type": "Tiptronic 7-speed S5 / S6",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "ATF / DSG Fluid",
                    "quantite_huile_l": 6.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Audi S",
                    "nom_du_type": "ZF 7-8 speed auto S4/S5/S6 (2015+)",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Audi RS",
                    "nom_du_type": "S-Tronic 7-speed RS3",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "DSG Fluid",
                    "quantite_huile_l": 6.3,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Audi RS",
                    "nom_du_type": "Tiptronic / S-Tronic RS4 / RS5 / RS6",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "ATF / DSG Fluid",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Audi RS",
                    "nom_du_type": "ZF 8-speed RS7 (2013+)",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "BMW M",
                    "nom_du_type": "Manual 5-speed E30 M3",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # E36 M3
                {
                    "fabricant": "BMW M",
                    "nom_du_type": "Manual 5-speed E36 M3",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # E46 M3
                {
                    "fabricant": "BMW M",
                    "nom_du_type": "Manual 6-speed E46 M3",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 6,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.7,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # E60 M5 (SMG)
                {
                    "fabricant": "BMW M",
                    "nom_du_type": "SMG 7-speed E60 M5",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "ATF / SMG Fluid",
                    "quantite_huile_l": 6.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # F80 M3 / F82 M4 (DCT 7-speed)
                {
                    "fabricant": "BMW M",
                    "nom_du_type": "DCT 7-speed F80/F82 M3/M4",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "DCT Fluid",
                    "quantite_huile_l": 6.3,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # F10 M5 / F12 M6 (7-speed auto / ZF)
                {
                    "fabricant": "BMW M",
                    "nom_du_type": "ZF 7-speed F10/F12 M5/M6",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # G80 M3 / G82 M4 (DCT 8-speed auto)
                {
                    "fabricant": "BMW M",
                    "nom_du_type": "ZF 8-speed G80/G82 M3/M4",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF / ZF Fluid",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Borgward",
                    "nom_du_type": "Manual 4-speed Hansa",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Borgward",
                    "nom_du_type": "Manual 4-speed Isabella / P100",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.2,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # Modèles modernes Borgward BX5/BX7 (automatiques CVT / 6-8 speed auto)
                {
                    "fabricant": "Borgward",
                    "nom_du_type": "Automatic 6-speed BX5",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "ATF",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Borgward",
                    "nom_du_type": "Automatic 8-speed BX7",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # BX7 hybride (plug-in)
                {
                    "fabricant": "Borgward",
                    "nom_du_type": "CVT BX7 PHEV",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 1,  # CVT = 1 ratio variable
                    "qualite_huile": "CVT Fluid",
                    "quantite_huile_l": 4.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Veyron
                {
                    "fabricant": "Bugatti",
                    "nom_du_type": "Semi-automatic 7-speed Veyron",
                    "type_de_boite": "Semi-automatique",
                    "nombre_rapport": 7,
                    "qualite_huile": "High-Performance ATF",
                    "quantite_huile_l": 9.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Chiron
                {
                    "fabricant": "Bugatti",
                    "nom_du_type": "Semi-automatic 7-speed Chiron",
                    "type_de_boite": "Semi-automatique",
                    "nombre_rapport": 7,
                    "qualite_huile": "High-Performance ATF",
                    "quantite_huile_l": 9.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Divo
                {
                    "fabricant": "Bugatti",
                    "nom_du_type": "Semi-automatic 7-speed Divo",
                    "type_de_boite": "Semi-automatique",
                    "nombre_rapport": 7,
                    "qualite_huile": "High-Performance ATF",
                    "quantite_huile_l": 9.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Centodieci
                {
                    "fabricant": "Bugatti",
                    "nom_du_type": "Semi-automatic 7-speed Centodieci",
                    "type_de_boite": "Semi-automatique",
                    "nombre_rapport": 7,
                    "qualite_huile": "High-Performance ATF",
                    "quantite_huile_l": 9.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Bolide
                {
                    "fabricant": "Bugatti",
                    "nom_du_type": "Semi-automatic 7-speed Bolide",
                    "type_de_boite": "Semi-automatique",
                    "nombre_rapport": 7,
                    "qualite_huile": "High-Performance ATF",
                    "quantite_huile_l": 9.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Bentley",
                    "nom_du_type": "Automatic 4-speed Arnage",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 4,
                    "qualite_huile": "ZF ATF",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Continental GT ancienne génération
                {
                    "fabricant": "Bentley",
                    "nom_du_type": "Automatic 6-speed Continental GT",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "ZF ATF",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Continental GT / Flying Spur / Bentayga modernes
                {
                    "fabricant": "Bentley",
                    "nom_du_type": "Automatic 8-speed ZF",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "ZF ATF 8HP",
                    "quantite_huile_l": 8.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 100000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Bentayga hybride
                {
                    "fabricant": "Bentley",
                    "nom_du_type": "Automatic 7-speed Bentayga Hybrid",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 7,
                    "qualite_huile": "ZF ATF",
                    "quantite_huile_l": 7.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                {
                    "fabricant": "Cadillac",
                    "nom_du_type": "Hydra-Matic 3-speed Eldorado",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 3,
                    "qualite_huile": "Dexron III",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Cadillac",
                    "nom_du_type": "Turbo Hydra-Matic 4-speed DeVille",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 4,
                    "qualite_huile": "Dexron III",
                    "quantite_huile_l": 6.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Modernes 2000+
                {
                    "fabricant": "Cadillac",
                    "nom_du_type": "Automatic 6-speed CTS",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Cadillac",
                    "nom_du_type": "Automatic 8-speed Escalade",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 8.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Cadillac",
                    "nom_du_type": "Automatic 10-speed CT6",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 10,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 8.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 100000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

            {
                    "fabricant": "Buick",
                    "nom_du_type": "Hydra-Matic 3-speed",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 3,
                    "qualite_huile": "Dexron III",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Buick",
                    "nom_du_type": "Manual 4-speed",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Modernes 2000+
                {
                    "fabricant": "Buick",
                    "nom_du_type": "Automatic 6-speed",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Buick",
                    "nom_du_type": "Automatic 9-speed",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 9,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 8.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # CVT pour modèles compacts
                {
                    "fabricant": "Buick",
                    "nom_du_type": "CVT Encore / Verano",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 1,
                    "qualite_huile": "CVT Fluid",
                    "quantite_huile_l": 4.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Chevrolet",
                    "nom_du_type": "Manual 3-speed C1",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 3,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # C2 1963-1967
                {
                    "fabricant": "Chevrolet",
                    "nom_du_type": "Manual 4-speed C2",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # C3 1968-1982
                {
                    "fabricant": "Chevrolet",
                    "nom_du_type": "Automatic 4-speed C3",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 4,
                    "qualite_huile": "Dexron III",
                    "quantite_huile_l": 4.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # C4 1984-1996
                {
                    "fabricant": "Chevrolet",
                    "nom_du_type": "Automatic 4/6-speed C4",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "Dexron III/VI",
                    "quantite_huile_l": 5.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 70000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # C8 2020+
                {
                    "fabricant": "Chevrolet",
                    "nom_du_type": "DCT 8-speed C8",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "DCT Fluid",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 100000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                {
                    "fabricant": "Chrysler",
                    "nom_du_type": "TorqueFlite 3-speed",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 3,
                    "qualite_huile": "Dexron III",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Moderne Chrysler 2000+
                {
                    "fabricant": "Chrysler",
                    "nom_du_type": "Automatic 6-speed 300",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                # Ancienne 2CV
                {
                    "fabricant": "Citroën",
                    "nom_du_type": "Manual 4-speed 2CV",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 40000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Moderne C4 Cactus
                {
                    "fabricant": "Citroën",
                    "nom_du_type": "EAT6 Automatic",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "EAT Fluid",
                    "quantite_huile_l": 6.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                {
                    "fabricant": "Citroën Sport",
                    "nom_du_type": "Manual 6-speed DS3 Racing",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 6,
                    "qualite_huile": "API GL-4 Racing",
                    "quantite_huile_l": 3.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Citroën Sport",
                    "nom_du_type": "Automatic 6-speed DS4 Racing",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "EAT Racing",
                    "quantite_huile_l": 4.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                # Ancienne Dacia 1300
                {
                    "fabricant": "Dacia",
                    "nom_du_type": "Manual 4-speed 1300",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Logan 2004+
                {
                    "fabricant": "Dacia",
                    "nom_du_type": "Manual 5-speed Logan",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 3.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 70000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Duster 2021+ automatique
                {
                    "fabricant": "Dacia",
                    "nom_du_type": "Automatic 6-speed Duster",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 5.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                # Pantera 1971-1992
                {
                    "fabricant": "De Tomaso",
                    "nom_du_type": "Manual 5-speed Pantera",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 5,
                    "qualite_huile": "ZF GL-4",
                    "quantite_huile_l": 4.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Mangusta 1964-1971
                {
                    "fabricant": "De Tomaso",
                    "nom_du_type": "Manual 5-speed Mangusta",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 4.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Guarà 1993-2004
                {
                    "fabricant": "De Tomaso",
                    "nom_du_type": "Manual 6-speed Guarà",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 6,
                    "qualite_huile": "API GL-4 Racing",
                    "quantite_huile_l": 4.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # Ancienne Charger 1969
                {
                    "fabricant": "Dodge",
                    "nom_du_type": "TorqueFlite 3-speed Charger 1969",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 3,
                    "qualite_huile": "Dexron III",
                    "quantite_huile_l": 6.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Moderne Challenger 2020
                {
                    "fabricant": "Dodge",
                    "nom_du_type": "Automatic 8-speed Challenger 2020",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


                # Viper SRT 2003
                {
                    "fabricant": "Dodge SRT",
                    "nom_du_type": "Manual 6-speed Viper SRT",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 6,
                    "qualite_huile": "API GL-4 Racing",
                    "quantite_huile_l": 3.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # Challenger SRT Hellcat 2015
                {
                    "fabricant": "Dodge SRT",
                    "nom_du_type": "Automatic 8-speed Challenger SRT Hellcat",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 7.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # DS 3 2010 manuel
                {
                    "fabricant": "DS Automobiles",
                    "nom_du_type": "Manual 5-speed DS3",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # DS 3 Crossback 2020 automatique
                {
                    "fabricant": "DS Automobiles",
                    "nom_du_type": "Automatic 6-speed DS3 Crossback",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 4.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # DS 7 Crossback 2020 automatique
                {
                    "fabricant": "DS Automobiles",
                    "nom_du_type": "Automatic 8-speed DS7 Crossback",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "Dexron VI",
                    "quantite_huile_l": 5.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 100000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # 250 GT 1960s
                {
                    "fabricant": "Ferrari",
                    "nom_du_type": "Manual 4-speed 250 GT",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 4,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # 360 Modena 2000 Manuelle
                {
                    "fabricant": "Ferrari",
                    "nom_du_type": "Manual 6-speed 360 Modena",
                    "type_de_boite": "Manuelle",
                    "nombre_rapport": 6,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 3.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 70000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # 360 Modena F1 2000 Semi-automatique
                {
                    "fabricant": "Ferrari",
                    "nom_du_type": "F1 6-speed 360 Modena",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 6,
                    "qualite_huile": "Ferrari F1 Fluid",
                    "quantite_huile_l": 4.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 50000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # 458 Italia 2010 F1
                {
                    "fabricant": "Ferrari",
                    "nom_du_type": "F1 7-speed 458 Italia",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 7,
                    "qualite_huile": "Ferrari F1 Fluid",
                    "quantite_huile_l": 4.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 90000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                # SF90 Stradale 2020 F1 8 rapports
                {
                    "fabricant": "Ferrari",
                    "nom_du_type": "F1 8-speed SF90 Stradale",
                    "type_de_boite": "Automatique",
                    "nombre_rapport": 8,
                    "qualite_huile": "Ferrari F1 Fluid",
                    "quantite_huile_l": 5.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 100000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },





            {
                    "fabricant": "ZF",
                    "nom_du_type": "ZF8HP",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF",
                    "quantite_huile_l": 7.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,   # maintenant défini
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "Porsche",
                    "nom_du_type": "915",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "80W90",
                    "quantite_huile_l": 3.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Porsche",
                    "nom_du_type": "G50",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "75W90",
                    "quantite_huile_l": 3.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 80000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # ===== Porsche modernes =====
                {
                    "fabricant": "Porsche",
                    "nom_du_type": "Tiptronic S",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 5,
                    "qualite_huile": "ATF",
                    "quantite_huile_l": 9.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Porsche",
                    "nom_du_type": "PDK Gen1",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "PDK Fluid",
                    "quantite_huile_l": 7.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # ===== Porsche récents =====
                {
                    "fabricant": "Porsche",
                    "nom_du_type": "PDK Gen2",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "PDK Fluid",
                    "quantite_huile_l": 8.0,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "Porsche",
                    "nom_du_type": "PDK 8 rapports Turbo S",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "PDK Fluid",
                    "quantite_huile_l": 8.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                {
                    "fabricant": "BMW",
                    "nom_du_type": "Getrag 260",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "BMW",
                    "nom_du_type": "ZF S5-31",
                    "type_de_boite": TypeBoite.MANUELLE,
                    "nombre_rapport": 5,
                    "qualite_huile": "API GL-4",
                    "quantite_huile_l": 2.5,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # Anciennes boîtes automatiques
                {
                    "fabricant": "BMW",
                    "nom_du_type": "ZF 4HP22",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 4,
                    "qualite_huile": "ATF Dexron II",
                    "quantite_huile_l": 7,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "BMW",
                    "nom_du_type": "ZF 5HP18",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 5,
                    "qualite_huile": "ATF Dexron III",
                    "quantite_huile_l": 7,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # Récentes boîtes automatiques
                {
                    "fabricant": "BMW",
                    "nom_du_type": "ZF 6HP26",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 6,
                    "qualite_huile": "ATF 134",
                    "quantite_huile_l": 7,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "BMW",
                    "nom_du_type": "ZF 8HP45",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF 134",
                    "quantite_huile_l": 8,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "BMW",
                    "nom_du_type": "Steptronic 7G-Tronic",
                    "type_de_boite": TypeBoite.AUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "ATF 134",
                    "quantite_huile_l": 8,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },

                # Récentes boîtes semi-automatiques M
                {
                    "fabricant": "BMW",
                    "nom_du_type": "M Steptronic DCT",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 7,
                    "qualite_huile": "ATF 134",
                    "quantite_huile_l": 8,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },
                {
                    "fabricant": "BMW",
                    "nom_du_type": "M Steptronic DCT Gen2",
                    "type_de_boite": TypeBoite.SEMIAUTOMATIQUE,
                    "nombre_rapport": 8,
                    "qualite_huile": "ATF 134",
                    "quantite_huile_l": 8,
                    "kilometrage_boite": 0,
                    "intervalle_entretien_km": 60000,
                    "dernier_entretien": None,
                    "numero_boite": 1,
                    "voiture_modele": modele,
                    "voiture_exemplaire": None,
                },


            ]


            created_count = 0

            for data in boites_data:
                boite, created = VoitureBoite.objects.get_or_create(
                    fabricant=data["fabricant"],
                    nom_du_type=data["nom_du_type"],
                    numero_boite=data["numero_boite"],
                    voiture_modele=data["voiture_modele"],
                    voiture_exemplaire=data["voiture_exemplaire"],
                    defaults={
                        "type_de_boite": data["type_de_boite"],
                        "nombre_rapport": data["nombre_rapport"],
                        "qualite_huile": data["qualite_huile"],
                        "quantite_huile_l": data["quantite_huile_l"],
                        "kilometrage_boite": data["kilometrage_boite"],
                        "intervalle_entretien_km": data["intervalle_entretien_km"],
                        "dernier_entretien": data["dernier_entretien"],
                    }
                )

                if created:
                    created_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"{created_count} boîtes ajoutées pour le tenant '{tenant.schema_name}'"
        ))
