# Generated by Django 5.2.10 on 2026-05-04 10:41

import django.db.models.deletion
import maintenance.niveaux.models
import utils.mixin
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_particulier', '0008_remove_clientparticulier_societe_nom'),
        ('maindoeuvre', '0005_maindoeuvre_societe'),
        ('maintenance', '0006_alter_maintenance_kilometres_dernier_entretien'),
        ('proprietaire', '0006_alter_proprietaire_numero_compte'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemplacementBoite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis')),
                ('kilometres_boite', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilometres de la boite à remplacer')),
                ('type_utilisation', models.CharField(choices=[('societe', 'Société'), ('client', 'Client'), ('prive', 'Privé'), ('location', 'Location'), ('interne', 'Interne')], default='client', max_length=10)),
                ('kilometres_remplacement_boite', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres au remplacement de la boite')),
                ('variation_kilometres', models.PositiveIntegerField(default=0, editable=False, help_text='Calculé automatiquement : total - dernièr entretien', verbose_name='Variation de kilomètres depuis le dernier entretien')),
                ('remplacement_numero_boite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de série du moteur')),
                ('remplacement_nombre_boite', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Nombre de boite')),
                ('prix_boite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de la boite')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('boite_niveau_huile_etat', models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile")),
                ('boite_niveau_huile_quantite', models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name="Quantité d'huile ajoutée en litres")),
                ('boite_niveau_huile_qualite', models.CharField(choices=[('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile")),
                ('nombre_remplacements', models.PositiveIntegerField(default=0, editable=False)),
                ('remplacement_effectue', models.BooleanField(default=False, verbose_name='Remplacement effectué')),
                ('pays', models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=5)),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_boite', to='client_particulier.clientparticulier', verbose_name='Client')),
                ('main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_boite', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre")),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_boite', to='maintenance.maintenance')),
                ('proprietaires', models.ManyToManyField(blank=True, related_name='remplacements_boite', to='proprietaire.proprietairevoiture')),
                ('tech_last_maintained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_boite_maintained', to=settings.AUTH_USER_MODEL, verbose_name='Dernière maintenance effectuée par')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_boite', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_boite', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_boite', to='voiture_exemplaire.voitureexemplaire')),
            ],
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
