# Generated by Django 5.2.10 on 2026-05-01 07:38

import django.core.validators
import django.db.models.deletion
import maintenance.niveaux.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_particulier', '0004_clientparticulier_remarques_and_more'),
        ('maindoeuvre', '0005_maindoeuvre_societe'),
        ('niveaux', '0010_niveau_main_oeuvre'),
        ('proprietaire', '0005_proprietaire_created_at_proprietaire_date_naissance_and_more'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
        ('voiture_marque', '0002_voituremarque_societe'),
        ('voiture_modele', '0013_alter_voituremodele_created_at_and_more'),
        ('voiture_moteur', '0005_remove_moteurvoiture_kilometres_moteur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemplacementMoteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis')),
                ('immatriculation', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('numero_vin', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro VIN doit contenir exactement 17 caractères alphanumériques (lettres A-H, J-N, P, R-Z et chiffres).', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='Numéro VIN')),
                ('vin_simplifie', models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='VIN simplifié')),
                ('est_apres_2010', models.BooleanField(default=True)),
                ('annee_production', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Année de production')),
                ('mois_production', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('type_utilisation', models.CharField(choices=[('societe', 'Société'), ('client', 'Client'), ('prive', 'Privé'), ('location', 'Location'), ('interne', 'Interne')], default='client', max_length=10)),
                ('kilometres_dernier_entretien', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometres_moteur', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometres_remplacement_moteur', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres au remplacement moteur')),
                ('variation_kilometres', models.PositiveIntegerField(default=0, editable=False, help_text='Calculé automatiquement : total - dernièr entretien', verbose_name='Variationde kilomètres depuis le dernier entretien')),
                ('date_derniere_intervention', models.DateField(blank=True, null=True, verbose_name='Date de derniere entretien')),
                ('numero_moteur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de série du moteur')),
                ('nombre_moteur', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Nombre de moteur')),
                ('prix_moteur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix moteur')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('moteur_niveau_huile_etat', models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name="Niveau d'huile")),
                ('moteur_niveau_huile_quantite', models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name="Quantité d'huile ajoutée en litres")),
                ('moteur_niveau_huile_qualite', models.CharField(choices=[('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile")),
                ('refroidissement_etat', models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement')),
                ('refroidissement_quantite', models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name='Quantité de liquide de refroidissement ajoutée en litres')),
                ('refroidissement_qualite', models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité de liquide de refroidissement')),
                ('remplacement_effectue', models.BooleanField(default=False, verbose_name='Remplacement effectué')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('temps_minutes', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_moteur', to='client_particulier.clientparticulier', verbose_name='Client')),
                ('last_maintained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_moteur_maintained', to=settings.AUTH_USER_MODEL, verbose_name='Dernière maintenance effectuée par')),
                ('main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_moteur', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre")),
                ('niveaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remplacement_moteur', to='niveaux.niveau', verbose_name='Niveaux')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remplacement_moteur', to='proprietaire.proprietairevoiture')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societe.societe')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_moteur', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacement_moteur', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_moteur', to='voiture_exemplaire.voitureexemplaire')),
                ('voiture_marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remplacement_moteur', to='voiture_marque.voituremarque')),
                ('voiture_modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remplacement_moteur', to='voiture_modele.voituremodele')),
                ('voiture_moteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remplacement_moteur', to='voiture_moteur.moteurvoiture')),
            ],
        ),
    ]
