# Generated by Django 5.2.10 on 2026-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementboite',
            name='remplacement_numero_boite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de série de la boite'),
        ),
    ]
