# Generated by Django 5.2.10 on 2026-05-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0002_alter_remplacementboite_remplacement_numero_boite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementboite',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='75W', max_length=25, verbose_name="Qualité de l'huile"),
        ),
    ]
