# Generated by Django 5.2.10 on 2026-05-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0003_remove_remplacementmoteur_annee_production_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='temps_minutes',
        ),
    ]
