# Generated by Django 5.2.10 on 2026-05-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0003_alter_remplacementboite_boite_niveau_huile_etat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementboite',
            old_name='remplacement_nombre_boite',
            new_name='remplacement_boite_nombre',
        ),
        migrations.RenameField(
            model_name='remplacementboite',
            old_name='prix_boite',
            new_name='remplacement_boite_prix',
        ),
        migrations.RenameField(
            model_name='remplacementboite',
            old_name='remplacement_numero_boite',
            new_name='remplacement_boite_serie',
        ),
    ]
