# Generated by Django 5.2.10 on 2026-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0004_remove_remplacementmoteur_temps_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementmoteur',
            old_name='last_maintained_by',
            new_name='tech_last_maintained_by',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='voiture_marque',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='voiture_modele',
        ),
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='voiture_moteur',
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='kilometres_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilometres du moteur à remplacer'),
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='variation_kilometres',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculé automatiquement : total - dernièr entretien', verbose_name='Variation de kilomètres depuis le dernier entretien'),
        ),
    ]
