# Generated by Django 5.2.10 on 2026-05-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0004_rename_remplacement_nombre_boite_remplacementboite_remplacement_boite_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementboite',
            name='boite_niveau_huile_qualite',
        ),
        migrations.RemoveField(
            model_name='remplacementboite',
            name='type_utilisation',
        ),
    ]
