# Generated by Django 5.2.10 on 2026-05-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0005_rename_last_maintained_by_remplacementmoteur_tech_last_maintained_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='immatriculation',
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='kilometres_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
