# Generated by Django 5.2.10 on 2026-05-26 12:23

import maintenance.niveaux.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0005_remove_remplacementboite_boite_niveau_huile_qualite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementboite',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90')], default='75W', max_length=25, verbose_name="Qualité de l'huile"),
        ),
        migrations.AlterField(
            model_name='remplacementboite',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[maintenance.niveaux.models.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
    ]
