# Generated by Django 5.2.10 on 2026-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_moteur', '0006_remove_remplacementmoteur_immatriculation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementmoteur',
            name='niveaux',
        ),
        migrations.AlterField(
            model_name='remplacementmoteur',
            name='kilometres_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilometres du moteur à remplacer'),
        ),
    ]
