# Generated by Django 5.2.10 on 2026-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0006_alter_remplacementboite_boite_niveau_huile_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementboite',
            name='kilometres_boite',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometres de la boite à remplacer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remplacementboite',
            name='kilometres_remplacement_boite',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilomètres au remplacement de la boite'),
            preserve_default=False,
        ),
    ]
