# Generated by Django 5.2.10 on 2026-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0007_alter_remplacementboite_kilometres_boite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementboite',
            name='nombre_remplacements',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
