# Generated by Django 5.2.10 on 2026-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0008_alter_remplacementboite_nombre_remplacements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementboite',
            name='boite_niveau_huile_quantite',
        ),
        migrations.RemoveField(
            model_name='remplacementboite',
            name='nombre_remplacements',
        ),
        migrations.RemoveField(
            model_name='remplacementboite',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='remplacementboite',
            name='remplacement_effectue',
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='remplacement_boite_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Disque d'embrayage"),
        ),
    ]
