# Generated by Django 5.2.10 on 2026-07-16 13:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0009_remove_remplacementboite_boite_niveau_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='boite_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
    ]
