# Generated by Django 5.2.10 on 2026-07-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0010_remplacementboite_boite_niveau_huile_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='nombre_remplacements',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='pays',
            field=models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], default='BE', max_length=5),
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='remplacement_effectue',
            field=models.BooleanField(default=False, verbose_name='Remplacement effectué'),
        ),
    ]
