# Generated by Django 5.2.10 on 2026-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0011_remplacementboite_nombre_remplacements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remplacementboite',
            name='remplacement_boite_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Remplacement de la boite'),
        ),
    ]
