# Generated by Django 5.2.10 on 2026-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0014_alter_remplacementboite_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='niveau_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='MOBIL', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='niveau_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF_DSG', 'ATF DSG'), ('ATF_DCT', 'ATF DCT'), ('ATF_CVT', 'ATF CVT'), ('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('ATF_MERCON', 'ATF Mercon'), ('ATF_MERCON_V', 'ATF Mercon V'), ('ATF_MERCON_LV', 'ATF Mercon LV'), ('ATF_MULTI', 'ATF Multi Vehicle'), ('ATF_WS', 'ATF Toyota WS'), ('ATF_ZF_LIFEGUARD', 'ZF Lifeguard'), ('ATF_MOPAR', 'Mopar ATF+4'), ('ATF_AISIN', 'Aisin ATF'), ('ATF_MBV236', 'Mercedes MB 236.x'), ('ATF_VOLVO', 'Volvo ATF'), ('ATF_HONDA', 'Honda ATF DW-1'), ('ATF_NISSAN', 'Nissan Matic')], default='75W', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='remplacement_boite_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='remplacementboite',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
    ]
