# Generated by Django 5.2.10 on 2026-07-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0015_remplacementboite_niveau_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementboite',
            old_name='niveau_huile_qualite',
            new_name='Boite_niveau_huile_qualite',
        ),
        migrations.RenameField(
            model_name='remplacementboite',
            old_name='niveau_huile_fabricant',
            new_name='boite_niveau_huile_fabricant',
        ),
    ]
