# Generated by Django 5.2.10 on 2026-07-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0016_rename_niveau_huile_qualite_remplacementboite_boite_niveau_huile_qualite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remplacementboite',
            old_name='Boite_niveau_huile_qualite',
            new_name='boite_niveau_huile_qualite',
        ),
    ]
