# Generated by Django 5.2.10 on 2026-08-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0020_alter_remplacementboite_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='nombre_boites_montes',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Nombre de boites montées'),
        ),
        migrations.AlterField(
            model_name='remplacementboite',
            name='remplacement_boite_nombre',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Nombre de boite de remplacement'),
        ),
    ]
