# Generated by Django 5.2.10 on 2026-08-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0023_alter_remplacementboite_taux_horaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementboite',
            name='variation_kilometres',
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
