# Generated by Django 5.2.10 on 2026-08-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0024_remove_remplacementboite_variation_kilometres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementboite',
            name='kilometrage_variation',
        ),
        migrations.AddField(
            model_name='remplacementboite',
            name='variation_kilometres',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculé automatiquement : total - dernièr entretien', verbose_name='Variation de kilomètres depuis le dernier entretien'),
        ),
    ]
