# Generated by Django 5.2.10 on 2026-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0028_alter_remplacementboite_boite_niveau_huile_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
