# Generated by Django 5.2.10 on 2026-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0029_remplacementboite_kilometres_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='kilometres_rollback_boite',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
