# Generated by Django 5.2.10 on 2026-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0031_remplacementboite_kilometres_boite_rollback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='kilometres_remplacement',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres au moment du remplacement'),
        ),
        migrations.AlterField(
            model_name='remplacementboite',
            name='kilometres_boite_rollback',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Kilomètres rollback boite'),
        ),
    ]
