# Generated by Django 5.2.10 on 2026-09-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0032_remplacementboite_kilometres_remplacement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplacementboite',
            name='kilometres_remplacement_boite',
        ),
    ]
