# Generated by Django 5.2.10 on 2026-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplacement_boite', '0035_alter_remplacementboite_boite_niveau_huile_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplacementboite',
            name='remplacement_boite_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('ALFA_ROMEO', 'Alfa Romeo'), ('AUDI', 'Audi'), ('BMW', 'BMW'), ('CITROEN', 'Citroën'), ('FERRARI', 'Ferrari'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('MAZDA', 'Mazda'), ('MERCEDES', 'Mercedes-Benz'), ('MITSUBISHI', 'Mitsubishi'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('PEUGEOT', 'Peugeot'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('SUBARU', 'Subaru'), ('TOYOTA', 'Toyota'), ('VOLKSWAGEN', 'Volkswagen'), ('VOLVO', 'Volvo'), ('AISIN', 'Aisin'), ('ALLISON', 'Allison'), ('BORGWARNER', 'BorgWarner'), ('DANA', 'Dana'), ('EATON', 'Eaton'), ('GETRAG', 'Getrag (Magna)'), ('GRAZIANO', 'Graziano'), ('HYUNDAI_TRANSYS', 'Hyundai Transys'), ('JATCO', 'Jatco'), ('PUNCH', 'Punch Powertrain'), ('TREMEC', 'Tremec'), ('VOITH', 'Voith'), ('ZF', 'ZF'), ('ALBINS', 'Albins'), ('DRENTH', 'Drenth'), ('HEWLAND', 'Hewland'), ('HOLINGER', 'Holinger'), ('QUAIFE', 'Quaife'), ('RICARDO', 'Ricardo'), ('SADEV', 'Sadev'), ('SAMSONAS', 'Samsonas'), ('XTRAC', 'Xtrac'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='remplacementboite',
            name='remplacement_boite_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix'),
        ),
    ]
