# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outillage',
            fields=[
                ('id_outillage', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_htva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix HTVA')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('montant_calcule', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Montant calculé')),
                ('tva_a_recuperer', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='TVA à récupérer')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outillages', to='fournisseur.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Outillage',
                'verbose_name_plural': 'Outillages',
            },
        ),
    ]
