# Generated by Django 5.2.10 on 2026-03-13 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outillage', '0002_outillage_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='outillage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='outillage',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Mis à jour le'),
        ),
    ]
