# Generated by Django 5.2.10 on 2026-04-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outillage', '0003_outillage_created_at_outillage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='outillage',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
    ]
