# Generated by Django 5.2.10 on 2026-04-02 07:36

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0011_alter_voitureexemplaire_pays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleBteVitesseAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kilometrage_controle_boite_auto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du controle')),
                ('auto_emb_convertisseur_couple', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Convertisseur de couple')),
                ('auto_emb_embrayages_auto', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Embrayages automatiques')),
                ('pompes_huile', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Pompes à huile')),
                ('pompes_valves', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Valves de contrôle')),
                ('arbre_bte_torque', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Arbre de couple')),
                ('arbre_bte_secondaire_auto', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Arbre secondaire')),
                ('roulement_auto', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À vérifier / remplacer')], default='OK', max_length=25, verbose_name='Roulements internes')),
                ('huile_auto_quantite', models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres")),
                ('huile_auto_qualite', models.CharField(choices=[('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='ATF_III', max_length=25, verbose_name="Qualité de l'huile")),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_bte_vitesse_auto', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_bte_auto', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_bte_auto', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_bte_vitesse_auto', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres_checkup')),
            ],
            options={
                'verbose_name': 'Contrôle boite automatique',
                'verbose_name_plural': 'Contrôles boites automatiques',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
