# Generated by Django 5.2.10 on 2026-04-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0001_initial'),
        ('voiture_exemplaire', '0011_alter_voitureexemplaire_pays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlebtevitesseauto',
            options={'verbose_name': 'Contrôle boîte automatique', 'verbose_name_plural': 'Contrôles boîtes automatiques'},
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='kilometrage_controle_boite_auto',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du contrôle'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='tag',
            field=models.CharField(choices=[('WHITE', 'Blanc'), ('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='WHITE', max_length=10, verbose_name='État visuel / Tag'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_bte_vitesse_auto', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres checkup'),
        ),
    ]
