# Generated by Django 5.2.10 on 2026-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0002_alter_controlebtevitesseauto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
