# Generated by Django 5.2.10 on 2026-04-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0003_controlebtevitesseauto_created_at_and_more'),
        ('maindoeuvre', '0003_remove_maindoeuvre_temps_maindoeuvre_temps_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_bte_vitesse_auto', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
