# Generated by Django 5.2.10 on 2026-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0004_controlebtevitesseauto_main_oeuvre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilomètres chassis'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='WHITE', max_length=10, verbose_name='État visuel / Tag'),
        ),
    ]
