# Generated by Django 5.2.10 on 2026-05-26 12:23

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0005_alter_controlebtevitesseauto_kilometres_chassis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_secondaire_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Arbre secondaire'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_torque',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Arbre de couple'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='auto_emb_convertisseur_couple',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Convertisseur de couple'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='auto_emb_embrayages_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Embrayages automatiques'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='huile_auto_qualite',
            field=models.CharField(choices=[('ATF_III', 'ATF III'), ('ATF_DSG', 'ATF DSG'), ('ATF_DCT', 'ATF DCT'), ('ATF_CVT', 'ATF CVT'), ('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('ATF_MERCON', 'ATF Mercon'), ('ATF_MERCON_V', 'ATF Mercon V'), ('ATF_MERCON_LV', 'ATF Mercon LV'), ('ATF_MULTI', 'ATF Multi Vehicle'), ('ATF_WS', 'ATF Toyota WS'), ('ATF_ZF_LIFEGUARD', 'ZF Lifeguard'), ('ATF_MOPAR', 'Mopar ATF+4'), ('ATF_AISIN', 'Aisin ATF'), ('ATF_MBV236', 'Mercedes MB 236.x'), ('ATF_VOLVO', 'Volvo ATF'), ('ATF_HONDA', 'Honda ATF DW-1'), ('ATF_NISSAN', 'Nissan Matic')], default='ATF_III', max_length=25, verbose_name="Qualité de l'huile"),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='huile_auto_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.StepValueValidator(0.1)],verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='pompes_huile',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pompes à huile'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='pompes_valves',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Valves de contrôle'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='roulement_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Roulements internes'),
        ),
    ]
