# Generated by Django 5.2.10 on 2026-05-26 12:59

import maintenance.niveaux.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0006_alter_controlebtevitesseauto_arbre_bte_secondaire_auto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlebtevitesseauto',
            old_name='huile_auto_qualite',
            new_name='huile_auto_niveau_qualite',
        ),
        migrations.RemoveField(
            model_name='controlebtevitesseauto',
            name='huile_auto_quantite',
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='huile_auto_niveau_quantite',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
    ]
