# Generated by Django 5.2.10 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0007_rename_huile_auto_qualite_controlebtevitesseauto_huile_auto_niveau_qualite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
