# Generated by Django 5.2.10 on 2026-06-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0008_alter_controlebtevitesseauto_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='kilometrage_controle_boite_auto',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du contrôle'),
            preserve_default=False,
        ),
    ]
