# Generated by Django 5.2.10 on 2026-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0010_controlebtevitesseauto_taux_horaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlebtevitesseauto',
            name='huile_auto_niveau_qualite',
        ),
        migrations.RemoveField(
            model_name='controlebtevitesseauto',
            name='huile_auto_niveau_quantite',
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_secondaire_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_secondaire_auto_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_torque_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_torque_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='auto_emb_convertisseur_couple_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='auto_emb_convertisseur_couple_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='auto_emb_embrayages_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='auto_emb_embrayages_auto_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pompes_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pompes_huile_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pompes_valves_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pompes_valves_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='roulement_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='roulement_auto_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
