# Generated by Django 5.2.10 on 2026-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0018_alter_controlebtevitesseauto_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
