# Generated by Django 5.2.10 on 2026-08-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0019_controlebtevitesseauto_kilometrage_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlebtevitesseauto',
            old_name='pompes_huile',
            new_name='pompes_h',
        ),
        migrations.RenameField(
            model_name='controlebtevitesseauto',
            old_name='pompes_huile_prix',
            new_name='pompes_h_prix',
        ),
        migrations.RenameField(
            model_name='controlebtevitesseauto',
            old_name='pompes_huile_quantite',
            new_name='pompes_h_quantite',
        ),
    ]
