# Generated by Django 5.2.10 on 2026-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0020_rename_pompes_huile_controlebtevitesseauto_pompes_h_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlebtevitesseauto',
            old_name='auto_emb_embrayages_auto_prix',
            new_name='double_embrayage_prix',
        ),
        migrations.RenameField(
            model_name='controlebtevitesseauto',
            old_name='auto_emb_embrayages_auto_quantite',
            new_name='double_embrayage_quantite',
        ),
        migrations.RemoveField(
            model_name='controlebtevitesseauto',
            name='auto_emb_embrayages_auto',
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='double_embrayage_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Double embrayage'),
        ),
    ]
