# Generated by Django 5.2.10 on 2026-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0021_rename_auto_emb_embrayages_auto_prix_controlebtevitesseauto_double_embrayage_prix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlebtevitesseauto',
            name='double_embrayage_auto',
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='auto_emb_convertisseur_couple_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LUK', 'LuK / Schaeffler'), ('SACHS', 'SACHS / ZF'), ('VALEO', 'Valeo'), ('EXEDY', 'EXEDY'), ('AISIN', 'AISIN'), ('FCC', 'F.C.C.'), ('BORGWARNER', 'BorgWarner'), ('EATON', 'Eaton'), ('TWIN_DISC', 'Twin Disc'), ('SETCO', 'Setco Automotive'), ('TIELIU', 'Zhejiang Tieliu'), ('RAICAM', 'Raicam'), ('NISSIN', 'Nissin'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CONTINENTAL', 'Continental'), ('NSK', 'NSK'), ('FCC_JAPAN', 'FCC Japan'), ('AP_RACING', 'AP Racing'), ('TILTON', 'Tilton Engineering'), ('OS_GIKEN', 'OS Giken'), ('ACT', 'ACT (Advanced Clutch Technology)'), ('SPEC', 'SPEC Clutch'), ('CENTERFORCE', 'Centerforce'), ('CLUTCH_MASTERS', 'Clutch Masters'), ('COMPETITION_CLUTCH', 'Competition Clutch'), ('HELIX', 'Helix Autosport'), ('MANTIC', 'Mantic Clutch'), ('QUARTER_MASTER', 'Quarter Master'), ('MCLEOD', 'McLeod Racing'), ('HAYS', 'Hays Clutches'), ('RAM', 'RAM Clutches'), ('SOUTH_BEND', 'South Bend Clutch'), ('XTREME', 'Xtreme Clutch'), ('DKM', 'DKM Clutch'), ('FIDANZA', 'Fidanza'), ('CARBONETIC', 'Carbonetic'), ('NPC', 'NPC Performance Clutches'), ('HKS', 'HKS'), ('CUSCO', 'CUSCO'), ('ORC', 'Ogura Racing Clutch (ORC)'), ('ATS', 'ATS'), ('NISMO', 'NISMO'), ('TRD', 'TRD'), ('STI', 'STI'), ('TODA', 'Toda Racing'), ('JUN', 'JUN Auto'), ('GREDDY', 'GReddy / TRUST'), ('BLUE_PRINT', 'Blue Print'), ('FEBI', 'febi bilstein'), ('MEYLE', 'MEYLE'), ('MAPCO', 'MAPCO'), ('RIDEX', 'RIDEX'), ('STARK', 'STARK'), ('NK', 'NK'), ('JP_GROUP', 'JP Group'), ('MAXGEAR', 'MAXGEAR'), ('KAMOKA', 'KAMOKA'), ('DENCKERMANN', 'Denckermann'), ('STATIM', 'STATIM'), ('MECARM', 'MECARM'), ('KAWE', 'KAWE'), ('NATIONAL', 'National'), ('BORG_BECK', 'Borg & Beck'), ('QH', 'Quinton Hazell'), ('LPR', 'LPR'), ('FAST', 'FAST'), ('SAMKO', 'SAMKO'), ('STARLINE', 'Starline'), ('ASHIKA', 'ASHIKA'), ('JAPANPARTS', 'Japanparts'), ('JAPKO', 'JAPKO'), ('KNORR_BREMSE', 'Knorr-Bremse'), ('WABCO', 'WABCO / ZF'), ('HAMMER', 'Hammer Kupplungen'), ('LIPE', 'LIPE Clutch'), ('CEI', 'CEI'), ('EURORICAMBI', 'Euroricambi'), ('BMW', 'BMW Original'), ('MINI', 'MINI Original'), ('MERCEDES', 'Mercedes-Benz Original'), ('AUDI', 'Audi Original'), ('VOLKSWAGEN', 'Volkswagen Original'), ('PORSCHE', 'Porsche Original'), ('FORD', 'Ford Original'), ('OPEL', 'Opel Original'), ('PEUGEOT', 'Peugeot Original'), ('CITROEN', 'Citroën Original'), ('RENAULT', 'Renault Original'), ('DACIA', 'Dacia Original'), ('FIAT', 'Fiat Original'), ('ALFA_ROMEO', 'Alfa Romeo Original'), ('LANCIA', 'Lancia Original'), ('VOLVO', 'Volvo Original'), ('TOYOTA', 'Toyota Original'), ('LEXUS', 'Lexus Original'), ('HONDA', 'Honda Original'), ('NISSAN', 'Nissan Original'), ('MAZDA', 'Mazda Original'), ('SUBARU', 'Subaru Original'), ('MITSUBISHI', 'Mitsubishi Original'), ('SUZUKI', 'Suzuki Original'), ('HYUNDAI', 'Hyundai Original'), ('KIA', 'Kia Original'), ('LAND_ROVER', 'Land Rover Original'), ('JAGUAR', 'Jaguar Original'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=25, verbose_name='Convertisseur de couple'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='double_embrayage',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Double embrayage'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='double_embrayage_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LUK', 'LuK / Schaeffler'), ('SACHS', 'SACHS / ZF'), ('VALEO', 'Valeo'), ('EXEDY', 'EXEDY'), ('AISIN', 'AISIN'), ('FCC', 'F.C.C.'), ('BORGWARNER', 'BorgWarner'), ('EATON', 'Eaton'), ('TWIN_DISC', 'Twin Disc'), ('SETCO', 'Setco Automotive'), ('TIELIU', 'Zhejiang Tieliu'), ('RAICAM', 'Raicam'), ('NISSIN', 'Nissin'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CONTINENTAL', 'Continental'), ('NSK', 'NSK'), ('FCC_JAPAN', 'FCC Japan'), ('AP_RACING', 'AP Racing'), ('TILTON', 'Tilton Engineering'), ('OS_GIKEN', 'OS Giken'), ('ACT', 'ACT (Advanced Clutch Technology)'), ('SPEC', 'SPEC Clutch'), ('CENTERFORCE', 'Centerforce'), ('CLUTCH_MASTERS', 'Clutch Masters'), ('COMPETITION_CLUTCH', 'Competition Clutch'), ('HELIX', 'Helix Autosport'), ('MANTIC', 'Mantic Clutch'), ('QUARTER_MASTER', 'Quarter Master'), ('MCLEOD', 'McLeod Racing'), ('HAYS', 'Hays Clutches'), ('RAM', 'RAM Clutches'), ('SOUTH_BEND', 'South Bend Clutch'), ('XTREME', 'Xtreme Clutch'), ('DKM', 'DKM Clutch'), ('FIDANZA', 'Fidanza'), ('CARBONETIC', 'Carbonetic'), ('NPC', 'NPC Performance Clutches'), ('HKS', 'HKS'), ('CUSCO', 'CUSCO'), ('ORC', 'Ogura Racing Clutch (ORC)'), ('ATS', 'ATS'), ('NISMO', 'NISMO'), ('TRD', 'TRD'), ('STI', 'STI'), ('TODA', 'Toda Racing'), ('JUN', 'JUN Auto'), ('GREDDY', 'GReddy / TRUST'), ('BLUE_PRINT', 'Blue Print'), ('FEBI', 'febi bilstein'), ('MEYLE', 'MEYLE'), ('MAPCO', 'MAPCO'), ('RIDEX', 'RIDEX'), ('STARK', 'STARK'), ('NK', 'NK'), ('JP_GROUP', 'JP Group'), ('MAXGEAR', 'MAXGEAR'), ('KAMOKA', 'KAMOKA'), ('DENCKERMANN', 'Denckermann'), ('STATIM', 'STATIM'), ('MECARM', 'MECARM'), ('KAWE', 'KAWE'), ('NATIONAL', 'National'), ('BORG_BECK', 'Borg & Beck'), ('QH', 'Quinton Hazell'), ('LPR', 'LPR'), ('FAST', 'FAST'), ('SAMKO', 'SAMKO'), ('STARLINE', 'Starline'), ('ASHIKA', 'ASHIKA'), ('JAPANPARTS', 'Japanparts'), ('JAPKO', 'JAPKO'), ('KNORR_BREMSE', 'Knorr-Bremse'), ('WABCO', 'WABCO / ZF'), ('HAMMER', 'Hammer Kupplungen'), ('LIPE', 'LIPE Clutch'), ('CEI', 'CEI'), ('EURORICAMBI', 'Euroricambi'), ('BMW', 'BMW Original'), ('MINI', 'MINI Original'), ('MERCEDES', 'Mercedes-Benz Original'), ('AUDI', 'Audi Original'), ('VOLKSWAGEN', 'Volkswagen Original'), ('PORSCHE', 'Porsche Original'), ('FORD', 'Ford Original'), ('OPEL', 'Opel Original'), ('PEUGEOT', 'Peugeot Original'), ('CITROEN', 'Citroën Original'), ('RENAULT', 'Renault Original'), ('DACIA', 'Dacia Original'), ('FIAT', 'Fiat Original'), ('ALFA_ROMEO', 'Alfa Romeo Original'), ('LANCIA', 'Lancia Original'), ('VOLVO', 'Volvo Original'), ('TOYOTA', 'Toyota Original'), ('LEXUS', 'Lexus Original'), ('HONDA', 'Honda Original'), ('NISSAN', 'Nissan Original'), ('MAZDA', 'Mazda Original'), ('SUBARU', 'Subaru Original'), ('MITSUBISHI', 'Mitsubishi Original'), ('SUZUKI', 'Suzuki Original'), ('HYUNDAI', 'Hyundai Original'), ('KIA', 'Kia Original'), ('LAND_ROVER', 'Land Rover Original'), ('JAGUAR', 'Jaguar Original'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=25, verbose_name='Double embrayage'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_secondaire_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Arbre secondaire'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_torque',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Arbre de couple'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='auto_emb_convertisseur_couple',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Convertisseur de couple'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='huile_bte_auto_vitesse',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Huile de boite de vitesse'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='pompes_h',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pompes à huile'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='pompes_valves',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Valves de contrôle'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='roulement_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Roulements internes'),
        ),
    ]
