# Generated by Django 5.2.10 on 2026-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0024_controlebtevitesseauto_serrage_roues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_secondaire_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='arbre_bte_torque_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='auto_emb_convertisseur_couple_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='double_embrayage_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='pompes_h_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='pompes_valves_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='roulement_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
