# Generated by Django 5.2.10 on 2026-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0025_alter_controlebtevitesseauto_arbre_bte_secondaire_auto_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_entree_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Arbre d'entrée"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_entree_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_entree_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_sortie_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Arbre de sortie'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_sortie_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='arbre_sortie_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bagues_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Bagues de boîte automatique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bagues_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bagues_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bandes_frein_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Bandes de frein'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bandes_frein_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bandes_frein_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bloc_hydraulique',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Bloc hydraulique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bloc_hydraulique_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='bloc_hydraulique_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='calculateur_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Calculateur de boîte automatique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='calculateur_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='calculateur_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_position_selecteur_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Capteur de position du sélecteur'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_position_selecteur_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_position_selecteur_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_pression_huile_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Capteur de pression d'huile"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_pression_huile_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_pression_huile_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_temperature_huile_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Capteur de température d'huile"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_temperature_huile_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_temperature_huile_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_vitesse_entree_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Capteur de vitesse d'entrée"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_vitesse_entree_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_vitesse_entree_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_vitesse_sortie_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Capteur de vitesse de sortie'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_vitesse_sortie_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='capteur_vitesse_sortie_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='carter_huile_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Carter d'huile de boîte"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='carter_huile_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='carter_huile_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='connecteur_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Connecteur électrique de boîte'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='connecteur_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='connecteur_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='couronne_epicycloidale',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Couronne du train épicycloïdal'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='couronne_epicycloidale_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='couronne_epicycloidale_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='crepine_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Crépine de boîte automatique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='crepine_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='crepine_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='differentiel_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Différentiel'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='differentiel_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='differentiel_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='disques_acier_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Disques acier d'embrayage"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='disques_acier_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='disques_acier_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='disques_embrayage_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Disques d'embrayage internes"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='disques_embrayage_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='disques_embrayage_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='durites_huile_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Durites d'huile de boîte"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='durites_huile_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='durites_huile_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='echangeur_huile_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Échangeur d'huile de boîte"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='echangeur_huile_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='echangeur_huile_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='electrovannes',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Électrovannes'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='electrovannes_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='electrovannes_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='embrayages_internes_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Embrayages internes'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='embrayages_internes_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='embrayages_internes_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='faisceau_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Faisceau électrique de boîte'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='faisceau_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='faisceau_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='filtre_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Filtre de boîte automatique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='filtre_boite_auto_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('LUK', 'LuK / Schaeffler'), ('SACHS', 'SACHS / ZF'), ('VALEO', 'Valeo'), ('EXEDY', 'EXEDY'), ('AISIN', 'AISIN'), ('FCC', 'F.C.C.'), ('BORGWARNER', 'BorgWarner'), ('EATON', 'Eaton'), ('TWIN_DISC', 'Twin Disc'), ('SETCO', 'Setco Automotive'), ('TIELIU', 'Zhejiang Tieliu'), ('RAICAM', 'Raicam'), ('NISSIN', 'Nissin'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('CONTINENTAL', 'Continental'), ('NSK', 'NSK'), ('FCC_JAPAN', 'FCC Japan'), ('AP_RACING', 'AP Racing'), ('TILTON', 'Tilton Engineering'), ('OS_GIKEN', 'OS Giken'), ('ACT', 'ACT (Advanced Clutch Technology)'), ('SPEC', 'SPEC Clutch'), ('CENTERFORCE', 'Centerforce'), ('CLUTCH_MASTERS', 'Clutch Masters'), ('COMPETITION_CLUTCH', 'Competition Clutch'), ('HELIX', 'Helix Autosport'), ('MANTIC', 'Mantic Clutch'), ('QUARTER_MASTER', 'Quarter Master'), ('MCLEOD', 'McLeod Racing'), ('HAYS', 'Hays Clutches'), ('RAM', 'RAM Clutches'), ('SOUTH_BEND', 'South Bend Clutch'), ('XTREME', 'Xtreme Clutch'), ('DKM', 'DKM Clutch'), ('FIDANZA', 'Fidanza'), ('CARBONETIC', 'Carbonetic'), ('NPC', 'NPC Performance Clutches'), ('HKS', 'HKS'), ('CUSCO', 'CUSCO'), ('ORC', 'Ogura Racing Clutch (ORC)'), ('ATS', 'ATS'), ('NISMO', 'NISMO'), ('TRD', 'TRD'), ('STI', 'STI'), ('TODA', 'Toda Racing'), ('JUN', 'JUN Auto'), ('GREDDY', 'GReddy / TRUST'), ('BLUE_PRINT', 'Blue Print'), ('FEBI', 'febi bilstein'), ('MEYLE', 'MEYLE'), ('MAPCO', 'MAPCO'), ('RIDEX', 'RIDEX'), ('STARK', 'STARK'), ('NK', 'NK'), ('JP_GROUP', 'JP Group'), ('MAXGEAR', 'MAXGEAR'), ('KAMOKA', 'KAMOKA'), ('DENCKERMANN', 'Denckermann'), ('STATIM', 'STATIM'), ('MECARM', 'MECARM'), ('KAWE', 'KAWE'), ('NATIONAL', 'National'), ('BORG_BECK', 'Borg & Beck'), ('QH', 'Quinton Hazell'), ('LPR', 'LPR'), ('FAST', 'FAST'), ('SAMKO', 'SAMKO'), ('STARLINE', 'Starline'), ('ASHIKA', 'ASHIKA'), ('JAPANPARTS', 'Japanparts'), ('JAPKO', 'JAPKO'), ('KNORR_BREMSE', 'Knorr-Bremse'), ('WABCO', 'WABCO / ZF'), ('HAMMER', 'Hammer Kupplungen'), ('LIPE', 'LIPE Clutch'), ('CEI', 'CEI'), ('EURORICAMBI', 'Euroricambi'), ('BMW', 'BMW Original'), ('MINI', 'MINI Original'), ('MERCEDES', 'Mercedes-Benz Original'), ('AUDI', 'Audi Original'), ('VOLKSWAGEN', 'Volkswagen Original'), ('PORSCHE', 'Porsche Original'), ('FORD', 'Ford Original'), ('OPEL', 'Opel Original'), ('PEUGEOT', 'Peugeot Original'), ('CITROEN', 'Citroën Original'), ('RENAULT', 'Renault Original'), ('DACIA', 'Dacia Original'), ('FIAT', 'Fiat Original'), ('ALFA_ROMEO', 'Alfa Romeo Original'), ('LANCIA', 'Lancia Original'), ('VOLVO', 'Volvo Original'), ('TOYOTA', 'Toyota Original'), ('LEXUS', 'Lexus Original'), ('HONDA', 'Honda Original'), ('NISSAN', 'Nissan Original'), ('MAZDA', 'Mazda Original'), ('SUBARU', 'Subaru Original'), ('MITSUBISHI', 'Mitsubishi Original'), ('SUZUKI', 'Suzuki Original'), ('HYUNDAI', 'Hyundai Original'), ('KIA', 'Kia Original'), ('LAND_ROVER', 'Land Rover Original'), ('JAGUAR', 'Jaguar Original'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='filtre_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='filtre_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='freins_internes_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Freins internes'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='freins_internes_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='freins_internes_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joint_carter_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Joint de carter de boîte'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joint_carter_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joint_carter_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_pistons_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Joints de pistons'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_pistons_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_pistons_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_spi_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Joints spi de boîte'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_spi_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_spi_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_toriques_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Joints toriques de boîte'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_toriques_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='joints_toriques_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='mecatronique',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Unité mécatronique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='mecatronique_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='mecatronique_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignon_planetaire',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pignon planétaire'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignon_planetaire_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignon_planetaire_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_differentiel_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pignons de différentiel'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_differentiel_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_differentiel_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_internes_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pignons internes'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_internes_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_internes_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_satellites',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pignons satellites'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_satellites_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pignons_satellites_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pistons_embrayage_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Pistons d'embrayage"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pistons_embrayage_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pistons_embrayage_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pompe_hydraulique_boite',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pompe hydraulique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pompe_hydraulique_boite_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='pompe_hydraulique_boite_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='porte_satellites',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Porte-satellites'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='porte_satellites_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='porte_satellites_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='roue_libre_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Roue libre'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='roue_libre_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='roue_libre_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='selecteur_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Sélecteur de boîte'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='selecteur_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='selecteur_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='solenoides',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Solénoïdes'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='solenoides_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='solenoides_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='supports_boite_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Supports de boîte automatique'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='supports_boite_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='supports_boite_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='tambours_embrayage_auto',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="Tambours d'embrayage"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='tambours_embrayage_auto_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='tambours_embrayage_auto_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='train_epicycloidal',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Train épicycloïdal'),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='train_epicycloidal_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='train_epicycloidal_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
