# Generated by Django 5.2.10 on 2026-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0028_remove_controlebtevitesseauto_arbre_entree_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebtevitesseauto',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
