# Generated by Django 5.2.10 on 2026-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0031_controlebtevitesseauto_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='huile_bte_auto_vitesse_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CASTROL', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='huile_bte_auto_vitesse_qualite',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('ATF_III', 'ATF III'), ('ATF_DSG', 'ATF DSG'), ('ATF_DCT', 'ATF DCT'), ('ATF_CVT', 'ATF CVT'), ('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('ATF_MERCON', 'ATF Mercon'), ('ATF_MERCON_V', 'ATF Mercon V'), ('ATF_MERCON_LV', 'ATF Mercon LV'), ('ATF_MULTI', 'ATF Multi Vehicle'), ('ATF_WS', 'ATF Toyota WS'), ('ATF_ZF_LIFEGUARD', 'ZF Lifeguard'), ('ATF_MOPAR', 'Mopar ATF+4'), ('ATF_AISIN', 'Aisin ATF'), ('ATF_MBV236', 'Mercedes MB 236.x'), ('ATF_VOLVO', 'Volvo ATF'), ('ATF_HONDA', 'Honda ATF DW-1'), ('ATF_NISSAN', 'Nissan Matic')], default='ATF_III', max_length=25, verbose_name="Qualité de l'huile"),
        ),
    ]
