# Generated by Django 5.2.10 on 2026-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bte_vitesse_auto', '0034_controlebtevitesseauto_arbre_bte_secondaire_auto_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebtevitesseauto',
            name='huile_bte_auto_vitesse',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Huile de boîte de vitesse'),
        ),
    ]
