# Generated by Django 5.2.10 on 2026-02-14 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_compagnie', models.CharField(max_length=100, verbose_name='Nom de la compagnie')),
                ('courtier_nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du courtier')),
                ('courier_prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom du courtier')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('peppol_id', models.CharField(blank=True, help_text='Identifiant Peppol, ex : 0208:BE0123456789', max_length=50, null=True, verbose_name='Identifiant Peppol')),
            ],
            options={
                'verbose_name': 'Carrosserie',
                'verbose_name_plural': 'Carrosseries',
            },
        ),
    ]
