# Generated by Django 5.2.10 on 2026-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_alter_assurance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='nom_compagnie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la compagnie'),
        ),
    ]
