# Generated by Django 5.2.10 on 2026-02-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0005_assurance_created_at_assurance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='numero_iban',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
