# Generated by Django 5.2.10 on 2026-02-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0004_adresse_unique_adresse_par_societe'),
        ('assurance', '0007_alter_assurance_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assurances', to='adresse.adresse'),
        ),
    ]
