# Generated by Django 5.2.10 on 2026-03-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0008_alter_assurance_adresse'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assureur', to='societe.societe'),
        ),
    ]
