# Generated by Django 5.2.10 on 2026-09-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0007_adresse_societe'),
        ('assurance', '0010_assurance_remarques_alter_assurance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assurances', to='adresse.adresse'),
        ),
    ]
