# Generated by Django 5.2.10 on 2026-02-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleBruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière'), ('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit')], max_length=10, verbose_name='Emplacement')),
                ('type_bruit', models.CharField(choices=[('ROULEMENT_ROUE', 'Roulement de roue'), ('ROULEMENT_SUSPENSION', 'Roulement de suspension'), ('MOTEUR', 'Moteur'), ('BOITE_VITESSE', 'Boîte de vitesse'), ('PONT', 'Pont')], max_length=30, verbose_name='Type de bruit')),
                ('niveau_bruit', models.CharField(choices=[('NORMAL', 'Normal'), ('ANORMAL', 'Anormal')], default='NORMAL', max_length=10, verbose_name='Niveau de bruit')),
                ('commentaire', models.TextField(blank=True, verbose_name='Observation')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='VERT', max_length=10, verbose_name='Tag')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
