# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrosserie',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('cote', models.CharField(blank=True, choices=[('GA', 'Gauche'), ('DR', 'Droit')], max_length=2, null=True)),
                ('emplacement', models.CharField(blank=True, choices=[('AV', 'Avant'), ('AR', 'Arrière')], max_length=2, null=True)),
                ('libelle', models.CharField(choices=[('PARE_CHOCS', 'Pare-chocs'), ('BOUCLIER', 'Bouclier'), ('PARE_BRIS', 'Pare-brise'), ('VITRE_PORTE', 'Vitres de porte'), ('LUNETTE', 'Lunette'), ('RETROVISEUR', 'Rétroviseur'), ('AILE', 'Aile'), ('ELARG_AILE', 'Élargisseur d’aile'), ('BAS_CAISSE', 'Bas de caisse'), ('SUPP_RAD', 'Support de radiateur'), ('SUPP_PC', 'Support de pare-chocs'), ('PORTE', 'Porte'), ('POIGNEE', 'Poignée de porte'), ('COFFRE', 'Coffre / hayon'), ('JOINT_COFFRE', 'Joint de coffre'), ('JOINT_PORTE', 'Joint de porte'), ('COQUILLE', 'Coquille d’aile'), ('CLIPS', 'Clips'), ('VISSERIE', 'Visserie'), ('CAPOT', 'Capot')], max_length=30)),
                ('code_peinture', models.CharField(blank=True, max_length=50)),
                ('quantite_peinture_l', models.FloatField(default=0.0)),
                ('vernis', models.CharField(blank=True, max_length=50)),
                ('quantite_vernis_l', models.FloatField(default=0.0)),
                ('temps_h', models.FloatField(default=0.0, help_text="Temps de main d'oeuvre en heures")),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Pièce carrosserie',
                'verbose_name_plural': 'Pièces carrosserie',
            },
            bases=('piece.piece',),
        ),
    ]
