# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('piece_boite', '0001_initial'),
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrayage',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_embrayage', models.CharField(choices=[('SIMPLE_DISQUE', 'Embrayage simple disque'), ('DOUBLE_DISQUE', 'Embrayage double disque'), ('HYDRAULIQUE', 'Embrayage hydraulique')], max_length=20, verbose_name="Type d'embrayage")),
                ('disque', models.CharField(blank=True, max_length=255, null=True, verbose_name="Disque d'embrayage")),
                ('plateau', models.CharField(blank=True, max_length=255, null=True, verbose_name="Plateau d'embrayage")),
                ('butee', models.CharField(blank=True, max_length=255, null=True, verbose_name="Butée d'embrayage")),
                ('composants', models.JSONField(default=list, help_text='Liste des composants présents dans cet embrayage', verbose_name='Composants')),
                ('boites_mecaniques', models.ManyToManyField(blank=True, related_name='embrayages', to='piece_boite.boitemecanique', verbose_name='Boîtes mécaniques compatibles')),
                ('moteurs_compatibles', models.ManyToManyField(blank=True, related_name='embrayages', to='voiture_moteur.moteurvoiture')),
            ],
            options={
                'verbose_name': 'Embrayage',
                'verbose_name_plural': 'Embrayages',
            },
            bases=('piece.piece',),
        ),
    ]
