# Generated by Django 5.2.10 on 2026-02-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanicien',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('utilisateurs.utilisateur',),
        ),
    ]
