# Generated by Django 5.2.10 on 2026-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicien', '0002_chefmecanicien'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChefMecanicien',
        ),
    ]
