# Generated by Django 5.2.10 on 2026-05-02 09:04

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maindoeuvre', '0005_maindoeuvre_societe'),
        ('maintenance', '0006_alter_maintenance_kilometres_dernier_entretien'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis')),
                ('kilometres_turbo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du controle')),
                ('jeu_axe_turbo', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Jeu dans l'axe de turbo")),
                ('etat_turbine_admission', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='État de la turbine côté admission')),
                ('etat_turbine_echappement', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='État de la turbine côté échappement')),
                ('fuites_huile_turbo', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Fuites d'huile au niveau de la turbine")),
                ('fonctionnement_geometrie_variable', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Fonctionnement de la géometrie variable')),
                ('fonctionnement_electrovalve', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Fonctionnement de l'électro-valve")),
                ('turbo', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Turbo à remplacer')),
                ('turbo_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turbo_quantite', models.IntegerField(default=0)),
                ('intercooler', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Intercooler')),
                ('intercooler_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('intercooler_quantite', models.IntegerField(default=0)),
                ('electrovanne', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Electro-valve')),
                ('electrovanne_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electrovanne_quantite', models.IntegerField(default=0)),
                ('joints', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Joints')),
                ('joints_prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joints_quantite', models.IntegerField(default=0)),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turbo', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre")),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turbo', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turbo', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turbo', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turbo', to='voiture_exemplaire.voitureexemplaire', verbose_name='Turbo')),
            ],
            options={
                'verbose_name': 'Turbo',
                'verbose_name_plural': 'Turbos',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
