# Generated by Django 5.2.10 on 2026-05-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turbo',
            old_name='fuites_huile_turbo',
            new_name='fuites_huile_tur',
        ),
        migrations.RenameField(
            model_name='turbo',
            old_name='jeu_axe_turbo',
            new_name='jeu_axe_tur',
        ),
    ]
