# Generated by Django 5.2.10 on 2026-05-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0002_rename_fuites_huile_turbo_turbo_fuites_huile_tur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turbo',
            old_name='turbo',
            new_name='turbos',
        ),
        migrations.RenameField(
            model_name='turbo',
            old_name='turbo_prix',
            new_name='turbos_prix',
        ),
        migrations.RenameField(
            model_name='turbo',
            old_name='turbo_quantite',
            new_name='turbos_quantite',
        ),
    ]
