# Generated by Django 5.2.10 on 2026-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0003_rename_turbo_turbo_turbos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turbo',
            name='fonctionnement_electrovalve',
        ),
        migrations.AlterField(
            model_name='turbo',
            name='electrovanne',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Electro-vanne'),
        ),
    ]
