# Generated by Django 5.2.10 on 2026-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0004_remove_turbo_fonctionnement_electrovalve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbo',
            name='kilometres_turbo',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du controle'),
            preserve_default=False,
        ),
    ]
