# Generated by Django 5.2.10 on 2026-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0005_alter_turbo_kilometres_turbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbo',
            name='electrovanne',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Electro-vanne'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='etat_turbine_admission',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État de la turbine côté admission'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='etat_turbine_echappement',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État de la turbine côté échappement'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='fonctionnement_geometrie_variable',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fonctionnement de la géometrie variable'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='fuites_huile_tur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Fuites d'huile au niveau de la turbine"),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='intercooler',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Intercooler'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='jeu_axe_tur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Jeu dans l'axe de turbo"),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='joints',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Joints'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='turbos',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Turbo à remplacer'),
        ),
    ]
