# Generated by Django 5.2.10 on 2026-08-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0010_turbo_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbo',
            name='electrovanne_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DENSO', 'Denso'), ('NGK', 'NGK / NTK'), ('DELPHI', 'Delphi'), ('HELLA', 'Hella'), ('VDO', 'VDO'), ('CONTINENTAL', 'Continental'), ('PIERBURG', 'Pierburg'), ('FACET', 'Facet'), ('FEBI', 'Febi Bilstein'), ('MEYLE', 'Meyle'), ('VEMO', 'Vemo'), ('ERA', 'ERA'), ('FAE', 'FAE'), ('EPS', 'EPS'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('HITACHI', 'Hitachi'), ('VALEO', 'Valeo'), ('WALKER', 'Walker Products'), ('SIDAT', 'SIDAT'), ('METZGER', 'Metzger'), ('TOPRAN', 'Topran'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='turbo',
            name='intercooler_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('MAHLE', 'MAHLE'), ('BEHR', 'Behr'), ('VALEO', 'Valeo'), ('DENSO', 'Denso'), ('DELPHI', 'Delphi'), ('MODINE', 'Modine'), ('HANON', 'Hanon Systems'), ('SANDEN', 'Sanden'), ('MARELLI', 'Marelli'), ('NRF', 'NRF'), ('NISSENS', 'Nissens'), ('AVA', 'AVA Cooling Systems'), ('KOYORAD', 'Koyorad'), ('TYC', 'TYC'), ('GARRETT', 'Garrett'), ('BORGWARNER', 'BorgWarner'), ('MITSUBISHI', 'Mitsubishi'), ('IHI', 'IHI'), ('WAGNER_TUNING', 'Wagner Tuning'), ('MISHIMOTO', 'Mishimoto'), ('FORGE', 'Forge Motorsport'), ('AIRTEC', 'AIRTEC Motorsport'), ('DO88', 'do88'), ('CSF', 'CSF'), ('PWR', 'PWR'), ('PROALLOY', 'Pro Alloy'), ('TURBOSMART', 'Turbosmart'), ('AMS', 'AMS Performance'), ('APR', 'APR'), ('CTS_TURBO', 'CTS Turbo'), ('DINAN', 'Dinan'), ('COBB', 'COBB Tuning'), ('HELLA', 'HELLA'), ('RIDEX', 'RIDEX'), ('STARK', 'STARK'), ('FEBI', 'FEBI Bilstein'), ('MEYLE', 'MEYLE'), ('METZGER', 'Metzger'), ('VAN_WEZEL', 'Van Wezel'), ('PRASCO', 'Prasco'), ('THERMOTEC', 'Thermotec'), ('KALE', 'KALE'), ('JP_GROUP', 'JP Group'), ('MAXGEAR', 'MAXGEAR'), ('ABAKUS', 'ABAKUS'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='turbo',
            name='joints_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('GARRETT', 'Garrett'), ('BORGWARNER', 'BorgWarner'), ('KKK', 'KKK'), ('SCHWITZER', 'Schwitzer'), ('MITSUBISHI', 'Mitsubishi'), ('MHI', 'Mitsubishi Heavy Industries (MHI)'), ('IHI', 'IHI'), ('HOLSET', 'Holset'), ('CUMMINS', 'Cummins Turbo Technologies'), ('CONTINENTAL', 'Continental'), ('MAHLE', 'MAHLE'), ('BOSCH_MAHLE', 'Bosch Mahle Turbo Systems'), ('HITACHI', 'Hitachi'), ('TOYOTA', 'Toyota'), ('AISIN', 'Aisin'), ('HONEYWELL', 'Honeywell'), ('ROTOMASTER', 'Rotomaster'), ('TURBO_TECHNICS', 'Turbo Technics'), ('TURBOSMART', 'Turbosmart'), ('TURBONETICS', 'Turbonetics'), ('PRECISION', 'Precision Turbo & Engine'), ('COMP_TURBO', 'Comp Turbo'), ('TIAL', 'TiAL Sport'), ('TTE', 'The Turbo Engineers (TTE)'), ('LOBA', 'LOBA Motorsport'), ('WEISTEC', 'Weistec'), ('PURE_TURBOS', 'Pure Turbos'), ('MELETT', 'Melett'), ('JRONE', 'JRone'), ('SL_TURBO', 'SL Turbo'), ('NISSENS', 'Nissens'), ('DELPHI', 'Delphi'), ('NRF', 'NRF'), ('RIDEX', 'RIDEX'), ('STARK', 'STARK'), ('ALANKO', 'ALANKO'), ('LUCAS', 'Lucas'), ('BTS_TURBO', 'BTS Turbo'), ('BE_TURBO', 'BE Turbo'), ('TURBO_MOTOR', 'Turbo Motor'), ('MOTAIR', 'Motair'), ('ELSTOCK', 'Elstock'), ('TURBO_S_M', "Turbo's Hoet"), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='turbo',
            name='turbos_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('GARRETT', 'Garrett'), ('BORGWARNER', 'BorgWarner'), ('KKK', 'KKK'), ('SCHWITZER', 'Schwitzer'), ('MITSUBISHI', 'Mitsubishi'), ('MHI', 'Mitsubishi Heavy Industries (MHI)'), ('IHI', 'IHI'), ('HOLSET', 'Holset'), ('CUMMINS', 'Cummins Turbo Technologies'), ('CONTINENTAL', 'Continental'), ('MAHLE', 'MAHLE'), ('BOSCH_MAHLE', 'Bosch Mahle Turbo Systems'), ('HITACHI', 'Hitachi'), ('TOYOTA', 'Toyota'), ('AISIN', 'Aisin'), ('HONEYWELL', 'Honeywell'), ('ROTOMASTER', 'Rotomaster'), ('TURBO_TECHNICS', 'Turbo Technics'), ('TURBOSMART', 'Turbosmart'), ('TURBONETICS', 'Turbonetics'), ('PRECISION', 'Precision Turbo & Engine'), ('COMP_TURBO', 'Comp Turbo'), ('TIAL', 'TiAL Sport'), ('TTE', 'The Turbo Engineers (TTE)'), ('LOBA', 'LOBA Motorsport'), ('WEISTEC', 'Weistec'), ('PURE_TURBOS', 'Pure Turbos'), ('MELETT', 'Melett'), ('JRONE', 'JRone'), ('SL_TURBO', 'SL Turbo'), ('NISSENS', 'Nissens'), ('DELPHI', 'Delphi'), ('NRF', 'NRF'), ('RIDEX', 'RIDEX'), ('STARK', 'STARK'), ('ALANKO', 'ALANKO'), ('LUCAS', 'Lucas'), ('BTS_TURBO', 'BTS Turbo'), ('BE_TURBO', 'BE Turbo'), ('TURBO_MOTOR', 'Turbo Motor'), ('MOTAIR', 'Motair'), ('ELSTOCK', 'Elstock'), ('TURBO_S_M', "Turbo's Hoet"), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
