# Generated by Django 5.2.10 on 2026-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0011_turbo_electrovanne_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbo',
            name='electrovanne_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='electrovanne_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='intercooler_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='intercooler_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='joints_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='joints_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='turbos_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='turbo',
            name='turbos_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
