# Generated by Django 5.2.10 on 2026-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0013_alter_turbo_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbo',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
