# Generated by Django 5.2.10 on 2026-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0014_turbo_kilometrage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbo',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
