# Generated by Django 6.0 on 2026-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFreins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie', models.CharField(choices=[('AVANT', 'Avant'), ('ARRIERE', 'Arrière'), ('AV_AR', 'Avant et arrière')], max_length=10, verbose_name='Partie contrôlée')),
                ('usure_plaquettes', models.FloatField(verbose_name='Usure des plaquettes (%)')),
                ('epaisseur_disques', models.FloatField(verbose_name='Épaisseur des disques (mm)')),
                ('fentes_disques', models.BooleanField(default=False, verbose_name='Présence de fentes sur les disques')),
                ('fuites', models.BooleanField(default=False, verbose_name='Présence de fuite')),
                ('a_remplacer_av', models.BooleanField(default=False, verbose_name='À remplacer avant')),
                ('a_remplacer_ar', models.BooleanField(default=False, verbose_name='À remplacer arrière')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
