# Generated by Django 5.2.9 on 2025-12-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_apprentis_maintenance_chef_mecanicien'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFreins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie', models.CharField(choices=[('AVANT', 'Avant'), ('ARRIERE', 'Arrière'), ('AV_AR', 'Avant et arrière')], max_length=10, verbose_name='Partie contrôlée')),
                ('usure_plaquettes', models.FloatField(verbose_name='Usure des plaquettes (%)')),
                ('epaisseur_disques', models.FloatField(verbose_name='Épaisseur des disques (mm)')),
                ('fentes_disques', models.BooleanField(default=False, verbose_name='Présence de fentes sur les disques')),
                ('fuites', models.BooleanField(default=False, verbose_name='Présence de fuite')),
                ('a_remplacer_av', models.BooleanField(default=False, verbose_name='À remplacer avant')),
                ('a_remplacer_ar', models.BooleanField(default=False, verbose_name='À remplacer arrière')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_freins', to='maintenance.maintenance', verbose_name='Maintenance')),
            ],
        ),
    ]
