# Generated by Django 5.2.10 on 2026-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlefreins',
            name='a_remplacer_ar',
        ),
        migrations.RemoveField(
            model_name='controlefreins',
            name='a_remplacer_av',
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='disque_a_remplacer_ar',
            field=models.BooleanField(default=False, verbose_name='disques à remplacer arrière'),
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='disque_a_remplacer_av',
            field=models.BooleanField(default=False, verbose_name='Disques à remplacer avant'),
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='plaquettes_a_remplacer_ar',
            field=models.BooleanField(default=False, verbose_name='Plaquettes à  remplacer arrière'),
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='plaquettes_a_remplacer_av',
            field=models.BooleanField(default=False, verbose_name='Plaquettes à remplacer avant'),
        ),
    ]
