# Generated by Django 5.2.10 on 2026-02-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0003_remove_controlefreins_a_remplacer_ar_and_more'),
        ('maintenance', '0002_initial'),
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemplacementFreins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_remplacement', models.PositiveIntegerField(blank=True, help_text='Temps estimé ou réel pour effectuer le remplacement', null=True, verbose_name='Durée de remplacement (minutes)')),
                ('description', models.TextField(blank=True, help_text='Notes ou détails supplémentaires sur le remplacement effectué', verbose_name='Détails')),
                ('date_remplacement', models.DateTimeField(auto_now_add=True, verbose_name='Date de remplacement')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacements_freins', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('piece', models.ForeignKey(blank=True, help_text='La pièce de frein remplacée, ex : plaquettes, disques, étrier…', null=True, on_delete=django.db.models.deletion.SET_NULL, to='piece.piece', verbose_name='Pièce remplacée')),
            ],
            options={
                'verbose_name': 'Remplacement de freins',
                'verbose_name_plural': 'Remplacements de freins',
                'ordering': ['-date_remplacement'],
            },
        ),
    ]
