# Generated by Django 5.2.10 on 2026-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0004_remplacementfreins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remplacementfreins',
            options={'ordering': ['-date_remplacement'], 'verbose_name': 'Remplacement des freins', 'verbose_name_plural': 'Remplacements des freins'},
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='disque_a_remplacer_ar',
            field=models.BooleanField(default=False, verbose_name='Disques arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='disque_a_remplacer_av',
            field=models.BooleanField(default=False, verbose_name='Disques avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='plaquettes_a_remplacer_ar',
            field=models.BooleanField(default=False, verbose_name='Plaquettes arrière à  remplacer'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='plaquettes_a_remplacer_av',
            field=models.BooleanField(default=False, verbose_name='Plaquettes avant à remplacer'),
        ),
    ]
