# Generated by Django 5.2.10 on 2026-03-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0006_remove_controlefreins_disque_a_remplacer_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='kilometrage_freins',
            new_name='kilometrage_controle',
        ),
    ]
