# Generated by Django 5.2.10 on 2026-03-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0007_rename_kilometrage_freins_controlefreins_kilometrage_controle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlefreins',
            name='piece',
        ),
    ]
