# Generated by Django 5.2.10 on 2026-03-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0008_remove_controlefreins_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlefreins',
            name='utilisateurs',
        ),
    ]
