# Generated by Django 5.2.10 on 2026-03-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0009_remove_controlefreins_utilisateurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='kilometrage_controle',
            new_name='kilometrage_controle_brake',
        ),
    ]
