# Generated by Django 5.2.10 on 2026-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0010_rename_kilometrage_controle_controlefreins_kilometrage_controle_brake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlefreins',
            options={'verbose_name': 'Contrôle freins', 'verbose_name_plural': 'Contrôles freins'},
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='kilometrage_controle_brake',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage du controle des freins'),
        ),
    ]
