# Generated by Django 5.2.10 on 2026-03-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0011_alter_controlefreins_options_and_more'),
        ('maintenance', '0003_maintenance_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_freins', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
    ]
