# Generated by Django 5.2.10 on 2026-03-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0012_alter_controlefreins_maintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='tag_freins',
            new_name='tag_fff',
        ),
    ]
