# Generated by Django 5.2.10 on 2026-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0013_rename_tag_freins_controlefreins_tag_fff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_disques_remplacer_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_disques_remplacer_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_epaisseur_disques_ar',
            field=models.FloatField(default=0, verbose_name='Épaisseur des disques arrière (mm)'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_epaisseur_disques_av',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques avant (mm)'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_fentes_disques_ar',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques arrière'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_fentes_disques_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques avant'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_usure_plaquettes_ar',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes arrière (%)'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='freins_usure_plaquettes_av',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes avant (%)'),
        ),
    ]
