# Generated by Django 5.2.10 on 2026-03-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0014_alter_controlefreins_freins_disques_remplacer_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='tag_fff',
            new_name='tag',
        ),
    ]
