# Generated by Django 5.2.10 on 2026-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0015_rename_tag_fff_controlefreins_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_disques_remplacer_ar',
            new_name='arriere_freins_disques_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_epaisseur_disques_ar',
            new_name='arriere_freins_epaisseur_disques',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_fentes_disques_ar',
            new_name='arriere_freins_fentes_disques',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_plaquettes_remplacer_ar',
            new_name='arriere_freins_plaquettes_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_usure_plaquettes_ar',
            new_name='arriere_freins_usure_plaquettes',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_disques_remplacer_av',
            new_name='avant_freins_disques_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_epaisseur_disques_av',
            new_name='avant_freins_epaisseur_disques',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_fentes_disques_av',
            new_name='avant_freins_fentes_disques',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_plaquettes_remplacer_av',
            new_name='avant_freins_plaquettes_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_usure_plaquettes_av',
            new_name='avant_freins_usure_plaquettes',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_fuites',
            new_name='fuites_freins_fuites',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='frein_liquide_frein_etat',
            new_name='liquide_frein_etat',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_quantite_liquide_frein',
            new_name='liquide_quantite_liquide_frein',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_remplacement_liquide_frein',
            new_name='liquide_remplacement_liquide_frein',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='freins_specif_liquide_frein',
            new_name='liquide_specif_liquide_frein',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='frein_machoire_ard',
            new_name='machoire_ard',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='frein_machoire_arg',
            new_name='machoire_arg',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='frein_machoire_avd',
            new_name='machoire_avd',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='frein_machoire_avg',
            new_name='machoire_avg',
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='fuites_freins_flexibles',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fuite flexibles'),
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='fuites_freins_machoire',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fuite machoire'),
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='fuites_freins_tuyaux',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fuite tuyaux rigides'),
        ),
    ]
