# Generated by Django 5.2.10 on 2026-03-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0016_rename_freins_disques_remplacer_ar_controlefreins_arriere_freins_disques_remplacer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='arriere_freins_plaquettes_remplacer',
            new_name='arriere_freins_pl_plaquettes_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='arriere_freins_usure_plaquettes',
            new_name='arriere_freins_pl_usure_plaquettes',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='avant_freins_plaquettes_remplacer',
            new_name='avant_freins_pl_plaquettes_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='avant_freins_usure_plaquettes',
            new_name='avant_freins_pl_usure_plaquettes',
        ),
    ]
