# Generated by Django 5.2.10 on 2026-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0017_rename_arriere_freins_plaquettes_remplacer_controlefreins_arriere_freins_pl_plaquettes_remplacer_and'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='arriere_freins_disques_remplacer',
            new_name='arriere_freins_d_disques_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='arriere_freins_epaisseur_disques',
            new_name='arriere_freins_d_epaisseur_disques',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='arriere_freins_fentes_disques',
            new_name='arriere_freins_d_fentes_disques',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='avant_freins_disques_remplacer',
            new_name='avant_freins_d_disques_remplacer',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='avant_freins_epaisseur_disques',
            new_name='avant_freins_d_epaisseur_disques',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='avant_freins_fentes_disques',
            new_name='avant_freins_d_fentes_disques',
        ),
    ]
