# Generated by Django 5.2.10 on 2026-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0018_rename_arriere_freins_disques_remplacer_controlefreins_arriere_freins_d_disques_remplacer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlefreins',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
