# Generated by Django 5.2.10 on 2026-05-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0021_controlefreins_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='liquide_specif_liquide_frein',
            field=models.CharField(blank=True, choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=100, verbose_name='Spécification liquide de frein'),
        ),
    ]
