# Generated by Django 5.2.10 on 2026-05-26 13:08

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0022_alter_controlefreins_liquide_specif_liquide_frein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='liquide_quantite_liquide_frein',
            field=models.FloatField(blank=True, default=0, null=True, validators=[maintenance.niveaux.models.StepValueValidator(0.1)], verbose_name='Quantité liquide de frein (L)'),
        ),
    ]
