# Generated by Django 5.2.10 on 2026-05-27 15:30

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0024_alter_controlefreins_arriere_freins_d_disques_remplacer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='liquide_quantite_liquide_frein',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name='Quantité liquide de frein (L)'),
        ),
    ]
