# Generated by Django 5.2.10 on 2026-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0026_alter_controlefreins_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='kilometrage_controle_brake',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage du controle des freins'),
            preserve_default=False,
        ),
    ]
