# Generated by Django 5.2.10 on 2026-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0027_alter_controlefreins_kilometrage_controle_brake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='arriere_freins_d_disques_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques arrière'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='arriere_freins_pl_plaquettes_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes arrière'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='avant_freins_d_disques_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques avant'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='avant_freins_pl_plaquettes_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes avant'),
        ),
    ]
