# Generated by Django 5.2.10 on 2026-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0028_alter_controlefreins_arriere_freins_d_disques_remplacer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlefreins',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
