# Generated by Django 5.2.10 on 2026-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0029_controlefreins_serrage_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlefreins',
            name='arriere_freins_epaisseur_disque_ar_origine',
            field=models.FloatField(blank=True, null=True, verbose_name='Épaisseur disque arrière constructeur (mm)'),
        ),
    ]
