# Generated by Django 5.2.10 on 2026-07-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0030_controlefreins_arriere_freins_epaisseur_disque_ar_origine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='arriere_freins_epaisseur_disque_ar_origine',
            new_name='arriere_freins_d_epaisseur_disque_ar_origine',
        ),
    ]
