# Generated by Django 5.2.10 on 2026-07-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0031_rename_arriere_freins_epaisseur_disque_ar_origine_controlefreins_arriere_freins_d_epaisseur_disque_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlefreins',
            name='arriere_freins_d_epaisseur_disque_ar_origine',
        ),
    ]
