# Generated by Django 5.2.10 on 2026-07-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0035_controlefreins_liquide_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='liquide_fabricant',
            new_name='liquide_frein_fabricant',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='liquide_prix',
            new_name='liquide_frein_prix',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='liquide_quantite_liquide_frein',
            new_name='liquide_frein_quantite_liquide_frein',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='liquide_specif_liquide_frein',
            new_name='liquide_frein_specif_liquide_frein',
        ),
        migrations.RemoveField(
            model_name='controlefreins',
            name='liquide_remplacement_liquide_frein',
        ),
    ]
