# Generated by Django 5.2.10 on 2026-07-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0036_rename_liquide_fabricant_controlefreins_liquide_frein_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlefreins',
            old_name='liquide_frein_quantite_liquide_frein',
            new_name='liquide_frein_quantite',
        ),
        migrations.RenameField(
            model_name='controlefreins',
            old_name='liquide_frein_specif_liquide_frein',
            new_name='liquide_frein_specif',
        ),
    ]
