# Generated by Django 5.2.10 on 2026-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0037_rename_liquide_frein_quantite_liquide_frein_controlefreins_liquide_frein_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='avant_freins_pl_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
