# Generated by Django 5.2.10 on 2026-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0038_alter_controlefreins_avant_freins_pl_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefreins',
            name='arriere_freins_d_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des disques arrière'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='arriere_freins_pl_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des plaquettes arrière'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='avant_freins_d_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des disques avant'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='avant_freins_pl_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des plaquettes avant'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='machoire_ard_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant de la mâchoire arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='machoire_arg_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant de la mâchoire arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='machoire_avd_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant de la mâchoire avant droite'),
        ),
        migrations.AlterField(
            model_name='controlefreins',
            name='machoire_avg_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant de la mâchoire avant gauche'),
        ),
    ]
