# Generated by Django 5.2.10 on 2026-10-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freins', '0052_alter_controlefreins_liquide_frein_fabricant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlefreins',
            name='fuites_freins_machoire',
        ),
        migrations.AddField(
            model_name='controlefreins',
            name='fuites_freins_ma',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fuite mâchoire'),
        ),
    ]
