# Generated by Django 5.2.10 on 2026-10-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclairage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eclairage',
            options={'verbose_name': 'Éclairage', 'verbose_name_plural': 'éclairages'},
        ),
    ]
