# Generated by Django 5.2.10 on 2026-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_mecanicien', '0001_initial'),
        ('maintenance', '0009_alter_maintenance_type_maintenance'),
        ('utilisateurs', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChefMecanicien',
        ),
        migrations.CreateModel(
            name='ChefMecanicien',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('utilisateurs.utilisateur',),
        ),
    ]
