# Generated by Django 5.2.10 on 2026-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='ready_for',
            field=models.CharField(choices=[('SPA200', 'Spa-Francorchamps 200 km'), ('SPA300', 'Spa-Francorchamps 300 km'), ('SPA400', 'Spa-Francorchamps 400 km'), ('NURBURG2', 'Nurburg 2 tours'), ('NURBURG5', 'Nurburg 5 tours'), ('NURBURG7', 'Nurburg 7 tours'), ('NURBURG10', 'Nurburg 10 tours'), ('NURBURG12', 'Nurburg 12 tours'), ('NURBURG15', 'Nurburg 15 tours')], max_length=25, verbose_name='Plastiques'),
        ),
    ]
