# Generated by Django 5.2.10 on 2026-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0002_alter_checkuptrack_ready_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='jeu_roulement_roue',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu de roulement de roue'),
        ),
    ]
