# Generated by Django 5.2.10 on 2026-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0003_checkuptrack_jeu_roulement_roue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='nettoyage_interieur_plastiques',
            field=models.CharField(blank=True, choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, null=True, verbose_name='Plastiques'),
        ),
    ]
