# Generated by Django 5.2.10 on 2026-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0005_alter_checkuptrack_ready_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques avant arrière (mm)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_plaquettes_remplacer',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_usure_plaquettes',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes arrière (%)'),
        ),
    ]
