# Generated by Django 5.2.10 on 2026-04-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0006_alter_checkuptrack_freins_epaisseur_disques_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_epaisseur_disques',
            new_name='freins_epaisseur_disques_ar',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_plaquettes_remplacer',
            new_name='freins_plaquettes_remplacer_ar',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_usure_plaquettes',
            new_name='freins_usure_plaquettes_ar',
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques avant avant (mm)'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_plaquettes_remplacer_av',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes avant à remplacer'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_usure_plaquettes_av',
            field=models.IntegerField(default=0, verbose_name='Usure des plaquettes avant (%)'),
        ),
    ]
