# Generated by Django 5.2.10 on 2026-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0007_rename_freins_epaisseur_disques_checkuptrack_freins_epaisseur_disques_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_specif_liquide_frein',
            field=models.CharField(blank=True, choices=[('DOT3', 'Dot 3'), ('DOT4', 'Dot 4'), ('DOT5', 'Dot 5'), ('DOT51', 'Dot 5.1')], default='DOT4', max_length=100, verbose_name='Spécification liquide de frein'),
        ),
    ]
