# Generated by Django 5.2.10 on 2026-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0008_alter_checkuptrack_freins_specif_liquide_frein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkuptrack',
            name='freins_remplacement_liquide_frein',
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='frein_liquide_frein_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AREMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='État liquide de frein'),
        ),
    ]
