# Generated by Django 5.2.10 on 2026-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0009_remove_checkuptrack_freins_remplacement_liquide_frein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_roulement_roue',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement de roue'),
        ),
    ]
