# Generated by Django 5.2.10 on 2026-04-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0010_alter_checkuptrack_jeu_roulement_roue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques arrière (mm)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques avant (mm)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_sidewall',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Flanc des pneus'),
        ),
    ]
