# Generated by Django 5.2.10 on 2026-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0011_alter_checkuptrack_freins_epaisseur_disques_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_Biellette_barre_stabilisatrice',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellettes de barre stabilisatrice'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_cardan',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu des cardan'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotules de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_rotule_suspension',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotules de suspension'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='ready_for',
            field=models.CharField(blank=True, choices=[('', '---------'), ('SPA200', 'Spa-Francorchamps 200 km'), ('SPA300', 'Spa-Francorchamps 300 km'), ('SPA400', 'Spa-Francorchamps 400 km'), ('NURBURG2', 'Nürburgring 2 tours'), ('NURBURG5', 'Nürburgring 5 tours'), ('NURBURG7', 'Nürburgring 7 tours'), ('NURBURG10', 'Nürburgring 10 tours'), ('NURBURG12', 'Nürburgring 12 tours'), ('NURBURG15', 'Nürburgring 15 tours')], default='', max_length=25, verbose_name='Prête pour :'),
        ),
    ]
