# Generated by Django 5.2.10 on 2026-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0012_alter_checkuptrack_jeu_biellette_barre_stabilisatrice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotules de direction'),
        ),
    ]
