# Generated by Django 5.2.10 on 2026-05-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0014_checkuptrack_main_oeuvre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='jeu_Biellette_barre_stabilisatrice',
            new_name='jeu_biellette_barre_stabilisatrice',
        ),
    ]
