# Generated by Django 5.2.10 on 2026-05-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0015_rename_jeu_biellette_barre_stabilisatrice_checkuptrack_jeu_biellette_barre_stabilisatrice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='jeu_biellette_barre_stabilisatrice',
            new_name='jeu_biellette_bar_stab',
        ),
    ]
