# Generated by Django 5.2.10 on 2026-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0016_rename_jeu_biellette_barre_stabilisatrice_checkuptrack_jeu_biellette_bar_stab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_biellette_bar_stab',
            field=models.CharField(blank=True, choices=[('OK', 'Non'), ('NOT_OK', 'Oui'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Jeu biellettes de barre stabilisatrice'),
        ),
    ]
