# Generated by Django 5.2.10 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0017_alter_checkuptrack_jeu_biellette_bar_stab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
