# Generated by Django 5.2.10 on 2026-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0018_alter_checkuptrack_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='kilometrage_checkup_track',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du checkup piste'),
            preserve_default=False,
        ),
    ]
