# Generated by Django 5.2.10 on 2026-06-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0019_alter_checkuptrack_kilometrage_checkup_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='serrage_roues',
            field=models.CharField(choices=[('AFAIRE', 'À faire'), ('Fait', 'Fait')], default='AFAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
