# Generated by Django 5.2.10 on 2026-06-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0020_checkuptrack_serrage_roues'),
        ('maintenance', '0011_alter_maintenance_type_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkup_track', to='maintenance.maintenance', verbose_name='Checkup Track'),
        ),
    ]
