# Generated by Django 5.2.10 on 2026-07-03 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0022_alter_checkuptrack_boite_niveau_huile_qualite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='moteur_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_epaisseur_ard',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu arrière droit (mm)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_epaisseur_arg',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu arrière gauche (mm)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_epaisseur_avd',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu avant droit (mm)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_epaisseur_avg',
            field=models.FloatField(default=8.0, verbose_name='Épaisseur du pneu avant gauche (mm)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
    ]
