# Generated by Django 5.2.10 on 2026-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0023_alter_checkuptrack_boite_niveau_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='balais_essuie',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat des balais'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_embrayage',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="État de l'embrayage"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État de la boîte de vitesse'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='bruit_roulement_roue',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Bruit de roulement de roue'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='crochet_de_remorquage',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Crochet de remorquage installé'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_etat',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Etat direction assistée / crémaillère'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='essuie_glace',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Essuies-glace fonctionnel'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_disques_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_fentes_disques',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_fuites',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fuite'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_plaquettes_remplacer_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_plaquettes_remplacer_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Plaquettes avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_amortisseur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_arbre',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Jeu dans l'arbre de transmission"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_barre_stabilisatrice',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_biellette_bar_stab',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Jeu biellettes de barre stabilisatrice'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_biellette_direction',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_cardan',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu des cardan'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_multi_bras',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotules de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_rotule_suspension',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotules de suspension'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_roulement_roue',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement de roue'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_triangle',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='moteur_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État du moteur'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pare_brise_coups',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise avec coups'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pare_brise_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Fuite pont arrière'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48 BMW'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'Ford WSS-M97B44-D'), ('WSS_M97B51_A1', 'Ford WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité de liquide de refroidissement'),
        ),
    ]
