# Generated by Django 5.2.10 on 2026-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0025_alter_checkuptrack_boite_niveau_huile_qualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='crochet_de_remorquage',
            field=models.CharField(choices=[('OK', 'Monté'), ('NOT_OK', 'Démonté')], default='NOT_OK', max_length=25, verbose_name='Crochet de remorquage'),
        ),
    ]
