# Generated by Django 5.2.10 on 2026-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0029_alter_checkuptrack_serrage_roues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='pare_brise_coups',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pare-brise sans coups'),
        ),
    ]
