# Generated by Django 5.2.10 on 2026-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0031_checkuptrack_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='ready_for',
            field=models.CharField(blank=True, choices=[('', '---------'), ('SPA200', 'Spa-Francorchamps 200 km'), ('SPA300', 'Spa-Francorchamps 300 km'), ('SPA400', 'Spa-Francorchamps 400 km'), ('NURBURG2', 'Nürburgring 2 tours'), ('NURBURG5', 'Nürburgring 5 tours'), ('NURBURG7', 'Nürburgring 7 tours'), ('NURBURG10', 'Nürburgring 10 tours'), ('NURBURG12', 'Nürburgring 12 tours'), ('NURBURG15', 'Nürburgring 15 tours'), ('AUTRE200', 'Autre circuit 200 km'), ('AUTRE300', 'Autre circuit 300 km'), ('AUTRE400', 'Autre circuit 400 km')], default='', max_length=25, verbose_name='Prête pour :'),
        ),
    ]
