# Generated by Django 5.2.10 on 2026-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0032_alter_checkuptrack_ready_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_quantite_liquide_frein',
            new_name='freins_liquide_quantite',
        ),
        migrations.RemoveField(
            model_name='checkuptrack',
            name='niveau_direction',
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='boite_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de l'huile de boite"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='direction_niveau',
            field=models.CharField(blank=True, choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, null=True, verbose_name='Niveau du liquide de direction'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='direction_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva du liquide de direction"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='direction_qualite',
            field=models.CharField(blank=True, choices=[('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('LDS', 'LDS'), ('LHM', 'LHM'), ('PSF', 'PSF'), ('PSF_3', 'PSF-3'), ('PSF_4', 'PSF-4'), ('MB_236_3', 'Mercedes-Benz 236.3'), ('MB_345_0', 'Mercedes-Benz 345.0'), ('VW_G002000', 'Volkswagen G 002 000'), ('VW_G004000', 'Volkswagen G 004 000'), ('BMW_ATF', 'BMW ATF'), ('BMW_CHF', 'BMW CHF'), ('HONDA_PSF', 'Honda PSF'), ('TOYOTA_PSF', 'Toyota PSF'), ('MINERALE', 'Huile minérale'), ('SEMI_SYNTHETIQUE', 'Huile semi-synthétique'), ('SYNTHETIQUE', 'Huile synthétique'), ('CONSTRUCTEUR', 'Spécification constructeur'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, null=True, verbose_name='Qualité du liquide de direction'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='direction_quantite',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Quantité liquide de direction (L)'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='frein_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre')], default='CASTROL', max_length=25, verbose_name='Fabricant du liquide de frein'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='frein_liquide_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva du liquide de frein"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='moteur_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de l'huile moteur"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='nettoyage_exterieur_produits_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='nettoyage_exterieur_produits_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='nettoyage_interieur_produits_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='nettoyage_interieur_produits_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_anti_brouillard_arriere_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_anti_brouillard_arriere_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_anti_brouillard_arriere_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_anti_brouillard_avant_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_anti_brouillard_avant_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_anti_brouillard_avant_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_avant_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_avant_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_avant_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_clignotants_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_clignotants_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_clignotants_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_position_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_position_ar_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_position_ar_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_position_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_position_av_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_position_av_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_stops_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_stops_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_feux_stops_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_gros_phares_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_gros_phares_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_gros_phares_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_recul_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_recul_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_recul_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_troisieme_feux_stop_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_troisieme_feux_stop_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_troisieme_feux_stop_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='pneu_train_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='pneu_train_ar_quantite',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='pneu_train_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='pneu_train_av_quantite',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='pont_niveau_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de l'huile de pont"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='refroidissement_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva du liquide de refroidissement"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_niveau_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF_DSG', 'ATF DSG'), ('ATF_DCT', 'ATF DCT'), ('ATF_CVT', 'ATF CVT'), ('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('ATF_MERCON', 'ATF Mercon'), ('ATF_MERCON_V', 'ATF Mercon V'), ('ATF_MERCON_LV', 'ATF Mercon LV'), ('ATF_MULTI', 'ATF Multi Vehicle'), ('ATF_WS', 'ATF Toyota WS'), ('ATF_ZF_LIFEGUARD', 'ZF Lifeguard'), ('ATF_MOPAR', 'Mopar ATF+4'), ('ATF_AISIN', 'Aisin ATF'), ('ATF_MBV236', 'Mercedes MB 236.x'), ('ATF_VOLVO', 'Volvo ATF'), ('ATF_HONDA', 'Honda ATF DW-1'), ('ATF_NISSAN', 'Nissan Matic'), ('PDK_FFL-3', 'PDK FFL 3'), ('AUTRE', 'Autre')], default='75W', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='phares_gros_phares',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Grands phares'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='phares_troisieme_feux_stop',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Troisième feu stop'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_train_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Train arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_train_av',
            field=models.CharField(choices=[('OK', 'OK'), ('NON', 'Non'), ('A_REMPLACER', 'À remplacer')], default='OK', max_length=25, verbose_name='Train avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_huile_qualite',
            field=models.CharField(choices=[('75W140', '75W140'), ('AUTRE', 'Autre')], default='75W140', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48 BMW'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'Ford WSS-M97B44-D'), ('WSS_M97B51_A1', 'Ford WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant'), ('AUTRE', 'Autre')], default='G13', max_length=25, verbose_name='Qualité de liquide de refroidissement'),
        ),
    ]
