# Generated by Django 5.2.10 on 2026-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0033_rename_freins_quantite_liquide_frein_checkuptrack_freins_liquide_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_sidewall',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Flanc des pneus'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_train_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat du train arrière'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_train_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat du train avant'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Radiateur'),
        ),
    ]
