# Generated by Django 5.2.10 on 2026-07-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0034_alter_checkuptrack_pneu_sidewall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='direction_etat',
            new_name='direction_liquide_etat',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='direction_niveau',
            new_name='direction_liquide_niveau',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='direction_prix',
            new_name='direction_liquide_prix',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='direction_qualite',
            new_name='direction_liquide_qualite',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='direction_quantite',
            new_name='direction_liquide_quantite',
        ),
    ]
