# Generated by Django 5.2.10 on 2026-07-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0035_rename_direction_etat_checkuptrack_direction_liquide_etat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_specif_liquide_frein',
            new_name='freins_liquide_qualite',
        ),
    ]
