# Generated by Django 5.2.10 on 2026-07-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0036_rename_freins_specif_liquide_frein_checkuptrack_freins_liquide_qualite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='pont_etat',
            new_name='pont_niveau_etat',
        ),
    ]
