# Generated by Django 5.2.10 on 2026-07-26 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0038_checkuptrack_moteur_niveau_huile_fabricant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_pression_bar_ard',
            field=models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_pression_bar_arg',
            field=models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_pression_bar_avd',
            field=models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pneu_pression_bar_avg',
            field=models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu avant gauche en bar'),
        ),
    ]
