# Generated by Django 5.2.10 on 2026-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0040_checkuptrack_freins_plaquettes_remplacer_ar_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_epaisseur_disques_av',
            new_name='freins_epaisseur_disques_av_usure',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_plaquettes_remplacer_ar',
            new_name='freins_plaquettes_remplacer_ar_etat',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_usure_plaquettes_ar',
            new_name='freins_plaquettes_remplacer_ar_usure',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_plaquettes_remplacer_av',
            new_name='freins_plaquettes_remplacer_av_etat',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_usure_plaquettes_av',
            new_name='freins_plaquettes_remplacer_av_usure',
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='frein_epaisseur_disques_av',
            field=models.FloatField(default=0.0, verbose_name="Épaisseur des disques avant d'origine (mm)"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques arrière à remplacer'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des plaquettes'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_qualite',
            field=models.CharField(choices=[('ACIER', 'Acier'), ('CARBONE', 'Carbone'), ('CERAMIQUE', 'Céramique'), ('COMPOSITE', 'Composite'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Matière des disques'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_type',
            field=models.CharField(choices=[('MONOBLOC_PLEIN', 'Plein (monobloc)'), ('VENTILE', 'Ventilé'), ('RAINURE', 'Rainuré'), ('PERCE', 'Percé'), ('RAINURE_PERCE', 'Rainuré et percé'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Type des disques'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_usure',
            field=models.FloatField(default=0.0, verbose_name='Épaisseur des disques arrière (mm)'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Disques avant à remplacer'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_fabricant',
            field=models.CharField(choices=[('ATE', 'ATE'), ('BREMBO', 'Brembo'), ('BOSCH', 'Bosch'), ('TRW', 'TRW'), ('FERODO', 'Ferodo'), ('TEXTAR', 'Textar'), ('PAGID', 'Pagid'), ('JURID', 'Jurid'), ('DELPHI', 'Delphi'), ('VALEO', 'Valeo'), ('HELLA', 'Hella'), ('HELLA_PAGID', 'Hella Pagid'), ('ZIMMERMANN', 'Zimmermann'), ('MEYLE', 'Meyle'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('MINTEX', 'Mintex'), ('ROADHOUSE', 'Roadhouse'), ('REMSA', 'Remsa'), ('ICER', 'ICER'), ('EBC', 'EBC Brakes'), ('STOPTECH', 'StopTech'), ('AKEBONO', 'Akebono'), ('ADVICS', 'Advics'), ('NISSHINBO', 'Nisshinbo'), ('BENDIX', 'Bendix'), ('COMLINE', 'Comline'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MAPCO', 'Mapco'), ('NK', 'NK'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('DON', 'DON'), ('TOMEX', 'Tomex'), ('LPR', 'LPR'), ('CIFAM', 'Cifam'), ('METELLI', 'Metelli'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('SKF', 'SKF'), ('SNR', 'SNR'), ('WINMAX', 'Winmax'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant des disques'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_qualite',
            field=models.CharField(choices=[('ACIER', 'Acier'), ('CARBONE', 'Carbone'), ('CERAMIQUE', 'Céramique'), ('COMPOSITE', 'Composite'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Matière des disques'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_type',
            field=models.CharField(choices=[('MONOBLOC_PLEIN', 'Plein (monobloc)'), ('VENTILE', 'Ventilé'), ('RAINURE', 'Rainuré'), ('PERCE', 'Percé'), ('RAINURE_PERCE', 'Rainuré et percé'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Type de disques'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar',
            field=models.FloatField(default=0.0, verbose_name="Épaisseur des disques arrière d'origine (mm)"),
        ),
    ]
