# Generated by Django 5.2.10 on 2026-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0041_rename_freins_epaisseur_disques_av_checkuptrack_freins_epaisseur_disques_av_usure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_fentes_disques',
            new_name='freins_epaisseur_disques_ar_fentes',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='frein_liquide_fabricant',
            new_name='freins_liquide_fabricant',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='frein_liquide_frein_etat',
            new_name='freins_liquide_frein_etat',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='freins_fuites',
            new_name='freins_liquide_fuites',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='frein_liquide_prix',
            new_name='freins_liquide_prix',
        ),
        migrations.RemoveField(
            model_name='checkuptrack',
            name='frein_epaisseur_disques_av',
        ),
        migrations.RemoveField(
            model_name='checkuptrack',
            name='freins_disques_remplacer',
        ),
        migrations.RemoveField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar',
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_fentes',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Présence de fentes sur les disques arrière'),
        ),
    ]
