# Generated by Django 5.2.10 on 2026-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0043_alter_checkuptrack_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='balais_essuie_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='balais_essuie_quantite',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='essuie_glace_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='essuie_glace_quantite',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='pare_brise_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='balais_essuie',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat des balais arrières'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='essuie_glace',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Etat des balais avant'),
        ),
    ]
