# Generated by Django 5.2.10 on 2026-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0044_checkuptrack_balais_essuie_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='pare_brise_quantite',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantité'),
        ),
    ]
