# Generated by Django 5.2.10 on 2026-08-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0045_checkuptrack_pare_brise_quantite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='pare_brise_coups',
            new_name='pare_brise_av_coups',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='pare_brise_quantite',
            new_name='pare_brise_av_quantite',
        ),
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='pare_brise_remplacer',
            new_name='pare_brise_av_remplacer',
        ),
    ]
