# Generated by Django 5.2.10 on 2026-08-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0046_rename_pare_brise_coups_checkuptrack_pare_brise_av_coups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuptrack',
            old_name='pare_brise_prix',
            new_name='pare_brise_av_prix',
        ),
    ]
