# Generated by Django 5.2.10 on 2026-08-08 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0047_rename_pare_brise_prix_checkuptrack_pare_brise_av_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='refroidissement_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté')], default='OK', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide_niveau',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté')], default='OK', max_length=25, null=True, verbose_name='Niveau du liquide de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide_quantite',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité liquide de direction (L)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_quantite',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité liquide de frein (L)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
    ]
