# Generated by Django 5.2.10 on 2026-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0048_checkuptrack_refroidissement_etat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkuptrack',
            name='freins_liquide_frein_etat',
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='freins_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AREMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide_niveau',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, null=True, verbose_name='Niveau du liquide de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
