# Generated by Django 5.2.10 on 2026-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0049_remove_checkuptrack_freins_liquide_frein_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'A remplacer'), ('REMPLACER', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
    ]
