# Generated by Django 5.2.10 on 2026-08-09 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0050_alter_checkuptrack_freins_liquide_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité liquide de direction (L)'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité liquide de frein (L)'),
        ),
    ]
