# Generated by Django 5.2.10 on 2026-08-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0051_alter_checkuptrack_direction_liquide_quantite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkuptrack',
            name='direction_liquide_niveau',
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='direction_liquide',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Etat direction assistée / crémaillère'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide_etat',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, null=True, verbose_name='Niveau du liquide de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
    ]
