# Generated by Django 5.2.10 on 2026-08-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0052_remove_checkuptrack_direction_liquide_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_huile_qualite',
            field=models.CharField(choices=[('75W140', '75W140'), ('75W90', 'Porsche 75W90'), ('AUTRE', 'Autre')], default='75W140', max_length=25, verbose_name="Qualité d'huile"),
        ),
    ]
