# Generated by Django 5.2.10 on 2026-08-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0055_alter_checkuptrack_boite_niveau_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_reglages',
            field=models.CharField(choices=[('OK', 'OK'), ('FAIT', 'Fait'), ('A_FAIRE', 'A faire')], default='OK', max_length=25, verbose_name='Réglage des phares'),
        ),
    ]
