# Generated by Django 5.2.10 on 2026-08-19 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0060_alter_checkuptrack_boite_niveau_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='moteur_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_huile_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajoutée en litres'),
        ),
    ]
