# Generated by Django 5.2.10 on 2026-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0064_alter_checkuptrack_phares_avant_fabricant'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
