# Generated by Django 5.2.10 on 2026-08-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0068_alter_checkuptrack_freins_liquide_fabricant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouter les produits')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouter les produits')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
    ]
