# Generated by Django 5.2.10 on 2026-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0069_alter_checkuptrack_nettoyage_exterieur_produits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='bruit_roulement_roue',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('BRUIT', 'Petit bruit'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Bruit de roulement de roue'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide_etat',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, null=True, verbose_name='Niveau du liquide de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouter'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='moteur_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_huile_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name="Niveau d'huile"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'A remplacer')], default='OK', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='refroidissement_fabricant',
            field=models.CharField(choices=[('ABRO', 'ABRO'), ('AISIN', 'AISIN'), ('ARECA', 'Areca'), ('BARDAHL', 'Bardahl'), ('BASF_GLYSANTIN', 'BASF Glysantin'), ('BEL_RAY', 'Bel-Ray'), ('BIZOL', 'BIZOL'), ('BMW', 'BMW'), ('BOLK', 'BOLK'), ('BOSCH', 'Bosch'), ('CASTROL', 'Castrol'), ('CHAMPION', 'Champion'), ('COMMA', 'Comma'), ('ELF', 'ELF'), ('EUROL', 'Eurol'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('FUCHS', 'Fuchs'), ('GATES', 'Gates'), ('GENERAL_MOTORS', 'General Motors'), ('HEPU', 'HEPU'), ('HOLTS', 'Holts'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('IGOL', 'Igol'), ('IPONE', 'IPONE'), ('K2', 'K2'), ('KIA', 'Kia'), ('LIQUI_MOLY', 'Liqui Moly'), ('MANNOL', 'Mannol'), ('MAZDA', 'Mazda'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('MEYLE', 'Meyle'), ('MILLERS_OILS', 'Millers Oils'), ('MITSUBISHI', 'Mitsubishi'), ('MOBIL', 'Mobil'), ('MOPAR', 'Mopar'), ('MOTIP', 'Motip'), ('MOTOREX', 'Motorex'), ('MOTUL', 'Motul'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('ORLEN', 'Orlen'), ('PEMCO', 'Pemco'), ('PEUGEOT_CITROEN', 'Peugeot Citroën'), ('PETRONAS', 'Petronas'), ('PORSCHE', 'Porsche'), ('PRESTONE', 'Prestone'), ('PUTOLINE', 'Putoline'), ('RAVENOL', 'Ravenol'), ('REPSOL', 'Repsol'), ('RENAULT', 'Renault'), ('ROWE', 'ROWE'), ('SHELL', 'Shell'), ('SONAX', 'Sonax'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('SWAG', 'SWAG'), ('TEXACO', 'Texaco'), ('TOTALENERGIES', 'TotalEnergies'), ('TOYOTA', 'Toyota'), ('TRIPLE_QX', 'Triple QX'), ('VALEO', 'Valeo'), ('VALVOLINE', 'Valvoline'), ('VAG', 'VAG'), ('VOLVO', 'Volvo'), ('WOLF', 'Wolf'), ('XENUM', 'Xenum'), ('YACCO', 'Yacco'), ('YAMAHA', 'Yamaha'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
