# Generated by Django 5.2.10 on 2026-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0073_alter_checkuptrack_boite_niveau_huile_qualite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_amortisseur',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_arbre',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Jeu dans l'arbre de transmission"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_barre_stabilisatrice',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_biellette_bar_stab',
            field=models.CharField(blank=True, choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, null=True, verbose_name='Jeu biellettes de barre stabilisatrice'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_biellette_direction',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_cardan',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu des cardan'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_multi_bras',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotules de direction'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_rotule_suspension',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotules de suspension'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_roulement_roue',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement de roue'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='jeu_triangle',
            field=models.CharField(choices=[('NON_PRESENT', 'Non présent'), ('OK', 'OK'), ('JEU', 'Petit Jeu'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle'),
        ),
    ]
