# Generated by Django 5.2.10 on 2026-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0074_alter_checkuptrack_jeu_amortisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='balais_essuie',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Etat des balais arrières'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_embrayage',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name="État de l'embrayage"),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='boite_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='État de la boîte de vitesse'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='direction_liquide',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, null=True, verbose_name='Etat direction assistée / crémaillère'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='essuie_glace',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Etat des balais avant'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Disques arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_ar_fentes',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Présence de fentes'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Disques avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_epaisseur_disques_av_fentes',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Présence de fentes'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_fuites',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Présence de fuite'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_plaquettes_remplacer_ar_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Plaquettes arrière à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_plaquettes_remplacer_av_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Plaquettes avant à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='moteur_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='État du moteur'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pare_brise_av_coups',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pare-brise sans coups'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pare_brise_av_remplacer',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Pare-brise à remplacer'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='pont_niveau_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_PRESENT', 'Non présent')], default='OK', max_length=25, verbose_name='Fuite pont arrière'),
        ),
    ]
