# Generated by Django 5.2.10 on 2026-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0075_alter_checkuptrack_balais_essuie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
