# Generated by Django 5.2.10 on 2026-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0076_checkuptrack_kilometres_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='kilometres_boite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='kilometres_boite_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback boite'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='kilometres_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='kilometres_moteur_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback moteur'),
        ),
    ]
