# Generated by Django 5.2.10 on 2026-10-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0084_checkuptrack_lave_glace_liquide_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('AREMPLACER', 'A remplacer'), ('REMPLACER', 'Remplacé')], default='OK', max_length=25, verbose_name='Liquide de lave-glace'),
        ),
    ]
