# Generated by Django 5.2.10 on 2026-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0085_alter_checkuptrack_lave_glace_liquide_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits de nettoyage'),
        ),
        migrations.AlterField(
            model_name='checkuptrack',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits de nettoyage'),
        ),
    ]
