# Generated by Django 5.2.10 on 2026-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0086_alter_checkuptrack_nettoyage_exterieur_produits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_eclaire_plaque',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Éclaire plaque'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_eclaire_plaque_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_eclaire_plaque_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_eclaire_plaque_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='checkuptrack',
            name='phares_eclaire_plaque_type',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('H1', 'H1'), ('H3', 'H3'), ('H4', 'H4'), ('H7', 'H7'), ('H8', 'H8'), ('H9', 'H9'), ('H10', 'H10'), ('H11', 'H11'), ('H12', 'H12'), ('H13', 'H13'), ('H15', 'H15'), ('H16', 'H16'), ('H18', 'H18'), ('H19', 'H19'), ('HB1_9004', 'HB1 (9004)'), ('HB2_9003', 'HB2 (9003)'), ('HB3_9005', 'HB3 (9005)'), ('HB4_9006', 'HB4 (9006)'), ('HB5_9007', 'HB5 (9007)'), ('D1S', 'D1S'), ('D1R', 'D1R'), ('D2S', 'D2S'), ('D2R', 'D2R'), ('D3S', 'D3S'), ('D3R', 'D3R'), ('D4S', 'D4S'), ('D4R', 'D4R'), ('D5S', 'D5S'), ('D8S', 'D8S'), ('W1_2W', 'W1.2W'), ('W2W', 'W2W'), ('W3W', 'W3W'), ('W5W', 'W5W'), ('WY5W', 'WY5W'), ('P21W', 'P21W'), ('PY21W', 'PY21W'), ('P21_5W', 'P21/5W'), ('R5W', 'R5W'), ('R10W', 'R10W'), ('C5W', 'C5W'), ('C10W', 'C10W'), ('BA9S', 'BA9S'), ('BA15S', 'BA15S'), ('BA15D', 'BA15D'), ('BAY15D', 'BAY15D'), ('BAU15S', 'BAU15S'), ('SV7', 'SV7'), ('SV8_5', 'SV8.5'), ('LED_H1', 'LED H1'), ('LED_H4', 'LED H4'), ('LED_H7', 'LED H7'), ('LED_H11', 'LED H11'), ('LED_W5W', 'LED W5W'), ('LED_P21W', 'LED P21W'), ('LED_P21_5W', 'LED P21/5W'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name="Type d'ampoule"),
        ),
    ]
