# Generated by Django 5.2.10 on 2026-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup_track', '0087_checkuptrack_phares_eclaire_plaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuptrack',
            name='freins_liquide_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('AJOUTER', 'Ajouté'), ('A_REMPLACER', 'A remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='État liquide de frein'),
        ),
    ]
