# Generated by Django 5.2.10 on 2026-03-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0003_alter_intervention_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='total_htva',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='total_tva',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='total_tvac',
        ),
        migrations.CreateModel(
            name='InterventionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pare_chocs_avant', 'Pare-chocs avant'), ('pare_chocs_arrière', 'Pare-chocs arrière'), ('bouclier_av', 'Bouclier avant'), ('bouclier_ar', 'Bouclier arrière'), ('pare_brise', 'Pare-brise'), ('vitre_porte_avd', 'Vitre porte avant droite'), ('vitre_porte_avg', 'Vitre porte avant gauche'), ('vitre_porte_ard', 'Vitre porte arrière droite'), ('vitre_porte_arg', 'Vitre porte arrière gauche'), ('lunette', 'Lunette arrière'), ('retroviseur_d', 'Rétroviseur droit'), ('retroviseur_g', 'Rétroviseur gauche'), ('aile_avd', 'Aile avant droite'), ('aile_avg', 'Aile avant gauche'), ('aile_ard', 'Aile arrière droite'), ('aile_arg', 'Aile arrière gauche'), ('elargisseur_aile_avd', 'Élargisseur aile avant droite'), ('elargisseur_aile_avg', 'Élargisseur aile avant gauche'), ('elargisseur_aile_ard', 'Élargisseur aile arrière droite'), ('elargisseur_aile_arg', 'Élargisseur aile arrière gauche'), ('bas_de_caisse_d', 'Bas de caisse droit'), ('bas_de_caisse_g', 'Bas de caisse gauche'), ('support_radiateur', 'Support radiateur'), ('support_pare_choc', 'Support pare-chocs'), ('calandre', 'Calandre'), ('porte_avd', 'Porte avant droite'), ('porte_avg', 'Porte avant gauche'), ('porte_ard', 'Porte arrière droite'), ('porte_arg', 'Porte arrière gauche'), ('poignee_porte', 'Poignée de porte'), ('coffre_haillon', 'Coffre / Hayon'), ('joint_coffre', 'Joint de coffre'), ('joint_porte_avd', 'Joint porte avant droite'), ('joint_porte_avg', 'Joint porte avant gauche'), ('joint_porte_ard', 'Joint porte arrière droite'), ('joint_porte_arg', 'Joint porte arrière gauche'), ('coquille_aile_avd', 'Coquille aile avant droite'), ('coquille_aile_avg', 'Coquille aile avant gauche'), ('coquille_aile_ard', 'Coquille aile arrière droite'), ('coquille_aile_arg', 'Coquille aile arrière gauche'), ('clips', 'Clips'), ('visserie', 'Visserie'), ('capot', 'Capot'), ('peinture_avant_gauche', 'Peinture avant gauche'), ('peinture_avant_droite', 'Peinture avant droite'), ('peinture_arriere_gauche', 'Peinture arrière gauche'), ('peinture_face_avant', 'Peinture face avant'), ('peinture_capot', 'Peinture capot'), ('peinture_arriere', 'Peinture arrière'), ('peinture_complete', 'Peinture complète'), ('phare_avd', 'Phare avant droit'), ('phare_avg', 'Phare avant gauche'), ('phare_ard', 'Feu arrière droit'), ('phare_arg', 'Feu arrière gauche'), ('clignotant_avd', 'Clignotant avant droit'), ('clignotant_avg', 'Clignotant avant gauche'), ('clignotant_ard', 'Clignotant arrière droit'), ('clignotant_arg', 'Clignotant arrière gauche'), ('anti_brouillard_avd', 'Anti-brouillard avant droit'), ('anti_brouillard_avg', 'Anti-brouillard avant gauche'), ('anti_brouillard_ar', 'Anti-brouillard ar'), ('troisieme_feux_stop', 'Troisième feu stop'), ('capteur_recul', 'Capteur de recul')], max_length=50, verbose_name='Type de pièce')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('montant_calcule', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intervention.intervention')),
            ],
        ),
        migrations.DeleteModel(
            name='PieceIntervention',
        ),
    ]
