# Generated by Django 5.2.10 on 2026-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0004_remove_intervention_total_htva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionitem',
            name='type',
            field=models.CharField(choices=[('pare_chocs_avant', 'Pare-chocs avant'), ('pare_chocs_arrière', 'Pare-chocs arrière'), ('bouclier_av', 'Bouclier avant'), ('bouclier_ar', 'Bouclier arrière'), ('pare_brise', 'Pare-brise'), ('vitre_porte_avd', 'Vitre de porte avant droite'), ('vitre_porte_avg', 'Vitre de porte avant gauche'), ('vitre_porte_ard', 'Vitre de porte arrière droite'), ('vitre_porte_arg', 'Vitre de porte arrière gauche'), ('lunette', 'Lunette arrière'), ('retroviseur_d', 'Rétroviseur droit'), ('retroviseur_g', 'Rétroviseur gauche'), ('aile_avd', 'Aile avant droite'), ('aile_avg', 'Aile avant gauche'), ('aile_ard', 'Aile arrière droite'), ('aile_arg', 'Aile arrière gauche'), ('elargisseur_aile_avd', "Élargisseur d'aile avant droite"), ('elargisseur_aile_avg', "Élargisseur d'aile avant gauche"), ('elargisseur_aile_ard', "Élargisseur d'aile arrière droite"), ('elargisseur_aile_arg', "Élargisseur d'aile arrière gauche"), ('bas_de_caisse_d', 'Bas de caisse droit'), ('bas_de_caisse_g', 'Bas de caisse gauche'), ('support_radiateur', 'Support de radiateur'), ('support_pare_choc', 'Support de pare-chocs'), ('calandre', 'Calandre'), ('porte_avd', 'Porte avant droite'), ('porte_avg', 'Porte avant gauche'), ('porte_ard', 'Porte arrière droite'), ('porte_arg', 'Porte arrière gauche'), ('poignee_porte', 'Poignée de porte'), ('coffre_haillon', 'Coffre / Hayon'), ('joint_coffre', 'Joint de coffre'), ('joint_porte_avd', 'Joint de porte avant droite'), ('joint_porte_avg', 'Joint de porte avant gauche'), ('joint_porte_ard', 'Joint de porte arrière droite'), ('joint_porte_arg', 'Joint de porte arrière gauche'), ('coquille_aile_avd', "Coquille d'aile avant droite"), ('coquille_aile_avg', "Coquille d'aile avant gauche"), ('coquille_aile_ard', "Coquille d'aile arrière droite"), ('coquille_aile_arg', "Coquille d'aile arrière gauche"), ('clips', 'Clips'), ('visserie', 'Visserie'), ('capot', 'Capot'), ('peinture_avant_gauche', 'Peinture avant gauche'), ('peinture_avant_droite', 'Peinture avant droite'), ('peinture_arriere_gauche', 'Peinture arrière gauche'), ('peinture_face_avant', 'Peinture face avant'), ('peinture_capot', 'Peinture capot'), ('peinture_arriere', 'Peinture arrière'), ('peinture_complete', 'Peinture complète'), ('phare_avd', 'Phare avant droit'), ('phare_avg', 'Phare avant gauche'), ('phare_ard', 'Feu arrière droit'), ('phare_arg', 'Feu arrière gauche'), ('clignotant_avd', 'Clignotant avant droit'), ('clignotant_avg', 'Clignotant avant gauche'), ('clignotant_ard', 'Clignotant arrière droit'), ('clignotant_arg', 'Clignotant arrière gauche'), ('anti_brouillard_avd', 'Anti-brouillard avant droit'), ('anti_brouillard_avg', 'Anti-brouillard avant gauche'), ('anti_brouillard_ar', 'Anti-brouillard arrière'), ('troisieme_feux_stop', 'Troisième feu stop'), ('capteur_recul', 'Capteur de recul')], max_length=50, verbose_name='Type de pièce'),
        ),
    ]
