# Generated by Django 5.2.10 on 2026-02-15 13:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assurance', '0008_alter_assurance_adresse'),
        ('voiture_exemplaire', '0005_voitureexemplaire_est_avant_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssurancePolice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrat', models.CharField(max_length=100, unique=True, verbose_name='Numéro de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('prime_mensuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prime mensuelle (€)')),
                ('prime_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prime annuelle (€)')),
                ('franchise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Franchise (€)')),
                ('type_couverture', models.CharField(choices=[('rc', 'RC (Responsabilité civile)'), ('mini_omnium', 'Mini-Omnium'), ('omnium', 'Omnium complète'), ('omnium_financiere', 'Omnium financière')], default='rc', max_length=20, verbose_name='Type de couverture')),
                ('bonus_malus', models.IntegerField(blank=True, null=True, verbose_name='Bonus-Malus')),
                ('conducteur_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conducteur principal')),
                ('actif', models.BooleanField(default=True, verbose_name='Police active')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polices', to='assurance.assurance')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polices_assurance', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'verbose_name': "Police d'assurance",
                'verbose_name_plural': "Polices d'assurance",
                'ordering': ['-date_debut'],
            },
        ),
    ]
