# Generated by Django 5.2.10 on 2026-02-15 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0008_alter_assurance_adresse'),
        ('assurance_police', '0001_initial'),
        ('voiture_exemplaire', '0005_voitureexemplaire_est_avant_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancepolice',
            name='conducteur_principal',
        ),
        migrations.AddField(
            model_name='assurancepolice',
            name='courtier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assurancepolice',
            name='document_pdf',
            field=models.FileField(blank=True, null=True, upload_to='assurances/polices/'),
        ),
        migrations.AddField(
            model_name='assurancepolice',
            name='frequence_paiement',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='annuel', max_length=10, verbose_name='Fréquence de paiement'),
        ),
        migrations.AddField(
            model_name='assurancepolice',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('virement', 'Virement'), ('domiciliation', 'Domiciliation'), ('cash', 'Cash'), ('carte', 'Carte bancaire')], max_length=15, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='assurance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='polices', to='assurance.assurance'),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='bonus_malus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='franchise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='numero_contrat',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='prime_annuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='prime_mensuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='type_couverture',
            field=models.CharField(choices=[('rc', 'Responsabilité civile'), ('mini_omnium', 'Mini-Omnium'), ('omnium', 'Omnium complète'), ('omnium_financiere', 'Omnium financière')], default='rc', max_length=20, verbose_name='Type de couverture'),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='polices_assurance', to='voiture_exemplaire.voitureexemplaire'),
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_sinistre', models.DateField()),
                ('description', models.TextField()),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('responsable', models.BooleanField(default=True, verbose_name='Responsable')),
                ('cloture', models.BooleanField(default=False)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to='assurance_police.assurancepolice')),
            ],
            options={
                'verbose_name': 'Sinistre',
                'verbose_name_plural': 'Sinistres',
                'ordering': ['-date_sinistre'],
            },
        ),
    ]
