# Generated by Django 5.2.10 on 2026-03-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_police', '0002_remove_assurancepolice_conducteur_principal_and_more'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurancepolice',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polices_assurance', to='societe.societe'),
        ),
    ]
