# Generated by Django 5.2.10 on 2026-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_police', '0003_assurancepolice_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurancepolice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='assurancepolice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
