# Generated by Django 5.2.10 on 2026-09-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0010_assurance_remarques_alter_assurance_created_at_and_more'),
        ('assurance_police', '0005_alter_assurancepolice_assurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurancepolice',
            name='assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polices', to='assurance.assurance'),
        ),
    ]
