"""
Django settings for dBSolutionV3 project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=zdo*1q=lgk$r*fgyntvok1v7*n8t_h@zaxm6v#50i%114wyc9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'dBSolutionV3',
    'app',
    'api',
    'societe',
    'societe_cliente',
    'fournisseur',

    "voiture_pneus.apps.VoiturePneusConfig",
    "voiture_pneus_historique.apps.VoiturePneusHistoriqueConfig",
    'voiture_client',
    'voiture_exemplaire',
    'voiture_location',
    'voiture_marque',
    'voiture_modele',
    'voiture_vente',
    'voiture_moteur',
    'voiture_prive',
    'voiture_boite',
    'voiture_embrayage',




    'piece',
    'piece_ligne_achat',
    'piece_ligne_inventaire',
    'piece_ligne_vente',
    'piece_mouvement_stock',
    'piece_stock',
    'piece_fournisseur',
    'piece_facture_entree',
    'piece_facture_sortie',
    'adresse',
    'rest_framework',
    'rest_framework.authtoken',

    # apps 2FA
    'django_otp',
    'django_otp.plugins.otp_totp',   # pour Google Authenticator
    'two_factor',

    'tailwind',
    'theme',
    "django_browser_reload",





]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # pour les langues
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # middleware OTP
    'django_otp.middleware.OTPMiddleware',# 2 facteurs


    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_browser_reload.middleware.BrowserReloadMiddleware',  # rechargement des pages




]

ROOT_URLCONF = 'dBSolutionV3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dBSolutionV3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),       # nom de la base
        'USER': os.environ.get('DB_USER'),         # utilisateur DB
        'PASSWORD': os.environ.get('DB_PASSWORD'),      # mot de passe
        'HOST': os.environ.get('DB_HOST'),           # hôte DB
        'PORT': os.environ.get('DB_PORT'),                # port DB
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/



LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('en-us', 'English'),
    ('nl', 'Nederlands'),
    ('de', 'Deutsch'),  # 🇩🇪 Allemand
    ('it', 'Italiano'),  # 🇮🇹 Italien
    ('el', 'Ελληνικά'),  # 🇬🇷 Grec
    ('es', 'Español'),  # 🇪🇸 Espagnol
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]



TIME_ZONE = 'Europe/Brussels'
USE_TZ = True


USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

TAILWIND_APP_NAME = 'theme'


import logging


logging.getLogger('django.server').addFilter(
    lambda record: 'Broken pipe' not in record.getMessage()
)



LANGUAGE_COOKIE_NAME = "django_language"