"""
Django settings for dBSolutionV3 project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=zdo*1q=lgk$r*fgyntvok1v7*n8t_h@zaxm6v#50i%114wyc9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

PUBLIC_SCHEMA_NAME = 'public'

# dans settings.py
TENANT_PUBLIC_SCHEMA_NAME = 'public'

# Application definition

# django-tenants (OBLIGATOIRE)
TENANT_MODEL = "societe.Societe"
TENANT_DOMAIN_MODEL = "societe.Domain"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SHARED_APPS = (
    'django_tenants',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'dBSolutionV3',

    'societe',
    'adresse',

    'rest_framework',
    'rest_framework.authtoken',

    # apps 2FA
    'django_otp',
    'django_otp.plugins.otp_totp',   # pour Google Authenticator
    'two_factor',

    'tailwind',
    'theme',

    'widget_tweaks',
    'django_filters',
    'crispy_forms',
    'django_extensions',
    'import_export',
    'allauth',
    'guardian',
    'django_celery_beat',
    'djmoney',
    'channels',

    'polymorphic',

    'chartjs',
    'anymail',

    'django_pandas',




)


TENANT_APPS = (

    'piece',
    'panier',
    'facture',

    'client',
    'client.societe_cliente',
    'fournisseur',
    'carrosserie',

    'outillage',
    'investissements',

    'maintenance',
    'maintenance.check_up',
    'maintenance.entretien',
    'maintenance.niveaux',
    'maintenance.jeux_pieces',
    'maintenance.freins',
    'maintenance.silent_blocs',
    'maintenance.bruits',
    'maintenance.controle_check_up',
    'maintenance.nettoyage_interieur',
    'maintenance.nettoyage_exterieur',


    #'piece.piece_ligne_achat',
    #'piece.piece_ligne_inventaire',
    #'piece.piece_ligne_vente',
    #'piece.piece_mouvement_stock',
    #'piece.piece_stock',
    #'piece.piece_fournisseur',
    #'piece.piece_facture_entree',
    #'piece.piece_facture_sortie',
    'piece.piece_ampoules',
    #'piece.piece_batterie',
    'piece.piece_boite',
    'piece.piece_carrosserie',
    'piece.piece_climatisation',
    'piece.piece_differentiel',
    'piece.piece_direction',
    'piece.piece_echappement',
    'piece.piece_electricite',
    'piece.piece_electronique',
    'piece.piece_embrayage',
    'piece.piece_essuyage',
    'piece.piece_feux',
    'piece.piece_filtres',
    'piece.piece_fluides',
    'piece.piece_freins',
    'piece.piece_habitacle',
    'piece.piece_jantes',
    'piece.piece_moteur',
    'piece.piece_pneus',
    #'piece.piece_pont',
    #'piece.piece_silent_bloc',
    #'piece.piece_suspension',
    'piece.piece_train_AV',
    'piece.piece_train_AR',
    #'piece.piece_transmission',
    'piece.piece_hydraulique',
    'piece.piece_roue_rechange',

    'voiture',
    'voiture.voiture_marque',
    'voiture.voiture_modele',
    'voiture.voiture_moteur',
    'voiture.voiture_boite',
    'voiture.voiture_embrayage',
    'voiture.voiture_exemplaire',
    'voiture.voiture_freins',
    'voiture.voiture_jantes',
    'voiture.voiture_vente',
    "voiture.voiture_pneus.apps.VoiturePneusConfig",
    "voiture.voiture_pneus_historique.apps.VoiturePneusHistoriqueConfig",




    'authentification',
    'utilisateurs',
    'utilisateurs.mecanicien',
    'utilisateurs.apprentis',
    'utilisateurs.chef_mecanicien',
    'utilisateurs.carrossier',
    'utilisateurs.comptabilite',
    'utilisateurs.direction',
    'utilisateurs.instructeur',
    'utilisateurs.magasinier',
    'utilisateurs.vendeur',







)

INSTALLED_APPS = list(SHARED_APPS) + list(TENANT_APPS)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'authentification.middleware.TOTPRequiredMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware',

]

ROOT_URLCONF = 'dBSolutionV3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "theme/templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend'
)

WSGI_APPLICATION = 'dBSolutionV3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import os


ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'dbsolution.localhost']

#ALLOWED_HOSTS = ['.mondomaine.be']


DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.environ.get('DB_NAME'),       # nom de la base
        'USER': os.environ.get('DB_USER'),         # utilisateur DB
        'PASSWORD': os.environ.get('DB_PASSWORD'),      # mot de passe
        'HOST': os.environ.get('DB_HOST'),           # hôte DB
        'PORT': os.environ.get('DB_PORT'),                # port DB
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/



LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
    ('nl', 'Nederlands'),
    ('de', 'Deutsch'),  # 🇩🇪 Allemand
    ('it', 'Italiano'),  # 🇮🇹 Italien
    ('el', 'Ελληνικά'),  # 🇬🇷 Grec
    ('es', 'Español'),  # 🇪🇸 Espagnol
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]



TIME_ZONE = 'Europe/Brussels'
USE_TZ = True


USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "theme", "static"),  # tes fichiers statiques Tailwind
]

# Où Django copiera tous les fichiers statiques lors de collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

TAILWIND_APP_NAME = 'theme'


import logging


logging.getLogger('django.server').addFilter(
    lambda record: 'Broken pipe' not in record.getMessage()
)



LANGUAGE_COOKIE_NAME = "django_language"



PEPPOL_ENV = "TEST"  # ou "PROD"

PEPPOL_ACCESS_POINT_URL = {
    "TEST": "https://sandbox.accesspoint.peppol.eu/v1/invoices",
    "PROD": "https://api.ap.example/v1/invoices"
}[PEPPOL_ENV]

PEPPOL_API_KEY = "YOUR_TEST_API_KEY"
""""
PEPPOL_API_KEY = {
    "TEST": "test_xxxxx",
    "PROD": "prod_xxxxx"
}[PEPPOL_ENV]
"""





LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


SESSION_EXPIRE_AT_BROWSER_CLOSE = True
