"""
Django settings for dBSolutionV3 project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
import logging

BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------------------

SECRET_KEY = 'django-insecure-CHANGE-ME-IN-PROD'
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'dbsolution.localhost']

# ------------------------------------------------------------------------------
# DJANGO-TENANTS
# ------------------------------------------------------------------------------

TENANT_PUBLIC_SCHEMA_NAME = 'public'



TENANT_MODEL = "societe.Societe"
TENANT_DOMAIN_MODEL = "societe.Domain"  # Peut rester vide si tu n'utilises pas de sous-domaines

PUBLIC_SCHEMA_NAME = 'public'

DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)

# Important : désactiver le domaine pour path-based routing
USE_TENANT_DOMAINS = False


# ------------------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------------------

SHARED_APPS = (
    'django_tenants',
    'utilisateurs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Core
    'dBSolutionV3',

    # Libs
    'rest_framework',
    'rest_framework.authtoken',
    'guardian',

    # 2FA
    'django_otp',
    'django_otp.plugins.otp_totp',
    'two_factor',

    # Front
    'tailwind',
    'theme',
    'widget_tweaks',

    # Utils
    'django_filters',
    'crispy_forms',
    'django_extensions',
    'import_export',
    'django_celery_beat',
    'djmoney',
    'channels',
    'polymorphic',
    'chartjs',
    'anymail',
    'django_pandas',




    'adresse',
    'societe',
)



TENANT_APPS = (

    'piece',
    'panier',
    'facture',

    'client',
    'societe_cliente',
    'fournisseur',
    'carrosserie',
    'intervention',

    'outillage',
    'investissements',

    'maintenance',
    'maintenance.entretien',
    'maintenance.niveaux',
    'maintenance.jeux_pieces',
    'maintenance.freins',
    'maintenance.silent_blocs',
    'maintenance.bruits',
    'maintenance.check_up',
    'maintenance.nettoyage_interieur',
    'maintenance.nettoyage_exterieur',

    'fuel',


    #'piece.piece_ligne_achat',
    #'piece.piece_ligne_inventaire',
    #'piece.piece_ligne_vente',
    #'piece.piece_mouvement_stock',
    #'piece.piece_stock',
    #'piece.piece_fournisseur',
    #'piece.piece_facture_entree',
    #'piece.piece_facture_sortie',
    'piece.piece_ampoules',
    'piece.piece_batterie',
    'piece.piece_boite',
    'piece.piece_carrosserie',
    'piece.piece_climatisation',
    'piece.piece_differentiel',
    'piece.piece_direction',
    'piece.piece_echappement',
    'piece.piece_electricite',
    'piece.piece_electronique',
    'piece.piece_embrayage',
    'piece.piece_essuyage',
    'piece.piece_feux',
    'piece.piece_filtres',
    'piece.piece_fluides',
    'piece.piece_freins',
    'piece.piece_habitacle',
    'piece.piece_jantes',
    'piece.piece_moteur',
    'piece.piece_pneus',
    'piece.piece_pont',
    'piece.piece_silent_bloc',
    'piece.piece_suspension',
    'piece.piece_train_AV',
    'piece.piece_train_AR',
    'piece.piece_transmission',
    'piece.piece_hydraulique',
    'piece.piece_roue_rechange',
    'piece.piece_distribution',

    'voiture',
    'voiture.voiture_marque',
    'voiture.voiture_modele',
    'voiture.voiture_moteur',
    'voiture.voiture_boite',
    'voiture.voiture_embrayage',
    'voiture.voiture_exemplaire',
    'voiture.voiture_freins',
    'voiture.voiture_freins_ar',
    'voiture.voiture_jantes',
    'voiture.voiture_vente',
    "voiture.voiture_pneus.apps.VoiturePneusConfig",
    "voiture.voiture_pneus_historique.apps.VoiturePneusHistoriqueConfig",


    'utilisateurs.mecanicien',
    'utilisateurs.apprentis',
    'utilisateurs.chef_mecanicien',
    'utilisateurs.carrossier',
    'utilisateurs.comptabilite',
    'utilisateurs.direction',
    'utilisateurs.instructeur',
    'utilisateurs.instructeur_externe',
    'utilisateurs.magasinier',
    'utilisateurs.vendeur',

    'tenant',








)

INSTALLED_APPS = list(SHARED_APPS) + list(TENANT_APPS)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'tailwind'
# ------------------------------------------------------------------------------
# AUTHENTIFICATION
# ------------------------------------------------------------------------------

AUTH_USER_MODEL = "utilisateurs.Utilisateur"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
]

LOGIN_URL = '/fr/login/'
LOGIN_REDIRECT_URL = '/fr/'
LOGOUT_REDIRECT_URL = '/fr/login/'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SECURE_SSL_REDIRECT = False  # True seulement si tu passes par Nginx
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True



# ------------------------------------------------------------------------------
# MIDDLEWARE (ORDRE CRITIQUE)
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'utilisateurs.middleware.TOTPRequiredMiddleware',


    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "dBSolutionV3.middleware.tenant_required.TenantRequiredMiddleware",
]

# ------------------------------------------------------------------------------
# URLS / TEMPLATES
# ------------------------------------------------------------------------------

ROOT_URLCONF = 'dBSolutionV3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "theme/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dBSolutionV3.wsgi.application'
STATIC_VERSION = '1.0'

# ------------------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}

# ------------------------------------------------------------------------------
# PASSWORDS
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------------------------------
# I18N
# ------------------------------------------------------------------------------

LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
    ('nl', 'Nederlands'),
    ('de', 'Deutsch'),
    ('it', 'Italiano'),
    ('el', 'Ελληνικά'),
    ('es', 'Español'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Europe/Brussels'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGE_COOKIE_NAME = "django_language"

# ------------------------------------------------------------------------------
# STATIC FILES
# ------------------------------------------------------------------------------

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "theme" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

TAILWIND_APP_NAME = 'theme'

# ------------------------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------------------------

logging.getLogger('django.server').addFilter(
    lambda record: 'Broken pipe' not in record.getMessage()
)