# Generated by Django 5.2.10 on 2026-07-05 12:40

import django.core.validators
import django.db.models.deletion
import utils.mixin
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maindoeuvre', '0008_alter_maindoeuvre_taux_horaire'),
        ('maintenance', '0011_alter_maintenance_type_maintenance'),
        ('piece', '0003_alter_piece_emplacement_etagere_alter_piece_pays_and_more'),
        ('societe', '0004_societe_adresse'),
        ('voiture_exemplaire', '0024_voitureexemplaire_kilometres_rodage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis')),
                ('kilometres_rodage', models.PositiveIntegerField(verbose_name='Kilométrage au moment du rodage')),
                ('moteur_rodage_vidange', models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile moteur")),
                ('filtre_huile', models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacement du filtre à huile moteur')),
                ('moteur_bouchon_vidange', models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le bouchon de vidange')),
                ('moteur_joint_vidange', models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le joint du bouchon de vidange')),
                ('moteur_ajout_huile', models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Ajout de la nouvelle huile moteur')),
                ('moteur_ajout_huile_qualite', models.CharField(choices=[('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile")),
                ('moteur_ajout_huile_quantite', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name="Quantité d'huile moteur ajoutée en litres")),
                ('lave_glace_liquide_etat', models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace')),
                ('lave_glace_quantite', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de lave glace ajoutée en litres')),
                ('lave_glace_qualite', models.CharField(choices=[('HIVER', 'Hiver'), ('ETE', 'Eté')], default='HIVER', max_length=25, verbose_name='Qualité de liquide de lave glace')),
                ('frein_liquide_etat', models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins')),
                ('frein_liquide_quantite', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de freins ajoutée en litres')),
                ('frein_liquide_qualite', models.CharField(choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=25, verbose_name='Qualité de liquide de freins')),
                ('refroidissement_liquide_etat', models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement')),
                ('refroidissement_liquide_quantite', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de refroidissement ajouté en litres')),
                ('refroidissement_liquide_qualite', models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité de liquide de refroidissement')),
                ('liquide_direction_etat', models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction')),
                ('liquide_direction_quantite', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de direction ajouté en litres')),
                ('liquide_direction_qualite', models.CharField(choices=[('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('CHF_1_PLUS', 'CHF 1+'), ('CHF_LIFEGUARD', 'CHF Lifeguard Fluid'), ('PORSCHE_CHF_11S', 'Porsche / Pentosin CHF 11S (direction assistée)'), ('PORSCHE_CHF_202', 'Porsche / Pentosin CHF 202 (hydraulique moderne)'), ('PORSCHE_ATF_D3', 'Porsche ATF Dexron III (anciens modèles)'), ('BMW_CHF_11S', 'BMW / Pentosin CHF 11S (direction assistée)'), ('BMW_CHF_202', 'BMW / Pentosin CHF 202 (direction assistée moderne)'), ('BMW_CHF_7_1', 'BMW CHF 7.1 (anciens systèmes hydrauliques)'), ('BMW_ATF_D3', 'BMW ATF Dexron III (anciens modèles direction assistée)'), ('RENAULT_MATIC_D2', 'Renaultmatic D2 (ELF)'), ('RENAULT_MATIC_D3_SYN', 'Renaultmatic D3 SYN (ELF)'), ('ELF_MATIC_G3', 'ELF Matic G3'), ('RENAULT_PSF_D3', 'Renault PSF Dexron III (direction assistée hydraulique)'), ('RENAULT_ELF_PSF', 'Renault / ELF liquide direction assistée'), ('PSF_HYUNDAI_KIA', 'PSF Hyundai / Kia'), ('PSF_TOYOTA', 'PSF Toyota'), ('PSF_HONDA', 'PSF Honda'), ('UNIVERSAL_PSF', 'Liquide direction assistée universel')], default='UNIVERSAL_PSF', max_length=25, verbose_name='Qualité de liquide de direction')),
                ('phares_avant', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de route')),
                ('phares_gros_phares', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Grand phares')),
                ('phares_clignotants', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Clignotants')),
                ('phares_recul', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de recul')),
                ('phares_anti_brouillard_avant', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phares anti-brouillard avant')),
                ('phares_anti_brouillard_arriere', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Phares anti-brouillard arrière')),
                ('feux_stops', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux stop')),
                ('troisieme_feux_stop', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Troisième feux stop')),
                ('feux_position_av', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de position avant')),
                ('feux_position_ar', models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Feux de position arrière')),
                ('pneu_pression_bar_avd', models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu avant droit en bar')),
                ('pneu_pression_bar_avg', models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu avant gauche en bar')),
                ('pneu_pression_bar_ard', models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu arrière droit en bar')),
                ('pneu_pression_bar_arg', models.FloatField(default=2.4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Pression du pneu arrière gauche en bar')),
                ('serrage_roues', models.CharField(choices=[('AFAIRE', 'À faire'), ('Fait', 'Fait')], default='AFAIRE', max_length=25, verbose_name='Serrage des roues')),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodage', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre")),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rodage', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodage_piece', to='piece.piece')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='societe.societe')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodage_societe', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodage', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rodage', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'verbose_name': 'Rodage',
                'verbose_name_plural': 'Rodages',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
