# Generated by Django 5.2.10 on 2026-07-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodage',
            old_name='filtre_huile',
            new_name='moteur_filtre_huile',
        ),
        migrations.RenameField(
            model_name='rodage',
            old_name='feux_position_ar',
            new_name='phares_feux_position_ar',
        ),
        migrations.RenameField(
            model_name='rodage',
            old_name='feux_position_av',
            new_name='phares_feux_position_av',
        ),
        migrations.RenameField(
            model_name='rodage',
            old_name='feux_stops',
            new_name='phares_feux_stops',
        ),
        migrations.RenameField(
            model_name='rodage',
            old_name='troisieme_feux_stop',
            new_name='phares_troisieme_feux_stop',
        ),
    ]
