# Generated by Django 5.2.10 on 2026-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0003_alter_rodage_serrage_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodage',
            name='frein_liquide_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='rodage',
            name='lave_glace_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='rodage',
            name='liquide_direction_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='rodage',
            name='moteur_ajout_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='rodage',
            name='moteur_bouchon_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='rodage',
            name='moteur_bouchon_vidange_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='rodage',
            name='moteur_filtre_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='rodage',
            name='moteur_filtre_huile_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='rodage',
            name='moteur_joint_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='rodage',
            name='moteur_joint_vidange_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='rodage',
            name='refroidissement_prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Prix d'achat HTVA"),
        ),
    ]
