# Generated by Django 5.2.10 on 2026-08-12 10:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0009_rodage_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodage',
            name='pneu_pression_bar_ard',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.4'), max_digits=4, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='pneu_pression_bar_arg',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.4'), max_digits=4, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='pneu_pression_bar_avd',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.4'), max_digits=4, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='pneu_pression_bar_avg',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.4'), max_digits=4, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu avant gauche en bar'),
        ),
    ]
