# Generated by Django 5.2.10 on 2026-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0012_rename_lave_glace_liquide_etat_rodage_lave_glace_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodage',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
