# Generated by Django 5.2.10 on 2026-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0013_rodage_kilometrage_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodage',
            name='frein_liquide_qualite',
            field=models.CharField(choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='lave_glace_qualite',
            field=models.CharField(choices=[('HIVER', 'Hiver'), ('ETE', 'Eté')], default='HIVER', max_length=25, verbose_name='Qualitée'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='liquide_direction_qualite',
            field=models.CharField(choices=[('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('CHF_1_PLUS', 'CHF 1+'), ('CHF_LIFEGUARD', 'CHF Lifeguard Fluid'), ('PORSCHE_CHF_11S', 'Porsche / Pentosin CHF 11S (direction assistée)'), ('PORSCHE_CHF_202', 'Porsche / Pentosin CHF 202 (hydraulique moderne)'), ('PORSCHE_ATF_D3', 'Porsche ATF Dexron III (anciens modèles)'), ('BMW_CHF_11S', 'BMW / Pentosin CHF 11S (direction assistée)'), ('BMW_CHF_202', 'BMW / Pentosin CHF 202 (direction assistée moderne)'), ('BMW_CHF_7_1', 'BMW CHF 7.1 (anciens systèmes hydrauliques)'), ('BMW_ATF_D3', 'BMW ATF Dexron III (anciens modèles direction assistée)'), ('RENAULT_MATIC_D2', 'Renaultmatic D2 (ELF)'), ('RENAULT_MATIC_D3_SYN', 'Renaultmatic D3 SYN (ELF)'), ('ELF_MATIC_G3', 'ELF Matic G3'), ('RENAULT_PSF_D3', 'Renault PSF Dexron III (direction assistée hydraulique)'), ('RENAULT_ELF_PSF', 'Renault / ELF liquide direction assistée'), ('PSF_HYUNDAI_KIA', 'PSF Hyundai / Kia'), ('PSF_TOYOTA', 'PSF Toyota'), ('PSF_HONDA', 'PSF Honda'), ('UNIVERSAL_PSF', 'Liquide direction assistée universel')], default='UNIVERSAL_PSF', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='refroidissement_liquide_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité'),
        ),
    ]
