# Generated by Django 5.2.10 on 2026-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0014_alter_rodage_frein_liquide_qualite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodage',
            name='lave_glace_qualite',
            field=models.CharField(choices=[('HIVER', 'Hiver'), ('ETE', 'Eté')], default='HIVER', max_length=25, verbose_name='Qualité'),
        ),
    ]
