# Generated by Django 5.2.10 on 2026-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0019_rodage_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodage',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Liquide de freins'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='lave_glace_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='lave_glace_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='liquide_direction_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Liquide de direction'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='liquide_direction_qualite',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('CHF_1_PLUS', 'CHF 1+'), ('CHF_LIFEGUARD', 'CHF Lifeguard Fluid'), ('PORSCHE_CHF_11S', 'Porsche / Pentosin CHF 11S (direction assistée)'), ('PORSCHE_CHF_202', 'Porsche / Pentosin CHF 202 (hydraulique moderne)'), ('PORSCHE_ATF_D3', 'Porsche ATF Dexron III (anciens modèles)'), ('BMW_CHF_11S', 'BMW / Pentosin CHF 11S (direction assistée)'), ('BMW_CHF_202', 'BMW / Pentosin CHF 202 (direction assistée moderne)'), ('BMW_CHF_7_1', 'BMW CHF 7.1 (anciens systèmes hydrauliques)'), ('BMW_ATF_D3', 'BMW ATF Dexron III (anciens modèles direction assistée)'), ('RENAULT_MATIC_D2', 'Renaultmatic D2 (ELF)'), ('RENAULT_MATIC_D3_SYN', 'Renaultmatic D3 SYN (ELF)'), ('ELF_MATIC_G3', 'ELF Matic G3'), ('RENAULT_PSF_D3', 'Renault PSF Dexron III (direction assistée hydraulique)'), ('RENAULT_ELF_PSF', 'Renault / ELF liquide direction assistée'), ('PSF_HYUNDAI_KIA', 'PSF Hyundai / Kia'), ('PSF_TOYOTA', 'PSF Toyota'), ('PSF_HONDA', 'PSF Honda'), ('UNIVERSAL_PSF', 'Liquide direction assistée universel')], default='CHOISIR', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Ajout de l'huile moteur"),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_bouchon_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Bouchon de vidange'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_filtre_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Filtre à huile moteur'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_filtre_huile_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KN', 'KN'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_joint_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Joint du bouchon de vidange'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_rodage_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile moteur"),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='refroidissement_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='refroidissement_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
