# Generated by Django 5.2.10 on 2026-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0020_alter_rodage_frein_liquide_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodage',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Liquide de freins'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='frein_liquide_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='lave_glace_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='lave_glace_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='liquide_direction_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Liquide de direction'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='liquide_direction_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_ajout_huile_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_ajout_huile_qualite',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_bouchon_vidange_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_joint_vidange_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='refroidissement_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACE', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='refroidissement_liquide_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='refroidissement_liquide_qualite',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant'), ('CONSTRUCTEUR', 'Constructeur')], default='G13', max_length=25, verbose_name='Qualité'),
        ),
    ]
