# Generated by Django 5.2.10 on 2026-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodage', '0023_alter_rodage_frein_liquide_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodage',
            name='moteur_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Ajout de l'huile moteur"),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_bouchon_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Bouchon de vidange'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_filtre_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Filtre à huile moteur'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_joint_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Joint du bouchon de vidange'),
        ),
        migrations.AlterField(
            model_name='rodage',
            name='moteur_rodage_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REMPLACE', 'Remplacé'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile moteur"),
        ),
    ]
