# Generated by Django 5.2.10 on 2026-02-04 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureJante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taille_jante_av', models.FloatField(verbose_name='Taille jante AV (pouces)')),
                ('taille_jante_ar', models.FloatField(verbose_name='Taille jante AR (pouces)')),
                ('deport_av', models.CharField(max_length=10, verbose_name='Déport AV (ETXX)')),
                ('deport_ar', models.CharField(max_length=10, verbose_name='Déport AR (ETXX)')),
                ('profil', models.CharField(max_length=10, verbose_name='Profil (XXXX)')),
                ('nouvelles_montes', models.ManyToManyField(blank=True, related_name='compatible_jantes', to='voiture_jantes.voiturejante', verbose_name='Nouvelle monte')),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='jantes', to='voiture_exemplaire.voitureexemplaire')),
                ('voitures_modeles', models.ManyToManyField(blank=True, related_name='jantes', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Voiture – jante',
                'verbose_name_plural': 'Voitures – jantes',
            },
        ),
    ]
