# Generated by Django 5.2.9 on 2025-12-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceRoueRechange',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('sites', models.CharField(choices=[('BE', 'Belgique'), ('GE', 'Germany'), ('O', 'Other')], max_length=20)),
                ('side', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière')], max_length=20)),
                ('type_roue', models.CharField(choices=[('SLICK', 'Slick'), ('SEMI-SLICK', 'Semi-slick'), ('PLUIE', 'Pluie'), ('NEIGE', 'Neige')], max_length=20)),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
            bases=('piece.piece',),
        ),
    ]
