# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceRoueRechange',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('sites', models.CharField(choices=[('BE', 'Belgique'), ('GE', 'Allemagne'), ('O', 'Autre')], max_length=20, verbose_name='Site')),
                ('side', models.CharField(choices=[('AV', 'Avant'), ('AR', 'Arrière')], max_length=20, verbose_name='Côté')),
                ('type_roue', models.CharField(choices=[('SLICK', 'Slick'), ('SEMI-SLICK', 'Semi-slick'), ('PLUIE', 'Pluie'), ('NEIGE', 'Neige')], max_length=20, verbose_name='Type de roue')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
            ],
            options={
                'verbose_name': 'Roue de rechange',
                'verbose_name_plural': 'Roues de rechange',
            },
            bases=('piece.piece',),
        ),
    ]
