# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructeurExterne',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role_direction', models.CharField(default='Instructeur', max_length=50)),
                ('numero_facture', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('facture', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('utilisateurs.utilisateur',),
        ),
    ]
