# Generated by Django 6.0 on 2026-01-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructeur_externe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructeurexterne',
            name='role_direction',
        ),
    ]
