# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceHabitacle',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
            ],
            options={
                'verbose_name': 'Pièce habitacle',
                'verbose_name_plural': 'Pièces habitacle',
            },
            bases=('piece.piece',),
        ),
        migrations.CreateModel(
            name='Airbag',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
                ('position', models.CharField(choices=[('conducteur', 'Conducteur'), ('passager', 'Passager'), ('lat_gauche', 'Latéral gauche'), ('lat_droit', 'Latéral droit'), ('siege_conducteur', 'Siège conducteur'), ('siege_passager', 'Siège passager'), ('sieges_ar_droit', 'Sièges arrière droit'), ('sieges_ar_gauche', 'Sièges arrière gauche')], max_length=20, verbose_name="Position de l'airbag")),
            ],
            options={
                'verbose_name': 'Airbag',
                'verbose_name_plural': 'Airbags',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='CeintureSecurite',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
            ],
            options={
                'verbose_name': 'Ceinture de sécurité',
                'verbose_name_plural': 'Ceintures de sécurité',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='CompteursCommodo',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
            ],
            options={
                'verbose_name': 'Compteurs / Commodo',
                'verbose_name_plural': 'Compteurs / Commodo',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
            ],
            options={
                'verbose_name': 'GPS',
                'verbose_name_plural': 'GPS',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='Harnais',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
            ],
            options={
                'verbose_name': 'Harnais',
                'verbose_name_plural': 'Harnais',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
                ('type_siege', models.CharField(choices=[('conducteur', 'Siège conducteur'), ('passager', 'Siège passager'), ('ar_droit', 'Siège arrière droit'), ('ar_gauche', 'Siège arrière gauche')], max_length=20, verbose_name='Type de siège')),
            ],
            options={
                'verbose_name': 'Siège',
                'verbose_name_plural': 'Sièges',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='Tapis',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
            ],
            options={
                'verbose_name': 'Tapis',
                'verbose_name_plural': 'Tapis',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
        migrations.CreateModel(
            name='Volant',
            fields=[
                ('piecehabitacle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece_habitacle.piecehabitacle')),
            ],
            options={
                'verbose_name': 'Volant',
                'verbose_name_plural': 'Volants',
            },
            bases=('piece_habitacle.piecehabitacle',),
        ),
    ]
