# Generated by Django 6.0 on 2025-12-14 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_pneus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiturePneusHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_pneus', models.CharField(max_length=20)),
                ('pneus_avant', models.CharField(max_length=15)),
                ('pneus_arriere', models.CharField(max_length=15)),
                ('kilometres_effectues', models.PositiveIntegerField()),
                ('date_remplacement', models.DateField(auto_now_add=True)),
                ('numero_remplacement', models.PositiveSmallIntegerField()),
                ('voiture_pneus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='voiture_pneus.voiturepneus')),
            ],
        ),
    ]
