# Generated by Django 5.2.10 on 2026-08-17 09:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maindoeuvre', '0013_alter_maindoeuvre_utilisateur'),
        ('maintenance', '0020_alter_maintenance_type_maintenance'),
        ('societe', '0010_alter_societe_numero_tel'),
        ('voiture_exemplaire', '0025_alter_voitureexemplaire_est_apres_2010_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('pays', models.CharField(choices=[('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('CZ', 'Tchéquie'), ('DE', 'Allemagne'), ('DK', 'Danemark'), ('EE', 'Estonie'), ('ES', 'Espagne'), ('FI', 'Finlande'), ('FR', 'France'), ('GR', 'Grèce'), ('HR', 'Croatie'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('IT', 'Italie'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('LV', 'Lettonie'), ('MT', 'Malte'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SE', 'Suède'), ('SI', 'Slovénie'), ('SK', 'Slovaquie')], default='BE', max_length=5, verbose_name='Pays')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis')),
                ('kilometrage_injection', models.PositiveIntegerField(verbose_name="Kilométrage du contrôle de l'injection")),
                ('type_carburant', models.CharField(choices=[('ESSENCE', 'Essence'), ('ETHANOL', 'Éthanol / E85'), ('DIESEL', 'Diesel'), ('CNG', 'CNG / Gaz naturel'), ('LPG', 'LPG / GPL'), ('HYDROGENE', 'Hydrogène'), ('AUTRE', 'Autre')], default='ESSENCE', max_length=20, verbose_name='Type de carburant')),
                ('pompe_carburant_etat', models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='État de la pompe à carburant')),
                ('pompe_carburant_fabricant', models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('VDO', 'VDO'), ('PIERBURG', 'Pierburg'), ('HITACHI', 'Hitachi'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('WALBRO', 'Walbro'), ('TI_AUTOMOTIVE', 'TI Automotive'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='INCONNU', max_length=50, verbose_name='Fabricant de la pompe à carburant')),
                ('pompe_carburant_pression_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pression de la pompe à carburant en bar')),
                ('pompe_carburant_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix de la pompe à carburant')),
                ('pompe_carburant_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité de pompes à carburant')),
                ('pompe_haute_pression_etat', models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='NON_APPLICABLE', max_length=20, verbose_name='État de la pompe haute pression')),
                ('pompe_haute_pression_fabricant', models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HITACHI', 'Hitachi'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='INCONNU', max_length=50, verbose_name='Fabricant de la pompe haute pression')),
                ('pompe_haute_pression_pression_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pression de la pompe haute pression en bar')),
                ('pompe_haute_pression_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix de la pompe haute pression')),
                ('pompe_haute_pression_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité de pompes haute pression')),
                ('rampe_injection_etat', models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name="État de la rampe d'injection")),
                ('rampe_injection_fabricant', models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HITACHI', 'Hitachi'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='INCONNU', max_length=50, verbose_name="Fabricant de la rampe d'injection")),
                ('rampe_injection_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix de la rampe d'injection")),
                ('rampe_injection_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de rampes d'injection")),
                ('capteur_pression_rampe_etat', models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='État du capteur de pression de rampe')),
                ('capteur_pression_rampe_fabricant', models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HELLA', 'Hella'), ('FACET', 'Facet'), ('FAE', 'FAE'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='INCONNU', max_length=50, verbose_name='Fabricant du capteur de pression de rampe')),
                ('pression_rampe_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pression de rampe mesurée en bar')),
                ('capteur_pression_rampe_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix du capteur de pression de rampe')),
                ('capteur_pression_rampe_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité de capteurs de pression de rampe')),
                ('tuyaux_haute_pression_etat', models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='NON_APPLICABLE', max_length=20, verbose_name='État des tuyaux haute pression')),
                ('tuyaux_haute_pression_fabricant', models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='INCONNU', max_length=50, verbose_name='Fabricant des tuyaux haute pression')),
                ('tuyaux_haute_pression_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix des tuyaux haute pression')),
                ('tuyaux_haute_pression_quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité de tuyaux haute pression')),
                ('injecteurs_etat', models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='État des injecteurs')),
                ('nombre_injecteurs', models.PositiveSmallIntegerField(default=4, verbose_name="Nombre d'injecteurs")),
                ('injecteurs_fabricant', models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('SIEMENS', 'Siemens'), ('HITACHI', 'Hitachi'), ('KEIHIN', 'Keihin'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='INCONNU', max_length=50, verbose_name='Fabricant des injecteurs')),
                ('injecteurs_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix unitaire d'un injecteur")),
                ('injecteurs_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité d'injecteurs remplacés")),
                ('injecteur_1_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 1 en ohms')),
                ('injecteur_2_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 2 en ohms')),
                ('injecteur_3_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 3 en ohms')),
                ('injecteur_4_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 4 en ohms')),
                ('injecteur_5_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 5 en ohms')),
                ('injecteur_6_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 6 en ohms')),
                ('injecteur_7_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 7 en ohms')),
                ('injecteur_8_resistance_ohm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Résistance injecteur 8 en ohms')),
                ('nettoyage_injecteurs', models.BooleanField(default=False, verbose_name='Nettoyage des injecteurs effectué')),
                ('nettoyage_injecteurs_quantite', models.PositiveSmallIntegerField(default=0, verbose_name="Nombre d'injecteurs nettoyés")),
                ('nettoyage_injecteurs_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix du nettoyage des injecteurs')),
                ('connecteurs_injecteurs_etat', models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name="État des connecteurs d'injecteurs")),
                ('connecteurs_injecteurs_fabricant', models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('TE_CONNECTIVITY', 'TE Connectivity'), ('AMP', 'AMP'), ('MOLEX', 'Molex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='INCONNU', max_length=50, verbose_name="Fabricant des connecteurs d'injecteurs")),
                ('connecteurs_injecteurs_prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix des connecteurs d'injecteurs")),
                ('connecteurs_injecteurs_quantite', models.PositiveIntegerField(default=0, verbose_name="Quantité de connecteurs d'injecteurs remplacés")),
                ('diagnostic_effectue', models.BooleanField(default=False, verbose_name="Diagnostic du système d'injection effectué")),
                ('code_defaut', models.CharField(blank=True, max_length=255, verbose_name='Codes défaut')),
                ('resultat_diagnostic', models.TextField(blank=True, verbose_name='Résultat du diagnostic')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('taux_horaire', models.DecimalField(choices=[(Decimal('0.00'), '0,00 €'), (Decimal('25.00'), '25,00 €'), (Decimal('30.00'), '30,00 €'), (Decimal('35.00'), '35,00 €'), (Decimal('40.00'), '40,00 €'), (Decimal('45.00'), '45,00 €'), (Decimal('50.00'), '50,00 €'), (Decimal('55.00'), '55,00 €'), (Decimal('60.00'), '60,00 €'), (Decimal('65.00'), '65,00 €'), (Decimal('70.00'), '70,00 €'), (Decimal('75.00'), '75,00 €'), (Decimal('80.00'), '80,00 €'), (Decimal('85.00'), '85,00 €'), (Decimal('90.00'), '90,00 €'), (Decimal('95.00'), '95,00 €'), (Decimal('100.00'), '100,00 €'), (Decimal('105.00'), '105,00 €'), (Decimal('11.00'), '110,00 €'), (Decimal('115.00'), '115,00 €'), (Decimal('120.00'), '120,00 €'), (Decimal('125.00'), '125,00 €'), (Decimal('130.00'), '130,00 €')], decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Taux horaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre")),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injection', to='maintenance.maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Injection',
                'verbose_name_plural': 'Injections',
                'ordering': ['-id'],
            },
        ),
    ]
