# Generated by Django 5.2.10 on 2026-08-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injection',
            name='observations',
        ),
    ]
