# Generated by Django 5.2.10 on 2026-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0002_remove_injection_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injection',
            old_name='nettoyage_injecteurs',
            new_name='nettoyage_injecteurs_etat',
        ),
        migrations.AlterField(
            model_name='injection',
            name='capteur_pression_rampe_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HELLA', 'Hella'), ('FACET', 'Facet'), ('FAE', 'FAE'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=50, verbose_name='Fabricant du capteur de pression de rampe'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='connecteurs_injecteurs_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('TE_CONNECTIVITY', 'TE Connectivity'), ('AMP', 'AMP'), ('MOLEX', 'Molex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=50, verbose_name="Fabricant des connecteurs d'injecteurs"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injecteurs_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('SIEMENS', 'Siemens'), ('HITACHI', 'Hitachi'), ('KEIHIN', 'Keihin'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=50, verbose_name='Fabricant des injecteurs'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_carburant_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('VDO', 'VDO'), ('PIERBURG', 'Pierburg'), ('HITACHI', 'Hitachi'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('WALBRO', 'Walbro'), ('TI_AUTOMOTIVE', 'TI Automotive'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=50, verbose_name='Fabricant de la pompe à carburant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_haute_pression_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HITACHI', 'Hitachi'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=50, verbose_name='Fabricant de la pompe haute pression'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='rampe_injection_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HITACHI', 'Hitachi'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=50, verbose_name="Fabricant de la rampe d'injection"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='tuyaux_haute_pression_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=50, verbose_name='Fabricant des tuyaux haute pression'),
        ),
    ]
