# Generated by Django 5.2.10 on 2026-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0003_rename_nettoyage_injecteurs_injection_nettoyage_injecteurs_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injection',
            name='nettoyage_injecteurs_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='Nettoyage des injecteurs effectué'),
        ),
    ]
