# Generated by Django 5.2.10 on 2026-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0005_alter_injection_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
