# Generated by Django 5.2.10 on 2026-09-23 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0010_injection_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injection',
            name='capteur_pression_rampe_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='État du capteur de pression de rampe'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='connecteurs_injecteurs_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name="État des connecteurs d'injecteurs"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injecteurs_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='État des injecteurs'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='nettoyage_injecteurs_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('NETTOYE', 'Nettoyé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='Nettoyage des injecteurs effectué'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='nettoyage_injecteurs_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix du nettoyage par injecteur'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_carburant_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name='État de la pompe à carburant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_haute_pression_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_APPLICABLE', 'Non applicable')], default='NON_APPLICABLE', max_length=20, verbose_name='État de la pompe haute pression'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='rampe_injection_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_APPLICABLE', 'Non applicable')], default='OK', max_length=20, verbose_name="État de la rampe d'injection"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='tuyaux_haute_pression_etat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_CONTROLER', 'À contrôler'), ('NOT_OK', 'À remplacer'), ('REMPLACE', 'Remplacé'), ('NON_APPLICABLE', 'Non applicable')], default='NON_APPLICABLE', max_length=20, verbose_name='État des tuyaux haute pression'),
        ),
    ]
