# Generated by Django 5.2.10 on 2026-09-25 06:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0011_alter_injection_capteur_pression_rampe_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injection',
            name='capteur_pression_rampe_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HELLA', 'Hella'), ('FACET', 'Facet'), ('FAE', 'FAE'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=50, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='capteur_pression_rampe_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='capteur_pression_rampe_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='connecteurs_injecteurs_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('TE_CONNECTIVITY', 'TE Connectivity'), ('AMP', 'AMP'), ('MOLEX', 'Molex'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=50, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='connecteurs_injecteurs_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='connecteurs_injecteurs_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injecteurs_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('SIEMENS', 'Siemens'), ('HITACHI', 'Hitachi'), ('KEIHIN', 'Keihin'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=50, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injecteurs_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injecteurs_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_carburant_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('VDO', 'VDO'), ('PIERBURG', 'Pierburg'), ('HITACHI', 'Hitachi'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('WALBRO', 'Walbro'), ('TI_AUTOMOTIVE', 'TI Automotive'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=50, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_carburant_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_carburant_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_haute_pression_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HITACHI', 'Hitachi'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=50, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_haute_pression_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='pompe_haute_pression_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='rampe_injection_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('VDO', 'VDO'), ('HITACHI', 'Hitachi'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=50, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='rampe_injection_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='rampe_injection_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='tuyaux_haute_pression_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('DELPHI', 'Delphi'), ('DENSO', 'Denso'), ('CONTINENTAL', 'Continental'), ('OEM', 'Origine constructeur (OEM)'), ('AUTRE', 'Autre fabricant'), ('INCONNU', 'Fabricant inconnu')], default='CHOISIR', max_length=50, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='tuyaux_haute_pression_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='injection',
            name='tuyaux_haute_pression_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
