# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceHydraulique',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_hydraulique', models.CharField(choices=[('FRONT_LIFT', 'Front lift'), ('REAR_LIFT', 'Rear lift'), ('COMPRESSEUR', 'Compresseur'), ('HUILE_COMPRESSEUR', 'Huile compresseur')], max_length=50, verbose_name='Type de pièce hydraulique')),
            ],
            options={
                'verbose_name': 'Pièce hydraulique',
                'verbose_name_plural': 'Pièces hydrauliques',
            },
            bases=('piece.piece',),
        ),
    ]
