# Generated by Django 5.2.10 on 2026-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie_accessoires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courroieaccessoires',
            old_name='poulie_dumper_prix',
            new_name='poulie_damper_prix',
        ),
        migrations.RenameField(
            model_name='courroieaccessoires',
            old_name='poulie_dumper_quantite',
            new_name='poulie_damper_quantite',
        ),
        migrations.RemoveField(
            model_name='courroieaccessoires',
            name='poulie_dumper',
        ),
        migrations.AddField(
            model_name='courroieaccessoires',
            name='poulie_damper',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Poulie Damper'),
        ),
    ]
