# Generated by Django 5.2.10 on 2026-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie_accessoires', '0002_rename_poulie_dumper_prix_courroieaccessoires_poulie_damper_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courroieaccessoires',
            name='courroie_daccessoires',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Courroie d'accessoires"),
        ),
        migrations.AlterField(
            model_name='courroieaccessoires',
            name='galet_tendeur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Galet Tendeur'),
        ),
        migrations.AlterField(
            model_name='courroieaccessoires',
            name='poulie_damper',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Poulie Damper'),
        ),
    ]
