# Generated by Django 5.2.10 on 2026-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie_accessoires', '0004_courroieaccessoires_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroieaccessoires',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
