# Generated by Django 5.2.10 on 2026-08-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie_accessoires', '0011_alter_courroieaccessoires_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroieaccessoires',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
