# Generated by Django 5.2.10 on 2026-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie_accessoires', '0012_courroieaccessoires_kilometrage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroieaccessoires',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
