# Generated by Django 5.2.10 on 2026-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie_accessoires', '0013_courroieaccessoires_kilometres_rollback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courroieaccessoires',
            name='kilometrage_access',
            field=models.PositiveIntegerField(verbose_name="Kilométrage du contrôle de la courroie d'accessoires"),
        ),
    ]
