# Generated by Django 5.2.10 on 2026-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie_accessoires', '0016_courroieaccessoires_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courroieaccessoires',
            name='courroie_daccessoires_fabricant',
            field=models.CharField(blank=True, choices=[('CHOISIR', 'Choisir'), ('CONTINENTAL', 'Continental / ContiTech'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BOSCH', 'Bosch'), ('SKF', 'SKF'), ('INA', 'INA'), ('SNR', 'SNR'), ('HUTCHINSON', 'Hutchinson'), ('OPTIBELT', 'Optibelt'), ('MITSUBOSHI', 'Mitsuboshi'), ('BANDO', 'Bando'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('BLUE_PRINT', 'Blue Print'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('MAPCO', 'Mapco'), ('RIDEX', 'Ridex'), ('STARK', 'Stark'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('TRISCAN', 'Triscan'), ('METELLI', 'Metelli'), ('GRAF', 'Graf'), ('HEPU', 'HEPU'), ('DOLZ', 'Dolz'), ('KAVO_PARTS', 'Kavo Parts'), ('JAPANPARTS', 'Japanparts'), ('ASHIKA', 'Ashika'), ('HERTH_BUSS', 'Herth+Buss'), ('NIPPARTS', 'Nipparts'), ('ACKOJA', 'ACKOJA'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('VALEO', 'Valeo'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
