# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('piece_fluides', '0001_initial'),
        ('voiture_exemplaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kilometrage_prevu', models.PositiveIntegerField()),
                ('kilometrage_realise', models.PositiveIntegerField(blank=True, null=True)),
                ('alerte_avant_km', models.PositiveIntegerField(default=400)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('termine', models.BooleanField(default=False)),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'ordering': ['kilometrage_prevu'],
            },
        ),
        migrations.CreateModel(
            name='EntretienFluide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(help_text='Litres')),
                ('entretien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluides', to='entretien.entretien')),
                ('piece_fluide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piece_fluides.fluide')),
            ],
        ),
        migrations.CreateModel(
            name='EntretienOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('VIDANGE', 'Vidange'), ('FILTRE_HUILE', 'Filtre à huile'), ('BOUGIES', 'Bougies'), ('FILTRE_AIR', 'Filtre à air'), ('FILTRE_HABITACLE', 'Filtre habitacle')], max_length=50)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('entretien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='entretien.entretien')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piece.piece')),
            ],
        ),
    ]
