# Generated by Django 5.2.10 on 2026-04-27 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0001_initial'),
        ('maintenance', '0006_alter_maintenance_kilometres_dernier_entretien'),
        ('piece', '0003_alter_piece_emplacement_etagere_alter_piece_pays_and_more'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretienoperation',
            name='entretien',
        ),
        migrations.RemoveField(
            model_name='entretienoperation',
            name='piece',
        ),
        migrations.AlterModelOptions(
            name='entretien',
            options={'verbose_name': 'Entretien', 'verbose_name_plural': 'entretiens'},
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='alerte_avant_km',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='date_prevue',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='date_realisation',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='kilometrage_prevu',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='kilometrage_realise',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='termine',
        ),
        migrations.AddField(
            model_name='entretien',
            name='boite_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile moteur"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='boite_ajout_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='boite_ajout_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='boite_bouchon_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le bouchon de vidange'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='boite_entretien_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile de boite de vitesses"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='boite_joint_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le joint du bouchon de vidange'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_a_air',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le filtre à air'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_a_carburant',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le filtre à carburant'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_habitacle',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Remplacer le filtre d'habitacle"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacement du filtre à huile moteur'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_huile_bte',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacement du filtre à huile de boite de vitesses'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='frein_liquide_qualite',
            field=models.CharField(choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=25, verbose_name='Qualité de liquide de freins'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='frein_liquide_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de freins ajoutée en litres'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometrage_entretien',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Kilométrage au moment de l'entretien"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='lave_glace_qualite',
            field=models.CharField(choices=[('HIVER', 'Hiver'), ('ETE', 'Eté')], default='HIVER', max_length=25, verbose_name='Qualité de liquide de lave glace'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='lave_glace_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de lave glace ajoutée en litres'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entretien', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='moteur_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Ajout de la nouvelle huile moteur'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='moteur_ajout_huile_qualite',
            field=models.CharField(choices=[('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='moteur_ajout_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='moteur_bouchon_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le bouchon de vidange'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='moteur_bougies',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer les bougies'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='moteur_entretien_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile moteur"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='moteur_joint_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le joint du bouchon de vidange'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretien_piece', to='piece.piece'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_ard',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_arg',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_avd',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_avg',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu avant gauche en bar'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile moteur"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_ajout_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_ajout_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_bouchon_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le bouchon de vidange'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_entretien_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile de boite de vitesses"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_joint_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le joint du bouchon de vidange'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='quantite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='tech_nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='tech_role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_tech_societe_entretien', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='tech_technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_techs_entretien', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='voiture_exemplaire.voitureexemplaire'),
        ),
        migrations.DeleteModel(
            name='EntretienFluide',
        ),
        migrations.DeleteModel(
            name='EntretienOperation',
        ),
    ]
