# Generated by Django 5.2.10 on 2026-03-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretienoperation',
            name='type_operation',
            field=models.CharField(choices=[('VIDANGE', 'Vidange'), ('FILTRE_HUILE', 'Filtre à huile'), ('BOUGIES', 'Bougies'), ('FILTRE_AIR', 'Filtre à air'), ('FILTRE_HABITACLE', 'Filtre habitacle'), ('FILTRE_CARBURANT', 'Filtre à carburant')], max_length=50),
        ),
    ]
