# Generated by Django 5.2.10 on 2026-03-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0003_remove_entretienoperation_entretien_and_more'),
        ('piece_fluides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='frein_liquide_qualite',
            field=models.CharField(choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=25, verbose_name='Qualité de liquide de freins'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='frein_liquide_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de freins ajoutée en litres'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='lave_glace_qualite',
            field=models.CharField(choices=[('HIVER', 'Hiver'), ('ETE', 'Eté')], default='HIVER', max_length=25, verbose_name='Qualité de liquide de lave glace'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='lave_glace_quantite',
            field=models.FloatField(default=0, verbose_name='Quantité de liquide de lave glace ajoutée en litres'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile moteur"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_ajout_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_ajout_huile_quantite',
            field=models.FloatField(default=0, verbose_name="Quantité d'huile ajoutée en litres"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_bouchon_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le bouchon de vidange'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_entretien_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile de boite de vitesses"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_filtre_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacement du filtre à huile de boite de vitesses'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_joint_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le joint du bouchon de vidange'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='piece_fluide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entretien_fluides', to='piece_fluides.fluide'),
        ),
    ]
