# Generated by Django 5.2.10 on 2026-04-28 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0004_entretien_created_at_entretien_updated_at_and_more'),
        ('utilisateurs', '0002_maindoeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens', to='utilisateurs.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
