# Generated by Django 5.2.10 on 2026-03-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0004_entretien_frein_liquide_etat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='alerte_avant_km',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='date_prevue',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='date_realisation',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='kilometrage_prevu',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='kilometrage_realise',
        ),
    ]
