# Generated by Django 5.2.10 on 2026-03-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0005_remove_entretien_alerte_avant_km_and_more'),
        ('voiture_exemplaire', '0010_voitureexemplaire_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='voiture_exemplaire.voitureexemplaire'),
        ),
    ]
