# Generated by Django 5.2.10 on 2026-04-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0005_entretien_main_oeuvre'),
        ('maindoeuvre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
