# Generated by Django 5.2.10 on 2026-03-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0006_alter_entretien_voiture_exemplaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretien',
            old_name='moteur_filtre_huile',
            new_name='filtre_huile',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='boite_filtre_huile',
            new_name='filtre_huile_bte',
        ),
    ]
