# Generated by Django 5.2.10 on 2026-04-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0006_alter_entretien_main_oeuvre'),
        ('maindoeuvre', '0002_alter_maindoeuvre_options_alter_maindoeuvre_temps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='temps_main_oeuvre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Temps main d'oeuvre"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretien', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
