# Generated by Django 5.2.10 on 2026-04-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0007_entretien_temps_main_oeuvre_and_more'),
        ('maindoeuvre', '0002_alter_maindoeuvre_options_alter_maindoeuvre_temps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='temps_main_oeuvre',
        ),
        migrations.AlterField(
            model_name='entretien',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
