# Generated by Django 5.2.10 on 2026-03-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0007_rename_moteur_filtre_huile_entretien_filtre_huile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='pont_filtre_huile',
        ),
    ]
