# Generated by Django 5.2.10 on 2026-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0008_remove_entretien_pont_filtre_huile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_ard',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_arg',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_avd',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pneu_pression_bar_avg',
            field=models.FloatField(default=2.4, verbose_name='Pression du pneu avant gauche en bar'),
        ),
    ]
