# Generated by Django 5.2.10 on 2026-05-29 13:23

import maintenance.entretien.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0009_entretien_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='boite_ajout_huile_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name="Quantité d'huile de boite ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Quantité de liquide de freins ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='lave_glace_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Quantité de liquide de lave glace ajoutée en litres'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='liquide_direction_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Quantité de liquide de direction ajouté en litres'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_ajout_huile_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name="Quantité d'huile moteur ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_ard',
            field=models.FloatField(default=2.4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_arg',
            field=models.FloatField(default=2.4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_avd',
            field=models.FloatField(default=2.4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_avg',
            field=models.FloatField(default=2.4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Pression du pneu avant gauche en bar'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name="Quantité d'huile de pont ajoutée en litres"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[maintenance.entretien.models.validate_step_0_1], verbose_name='Quantité de liquide de refroidissement ajouté en litres'),
        ),
    ]
