# Generated by Django 5.2.10 on 2026-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0009_entretien_pneu_pression_bar_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacer')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Ajout de la nouvelle huile moteur'),
        ),
    ]
