# Generated by Django 5.2.10 on 2026-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0011_alter_entretien_boite_ajout_huile_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
    ]
