# Generated by Django 5.2.10 on 2026-06-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0012_alter_entretien_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='kilometrage_entretien',
            field=models.PositiveIntegerField(default=0, verbose_name="Kilométrage au moment de l'entretien"),
            preserve_default=False,
        ),
    ]
