# Generated by Django 5.2.10 on 2026-06-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0013_alter_entretien_kilometrage_entretien'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='serrage_roues',
            field=models.CharField(choices=[('AFAIRE', 'À faire'), ('Fait', 'Fait')], default='AFAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
