# Generated by Django 5.2.10 on 2026-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0014_entretien_serrage_roues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile de pont"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF DSG', 'ATF DSG')], default='0W30', max_length=25, verbose_name="Qualité d'huile de pont"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pont_entretien_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile de pnt"),
        ),
    ]
