# Generated by Django 5.2.10 on 2026-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0015_alter_entretien_pont_ajout_huile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Ajout de la nouvelle huile de pont'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pont_entretien_vidange',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Vidange de l'huile de pont"),
        ),
    ]
