# Generated by Django 5.2.10 on 2026-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0016_alter_entretien_pont_ajout_huile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile_qualite',
            field=models.CharField(choices=[('75W140', '75W140')], default='75W140', max_length=25, verbose_name="Qualité d'huile de pont"),
        ),
    ]
