# Generated by Django 5.2.10 on 2026-07-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0019_entretien_feux_position_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretien',
            old_name='feux_position_ar',
            new_name='phares_feux_position_ar',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='feux_position_av',
            new_name='phares_feux_position_av',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='feux_stops',
            new_name='phares_feux_stops',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='troisieme_feux_stop',
            new_name='phares_troisieme_feux_stop',
        ),
    ]
