# Generated by Django 5.2.10 on 2026-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0020_rename_feux_position_ar_entretien_phares_feux_position_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
