# Generated by Django 5.2.10 on 2026-07-19 09:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0021_alter_entretien_serrage_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='taux_horaire',
            field=models.DecimalField(choices=[(Decimal('25.00'), '25,00 €'), (Decimal('30.00'), '30,00 €'), (Decimal('35.00'), '35,00 €'), (Decimal('40.00'), '40,00 €'), (Decimal('45.00'), '45,00 €'), (Decimal('50.00'), '50,00 €'), (Decimal('55.00'), '55,00 €'), (Decimal('60.00'), '60,00 €'), (Decimal('65.00'), '65,00 €'), (Decimal('70.00'), '70,00 €')], decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Taux horaire'),
        ),
    ]
