# Generated by Django 5.2.10 on 2026-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0023_rename_filtre_huile_bte_entretien_boite_filtre_huile_bte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_air_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant du filtre à air'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_carburant_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant du filtre à carburant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_habitacle_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre')], default='BOSCH', max_length=25, verbose_name="Nom du fabricant du filtre d'habitacle"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_huile_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant du filtre à huile'),
        ),
    ]
