# Generated by Django 5.2.10 on 2026-07-21 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0027_entretien_boite_bouchon_vidange_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretien',
            old_name='boite_filtre_huile_bte_prix',
            new_name='filtre_huile_boite_prix',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='boite_filtre_huile_bte',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='boite_filtre_huile_bte_fabricant',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='boite_filtre_huile_bte_quantite',
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_huile_boite',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name='Remplacer le filtre à huile de boîte de vitesses'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_huile_boite_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KN', 'KN'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant du filtre à huile de boîte de vitesses'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='filtre_huile_boite_quantite',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de filtres à huile de boîte de vitesses'),
        ),
    ]
