# Generated by Django 5.2.10 on 2026-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0028_rename_boite_filtre_huile_bte_prix_entretien_filtre_huile_boite_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='boite_joint_vidange_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité de joints de bouchon de vidange'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='bougies_quantite',
            field=models.PositiveIntegerField(default=4, verbose_name='Quantité de bougies'),
        ),
    ]
