# Generated by Django 5.2.10 on 2026-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0029_alter_entretien_boite_joint_vidange_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='liquide_direction_qualite',
            field=models.CharField(choices=[('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('LDS', 'LDS'), ('LHM', 'LHM'), ('PSF', 'PSF'), ('PSF_3', 'PSF-3'), ('PSF_4', 'PSF-4'), ('MB_236_3', 'Mercedes-Benz 236.3'), ('MB_345_0', 'Mercedes-Benz 345.0'), ('VW_G002000', 'Volkswagen G 002 000'), ('VW_G004000', 'Volkswagen G 004 000'), ('BMW_ATF', 'BMW ATF'), ('BMW_CHF', 'BMW CHF'), ('HONDA_PSF', 'Honda PSF'), ('TOYOTA_PSF', 'Toyota PSF'), ('MINERALE', 'Huile minérale'), ('SEMI_SYNTHETIQUE', 'Huile semi-synthétique'), ('SYNTHETIQUE', 'Huile synthétique'), ('CONSTRUCTEUR', 'Spécification constructeur'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Qualité de liquide de direction'),
        ),
    ]
