# Generated by Django 5.2.10 on 2026-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0031_alter_entretien_boite_bouchon_vidange_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='bougies_fabricant',
            field=models.CharField(choices=[('NGK', 'NGK'), ('DENSO', 'DENSO'), ('BOSCH', 'Bosch'), ('CHAMPION', 'Champion'), ('BERU', 'Beru'), ('EYQUEM', 'Eyquem'), ('VALEO', 'Valeo'), ('FEBI', 'Febi Bilstein'), ('HELLA', 'Hella'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('DELPHI', 'Delphi'), ('BORGWARNER', 'BorgWarner'), ('MOTORCRAFT', 'Motorcraft'), ('ACDELCO', 'ACDelco'), ('MOPAR', 'Mopar'), ('PIERBURG', 'Pierburg'), ('RIDEX', 'RIDEX'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NPS', 'NPS'), ('AUTOLITE', 'Autolite'), ('BRISK', 'Brisk'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Nom du fabricant des bougies'),
        ),
    ]
