# Generated by Django 5.2.10 on 2026-08-10 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0035_alter_entretien_filtre_huile_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='boite_ajout_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='MOBIL', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_ajout_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_bouchon_vidange_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='AUTRE', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_bouchon_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_bouchon_vidange_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_joint_vidange_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='AUTRE', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_joint_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_joint_vidange_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_air_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KN', 'KN'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_air_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_air_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_carburant_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KN', 'KN'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_carburant_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_a_carburant_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_habitacle_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_habitacle_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_huile_boite_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KN', 'KN'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_huile_boite_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_huile_boite_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_huile_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KN', 'KN'), ('KNECHT', 'Knecht'), ('PURFLUX', 'Purflux'), ('HENGST', 'Hengst'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('CHAMPION', 'Champion'), ('WIX', 'WIX Filters'), ('NIPPARTS', 'Nipparts'), ('BLUE_PRINT', 'Blue Print'), ('JAPANPARTS', 'Japanparts'), ('HERTH_BUSS', 'Herth+Buss'), ('SOFIMA', 'Sofima'), ('MISFAT', 'Misfat'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('SCT', 'SCT Germany'), ('DENCKERMANN', 'Denckermann'), ('COMLINE', 'Comline'), ('VALEO', 'Valeo'), ('DELPHI', 'Delphi'), ('MEYLE', 'Meyle'), ('RIDEX', 'RIDEX'), ('TOPRAN', 'Topran'), ('VAICO', 'Vaico'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('ALCO', 'ALCO Filters'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin Filters'), ('COOPERSFIAAM', 'CoopersFiaam'), ('TECNECO', 'Tecneco'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='BOSCH', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='filtre_huile_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='MOBIL', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_qualite',
            field=models.CharField(choices=[('DOT 3', 'DOT 3'), ('DOT 4', 'DOT 4'), ('DOT 5', 'DOT 5'), ('DOT 5.1', 'DOT 5.1')], default='DOT 4', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='lave_glace_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='MOBIL', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='lave_glace_qualite',
            field=models.CharField(choices=[('HIVER', 'Hiver'), ('ETE', 'Eté')], default='HIVER', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='lave_glace_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité en litres'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='liquide_direction_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='MOBIL', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='liquide_direction_qualite',
            field=models.CharField(choices=[('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('CHF_7_1', 'CHF 7.1'), ('CHF_11S', 'CHF 11S'), ('CHF_202', 'CHF 202'), ('LDS', 'LDS'), ('LHM', 'LHM'), ('PSF', 'PSF'), ('PSF_3', 'PSF-3'), ('PSF_4', 'PSF-4'), ('MB_236_3', 'Mercedes-Benz 236.3'), ('MB_345_0', 'Mercedes-Benz 345.0'), ('VW_G002000', 'Volkswagen G 002 000'), ('VW_G004000', 'Volkswagen G 004 000'), ('BMW_ATF', 'BMW ATF'), ('BMW_CHF', 'BMW CHF'), ('HONDA_PSF', 'Honda PSF'), ('TOYOTA_PSF', 'Toyota PSF'), ('MINERALE', 'Huile minérale'), ('SEMI_SYNTHETIQUE', 'Huile semi-synthétique'), ('SYNTHETIQUE', 'Huile synthétique'), ('CONSTRUCTEUR', 'Spécification constructeur'), ('AUTRE', 'Autre'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='liquide_direction_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajouté en litres'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_bouchon_vidange_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='AUTRE', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_bouchon_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_bouchon_vidange_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_joint_vidange_fabricant',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='AUTRE', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_joint_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_joint_vidange_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='MOBIL', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='MOBIL', max_length=25, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_quantite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité ajouté en litres'),
        ),
    ]
