# Generated by Django 5.2.10 on 2026-08-11 10:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0036_alter_entretien_boite_ajout_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_ard',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu arrière droit en bar'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_arg',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu arrière gauche en bar'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_avd',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu avant droit en bar'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pneu_pression_bar_avg',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=3, validators=[django.core.validators.StepValueValidator(Decimal('0.1'))], verbose_name='Pression du pneu avant gauche en bar'),
        ),
    ]
