# Generated by Django 5.2.10 on 2026-08-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0039_alter_entretien_boite_ajout_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='MOBIL', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='pont_ajout_huile_qualite',
            field=models.CharField(choices=[('75W80', '75W80'), ('75W85', '75W85'), ('75W90', '75W90'), ('75W110', '75W110'), ('75W140', '75W140'), ('80W90', '80W90'), ('80W140', '80W140'), ('85W90', '85W90'), ('85W140', '85W140'), ('SAE90', 'SAE 90'), ('SAE140', 'SAE 140'), ('PORSCHE_75W90', 'Porsche 75W90'), ('PORSCHE_75W140', 'Porsche 75W140'), ('AUTRE', 'Autre'), ('INCONNUE', 'Huile inconnue')], default='75W80', max_length=25, verbose_name="Qualité d'huile de pont"),
        ),
    ]
