# Generated by Django 5.2.10 on 2026-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0041_alter_entretien_boite_ajout_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='bougies_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
