# Generated by Django 5.2.10 on 2026-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0042_alter_entretien_bougies_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='lave_glace_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='liquide_direction_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouter'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
