# Generated by Django 5.2.10 on 2026-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0047_entretien_phares_anti_brouillard_arriere_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='phares_avant_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('HELLA', 'Hella'), ('VALEO', 'Valeo'), ('NARVA', 'Narva'), ('GE', 'GE'), ('RING', 'Ring'), ('PIAA', 'PIAA'), ('MTECH', 'M-Tech'), ('NEOLUX', 'Neolux'), ('TUNGSRAM', 'Tungsram'), ('CONSTRUCTEUR', 'Constructeur'), ('AUTRE', 'Autre')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
