# Generated by Django 5.2.10 on 2026-08-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0049_alter_entretien_liquide_direction_fabricant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
