# Generated by Django 5.2.10 on 2026-08-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0052_alter_entretien_boite_ajout_huile_qualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='boite_ajout_huile',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter')], default='A_FAIRE', max_length=25, verbose_name="Ajout de l'huile de boite de vitesse"),
        ),
    ]
