# Generated by Django 5.2.10 on 2026-09-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0053_alter_entretien_boite_ajout_huile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretien',
            old_name='lave_glace_liquide_etat',
            new_name='lave_glace_liquide',
        ),
    ]
