# Generated by Django 5.2.10 on 2026-09-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0054_rename_lave_glace_liquide_etat_entretien_lave_glace_liquide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretien',
            old_name='lave_glace_fabricant',
            new_name='lave_glace_liquide_fabricant',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='lave_glace_prix',
            new_name='lave_glace_liquide_prix',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='lave_glace_qualite',
            new_name='lave_glace_liquide_qualite',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='lave_glace_quantite',
            new_name='lave_glace_liquide_quantite',
        ),
    ]
