# Generated by Django 5.2.10 on 2026-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0055_rename_lave_glace_fabricant_entretien_lave_glace_liquide_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretien',
            old_name='filtre_huile_boite',
            new_name='filtre_huile_bte',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='filtre_huile_boite_fabricant',
            new_name='filtre_huile_bte_fabricant',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='filtre_huile_boite_prix',
            new_name='filtre_huile_bte_prix',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='filtre_huile_boite_quantite',
            new_name='filtre_huile_bte_quantite',
        ),
        migrations.AlterField(
            model_name='entretien',
            name='boite_ajout_huile_qualite',
            field=models.CharField(choices=[('75W', '75W'), ('75W80', '75W80'), ('75W90', '75W90'), ('80W', '80W'), ('80W90', '80W90'), ('85W90', '85W90'), ('ATF_III', 'ATF III'), ('ATF_DSG', 'ATF DSG'), ('ATF_DCT', 'ATF DCT'), ('ATF_CVT', 'ATF CVT'), ('ATF_DEXRON_II', 'ATF Dexron II'), ('ATF_DEXRON_III', 'ATF Dexron III'), ('ATF_DEXRON_VI', 'ATF Dexron VI'), ('ATF_MERCON', 'ATF Mercon'), ('ATF_MERCON_V', 'ATF Mercon V'), ('ATF_MERCON_LV', 'ATF Mercon LV'), ('ATF_MULTI', 'ATF Multi Vehicle'), ('ATF_WS', 'ATF Toyota WS'), ('ATF_ZF_LIFEGUARD', 'ZF Lifeguard'), ('ATF_MOPAR', 'Mopar ATF+4'), ('ATF_AISIN', 'Aisin ATF'), ('ATF_MBV236', 'Mercedes MB 236.x'), ('ATF_VOLVO', 'Volvo ATF'), ('ATF_HONDA', 'Honda ATF DW-1'), ('ATF_NISSAN', 'Nissan Matic'), ('PORSCHE_PDK', 'Porsche PDK'), ('PORSCHE_DCT', 'Porsche DCT'), ('PORSCHE_TIPTRONIC', 'Porsche Tiptronic'), ('VAG_DSG_DQ250', 'VAG DSG DQ250'), ('VAG_DSG_DQ381', 'VAG DSG DQ381'), ('VAG_DSG_DQ500', 'VAG DSG DQ500'), ('VAG_DSG_DQ200', 'VAG DSG DQ200'), ('VAG_S_TRONIC', 'Audi S tronic'), ('VAG_MULTITRONIC', 'Audi Multitronic'), ('VAG_TIPTRONIC', 'VAG Tiptronic'), ('FORD_MERCON', 'Ford Mercon'), ('FORD_MERCON_V', 'Ford Mercon V'), ('FORD_MERCON_LV', 'Ford Mercon LV'), ('FORD_MERCON_ULV', 'Ford Mercon ULV'), ('FORD_POWERSHIFT', 'Ford PowerShift'), ('FORD_CVT', 'Ford CVT'), ('ALFA_TCT', 'Alfa Romeo TCT'), ('ALFA_SELESPEED', 'Alfa Romeo Selespeed'), ('ALFA_ATF', 'Alfa Romeo ATF'), ('ALFA_TUTELA', 'Alfa Romeo Tutela'), ('FERRARI_DCT', 'Ferrari DCT'), ('FERRARI_F1', 'Ferrari F1'), ('FERRARI_GETRAG', 'Ferrari Getrag'), ('FERRARI_ATF', 'Ferrari ATF')], default='75W', max_length=25, verbose_name="Qualité d'huile"),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_fabricant',
            field=models.CharField(choices=[('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant'), ('CONSTRUCTEUR', 'Constructeur')], default='G13', max_length=25, verbose_name='Qualité'),
        ),
    ]
