# Generated by Django 5.2.10 on 2026-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0056_rename_filtre_huile_boite_entretien_filtre_huile_bte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
