# Generated by Django 5.2.10 on 2026-09-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0058_alter_entretien_boite_ajout_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='kilometres_boite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometres_boite_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback boite'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometres_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometres_moteur_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback moteur'),
        ),
    ]
