# Generated by Django 5.2.10 on 2026-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0059_entretien_kilometres_boite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='kilometres_dernier_entretien',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometres_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometres_embrayage_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback embrayage'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometres_entretien_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback entretien'),
        ),
    ]
