# Generated by Django 5.2.10 on 2026-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0062_alter_entretien_boite_ajout_huile_fabricant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_qualite',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('G11', 'G 11 VAG'), ('G12', 'G 12 VAG'), ('G12_PLUS', 'G 12+ VAG'), ('G12_PLUS_PLUS', 'G 12++ VAG'), ('G13', 'G 13'), ('G48', 'G 48 BMW'), ('MB_325_0', 'MB 325.0 Mercedes'), ('MB_325_3', 'MB 325.3 Mercedes'), ('MB_325_5', 'MB 325.5 Mercedes'), ('TYPE_D', 'Type D Renault'), ('PSA_B71_5110', 'B71 5110 PSA'), ('WSS_M97B44_D', 'WSS-M97B44-D Ford'), ('WSS_M97B51_A1', 'WSS-M97B51-A1 Ford'), ('DEX_COOL', 'Dex-Cool GM'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant'), ('CONSTRUCTEUR', 'Constructeur')], default='G13', max_length=25, verbose_name='Qualité'),
        ),
    ]
