# Generated by Django 5.2.10 on 2026-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0063_alter_entretien_refroidissement_liquide_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='pont_bouchon_vidange_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_bouchon_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_bouchon_vidange_quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_joint_vidange_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('BOSCH', 'Bosch'), ('MANN_FILTER', 'MANN-Filter'), ('MAHLE', 'Mahle'), ('KNECHT', 'Knecht'), ('HENGST', 'Hengst'), ('PURFLUX', 'Purflux'), ('UFI', 'UFI'), ('FILTRON', 'Filtron'), ('FRAM', 'Fram'), ('WIX', 'WIX Filters'), ('ALCO', 'ALCO Filters'), ('SOFIMA', 'Sofima'), ('DONALDSON', 'Donaldson'), ('FLEETGUARD', 'Fleetguard'), ('BALDWIN', 'Baldwin'), ('NGK', 'NGK'), ('DENSO', 'Denso'), ('BERU', 'Beru'), ('CHAMPION', 'Champion'), ('LUK', 'LuK'), ('SACHS', 'Sachs'), ('VALEO', 'Valeo'), ('AISIN', 'Aisin'), ('BREMBO', 'Brembo'), ('ATE', 'ATE'), ('TEXTAR', 'Textar'), ('FERODO', 'Ferodo'), ('TRW', 'TRW'), ('JURID', 'Jurid'), ('PAGID', 'Pagid'), ('REMSA', 'Remsa'), ('LEMFORDER', 'Lemförder'), ('MEYLE', 'Meyle'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('MOOG', 'Moog'), ('SIDEM', 'Sidem'), ('DELPHI', 'Delphi'), ('SKF', 'SKF'), ('FAG', 'FAG'), ('TIMKEN', 'Timken'), ('NSK', 'NSK'), ('KOYO', 'Koyo'), ('NTN', 'NTN'), ('SNR', 'SNR'), ('CONTINENTAL', 'Continental'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BEHR', 'Behr'), ('HELLA', 'Hella'), ('NRF', 'NRF'), ('VARTA', 'Varta'), ('EXIDE', 'Exide'), ('YUASA', 'Yuasa'), ('OSRAM', 'Osram'), ('PHILIPS', 'Philips'), ('WALKER', 'Walker'), ('PIERBURG', 'Pierburg'), ('VDO', 'VDO'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('OPEL', 'Opel'), ('FORD', 'Ford'), ('RENAULT', 'Renault'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('HERTH_BUSS', 'Herth+Buss'), ('JAPANPARTS', 'Japanparts'), ('BLUE_PRINT', 'Blue Print'), ('NIPPARTS', 'Nipparts'), ('COMLINE', 'Comline'), ('DENCKERMANN', 'Denckermann'), ('VAICO', 'Vaico'), ('TOPRAN', 'Topran'), ('RIDEX', 'RIDEX'), ('MAXGEAR', 'Maxgear'), ('JC_PREMIUM', 'JC Premium'), ('ASHIKA', 'Ashika'), ('OPEN_PARTS', 'Open Parts'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_joint_vidange_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='pont_joint_vidange_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='moteur_ajout_huile_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CASTROL', 'Castrol'), ('MOTUL', 'Motul'), ('MOBIL', 'Mobil 1'), ('SHELL', 'Shell'), ('TOTAL', 'TotalEnergies'), ('ELF', 'ELF'), ('LIQUI_MOLY', 'Liqui Moly'), ('FUCHS', 'Fuchs'), ('VALVOLINE', 'Valvoline'), ('PENRITE', 'Penrite'), ('RAVENOL', 'Ravenol'), ('ROWE', 'Rowe'), ('ENEOS', 'ENEOS'), ('PETRONAS', 'Petronas'), ('EUROL', 'Eurol'), ('COMMA', 'Comma'), ('MANNOL', 'Mannol'), ('YACCO', 'Yacco'), ('REDLINE', 'Red Line'), ('AMSOIL', 'Amsoil'), ('KROON_OIL', 'Kroon-Oil'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('PENTOSIN', 'Pentosin'), ('ZF', 'ZF'), ('AISIN', 'Aisin'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('NISSAN', 'Nissan'), ('MERCEDES', 'Mercedes-Benz'), ('BMW', 'BMW'), ('VOLKSWAGEN', 'Volkswagen'), ('PORSCHE', 'Porsche'), ('RENAULT', 'Renault'), ('PSA', 'Peugeot / Citroën'), ('HYUNDAI_KIA', 'Hyundai / Kia'), ('FORD', 'Ford'), ('GM', 'General Motors'), ('MOPAR', 'Mopar'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur')], default='CHOISIR', max_length=25, verbose_name='Fabricant'),
        ),
    ]
