# Generated by Django 5.2.10 on 2026-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0067_entretien_phares_eclaire_plaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='frein_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de freins'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='lave_glace_liquide',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de lave-glace'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='liquide_direction_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de direction'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='refroidissement_liquide_etat',
            field=models.CharField(choices=[('BON', 'Bon'), ('AJOUTER', 'Ajouté'), ('REMPLACER', 'Remplacé')], default='BON', max_length=25, verbose_name='Niveau de liquide de refroidissement'),
        ),
    ]
