# Generated by Django 5.2.10 on 2026-02-04 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_boite', '0001_initial'),
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoteurVoiture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motoriste', models.CharField(max_length=40)),
                ('code_moteur', models.CharField(max_length=50)),
                ('type_moteur', models.CharField(choices=[('TURBO', 'Turbo'), ('ATM', 'Atmosphérique'), ('WANKEL', 'Wankel'), ('HYB_E', 'Hybride essence'), ('HYB_TE', 'Hybride turbo essence'), ('ELEC', 'Machine électrique')], max_length=40)),
                ('carburant', models.CharField(choices=[('ESS', 'Essence'), ('DSL', 'Diesel'), ('ELEC', 'Électricité'), ('CNG', 'Gaz naturel (CNG)'), ('LPG', 'GPL'), ('H2', 'Hydrogène')], max_length=40)),
                ('cylindree_l', models.FloatField(verbose_name='Cylindrée (L)')),
                ('distribution', models.CharField(choices=[('CHAINE', 'Chaîne'), ('COURROIE', 'Courroie')], max_length=40)),
                ('nombre_cylindres', models.IntegerField(blank=True, default=1, null=True, verbose_name='Nombre de cylindres')),
                ('puissance_ch', models.IntegerField(blank=True, null=True)),
                ('puissance_tr_min', models.IntegerField(blank=True, null=True, verbose_name='Puissance à (tr/min)')),
                ('couple_nm', models.IntegerField(blank=True, null=True)),
                ('couple_tr_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Couple à (tr/min)')),
                ('qualite_huile', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite_huile_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kilometrage_moteur', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('numero_moteur', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('intervalle_km_entretien', models.PositiveIntegerField(blank=True, default=15000, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moteurs', to='voiture_boite.voitureboite')),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='moteurs', to='voiture_exemplaire.voitureexemplaire')),
                ('voitures_modeles', models.ManyToManyField(blank=True, related_name='moteurs', to='voiture_modele.voituremodele')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_moteur__gte', 1), ('numero_moteur__lte', 10)), name='numero_moteur_1_10')],
            },
        ),
    ]
