# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoteurVoiture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_moteur', models.CharField(choices=[('TURBO', 'Turbo'), ('ATM', 'Atmosphérique'), ('WANKEL', 'Wankel'), ('HYB_E', 'Hybride essence'), ('HYB_TE', 'Hybride turbo essence'), ('ELEC', 'Machine électrique')], max_length=20)),
                ('carburant', models.CharField(choices=[('ESS', 'Essence'), ('DSL', 'Diesel'), ('ELEC', 'Électricité'), ('CNG', 'Gaz naturel (CNG)'), ('LPG', 'GPL'), ('H2', 'Hydrogène')], max_length=20)),
                ('cylindree_l', models.FloatField(verbose_name='Cylindrée (L)')),
                ('distribution', models.CharField(choices=[('CHAINE', 'Chaîne'), ('COURROIE', 'Courroie')], max_length=20)),
                ('nombre_cylindres', models.PositiveSmallIntegerField()),
                ('puissance_ch', models.PositiveIntegerField()),
                ('puissance_tr_min', models.PositiveIntegerField(verbose_name='Puissance à (tr/min)')),
                ('couple_nm', models.PositiveIntegerField()),
                ('couple_tr_min', models.PositiveIntegerField(verbose_name='Couple à (tr/min)')),
                ('qualite_huile', models.CharField(max_length=50)),
                ('quantite_huile_l', models.FloatField(verbose_name='Quantité d’huile (L)')),
                ('kilometrage_moteur', models.PositiveIntegerField(default=0)),
                ('numero_moteur', models.PositiveSmallIntegerField(default=1, help_text='1 à 10 (incrémenté à chaque remplacement)')),
                ('intervalle_km_entretien', models.PositiveIntegerField(default=15000, verbose_name='Intervalle entretien (km)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moteurs', to='voiture_exemplaire.voitureexemplaire')),
                ('voiture_modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moteurs', to='voiture_modele.voituremodele')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_moteur__gte', 1), ('numero_moteur__lte', 10)), name='numero_moteur_1_10'), models.CheckConstraint(condition=models.Q(('voiture_modele__isnull', False), ('voiture_exemplaire__isnull', False), _connector='OR'), name='moteur_lie_a_voiture')],
            },
        ),
    ]
