# Generated by Django 6.0 on 2026-01-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_moteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moteurvoiture',
            name='code_moteur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moteurvoiture',
            name='motoriste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
