# Generated by Django 6.0 on 2026-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_exemplaire', '0003_alter_voitureexemplaire_nombre_proprietaires'),
        ('voiture_modele', '0003_alter_voituremodele_nom_variante'),
        ('voiture_moteur', '0002_moteurvoiture_code_moteur_moteurvoiture_motoriste'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moteurvoiture',
            name='moteur_lie_a_voiture',
        ),
        migrations.AddField(
            model_name='moteurvoiture',
            name='voitures_exemplaires',
            field=models.ManyToManyField(blank=True, related_name='moteurs', to='voiture_exemplaire.voitureexemplaire'),
        ),
        migrations.AddField(
            model_name='moteurvoiture',
            name='voitures_modeles',
            field=models.ManyToManyField(blank=True, related_name='moteurs', to='voiture_modele.voituremodele'),
        ),
        migrations.AlterField(
            model_name='moteurvoiture',
            name='code_moteur',
            field=models.CharField(default='DEFAULT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moteurvoiture',
            name='intervalle_km_entretien',
            field=models.PositiveIntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='moteurvoiture',
            name='motoriste',
            field=models.CharField(default='DEFAULT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moteurvoiture',
            name='numero_moteur',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='moteurvoiture',
            name='voiture_exemplaire',
        ),
        migrations.RemoveField(
            model_name='moteurvoiture',
            name='voiture_modele',
        ),
    ]
