# Generated by Django 5.2.10 on 2026-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_moteur', '0002_moteurvoiture_created_at_moteurvoiture_remarques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moteurvoiture',
            name='kilometre_remplacement_moteur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='moteurvoiture',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
