# Generated by Django 6.0 on 2026-01-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_moteur', '0003_remove_moteurvoiture_moteur_lie_a_voiture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moteurvoiture',
            name='type_moteur',
            field=models.CharField(choices=[('TURBO', 'Turbo'), ('ATM', 'Atmosphérique'), ('WANKEL', 'Wankel'), ('HYB_E', 'Hybride essence'), ('HYB_TE', 'Hybride turbo essence'), ('ELEC', 'Machine électrique')], max_length=40),
        ),
    ]
