# Generated by Django 5.2.10 on 2026-04-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_moteur', '0003_moteurvoiture_kilometre_remplacement_moteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moteurvoiture',
            old_name='kilometrage_moteur',
            new_name='kilometres_moteur',
        ),
        migrations.RenameField(
            model_name='moteurvoiture',
            old_name='kilometre_remplacement_moteur',
            new_name='kilometres_remplacement_moteur',
        ),
    ]
