# Generated by Django 5.2.10 on 2026-04-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_moteur', '0004_rename_kilometrage_moteur_moteurvoiture_kilometres_moteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moteurvoiture',
            name='kilometres_moteur',
        ),
        migrations.RemoveField(
            model_name='moteurvoiture',
            name='kilometres_remplacement_moteur',
        ),
    ]
