# Generated by Django 6.0 on 2026-01-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_moteur', '0004_alter_moteurvoiture_type_moteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moteurvoiture',
            name='code_moteur',
            field=models.CharField(max_length=50),
        ),
    ]
