# Generated by Django 5.2.10 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_moteur', '0005_remove_moteurvoiture_kilometres_moteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moteurvoiture',
            name='qualite_huile',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('0W16', '0W16'), ('0W20', '0W20'), ('0W30', '0W30'), ('0W40', '0W40'), ('5W20', '5W20'), ('5W30', '5W30'), ('5W40', '5W40'), ('10W40', '10W40'), ('10W50', '10W50'), ('10W60', '10W60'), ('15W40', '15W40'), ('15W50', '15W50'), ('20W50', '20W50')], default='0W30', max_length=25, verbose_name="Qualité d'huile"),
        ),
    ]
