# Generated by Django 5.2.10 on 2026-02-04 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureBoite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fabricant', models.CharField(blank=True, max_length=30, null=True)),
                ('nom_du_type', models.CharField(blank=True, help_text='PDK, DSG ?', max_length=100, null=True)),
                ('type_de_boite', models.CharField(blank=True, choices=[('MANUELLE', 'Manuelle'), ('SEMI-AUTOMATIQUE', 'Semi-automatique'), ('AUTOMATIQUE', 'Automatique'), ('ELECTRIQUE', 'Electrique')], default='AUTOMATIQUE', max_length=40, null=True)),
                ('oem', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_rapport', models.PositiveSmallIntegerField(blank=True, default=5, help_text='nombre rapport', null=True)),
                ('qualite_huile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualité huile boîte')),
                ('quantite_huile_l', models.FloatField(blank=True, null=True, verbose_name='Quantité huile boîte (L)')),
                ('kilometrage_boite', models.PositiveIntegerField(default=0)),
                ('intervalle_entretien_km', models.PositiveIntegerField(blank=True, default=60000, null=True, verbose_name='Intervalle entretien (km)')),
                ('dernier_entretien', models.CharField(blank=True, choices=[('VIDANGE', 'Vidange'), ('FILTRE', 'Changement filtre'), ('REMPLACEMENT', 'Remplacement boîte')], max_length=20, null=True)),
                ('numero_boite', models.PositiveSmallIntegerField(blank=True, default=1, help_text='1 à 10 (incrémenté à chaque remplacement)', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='boites', to='voiture_exemplaire.voitureexemplaire')),
                ('voitures_modeles', models.ManyToManyField(blank=True, related_name='boites', to='voiture_modele.voituremodele')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_boite__gte', 1), ('numero_boite__lte', 10)), name='numero_boite_1_10')],
            },
        ),
    ]
