# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureBoite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualite_huile', models.CharField(max_length=20, verbose_name='Qualité huile boîte')),
                ('quantite_huile_l', models.FloatField(verbose_name='Quantité huile boîte (L)')),
                ('kilometrage_boite', models.PositiveIntegerField(default=0)),
                ('intervalle_entretien_km', models.PositiveIntegerField(default=60000, verbose_name='Intervalle entretien (km)')),
                ('dernier_entretien', models.CharField(blank=True, choices=[('VIDANGE', 'Vidange'), ('FILTRE', 'Changement filtre'), ('REMPLACEMENT', 'Remplacement boîte')], max_length=20, null=True)),
                ('numero_boite', models.PositiveSmallIntegerField(default=1, help_text='1 à 10 (incrémenté à chaque remplacement)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boites', to='voiture_exemplaire.voitureexemplaire')),
                ('voiture_modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boites', to='voiture_modele.voituremodele')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_boite__gte', 1), ('numero_boite__lte', 10)), name='numero_boite_1_10'), models.CheckConstraint(condition=models.Q(('voiture_modele__isnull', False), ('voiture_exemplaire__isnull', False), _connector='OR'), name='boite_liée_a_voiture')],
            },
        ),
    ]
