# Generated by Django 5.2.10 on 2026-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_boite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitureboite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='voitureboite',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voitureboite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
