# Generated by Django 5.2.10 on 2026-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_boite', '0002_voitureboite_created_at_voitureboite_remarques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voitureboite',
            name='kilometrage_boite',
        ),
        migrations.AddField(
            model_name='voitureboite',
            name='kilometres_boite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='voitureboite',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='voitureboite',
            name='kilometres_remplacement_boite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
