# Generated by Django 5.2.10 on 2026-04-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_boite', '0003_remove_voitureboite_kilometrage_boite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voitureboite',
            name='kilometres_boite',
        ),
        migrations.RemoveField(
            model_name='voitureboite',
            name='kilometres_remplacement_boite',
        ),
    ]
