# Generated by Django 5.2.10 on 2026-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_boite', '0004_remove_voitureboite_kilometres_boite_and_more'),
        ('voiture_exemplaire', '0018_voitureexemplaire_nombre_remplacements_moteurs'),
        ('voiture_modele', '0013_alter_voituremodele_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voitureboite',
            name='numero_boite_1_10',
        ),
        migrations.AddField(
            model_name='voitureboite',
            name='nombre_remplacements_boites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='voitureboite',
            constraint=models.CheckConstraint(condition=models.Q(('numero_boite__gte', 1), ('numero_boite__lte', 10)), name='numero_boite_1_20'),
        ),
    ]
