# Generated by Django 5.2.10 on 2026-04-02 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0011_alter_voitureexemplaire_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureFreinsAV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marque_disques_av', models.CharField(blank=True, max_length=100, null=True)),
                ('marque_plaquettes_av', models.CharField(blank=True, max_length=100, null=True)),
                ('taille_disque_av', models.FloatField(blank=True, null=True, verbose_name='Taille disque AV (mm)')),
                ('epaisseur_disque_av', models.FloatField(blank=True, null=True, verbose_name='Épaisseur disque AV (mm)')),
                ('epaisseur_min_disque_av', models.FloatField(blank=True, null=True, verbose_name='Épaisseur minimum disque AV (mm)')),
                ('plaquettes_av', models.FloatField(blank=True, null=True, verbose_name='Plaquettes AV (mm)')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freins_av', to='societe.societe')),
                ('voitures_exemplaires', models.ManyToManyField(blank=True, related_name='freins_av', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'verbose_name': 'Voiture – Freins Avant',
                'verbose_name_plural': 'Voitures – Freins Avant',
            },
        ),
    ]
