# Generated by Django 5.2.10 on 2026-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_av', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturefreinsav',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
    ]
