# Generated by Django 5.2.10 on 2026-04-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_av', '0002_voiturefreinsav_remarques'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturefreinsav',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='voiturefreinsav',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
