# Generated by Django 5.2.10 on 2026-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_av', '0003_voiturefreinsav_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturefreinsav',
            name='numero_oem_disques_av',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero oem disque AV (mm)'),
        ),
        migrations.AddField(
            model_name='voiturefreinsav',
            name='numero_oem_plaquettes_av',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero oem plaquette AV (mm)'),
        ),
    ]
