# Generated by Django 5.2.10 on 2026-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_av', '0005_alter_voiturefreinsav_numero_oem_disques_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiturefreinsav',
            name='numero_oem_disques_av',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro OEM disque AV'),
        ),
        migrations.AlterField(
            model_name='voiturefreinsav',
            name='numero_oem_plaquettes_av',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro OEM plaquette AV'),
        ),
    ]
