# Generated by Django 5.2.10 on 2026-05-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_freins_av', '0006_alter_voiturefreinsav_numero_oem_disques_av_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturefreinsav',
            name='frein_av_matiere',
            field=models.CharField(choices=[('ACIER', 'Acier'), ('CARBONE', 'Carbone'), ('CERAMIQUE', 'Céramique'), ('COMPOSITE', 'Composite')], default='ACIER', max_length=25, verbose_name='Matière des disques avant'),
        ),
        migrations.AddField(
            model_name='voiturefreinsav',
            name='plaquette_av_matiere',
            field=models.CharField(choices=[('ORGANIC', 'Organique (NAO)'), ('LOW_METALLIC', 'Semi-métallique'), ('METALLIC', 'Métallique'), ('CERAMIC', 'Céramique haute performance')], default='ORGANIC', max_length=25, verbose_name='Matière des plaquettes avant'),
        ),
        migrations.AddField(
            model_name='voiturefreinsav',
            name='type_disques_av',
            field=models.CharField(choices=[('MONOBLOC_PLEIN', 'Plein (monobloc)'), ('VENTILE', 'Ventilé'), ('RAINURE', 'Rainuré'), ('PERCE', 'Percé'), ('RAINURE_PERCE', 'Rainuré et percé')], default='MONOBLOC_PLEIN', max_length=25, verbose_name='Type disque avant'),
        ),
    ]
