# Generated by Django 6.0 on 2026-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeuPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('ROTULE_DIRECTION', 'Rotule de direction'), ('ROTULE_SUSPENSION', 'Rotule de suspension'), ('BIELLETTE_BARRE_STAB', 'Biellette de barre stabilisatrice'), ('BARRE_STABILISATRICE', 'Barre stabilisatrice'), ('AMORTISSEUR', 'Amortisseur'), ('ROULEMENT_ROUE', 'Roulement de roue'), ('TRIANGLE', 'Triangle'), ('MULTI_BRAS', 'Multi-bras')], max_length=50, verbose_name='Pièce contrôlée')),
                ('emplacement', models.CharField(choices=[('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('AV', 'Avant'), ('AR', 'Arrière'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=10, verbose_name='Emplacement')),
                ('etat', models.CharField(blank=True, choices=[('BON', 'Bon'), ('USE', 'Usé'), ('HS', 'Hors service')], max_length=10, null=True, verbose_name='État')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='VERT', max_length=10, verbose_name='État visuel / Tag')),
                ('commentaire', models.TextField(blank=True, verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('APPRENTI', 'Apprenti'), ('MECANICIEN', 'Mécanicien'), ('CHEF', 'Chef mécanicien')], max_length=20)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
