# Generated by Django 5.2.9 on 2025-12-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_apprentis_maintenance_chef_mecanicien'),
        ('utilisateurs', '0001_initial'),
        ('voiture_exemplaire', '0002_alter_voitureexemplaire_numero_moteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeuPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('ROTULE_DIRECTION', 'Rotule de direction'), ('ROTULE_SUSPENSION', 'Rotule de suspension'), ('BIELLETTE_BARRE_STAB', 'Biellette de barre stabilisatrice'), ('BARRE_STABILISATRICE', 'Barre stabilisatrice'), ('AMORTISSEUR', 'Amortisseur'), ('ROULEMENT_ROUE', 'Roulement de roue'), ('TRIANGLE', 'Triangle'), ('MULTI_BRAS', 'Multi-bras')], max_length=50, verbose_name='Pièce contrôlée')),
                ('emplacement', models.CharField(choices=[('AVG', 'Avant gauche'), ('AVD', 'Avant droit'), ('ARG', 'Arrière gauche'), ('ARD', 'Arrière droit'), ('AV', 'Avant'), ('AR', 'Arrière'), ('SUP', 'Supérieur'), ('INF', 'Inférieur')], max_length=10, verbose_name='Emplacement')),
                ('etat', models.CharField(blank=True, choices=[('BON', 'Bon'), ('USE', 'Usé'), ('HS', 'Hors service')], max_length=10, null=True, verbose_name='État')),
                ('commentaire', models.TextField(blank=True, verbose_name='Observation')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeux_pieces', to='maintenance.maintenance', verbose_name='Maintenance')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
        ),
        migrations.CreateModel(
            name='RapportMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_generale', models.TextField(verbose_name='Note générale / rapport')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilisateurs.utilisateur', verbose_name='Rédigé par')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='maintenance.maintenance')),
            ],
        ),
    ]
