# Generated by Django 5.2.9 on 2025-12-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0001_initial'),
        ('maintenance', '0003_maintenance_apprentis_maintenance_chef_mecanicien'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeupiece',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='VERT', max_length=10, verbose_name='État visuel / Tag'),
        ),
        migrations.CreateModel(
            name='NoteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('APPRENTI', 'Apprenti'), ('MECANICIEN', 'Mécanicien'), ('CHEF', 'Chef mécanicien')], max_length=20)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilisateurs.utilisateur')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='maintenance.maintenance')),
            ],
        ),
        migrations.DeleteModel(
            name='RapportMaintenance',
        ),
    ]
