# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jeux_pieces', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('voiture_exemplaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jeupiece',
            name='maintenance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jeux_pieces', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='jeupiece',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='notemaintenance',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemaintenance',
            name='maintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='maintenance.maintenance'),
        ),
    ]
