# Generated by Django 5.2.10 on 2026-03-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0003_remove_notemaintenance_auteur_and_more'),
        ('voiture_exemplaire', '0009_alter_voitureexemplaire_pays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='utilisateur_role',
            field=models.CharField(blank=True, choices=[('APPRENTI', 'Apprenti'), ('MECANICIEN', 'Mécanicien'), ('CHEF', 'Chef mécanicien')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='voiture_exemplaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jeux_pieces_checkup', to='voiture_exemplaire.voitureexemplaire', verbose_name='Kilomètres jeu pièces'),
        ),
    ]
