# Generated by Django 5.2.10 on 2026-03-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0005_alter_controlejeuxpieces_options_and_more'),
        ('societe', '0002_alter_societe_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='date_creation',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='controlejeuxpieces',
            name='remarques',
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='tech_nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='tech_role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_jeux_societe', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='tech_technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_jeux_technicien', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='utilisateurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_jeux_utilisateurs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
