# Generated by Django 5.2.10 on 2026-03-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0006_rename_date_creation_controlejeuxpieces_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='utilisateurs',
            new_name='tech_utilisateurs',
        ),
        migrations.RemoveField(
            model_name='controlejeuxpieces',
            name='tech_technicien',
        ),
    ]
