# Generated by Django 5.2.10 on 2026-03-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0007_rename_utilisateurs_controlejeuxpieces_tech_utilisateurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
    ]
