# Generated by Django 5.2.10 on 2026-03-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0008_controlejeuxpieces_remarques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='tech_utilisateurs',
            new_name='tech_technicien',
        ),
    ]
