# Generated by Django 5.2.10 on 2026-03-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0009_rename_tech_utilisateurs_controlejeuxpieces_tech_technicien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlejeuxpieces',
            name='kilometrage_checkup',
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='kilometrage_jeu',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du controle des jeux'),
        ),
    ]
