# Generated by Django 5.2.10 on 2026-03-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0010_remove_controlejeuxpieces_kilometrage_checkup_and_more'),
        ('maintenance', '0003_maintenance_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='maintenance',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jeux_pieces', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
    ]
