# Generated by Django 5.2.10 on 2026-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0011_alter_controlejeuxpieces_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
