# Generated by Django 5.2.10 on 2026-04-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0012_controlejeuxpieces_created_at_and_more'),
        ('maindoeuvre', '0003_remove_maindoeuvre_temps_maindoeuvre_temps_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeux_pieces', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
