# Generated by Django 5.2.10 on 2026-05-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0013_controlejeuxpieces_main_oeuvre'),
        ('maintenance', '0011_alter_maintenance_type_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jeux_pieces', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
    ]
