# Generated by Django 5.2.10 on 2026-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0016_alter_controlejeuxpieces_kilometrage_jeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu amortisseur avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_barre_stabilisatrice_ar',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice arrière'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_barre_stabilisatrice_av',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu barre stabilisatrice avant'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu suspension multi-bras avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de direction avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension inférieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeux rotule de suspension supérieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu roulement avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant droit'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu triangle avant gauche'),
        ),
    ]
