# Generated by Django 5.2.10 on 2026-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0018_controlejeuxpieces_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la biellette de barre stabilisatrice arrière droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la biellette de barre stabilisatrice arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la biellette de barre stabilisatrice avant droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la biellette de barre stabilisatrice avant gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_Biellette_barre_stabilisatrice_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix de l'amortisseur arrière droit"),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix de l'amortisseur arrière gauche"),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix de l'amortisseur avant droit"),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix de l'amortisseur avant gauche"),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_amortisseur_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_barre_stabilisatrice_ar_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la barre stabilisatrice arrière'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_barre_stabilisatrice_ar_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_barre_stabilisatrice_av_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la barre stabilisatrice avant'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_barre_stabilisatrice_av_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la suspension multi-bras arrière droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la suspension multi-bras arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la suspension multi-bras avant droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la suspension multi-bras avant gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_multi_bras_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de direction arrière droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de direction arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de direction avant droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de direction avant gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_direction_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension inférieure arrière droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension inférieure arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension inférieure avant droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension inférieure avant gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension supérieure arrière droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension supérieure arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension supérieure avant droite'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de la rotule de suspension supérieure avant gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du roulement arrière droit'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du roulement arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du roulement avant droit'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du roulement avant gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_roulement_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_ard_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du triangle arrière droit'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_ard_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_arg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du triangle arrière gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_arg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_avd_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du triangle avant droit'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_avd_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_avg_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix du triangle avant gauche'),
        ),
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='jeu_triangle_avg_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure avant droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_inferieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension inférieure avant gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure arrière droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure arrière gauche'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure avant droite'),
        ),
        migrations.AlterField(
            model_name='controlejeuxpieces',
            name='jeu_rotule_suspension_superieure_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Jeu rotule de suspension supérieure avant gauche'),
        ),
    ]
