# Generated by Django 5.2.10 on 2026-07-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0021_alter_controlejeuxpieces_taux_horaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_ard',
            new_name='jeu_biellette_barre_stabilisatrice_ard',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_ard_fabricant',
            new_name='jeu_biellette_barre_stabilisatrice_ard_fabricant',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_ard_prix',
            new_name='jeu_biellette_barre_stabilisatrice_ard_prix',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_ard_quantite',
            new_name='jeu_biellette_barre_stabilisatrice_ard_quantite',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_arg',
            new_name='jeu_biellette_barre_stabilisatrice_arg',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_arg_fabricant',
            new_name='jeu_biellette_barre_stabilisatrice_arg_fabricant',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_arg_prix',
            new_name='jeu_biellette_barre_stabilisatrice_arg_prix',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avd',
            new_name='jeu_biellette_barre_stabilisatrice_avd',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avd_fabricant',
            new_name='jeu_biellette_barre_stabilisatrice_avd_fabricant',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avd_prix',
            new_name='jeu_biellette_barre_stabilisatrice_avd_prix',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avd_quantite',
            new_name='jeu_biellette_barre_stabilisatrice_avd_quantite',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avg',
            new_name='jeu_biellette_barre_stabilisatrice_avg',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avg_fabricant',
            new_name='jeu_biellette_barre_stabilisatrice_avg_fabricant',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avg_prix',
            new_name='jeu_biellette_barre_stabilisatrice_avg_prix',
        ),
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_avg_quantite',
            new_name='jeu_biellette_barre_stabilisatrice_avg_quantite',
        ),
    ]
