# Generated by Django 5.2.10 on 2026-07-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0022_rename_jeu_biellette_barre_stabilisatrice_ard_controlejeuxpieces_jeu_biellette_barre_stabilisatrice_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlejeuxpieces',
            old_name='jeu_Biellette_barre_stabilisatrice_arg_quantite',
            new_name='jeu_biellette_barre_stabilisatrice_arg_quantite',
        ),
    ]
