# Generated by Django 5.2.10 on 2026-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0023_rename_jeu_biellette_barre_stabilisatrice_arg_quantite_controlejeuxpieces_jeu_biellette_barre_stabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='pays',
            field=models.CharField(choices=[('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('CY', 'Chypre'), ('CZ', 'Tchéquie'), ('DE', 'Allemagne'), ('DK', 'Danemark'), ('EE', 'Estonie'), ('ES', 'Espagne'), ('FI', 'Finlande'), ('FR', 'France'), ('GR', 'Grèce'), ('HR', 'Croatie'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('IT', 'Italie'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('LV', 'Lettonie'), ('MT', 'Malte'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SE', 'Suède'), ('SI', 'Slovénie'), ('SK', 'Slovaquie')], default='BE', max_length=5, verbose_name='Pays'),
        ),
    ]
