# Generated by Django 5.2.10 on 2026-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0025_alter_controlejeuxpieces_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
