# Generated by Django 5.2.10 on 2026-08-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0026_controlejeuxpieces_kilometrage_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='serrage_roues',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('FAIT', 'Fait')], default='A_FAIRE', max_length=25, verbose_name='Serrage des roues'),
        ),
    ]
