# Generated by Django 5.2.10 on 2026-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_pieces', '0029_alter_controlejeuxpieces_jeu_amortisseur_ard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlejeuxpieces',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
