# Generated by Django 5.2.10 on 2026-07-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refroidissement',
            old_name='fuite_localisation',
            new_name='presence_fuite_localisation',
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='boitier_eau',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=20, verbose_name="Boîtier d'eau"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='chaufferette',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=20, verbose_name='Radiateur de chauffage'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='durites',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=20, verbose_name='Durites de refroidissement'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='radiateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=20, verbose_name='Radiateur moteur'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='sonde_temperature_liquide',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=20, verbose_name='Sonde de température du liquide'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='thermostat',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=20, verbose_name='Thermostat'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='ventilateur',
            field=models.CharField(choices=[('OK', 'OK'), ('A_REMPLACER', 'À remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=20, verbose_name='Ventilateur de refroidissement'),
        ),
    ]
