# Generated by Django 5.2.10 on 2026-07-18 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0002_rename_fuite_localisation_refroidissement_presence_fuite_localisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refroidissement',
            name='taux_horaire',
            field=models.DecimalField(choices=[(Decimal('50.00'), '50 €/h'), (Decimal('60.00'), '60 €/h'), (Decimal('70.00'), '70 €/h'), (Decimal('80.00'), '80 €/h'), (Decimal('90.00'), '90 €/h'), (Decimal('100.00'), '100 €/h'), (Decimal('110.00'), '110 €/h')], decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Taux horaire'),
        ),
    ]
