# Generated by Django 5.2.10 on 2026-07-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0003_refroidissement_taux_horaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refroidissement',
            old_name='ventilateur',
            new_name='ventilateur_etat',
        ),
    ]
