# Generated by Django 5.2.10 on 2026-07-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0004_rename_ventilateur_refroidissement_ventilateur_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refroidissement',
            name='ventilateur_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='ventilateur_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='ventilateur_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='ventilateur_tva_vente',
        ),
    ]
