# Generated by Django 5.2.10 on 2026-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0005_remove_refroidissement_ventilateur_prix_ttc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refroidissement',
            old_name='sonde_temperature_liquide',
            new_name='sonde_temperature_etat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='boitier_eau_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='boitier_eau_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='boitier_eau_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='boitier_eau_tva_vente',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='chaufferette_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='chaufferette_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='chaufferette_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='chaufferette_tva_vente',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='durites_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='durites_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='durites_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='durites_tva_vente',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='radiateur_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='radiateur_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='radiateur_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='radiateur_tva_vente',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='sonde_temperature_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='sonde_temperature_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='sonde_temperature_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='sonde_temperature_tva_vente',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='thermostat_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='thermostat_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='thermostat_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='thermostat_tva_vente',
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='Étiquette'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='ventilateur_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité de ventilateurs'),
        ),
    ]
