# Generated by Django 5.2.10 on 2026-07-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0006_rename_sonde_temperature_liquide_refroidissement_sonde_temperature_etat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refroidissement',
            old_name='sonde_temperature_prix_achat',
            new_name='sonde_t_prix_achat',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='sonde_temperature_quantite',
            new_name='sonde_t_quantite',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='sonde_temperature_signal_correct',
            new_name='sonde_t_signal_correct',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='sonde_temperature_valeur',
            new_name='sonde_t_valeur',
        ),
    ]
