# Generated by Django 5.2.10 on 2026-07-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0007_rename_sonde_temperature_prix_achat_refroidissement_sonde_t_prix_achat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refroidissement',
            old_name='sonde_temperature_etat',
            new_name='sonde_t_etat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='liquide_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='liquide_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='liquide_tva_achat',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='liquide_tva_vente',
        ),
    ]
