# Generated by Django 5.2.10 on 2026-08-12 12:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0012_refroidissement_liquide_fabricant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refroidissement',
            old_name='chaufferette_prix_achat',
            new_name='chaufferette_prix',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='durites_prix_achat',
            new_name='durites_prix',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='liquide_prix_achat',
            new_name='liquide_prix',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='radiateur_prix_achat',
            new_name='radiateur_prix',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='sonde_t_prix_achat',
            new_name='sonde_t_prix',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='thermostat_prix_achat',
            new_name='thermostat_prix',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='ventilateur_prix_achat',
            new_name='ventilateur_prix',
        ),
        migrations.RemoveField(
            model_name='refroidissement',
            name='boitier_eau_prix_achat',
        ),
        migrations.AddField(
            model_name='refroidissement',
            name='boitier_eau_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA du boîtier d'eau"),
        ),
    ]
