# Generated by Django 5.2.10 on 2026-08-19 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0015_alter_refroidissement_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refroidissement',
            name='boitier_eau_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='boitier_eau_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='chaufferette_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='chaufferette_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='durites_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='durites_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='liquide_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='liquide_quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantité ajoutée en litres', max_digits=7, verbose_name='Quantité de liquide utilisée'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='liquide_type',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=20, verbose_name='Type du liquide de refroidissement'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='radiateur_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='radiateur_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='sonde_t_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='sonde_t_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='thermostat_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='thermostat_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='ventilateur_prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AlterField(
            model_name='refroidissement',
            name='ventilateur_quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
