# Generated by Django 5.2.10 on 2026-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0016_alter_refroidissement_boitier_eau_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refroidissement',
            old_name='boitier_eau',
            new_name='boitier_eau_etat',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='chaufferette',
            new_name='chaufferette_etat',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='durites',
            new_name='durites_etat',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='radiateur',
            new_name='radiateur_etat',
        ),
        migrations.RenameField(
            model_name='refroidissement',
            old_name='thermostat',
            new_name='thermostat_etat',
        ),
    ]
