# Generated by Django 5.2.10 on 2026-08-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0017_rename_boitier_eau_refroidissement_boitier_eau_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refroidissement',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
