# Generated by Django 5.2.10 on 2026-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidissement', '0021_alter_refroidissement_liquide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refroidissement',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
