# Generated by Django 5.2.9 on 2025-12-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_maintenance_apprentis_maintenance_chef_mecanicien'),
        ('utilisateurs', '0001_initial'),
        ('voiture_exemplaire', '0002_alter_voitureexemplaire_numero_moteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='NettoyageInterieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitres', models.BooleanField(default=False, verbose_name='Vitres')),
                ('pare_brise', models.BooleanField(default=False, verbose_name='Pare-brise')),
                ('aspirateur', models.BooleanField(default=False, verbose_name='Aspirateur')),
                ('interieur_portes', models.BooleanField(default=False, verbose_name='Intérieurs de porte')),
                ('tableau_de_bord', models.BooleanField(default=False, verbose_name='Tableau de bord')),
                ('plastiques', models.BooleanField(default=False, verbose_name='Plastiques')),
                ('validation', models.BooleanField(default=False, verbose_name='Validation finale')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_interieur', to='maintenance.maintenance', verbose_name='Check up')),
                ('mecanicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nettoyages_interieur', to='utilisateurs.utilisateur', verbose_name='Mécanicien')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_interieur', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Nettoyage intérieur',
                'verbose_name_plural': 'Nettoyages intérieurs',
            },
        ),
    ]
