# Generated by Django 5.2.10 on 2026-03-23 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0001_initial'),
        ('societe', '0002_alter_societe_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='mecanicien',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='validation',
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='tag',
            field=models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='tech_nom_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='tech_role_technicien',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nettoyages_interieur_societe', to='societe.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='tech_utilisateurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nettoyage_interieur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
