# Generated by Django 5.2.10 on 2026-03-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenance_societe'),
        ('nettoyage_interieur', '0002_remove_nettoyageinterieur_mecanicien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='aspirateur',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='interieur_portes',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='pare_brise',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='plastiques',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='tableau_de_bord',
        ),
        migrations.RemoveField(
            model_name='nettoyageinterieur',
            name='vitres',
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='kilometrage_net_int',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du Nettoyage intérieur'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_aspirateur',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Aspirateur'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_console',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Console centrale'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_interieur_portes',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Ouvrants de portes'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_pare_brise',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Pare-brise'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_plastiques',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Plastiques'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_tableau_de_bord',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Tableau de bord'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_vitres',
            field=models.CharField(choices=[('A_FAIRE', 'A faire'), ('FAIT', 'Fait'), ('REPORTER', 'Reporter'), ('PROPRE', 'Propre')], default='A_FAIRE', max_length=25, verbose_name='Vitres'),
        ),
        migrations.AlterField(
            model_name='nettoyageinterieur',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_interieur', to='maintenance.maintenance', verbose_name='Nettoyage Interieur'),
        ),
    ]
