# Generated by Django 5.2.10 on 2026-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0003_remove_nettoyageinterieur_aspirateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageinterieur',
            old_name='tag',
            new_name='tag_nettoyage_ext',
        ),
    ]
