# Generated by Django 5.2.10 on 2026-03-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0004_rename_tag_nettoyageinterieur_tag_nettoyage_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageinterieur',
            old_name='tag_nettoyage_ext',
            new_name='tag_nettoyage_int',
        ),
    ]
