# Generated by Django 5.2.10 on 2026-03-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0005_rename_tag_nettoyage_ext_nettoyageinterieur_tag_nettoyage_int'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageinterieur',
            old_name='tech_utilisateurs',
            new_name='tech_technicien',
        ),
    ]
