# Generated by Django 5.2.10 on 2026-04-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0006_rename_tech_utilisateurs_nettoyageinterieur_tech_technicien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageinterieur',
            old_name='tag_nettoyage_int',
            new_name='tag',
        ),
    ]
