# Generated by Django 5.2.10 on 2026-04-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindoeuvre', '0003_remove_maindoeuvre_temps_maindoeuvre_temps_minutes'),
        ('nettoyage_interieur', '0007_rename_tag_nettoyage_int_nettoyageinterieur_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nettoyage_interieur', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
