# Generated by Django 5.2.10 on 2026-04-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0008_nettoyageinterieur_main_oeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
