# Generated by Django 5.2.10 on 2026-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0010_alter_nettoyageinterieur_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageinterieur',
            name='kilometrage_net_int',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du Nettoyage intérieur'),
            preserve_default=False,
        ),
    ]
