# Generated by Django 5.2.10 on 2026-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0012_nettoyageinterieur_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_produits_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_produits_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
