# Generated by Django 5.2.10 on 2026-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0019_alter_nettoyageinterieur_nettoyage_interieur_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageinterieur',
            name='nettoyage_interieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
    ]
