# Generated by Django 5.2.10 on 2026-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_interieur', '0020_alter_nettoyageinterieur_nettoyage_interieur_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettoyageinterieur',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
