# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoiteAutomatique',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('nb_vitesses', models.IntegerField(choices=[(4, '4 vitesses'), (5, '5 vitesses'), (6, '6 vitesses'), (8, '8 vitesses')], verbose_name='Nombre de vitesses')),
                ('convertisseur_torque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Convertisseur de couple')),
                ('embrayage_hydraulique', models.CharField(blank=True, max_length=255, null=True, verbose_name='Embrayage hydraulique')),
                ('train_planetaire', models.CharField(blank=True, max_length=255, null=True, verbose_name='Train planétaire')),
                ('frein_planetaire', models.CharField(blank=True, max_length=255, null=True, verbose_name='Frein planétaire')),
                ('piston', models.CharField(blank=True, max_length=255, null=True, verbose_name='Piston')),
                ('valve_body', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bloc hydraulique')),
                ('solenoides', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solénoïdes')),
                ('huile_transmission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Huile de transmission')),
            ],
            options={
                'verbose_name': 'Boîte automatique',
                'verbose_name_plural': 'Boîtes automatiques',
            },
            bases=('piece.piece',),
        ),
        migrations.CreateModel(
            name='BoiteMecanique',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('nb_vitesses', models.IntegerField(choices=[(5, '5 vitesses'), (6, '6 vitesses'), (7, '7 vitesses')], verbose_name='Nombre de vitesses')),
                ('pignon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pignon')),
                ('synchro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Synchroniseur')),
                ('arbre_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arbre principal')),
                ('arbre_secondaire', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arbre secondaire')),
                ('fourchette_vitesse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fourchette de vitesse')),
                ('tringlerie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tringlerie')),
                ('huile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Huile de boîte')),
            ],
            options={
                'verbose_name': 'Boîte mécanique',
                'verbose_name_plural': 'Boîtes mécaniques',
            },
            bases=('piece.piece',),
        ),
    ]
