# Generated by Django 6.0 on 2026-01-05 09:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureMarque',
            fields=[
                ('id_marque', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_marque', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Le nom de la marque doit contenir au moins 2 caractères'), django.core.validators.MaxLengthValidator(50, message='Le nom de la marque ne peut pas dépasser 50 caractères')])),
            ],
            options={
                'verbose_name': 'Marque de voiture',
                'verbose_name_plural': 'Marques de voitures',
                'ordering': ['nom_marque'],
            },
        ),
        migrations.CreateModel(
            name='MarqueFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marques_favorites', to=settings.AUTH_USER_MODEL)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='voiture_marque.voituremarque')),
            ],
            options={
                'verbose_name': 'Marque favorite',
                'verbose_name_plural': 'Marques favorites',
                'ordering': ['-created_at'],
                'unique_together': {('utilisateur', 'marque')},
            },
        ),
    ]
