# Generated by Django 6.0 on 2025-12-14 09:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureMarque',
            fields=[
                ('id_marque', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_marque', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Le nom de la marque doit contenir au moins 2 caractères'), django.core.validators.MaxLengthValidator(50, message='Le nom de la marque ne peut pas dépasser 50 caractères')])),
            ],
            options={
                'verbose_name': 'Marque de voiture',
                'verbose_name_plural': 'Marques de voitures',
                'ordering': ['nom_marque'],
            },
        ),
    ]
