# Generated by Django 6.0 on 2026-01-09 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_marque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='marquefavorite',
            old_name='utilisateur',
            new_name='societe',
        ),
        migrations.AlterUniqueTogether(
            name='marquefavorite',
            unique_together={('societe', 'marque')},
        ),
    ]
