# Generated by Django 6.0 on 2026-01-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_marque', '0002_marquefavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marquefavorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marque favorite', 'verbose_name_plural': 'Marques favorites'},
        ),
    ]
