# Generated by Django 5.2.10 on 2026-05-30 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture_marque', '0003_alter_voituremarque_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituremarque',
            name='nom_marque',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Le nom de la marque doit contenir au moins 2 caractères'), django.core.validators.MaxLengthValidator(50, message='Le nom de la marque ne peut pas dépasser 50 caractères')]),
        ),
    ]
