# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_check_up', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlegeneral',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_general', to='maintenance.maintenance', verbose_name='Maintenance'),
        ),
        migrations.AddField(
            model_name='amortisseurcontrole',
            name='controle_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortisseurs', to='controle_check_up.controlegeneral', verbose_name='Contrôle général'),
        ),
        migrations.AddField(
            model_name='ressortcontrole',
            name='controle_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressorts', to='controle_check_up.controlegeneral', verbose_name='Contrôle général'),
        ),
    ]
