# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('voiture_exemplaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NettoyageExterieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traces_gomme', models.BooleanField(default=False, verbose_name='Traces de gomme')),
                ('carrosserie', models.BooleanField(default=False, verbose_name='Carrosserie')),
                ('jantes', models.BooleanField(default=False, verbose_name='Jantes')),
                ('validation', models.BooleanField(default=False, verbose_name='Validation finale')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_exterieur', to='maintenance.maintenance', verbose_name='Check up')),
                ('mecanicien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nettoyage_exterieur', to=settings.AUTH_USER_MODEL, verbose_name='Mécanicien')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_exterieur', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Nettoyage extérieur',
                'verbose_name_plural': 'Nettoyages extérieurs',
            },
        ),
    ]
