# Generated by Django 5.2.10 on 2026-03-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0002_remove_nettoyageexterieur_carrosserie_and_more'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettoyageexterieur',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='tech_societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nettoyages_exterieur_societe', to='societe.societe', verbose_name='Société'),
        ),
    ]
