# Generated by Django 5.2.10 on 2026-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0003_nettoyageexterieur_remarques_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageexterieur',
            old_name='tag',
            new_name='tag_nettoyage_ext',
        ),
    ]
