# Generated by Django 5.2.10 on 2026-03-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0004_rename_tag_nettoyageexterieur_tag_nettoyage_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageexterieur',
            old_name='tech_utilisateurs',
            new_name='tech_technicien',
        ),
    ]
