# Generated by Django 5.2.10 on 2026-03-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0005_rename_tech_utilisateurs_nettoyageexterieur_tech_technicien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageexterieur',
            old_name='tag_nettoyage_ext',
            new_name='tag_nettoyage',
        ),
    ]
