# Generated by Django 5.2.10 on 2026-03-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0006_rename_tag_nettoyage_ext_nettoyageexterieur_tag_nettoyage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageexterieur',
            old_name='tag_nettoyage',
            new_name='tag_nettoyage_ext',
        ),
    ]
