# Generated by Django 5.2.10 on 2026-04-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0007_rename_tag_nettoyage_nettoyageexterieur_tag_nettoyage_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nettoyageexterieur',
            old_name='tag_nettoyage_ext',
            new_name='tag',
        ),
    ]
