# Generated by Django 5.2.10 on 2026-05-11 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenance_tech_nom_technicien_and_more'),
        ('nettoyage_exterieur', '0010_nettoyageexterieur_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_exterieur', to='maintenance.maintenance', verbose_name='nettoyage_ext'),
        ),
    ]
