# Generated by Django 5.2.10 on 2026-05-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_maintenance_type_maintenance'),
        ('nettoyage_exterieur', '0011_alter_nettoyageexterieur_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nettoyages_exterieur', to='maintenance.maintenance', verbose_name='Nettoyage extérieur'),
        ),
    ]
