# Generated by Django 5.2.10 on 2026-06-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0013_alter_nettoyageexterieur_kilometres_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='kilometrage_net_ext',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du Nettoyage extérieur'),
            preserve_default=False,
        ),
    ]
