# Generated by Django 5.2.10 on 2026-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0016_nettoyageexterieur_nettoyage_exterieur_produits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='nettoyage_exterieur_sechage',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Séchage'),
        ),
    ]
