# Generated by Django 5.2.10 on 2026-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0019_alter_nettoyageexterieur_taux_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
    ]
