# Generated by Django 5.2.10 on 2026-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0022_alter_nettoyageexterieur_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettoyageexterieur',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
