# Generated by Django 5.2.10 on 2026-08-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0023_nettoyageexterieur_kilometrage_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouter les produits')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
    ]
