# Generated by Django 5.2.10 on 2026-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0024_alter_nettoyageexterieur_nettoyage_exterieur_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouter')], default='SANS', max_length=25, verbose_name='Produits'),
        ),
    ]
