# Generated by Django 5.2.10 on 2026-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0025_alter_nettoyageexterieur_nettoyage_exterieur_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettoyageexterieur',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
