# Generated by Django 5.2.10 on 2026-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettoyage_exterieur', '0029_alter_nettoyageexterieur_nettoyage_exterieur_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettoyageexterieur',
            name='nettoyage_exterieur_produits',
            field=models.CharField(choices=[('SANS', 'Sans produits'), ('AJOUTER', 'Ajouté')], default='SANS', max_length=25, verbose_name='Produits de nettoyage'),
        ),
    ]
