# Generated by Django 5.2.10 on 2026-04-25 09:30

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0006_alter_maintenance_kilometres_dernier_entretien'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis')),
                ('kilometrage_abs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage au moment du controle ABS ')),
                ('pays', models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=5)),
                ('pompe_abs', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Pompe d'ABS")),
                ('pompe_abs_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de la pompe ABS")),
                ('pompe_abs_tva_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à récupérer')),
                ('pompe_abs_marge', models.IntegerField(blank=True, null=True, verbose_name='Marge')),
                ('pompe_abs_prix_vente_htva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente htva')),
                ('pompe_abs_tva_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer')),
                ('pompe_abs_prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TVAC')),
                ('pompe_abs_quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('calculateur_abs', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="calculateur d'ABS")),
                ('calculateur_abs_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de la pompe à eau")),
                ('calculateur_abs_tva_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à récupérer')),
                ('calculateur_abs_marge', models.IntegerField(blank=True, null=True, verbose_name='Marge')),
                ('calculateur_abs_prix_vente_htva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente htva')),
                ('calculateur_abs_tva_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer')),
                ('calculateur_abs_prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TVAC')),
                ('calculateur_abs_quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('capteur_abs_avd', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='capteur ABS avant droit')),
                ('capteur_abs_avg', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='capteur ABS avant gauche')),
                ('capteur_abs_ard', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='capteur ABS arrière droit')),
                ('capteur_abs_arg', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='capteur ABS arrière gauche')),
                ('capteur_abs', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='capteur ABS')),
                ('capteur_abs_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de la pompe à eau")),
                ('capteur_abs_tva_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à récupérer')),
                ('capteur_abs_marge', models.IntegerField(blank=True, null=True, verbose_name='Marge')),
                ('capteur_abs_prix_vente_htva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente htva')),
                ('capteur_abs_tva_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer')),
                ('capteur_abs_prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TVAC')),
                ('capteur_abs_quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abs', to='maintenance.maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abs', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'verbose_name': 'système_abs',
                'verbose_name_plural': 'Systèmes_abss',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
