# Generated by Django 5.2.10 on 2026-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0002_alter_abs_capteur_abs_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Capteur ABS'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Capteur ABS arrière droit'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Capteur ABS arrière gauche'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Capteur ABS avant droit'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Capteur ABS avant gauche'),
        ),
    ]
