# Generated by Django 5.2.10 on 2026-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0003_alter_abs_capteur_abs_alter_abs_capteur_abs_ard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs',
            name='calculateur_abs',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name="Calculateur d'ABS"),
        ),
    ]
