# Generated by Django 5.2.10 on 2026-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0005_abs_main_oeuvre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs',
            name='calculateur_abs_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva du calculateur d'ABS"),
        ),
    ]
