# Generated by Django 5.2.10 on 2026-05-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0006_alter_abs_calculateur_abs_prix_achat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abs',
            old_name='calculateur_abs_prix_achat',
            new_name='calculateur_abs_prix',
        ),
        migrations.RenameField(
            model_name='abs',
            old_name='capteur_abs_prix_achat',
            new_name='capteur_abs_prix',
        ),
        migrations.RenameField(
            model_name='abs',
            old_name='pompe_abs_prix_achat',
            new_name='pompe_abs_prix',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='calculateur_abs_marge',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='calculateur_abs_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='calculateur_abs_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='calculateur_abs_tva_achat',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='calculateur_abs_tva_vente',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='capteur_abs_marge',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='capteur_abs_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='capteur_abs_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='capteur_abs_tva_achat',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='capteur_abs_tva_vente',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='pompe_abs_marge',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='pompe_abs_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='pompe_abs_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='pompe_abs_tva_achat',
        ),
        migrations.RemoveField(
            model_name='abs',
            name='pompe_abs_tva_vente',
        ),
    ]
