# Generated by Django 5.2.10 on 2026-05-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0007_rename_calculateur_abs_prix_achat_abs_calculateur_abs_prix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abs',
            options={'verbose_name': 'système_abs', 'verbose_name_plural': 'Systèmes_abs'},
        ),
    ]
