# Generated by Django 5.2.10 on 2026-05-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0008_alter_abs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abs',
            options={'verbose_name': 'Système ABS', 'verbose_name_plural': 'Systèmes ABS'},
        ),
    ]
