# Generated by Django 5.2.10 on 2026-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0009_alter_abs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs',
            name='kilometrage_abs',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment du controle ABS '),
            preserve_default=False,
        ),
    ]
