# Generated by Django 5.2.10 on 2026-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0011_rename_capteur_abs_quantite_abs_capteur_abs_ard_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abs',
            name='calculateur_abs',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Calculateur d'ABS"),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_ard',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Capteur ABS arrière droit'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_arg',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Capteur ABS arrière gauche'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_avd',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Capteur ABS avant droit'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='capteur_abs_avg',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Capteur ABS avant gauche'),
        ),
        migrations.AlterField(
            model_name='abs',
            name='pompe_abs',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name="Pompe d'ABS"),
        ),
    ]
