# Generated by Django 5.2.10 on 2026-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0023_alter_abs_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='abs',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
