# Generated by Django 5.2.10 on 2026-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0025_abs_kilometres_boite_abs_kilometres_boite_rollback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abs',
            name='kilometres_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='abs',
            name='kilometres_embrayage_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres rollback embrayage'),
        ),
    ]
