# Generated by Django 5.2.10 on 2026-05-03 12:23

import client_atelier.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adresse', '0005_alter_adresse_societe'),
        ('societe', '0002_alter_societe_adresse'),
        ('societe_cliente', '0009_alter_societecliente_options_and_more'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAtelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client_particulier', models.UUIDField(default=uuid.uuid4)),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom du client')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du client')),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('numero_carte_id', models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro de carte d'identité")),
                ('numero_compte', models.CharField(blank=True, max_length=34, null=True, validators=[client_atelier.models.validate_iban], verbose_name='Numéro de compte bancaire')),
                ('numero_carte_bancaire', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de carte bancaire')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('adresse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresse.adresse', verbose_name='Adresse')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_atelier', to='societe.societe')),
                ('societe_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_atelier', to='societe_cliente.societecliente')),
                ('voitures', models.ManyToManyField(blank=True, related_name='client_particulier', to='voiture_exemplaire.voitureexemplaire', verbose_name='Voitures')),
            ],
        ),
    ]
