# Generated by Django 5.2.10 on 2026-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_atelier', '0001_initial'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientatelier',
            name='voitures',
            field=models.ManyToManyField(blank=True, related_name='client_atelier', to='voiture_exemplaire.voitureexemplaire', verbose_name='Voitures'),
        ),
    ]
