# Generated by Django 5.2.10 on 2026-05-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_atelier', '0002_alter_clientatelier_voitures'),
        ('client_particulier', '0009_delete_clientpilotage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientatelier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientatelier',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='clientatelier',
            name='numero_carte_bancaire',
        ),
        migrations.RemoveField(
            model_name='clientatelier',
            name='numero_carte_id',
        ),
        migrations.RemoveField(
            model_name='clientatelier',
            name='numero_compte',
        ),
        migrations.RemoveField(
            model_name='clientatelier',
            name='numero_telephone',
        ),
        migrations.RemoveField(
            model_name='clientatelier',
            name='prenom',
        ),
        migrations.AddField(
            model_name='clientatelier',
            name='client_particulier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_particulier.clientparticulier', verbose_name='Client atelier'),
        ),
    ]
