# Generated by Django 5.2.10 on 2026-09-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0007_adresse_societe'),
        ('client_atelier', '0003_remove_clientatelier_email_remove_clientatelier_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientatelier',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='client_atelier', to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
