# Generated by Django 5.2.10 on 2026-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece_moteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecemoteur',
            name='type_piece_moteur',
            field=models.CharField(choices=[('arbre_came_ad', 'Arbre à cames admission'), ('arbre_came_ec', 'Arbre à cames échappement'), ('vilebrequin', 'Vilebrequin'), ('bielle', 'Bielle'), ('durite_eau', 'Durite Eau'), ('durite_huile', 'Durite Huile'), ('durite_carburant', 'Durite Carburant'), ('piston', 'Piston'), ('soupape', 'Soupape'), ('bloc', 'Bloc moteur'), ('ressorts_soupape', 'Ressorts de Soupapes'), ('culbuteurs', 'Culbuteurs'), ('culasse', 'Culasse'), ('carter_huile', 'Carter Huile'), ('pompe_huile', 'Pompe Huile'), ('echangeur', 'Échangeur'), ('pressoirs_hydraulique', 'Pressoirs Hydraulique'), ('joint_culasse', 'Joint de Culasse'), ('Poulie_AAC_ADM', 'Poulie Arbre A Came Admission'), ('Poulie_AAC_ECH', 'Poulie Arbre A Came Échappement'), ('poulie_vilebrequin', 'Poulie de Vilebrequin'), ('distribution', 'Distribution'), ('chaine_distribution', 'Chaine de Distribution'), ('Courroie_distribution', 'Courroie de Distribution'), ('galets', 'Galets'), ('galet_tendeur', 'Galet Tendeur'), ('cache_soupapes', 'Cache Soupapes'), ('Bougies_allumage', 'Bougies Allumage'), ("Bobine d'allumage", "Bobine d'allumage"), ('bougies_préchauffage', 'Bougies Préchauffage'), ('vanne_EGR', 'Vanne EGR'), ('collecteur_admission', "Collecteur d'admission"), ('Collecteur_échappement', "Collecteur d'échappement"), ('injecteurs', 'Injecteurs'), ('pompe_carburant', 'Pompe à Carburant'), ('rampe_injection', "Rampe d'injection"), ('turbo', 'Turbo'), ('joint', 'Joint moteur'), ('kit_joints', 'Kit de joints'), ('poussoirs', 'Poussoirs'), ('pompe_eau', 'Pompe à Eau'), ('pompe_vide', 'Pompe à vide')], max_length=50, verbose_name='Type de pièce moteur'),
        ),
    ]
