# Generated by Django 6.0 on 2026-01-05 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rue', models.CharField(max_length=255, verbose_name='Rue')),
                ('numero', models.CharField(max_length=10, verbose_name='Numéro')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Belgique', max_length=100, verbose_name='Pays')),
                ('code_pays', models.CharField(default='BE', max_length=5, verbose_name='Code pays')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['ville', 'rue'],
            },
        ),
    ]
