# Generated by Django 5.2.10 on 2026-02-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0001_initial'),
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='societe.societe'),
        ),
    ]
