# Generated by Django 5.2.10 on 2026-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0002_adresse_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='boite',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Boite'),
        ),
    ]
