# Generated by Django 5.2.10 on 2026-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0003_adresse_boite'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adresse',
            constraint=models.UniqueConstraint(fields=('societe', 'rue', 'numero', 'boite', 'code_postal', 'ville'), name='unique_adresse_par_societe'),
        ),
    ]
