# Generated by Django 5.2.10 on 2026-03-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0004_adresse_unique_adresse_par_societe'),
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresse_clients', to='societe.societe'),
        ),
    ]
