# Generated by Django 5.2.10 on 2026-05-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0005_alter_adresse_societe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='societe',
        ),
    ]
