# Generated by Django 5.2.10 on 2026-02-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0002_adresse_societe'),
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresse_societe', to='adresse.adresse'),
        ),
    ]
