# Generated by Django 5.2.10 on 2026-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0002_alter_societe_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='societe',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
