# Generated by Django 5.2.10 on 2026-05-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresse', '0007_adresse_societe'),
        ('societe', '0003_remove_societe_adresse_alter_societe_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='société', to='adresse.adresse', verbose_name='Adresse'),
        ),
    ]
