# Generated by Django 5.2.10 on 2026-07-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0004_societe_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='max_utilisateurs',
            field=models.PositiveIntegerField(default=3, verbose_name="Nombre maximum d'utilisateurs"),
            preserve_default=False,
        ),
    ]
