# Generated by Django 5.2.10 on 2026-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0006_alter_societe_max_utilisateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='numero_tva',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numéro de TVA'),
        ),
    ]
