# Generated by Django 5.2.10 on 2026-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0007_societe_iban_alter_societe_numero_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='numero_tel',
            field=models.CharField(blank=True, max_length=25, verbose_name='Numéro de téléphone'),
        ),
    ]
