# Generated by Django 5.2.10 on 2026-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0008_societe_numero_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='numero_tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
