# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piece', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceBatterie',
            fields=[
                ('piece_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piece.piece')),
                ('type_piece_batterie', models.CharField(choices=[('batterie_12v', 'Batterie 12V'), ('batterie_agm', 'Batterie AGM'), ('batterie_eFB', 'Batterie EFB'), ('batterie_lithium', 'Batterie lithium'), ('batterie_haute_tension', 'Batterie haute tension (hybride/électrique)'), ('capteur_batterie', 'Capteur de batterie (IBS)'), ('boitier_batterie', 'Boîtier de batterie'), ('cache_batterie', 'Cache batterie'), ('systeme_maintien_batterie', 'Système de maintien batterie'), ('cosse_batterie_pos', 'Cosse batterie positive'), ('cosse_batterie_neg', 'Cosse batterie négative'), ('cable_batterie', 'Câble de batterie'), ('borne_batterie', 'Borne de batterie'), ('fusible_batterie', 'Fusible batterie'), ('porte_fusible_batterie', 'Porte-fusible batterie'), ('bride_batterie', 'Bride de batterie'), ('support_batterie', 'Support de batterie'), ('vis_fixation_batterie', 'Vis de fixation batterie'), ('gaine_protection', 'Gaine de protection'), ('isolant_batterie', 'Isolant de batterie'), ('tapis_batterie', 'Tapis de batterie'), ('kit_fixation_batterie', 'Kit fixation batterie'), ('kit_cosses_batterie', 'Kit cosses batterie'), ('kit_cables_batterie', 'Kit câbles batterie')], max_length=70, verbose_name='Type de pièce batterie')),
                ('voiture_modele', models.ManyToManyField(blank=True, related_name='pieces_batterie', to='voiture_modele.voituremodele')),
            ],
            options={
                'verbose_name': 'Pièce de batterie',
                'verbose_name_plural': 'Pièces de batterie',
            },
            bases=('piece.piece',),
        ),
    ]
