# Generated by Django 5.2.10 on 2026-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece_batterie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecebatterie',
            name='amperage',
            field=models.IntegerField(default=0, help_text='Ampèrage Maximum', verbose_name='Amperage'),
        ),
        migrations.AddField(
            model_name='piecebatterie',
            name='ampere_heures',
            field=models.IntegerField(default=0, verbose_name='Ampere heures'),
        ),
    ]
