# Generated by Django 5.2.10 on 2026-04-22 13:31

import django.db.models.deletion
import utils.mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0005_rename_kilometres_derniere_entretien_maintenance_kilometres_dernier_entretien'),
        ('societe', '0002_alter_societe_adresse'),
        ('voiture_exemplaire', '0017_voitureexemplaire_kilometres_remplacement_boite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourroieDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometres_chassis', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis')),
                ('kilometrage_courroie_distribution', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage de la courroie de distribution')),
                ('pays', models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=5)),
                ('diagnostic_rapport', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25)),
                ('courroie_distribution', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Courroie de distribution')),
                ('courroie_distribution_pompe_a_eau', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Pompe à eau')),
                ('courroie_distribution_kit', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Nouveau kit complet distribution')),
                ('courroie_distribution_prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva")),
                ('courroie_distribution_tva_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à récupérer')),
                ('courroie_distribution_marge', models.IntegerField(blank=True, null=True, verbose_name='Marge')),
                ('courroie_distribution_prix_vente_htva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente htva')),
                ('courroie_distribution_tva_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer')),
                ('courroie_distribution_prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TVAC')),
                ('courroie_distribution_quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('tag', models.CharField(choices=[('VERT', 'Vert'), ('JAUNE', 'Jaune'), ('ROUGE', 'Rouge')], default='JAUNE', max_length=10, verbose_name='État visuel / Tag')),
                ('tech_nom_technicien', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('tech_role_technicien', models.CharField(blank=True, max_length=255, verbose_name='Rôle du technicien')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courroie_distribution', to='maintenance.maintenance')),
                ('tech_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courroie_distribution', to='societe.societe', verbose_name='Société')),
                ('tech_technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courroie_distribution', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('voiture_exemplaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courroie_distribution', to='voiture_exemplaire.voitureexemplaire')),
            ],
            options={
                'verbose_name': 'Courroie de distribution',
                'verbose_name_plural': 'Courroie de distributions',
            },
            bases=(utils.mixin.TechnicienMixin, models.Model),
        ),
    ]
