# Generated by Django 5.2.10 on 2026-04-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='diagnostic_rapport',
        ),
    ]
