# Generated by Django 5.2.10 on 2026-04-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0002_remove_courroiedistribution_diagnostic_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroiedistribution',
            name='courroie_distribution_prix_achat_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de la pompe à eau"),
        ),
        migrations.AlterField(
            model_name='courroiedistribution',
            name='courroie_distribution_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva de la courroie"),
        ),
    ]
