# Generated by Django 5.2.10 on 2026-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0003_courroiedistribution_courroie_distribution_prix_achat_prix_achat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courroiedistribution',
            old_name='courroie_distribution_prix_achat_prix_achat',
            new_name='courroie_distribution_pompe_a_eau_prix_achat',
        ),
        migrations.AlterField(
            model_name='courroiedistribution',
            name='courroie_distribution_kit',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Nouveau kit distribution'),
        ),
    ]
