# Generated by Django 5.2.10 on 2026-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0004_rename_courroie_distribution_prix_achat_prix_achat_courroiedistribution_courroie_distribution_pompe_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courroiedistribution',
            old_name='courroie_distribution_pompe_a_eau',
            new_name='pompe_a_eau',
        ),
        migrations.RenameField(
            model_name='courroiedistribution',
            old_name='courroie_distribution_pompe_a_eau_prix_achat',
            new_name='pompe_a_eau_prix_achat',
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='pompe_a_eau_marge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marge'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='pompe_a_eau_prix_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix TVAC'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='pompe_a_eau_prix_vente_htva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente htva'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='pompe_a_eau_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='pompe_a_eau_tva_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à récupérer'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='pompe_a_eau_tva_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA à payer'),
        ),
    ]
