# Generated by Django 5.2.10 on 2026-04-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0005_rename_courroie_distribution_pompe_a_eau_courroiedistribution_pompe_a_eau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courroiedistribution',
            old_name='kilometrage_courroie_distribution',
            new_name='kilometrage_cour',
        ),
    ]
