# Generated by Django 5.2.10 on 2026-04-25 06:38

import maintenance.niveaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0006_rename_kilometrage_courroie_distribution_courroiedistribution_kilometrage_cour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courroiedistribution',
            options={'verbose_name': 'Courroie de distribution', 'verbose_name_plural': 'Courroies de distributions'},
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='refroidissement_qualite',
            field=models.CharField(choices=[('G11', 'G 11'), ('G12', 'G 12'), ('G12_PLUS', 'G 12+'), ('G12_PLUS_PLUS', 'G 12++'), ('G13', 'G 13'), ('G48', 'G 48'), ('MB_325_0', 'MB 325.0'), ('MB_325_3', 'MB 325.3'), ('MB_325_5', 'MB 325.5'), ('TYPE_D', 'Type D'), ('PSA_B71_5110', 'PSA B71 5110'), ('WSS_M97B44_D', 'WSS-M97B44-D'), ('WSS_M97B51_A1', 'WSS-M97B51-A1'), ('DEX_COOL', 'Dex-Cool'), ('TOYOTA_SLLC', 'Toyota SLLC'), ('HONDA_TYPE_2', 'Honda Type 2'), ('NISSAN_L248', 'Nissan L248'), ('NISSAN_L250', 'Nissan L250'), ('HYUNDAI_KIA_LLC', 'Hyundai/Kia Long Life Coolant')], default='G13', max_length=25, verbose_name='Qualité de liquide de refroidissement'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='refroidissement_quantite',
            field=models.FloatField(default=0, validators=[maintenance.niveaux.models.validate_step_0_1], verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
    ]
