# Generated by Django 5.2.10 on 2026-04-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0007_alter_courroiedistribution_options_and_more'),
        ('maindoeuvre', '0003_remove_maindoeuvre_temps_maindoeuvre_temps_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroiedistribution',
            name='main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courroie_distribution', to='maindoeuvre.maindoeuvre', verbose_name="Main d'oeuvre"),
        ),
    ]
