# Generated by Django 5.2.10 on 2026-05-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0008_courroiedistribution_main_oeuvre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courroiedistribution',
            old_name='courroie_distribution_prix_achat',
            new_name='courroie_distribution_prix',
        ),
        migrations.RenameField(
            model_name='courroiedistribution',
            old_name='pompe_a_eau_prix_achat',
            new_name='pompe_a_eau_prix',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='courroie_distribution_marge',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='courroie_distribution_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='courroie_distribution_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='courroie_distribution_tva_achat',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='courroie_distribution_tva_vente',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='pompe_a_eau_marge',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='pompe_a_eau_prix_ttc',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='pompe_a_eau_prix_vente_htva',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='pompe_a_eau_tva_achat',
        ),
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='pompe_a_eau_tva_vente',
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='refroidissement',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer')], default='OK', max_length=25, verbose_name='Liquide de refroidissement'),
        ),
    ]
