# Generated by Django 5.2.10 on 2026-05-29 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0009_rename_courroie_distribution_prix_achat_courroiedistribution_courroie_distribution_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courroiedistribution',
            name='refroidissement_quantite',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.StepValueValidator(0.1)], verbose_name='Quantité de liquide de refroidissement ajoutée en litres'),
        ),
    ]
