# Generated by Django 5.2.10 on 2026-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0010_alter_courroiedistribution_refroidissement_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courroiedistribution',
            name='kilometrage_cour',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage de la courroie de distribution'),
            preserve_default=False,
        ),
    ]
