# Generated by Django 5.2.10 on 2026-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0011_alter_courroiedistribution_kilometrage_cour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courroiedistribution',
            name='courroie_distribution',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Courroie de distribution'),
        ),
        migrations.AlterField(
            model_name='courroiedistribution',
            name='courroie_distribution_kit',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Nouveau kit distribution'),
        ),
        migrations.AlterField(
            model_name='courroiedistribution',
            name='pompe_a_eau',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Pompe à eau'),
        ),
        migrations.AlterField(
            model_name='courroiedistribution',
            name='refroidissement',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Liquide de refroidissement'),
        ),
    ]
