# Generated by Django 5.2.10 on 2026-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0012_alter_courroiedistribution_courroie_distribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courroiedistribution',
            name='courroie_distribution_kit',
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='refroidissement_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat htva du liquide de refroidissement"),
        ),
    ]
