# Generated by Django 5.2.10 on 2026-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0014_courroiedistribution_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroiedistribution',
            name='refroidissement_fabricant',
            field=models.CharField(choices=[('ABRO', 'ABRO'), ('AISIN', 'AISIN'), ('ARECA', 'Areca'), ('BARDAHL', 'Bardahl'), ('BASF_GLYSANTIN', 'BASF Glysantin'), ('BEL_RAY', 'Bel-Ray'), ('BIZOL', 'BIZOL'), ('BMW', 'BMW'), ('BOLK', 'BOLK'), ('BOSCH', 'Bosch'), ('CASTROL', 'Castrol'), ('CHAMPION', 'Champion'), ('COMMA', 'Comma'), ('ELF', 'ELF'), ('EUROL', 'Eurol'), ('FEBI_BILSTEIN', 'Febi Bilstein'), ('FUCHS', 'Fuchs'), ('GATES', 'Gates'), ('GENERAL_MOTORS', 'General Motors'), ('HEPU', 'HEPU'), ('HOLTS', 'Holts'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('IGOL', 'Igol'), ('IPONE', 'IPONE'), ('K2', 'K2'), ('KIA', 'Kia'), ('LIQUI_MOLY', 'Liqui Moly'), ('MANNOL', 'Mannol'), ('MAZDA', 'Mazda'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('MEYLE', 'Meyle'), ('MILLERS_OILS', 'Millers Oils'), ('MITSUBISHI', 'Mitsubishi'), ('MOBIL', 'Mobil'), ('MOPAR', 'Mopar'), ('MOTIP', 'Motip'), ('MOTOREX', 'Motorex'), ('MOTUL', 'Motul'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('ORLEN', 'Orlen'), ('PEMCO', 'Pemco'), ('PEUGEOT_CITROEN', 'Peugeot Citroën'), ('PETRONAS', 'Petronas'), ('PORSCHE', 'Porsche'), ('PRESTONE', 'Prestone'), ('PUTOLINE', 'Putoline'), ('RAVENOL', 'Ravenol'), ('REPSOL', 'Repsol'), ('RENAULT', 'Renault'), ('ROWE', 'ROWE'), ('SHELL', 'Shell'), ('SONAX', 'Sonax'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('SWAG', 'SWAG'), ('TEXACO', 'Texaco'), ('TOTALENERGIES', 'TotalEnergies'), ('TOYOTA', 'Toyota'), ('TRIPLE_QX', 'Triple QX'), ('VALEO', 'Valeo'), ('VALVOLINE', 'Valvoline'), ('VAG', 'Volkswagen Audi Group'), ('VOLVO', 'Volvo'), ('WOLF', 'Wolf'), ('XENUM', 'Xenum'), ('YACCO', 'Yacco'), ('YAMAHA', 'Yamaha'), ('AUTRE', 'Autre'), ('CONSTRUCTEUR', 'Constructeur'), ('CHOISIR', 'Choisir')], default='CHOISIR', max_length=25, verbose_name='Fabricant du liquide de refroidissement'),
        ),
    ]
