# Generated by Django 5.2.10 on 2026-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0018_alter_courroiedistribution_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroiedistribution',
            name='courroie_distribution_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CONTINENTAL', 'Continental / ContiTech'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BOSCH', 'Bosch'), ('SKF', 'SKF'), ('INA', 'INA'), ('SNR', 'SNR'), ('HUTCHINSON', 'Hutchinson'), ('OPTIBELT', 'Optibelt'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('BLUE_PRINT', 'Blue Print'), ('METELLI', 'Metelli'), ('HEPU', 'HEPU'), ('GRAF', 'GRAF'), ('DOLZ', 'DOLZ'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('ORIGINE', "Pièce d'origine / OEM"), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant de la courroie de distribution'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_enrouleur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Galet enrouleur'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_enrouleur_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CONTINENTAL', 'Continental / ContiTech'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BOSCH', 'Bosch'), ('SKF', 'SKF'), ('INA', 'INA'), ('SNR', 'SNR'), ('HUTCHINSON', 'Hutchinson'), ('OPTIBELT', 'Optibelt'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('BLUE_PRINT', 'Blue Print'), ('METELLI', 'Metelli'), ('HEPU', 'HEPU'), ('GRAF', 'GRAF'), ('DOLZ', 'DOLZ'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('ORIGINE', "Pièce d'origine / OEM"), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_enrouleur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_enrouleur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_tendeur',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'A Remplacer'), ('REMPLACE', 'Remplacé')], default='OK', max_length=25, verbose_name='Galet tendeur'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_tendeur_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CONTINENTAL', 'Continental / ContiTech'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BOSCH', 'Bosch'), ('SKF', 'SKF'), ('INA', 'INA'), ('SNR', 'SNR'), ('HUTCHINSON', 'Hutchinson'), ('OPTIBELT', 'Optibelt'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('BLUE_PRINT', 'Blue Print'), ('METELLI', 'Metelli'), ('HEPU', 'HEPU'), ('GRAF', 'GRAF'), ('DOLZ', 'DOLZ'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('ORIGINE', "Pièce d'origine / OEM"), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_tendeur_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='galet_tendeur_quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AddField(
            model_name='courroiedistribution',
            name='pompe_a_eau_fabricant',
            field=models.CharField(choices=[('CHOISIR', 'Choisir'), ('CONTINENTAL', 'Continental / ContiTech'), ('GATES', 'Gates'), ('DAYCO', 'Dayco'), ('BOSCH', 'Bosch'), ('SKF', 'SKF'), ('INA', 'INA'), ('SNR', 'SNR'), ('HUTCHINSON', 'Hutchinson'), ('OPTIBELT', 'Optibelt'), ('MEYLE', 'Meyle'), ('FEBI', 'Febi Bilstein'), ('SWAG', 'SWAG'), ('BLUE_PRINT', 'Blue Print'), ('METELLI', 'Metelli'), ('HEPU', 'HEPU'), ('GRAF', 'GRAF'), ('DOLZ', 'DOLZ'), ('QUINTON_HAZELL', 'Quinton Hazell'), ('MAGNETI_MARELLI', 'Magneti Marelli'), ('ORIGINE', "Pièce d'origine / OEM"), ('AUTRE', 'Autre')], default='CHOISIR', max_length=30, verbose_name='Fabricant'),
        ),
        migrations.AlterField(
            model_name='courroiedistribution',
            name='pompe_a_eau_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat HTVA"),
        ),
    ]
