# Generated by Django 5.2.10 on 2026-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0022_alter_courroiedistribution_pompe_a_eau_fabricant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroiedistribution',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
