# Generated by Django 5.2.10 on 2026-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courroie', '0026_alter_courroiedistribution_refroidissement_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='courroiedistribution',
            name='kilometres_rollback',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kilomètres rollback'),
        ),
    ]
