# Generated by Django 6.0 on 2026-01-05 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voiture_exemplaire', '0001_initial'),
        ('voiture_marque', '0001_initial'),
        ('voiture_modele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, verbose_name='Immatriculation')),
                ('type_carburant', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel')], editable=False, max_length=10, verbose_name='Type de carburant')),
                ('volume_max', models.FloatField(verbose_name='Volume max (L)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du plein')),
                ('litres', models.FloatField(verbose_name='Litres')),
                ('prix_refuelling', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix du plein (€)')),
                ('prix_litre', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Prix au litre (€)')),
                ('validation', models.BooleanField(default=True, verbose_name='Validation')),
                ('voiture_exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='voiture_exemplaire.voitureexemplaire', verbose_name='Véhicule')),
                ('voiture_marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='voiture_marque.voituremarque', verbose_name='Marque')),
                ('voiture_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='voiture_modele.voituremodele', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Carburant',
                'verbose_name_plural': 'Carburants',
                'ordering': ['-date'],
            },
        ),
    ]
