# Generated by Django 5.2.10 on 2026-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_fuel_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='litres',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litres'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='prix_litre',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Prix au litre (€)'),
        ),
    ]
