# Generated by Django 5.2.10 on 2026-02-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_alter_fuel_litres_alter_fuel_prix_litre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='volume_max',
            new_name='taille_reservoir',
        ),
    ]
