# Generated by Django 5.2.10 on 2026-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_rename_volume_max_fuel_taille_reservoir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='taille_reservoir',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='voiture_marque',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='voiture_modele',
        ),
        migrations.AlterField(
            model_name='fuel',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Immatriculation'),
        ),
    ]
