# Generated by Django 5.2.10 on 2026-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_remove_fuel_taille_reservoir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='type_carburant',
            field=models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Hydrogène', 'Hydrogène'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Ethanol', 'Ethanol')], max_length=10, verbose_name='Type de carburant'),
        ),
    ]
