# Generated by Django 5.2.10 on 2026-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0010_alter_fuel_type_carburant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='type_carburant',
            field=models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('HYDROGENE', 'Hydrogène'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('ETHANOL', 'Ethanol')], default='ESSENCE', max_length=10, verbose_name='Type de carburant'),
        ),
    ]
