# Generated by Django 5.2.10 on 2026-02-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0011_alter_fuel_type_carburant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='prix_litre',
        ),
    ]
