# Generated by Django 5.2.10 on 2026-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0012_remove_fuel_prix_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='prix_litre',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Prix au litre (€)'),
            preserve_default=False,
        ),
    ]
