# Generated by Django 5.2.10 on 2026-02-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0013_fuel_prix_litre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='fuel',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name='Montant HT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuel',
            name='montant_tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TVA'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='pays',
            field=models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], default='BE', max_length=2, verbose_name='Pays du plein'),
            preserve_default=False,
        ),
    ]
