# Generated by Django 5.2.10 on 2026-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0014_rechargecarburant_fuel_montant_ht_fuel_montant_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
