# Generated by Django 5.2.10 on 2026-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0015_fuel_kilometres_chassis'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='kilometrage_fuel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilométrage au plein'),
        ),
    ]
