# Generated by Django 5.2.10 on 2026-02-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0016_fuel_kilometrage_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='nom_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
