# Generated by Django 5.2.10 on 2026-03-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0018_fuel_created_at_fuel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='pays',
            field=models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=2, verbose_name='Pays de la station'),
        ),
    ]
