# Generated by Django 5.2.10 on 2026-03-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0019_alter_fuel_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='pays',
            field=models.CharField(choices=[('BE', 'Belgique'), ('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=25, verbose_name='Pays de la station'),
        ),
    ]
