# Generated by Django 5.2.10 on 2026-04-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0020_alter_fuel_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='type_carburant',
            field=models.CharField(choices=[('ESSENCE98', 'Essence 98'), ('ESSENCE95', 'Essence 95'), ('DIESEL', 'Diesel'), ('DIESELPLUS', 'Diesel +'), ('HYDROGENE', 'Hydrogène'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('ETHANOL', 'Ethanol')], default='ESSENCE98', max_length=10, verbose_name='Type de carburant'),
        ),
    ]
