# Generated by Django 5.2.10 on 2026-04-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0021_alter_fuel_type_carburant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Mis à jour le'),
        ),
    ]
