# Generated by Django 5.2.10 on 2026-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0022_alter_fuel_created_at_alter_fuel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
    ]
