# Generated by Django 5.2.10 on 2026-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0023_fuel_remarques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='kilometrage_fuel',
            field=models.IntegerField(default=0, verbose_name='Kilométrage au plein'),
            preserve_default=False,
        ),
    ]
