# Generated by Django 5.2.10 on 2026-06-15 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0024_alter_fuel_kilometrage_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du plein'),
        ),
    ]
