# Generated by Django 5.2.10 on 2026-08-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0025_alter_fuel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='kilometres_chassis',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres chassis'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='pays',
            field=models.CharField(choices=[('AT', 'Autriche'), ('BE', 'Belgique'), ('BG', 'Bulgarie'), ('HR', 'Croatie'), ('CY', 'Chypre'), ('CZ', 'Tchéquie'), ('DK', 'Danemark'), ('EE', 'Estonie'), ('FI', 'Finlande'), ('FR', 'France'), ('DE', 'Allemagne'), ('GR', 'Grèce'), ('HU', 'Hongrie'), ('IE', 'Irlande'), ('IT', 'Italie'), ('LV', 'Lettonie'), ('LT', 'Lituanie'), ('LU', 'Luxembourg'), ('MT', 'Malte'), ('NL', 'Pays-Bas'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('RO', 'Roumanie'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('ES', 'Espagne'), ('SE', 'Suède'), ('GB', 'Royaume-Uni')], max_length=25, verbose_name='Pays de la station'),
        ),
    ]
