# Generated by Django 5.2.10 on 2026-08-13 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0026_alter_fuel_kilometres_chassis_alter_fuel_pays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='RechargeCarburant',
        ),
        migrations.AlterField(
            model_name='fuel',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuels', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
