# Generated by Django 5.2.10 on 2026-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0027_delete_rechargecarburant_alter_fuel_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
