# Generated by Django 5.2.10 on 2026-08-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embrayage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embrayage',
            old_name='liquide_frein_etat',
            new_name='liquide_frein',
        ),
    ]
