# Generated by Django 5.2.10 on 2026-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embrayage', '0004_alter_embrayage_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='embrayage',
            name='kilometrage_variation',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Variation du kilométrage'),
        ),
    ]
