# Generated by Django 5.2.10 on 2026-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embrayage', '0008_embrayage_kilometres_embrayage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embrayage',
            name='kilometres_remplacement_embrayage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Kilomètres au moment du remplacement'),
        ),
    ]
